### PR TITLE
No Implicit Exports

### PR DESCRIPTION
**Pull request by eborden**
This is a proposal adding a new syntactic language extension that allows disabling implicit exports.

[Rendered](https://github.com/eborden/ghc-proposals/blob/eborden/no-implicit-exports/proposals/0009-no-implicit-export.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks for the proposal. I don’t see the motivation, however: People who by the “no implicit export list” discipline have to write

   module Foo (…) where

anyways. So they do not gain anything from the language extension.

And people who do not buy the discipline, well, they won't use the language extension.

So who is this for?

**Comment by eborden** [comment]
@nomeata This is for teams, not individuals. Discipline, is often a faulty method of enforcing anything on a team. If a team wishes to enforce explicit exports then this extension or linting errors in CI are their only reasonable methods of recourse.

**Comment by gelisam** [comment]
Instead of changing the semantics of `module Foo where` to `module Foo () where`, which is almost certainly not what the user wants, wouldn't it make more sense to make the `module Foo where` syntax cause a warning on an error? In which case, a `-Wmissing-export-lists` along the lines of the existing [`-Wmissing-import-lists`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wmissing-import-lists) would make more sense.

**Comment by eborden** [comment]
@gelisam That sounds like a reasonable alternative :+1:

**Comment by bgamari** [comment]
Indeed, I think `-Wmissing-export-lists` would be a great addition.

**Comment by nomeata** [comment]
That’s my thought as well: This would be more suited for a warning.

Although I personally don’t buy the discipline, and would be reluctant to add it to `-Wall`.

**Comment by eborden** [comment]
Yes, adding it to `-Wall` would be far too opinionated.

**Comment by hvr** [comment]
@eborden I'm a bit surprised about the claim

> Much of the community has settled around the idea that implicit exports are a misfeature. 

as I didn't have that impression; is there any evidence you can provide to support that statement?

**Comment by eborden** [comment]
@hvr This claim may be hyperbolic or I may live within a bubble of explicit exports.

**Comment by ndmitchell** [comment]
If you want to limit excessive exports I recommend HLint (which already features a warning for exactly this case) and Weeder (which will spot if you export something you don't later use). I think companies that have a declared coding style which isn't enforced by HLint are probably making a mistake... Turning it into a GHC warning might be a reasonable idea (I certainly know other Haskell implementations have it as a warning), but it's merely a warning.

@hvr In industrial code in several companies I've had that opinion repeated (and I agree with it).

**Comment by nomeata** [comment]
I agree that `hlint` is the proper place to check for these things.

**Comment by int-index** [comment]
I think adding a warning (disabled by default) would be uncontroversial and could be added even without going through `ghc-proposals`.

**Comment by eborden** [comment]
I'm going to close this proposal. Consensus here seems to be around `-Wmissing-export-lists`, without a proposal needed for implementation. Thanks for your feedback everyone :tada:

**Comment by tebello-thejane** [comment]
Hmm...

Branch deleted by @eborden, so now there's no record of the proposal anywhere?

**Comment by eborden** [comment]
@tebello-thejane I can restore the branch. It is my general practice to delete dead branches, as to not add extra bloat to the project.

image

**Pull request closed without merging**
