### PR TITLE
Move template into proposals/ directory.

### PR DESCRIPTION
**Pull request by goldfirere**
This allows for very lightweight proposal-writing, just by
using the "edit" button on GitHub. No manual forking/cloning
required.

### CODE REVIEW

**Comment by bgamari** [comment]
A good point.

**Comment by AntC2** [comment]
[Don't know if anybody'll read this so long after the proposal's been merged.]

Having just put in my first proposal #56 ...

* Thanks! It was good to have Template.rst in the proposals direcory.
* But Richard's second part of changing the instructions to "edit" rather than copy haven't been carried through. It still says "copy" in both README.rst and detailed-instructions.rst.

I (mostly by chance) managed to create my proposal OK. (Note the web UI doesn't have a copy function.) But what I'd done is edit & rename Template.rst.

Then I panicked because Template.rst had disappeared.

**Comment by nomeata** [comment]
I agree that the workflow is suboptimal. The Github Web UI does not allow for *copying* files, just *renaming*. It is not a big deal (I clean these things up when merging). Suggestions for a better workflow are welcome.

**Comment by AntC2** [comment]
No, no, the workflow is good: just by using the "edit" button on github web UI (as per Richard's first comment above); then while editting also rename Template.rst for your proposal.

What's wrong is that the *instructions* say to copy.

So: don't change the workflow; do (please) change the instructions.

Thanks in advance for "cleaning things up". But I'm sure you've got plenty else to do. (I'll know better next time ;-)

**Comment by nomeata** [comment]
The problem with renaming the file is that if I merge the PR, the template would be deleted. But I can fix that upon merging.

Feel free to submit a PR improving the instructions.

**Comment by AntC2** [comment]
Thanks Joachim, I was trying to help by giving a bit of feedback of the 'user experience'. But I'm just getting more confused.

No you don't want me to write/improve the instructions, because I clearly don't understand.

Richard's suggested wording (patch 'da2450d') says "Rename the template file ...". But:

* That wording hasn't come through to any user-visible instructions.
* You're saying renaming is the wrong thing to do.

The user-visible detailed-instructions.rst talk about forking and cloning and branching. But Richard's suggested wording seems to say instead you can just click on the pencil icon and edit away.

OK if I'm working in the web UI (no copy function) can I do this? (which is roughly how I muddled through):

#. Point your browser to the ghc-proposals/ghc-proposals repository.

#. Click on "Fork" (in the upper right corner).

   (skip: Clone the repository to your computer.)

#. Create a new branch for your proposal (say, 'my-proposal').
   By typing that name in the Branch drop-down. (Will take a little time.)

#. Navigate to the 'proposals' directory inside that branch.
   (Where you'll find 0000-template.rst.)

#. Open 0000-template.rst, you'll see the rendered text.
   (Do not click on the pencil icon.)
   Click on 'Raw' to see the reStructuredText with markdown.
   Select all; Copy (to clipboard).
   backout to the 'proposals' directory.

#. Click on 'Create New File'.
   In the edit screen name the file per '0000-my-proposal.rst'.
   Paste the text copied from the Raw template.
   Edit away.
   Commit the edit, with an informative commit message.

#. Committing will show you the rendered file.
   Continue in-place editting (the pencil icon).
   Until ready to move to the Discussion phase.

**Comment by nomeata** [comment]
That is how I do it (copy’n’paste the template), but it is awfully complicated to explain.

https://github.com/blog/1327-creating-files-on-github Says that one can have a link that pre-fills the filename of a new file. I wonder if we can pre-fill the content as well somehow.

Forking ahead of time should not be necessary, GitHub will offer that if you select “Create New File”.

**Comment by nomeata** [comment]
Actually, we can: https://www.reddit.com/r/github/comments/3ty3g9/github_trick_how_to_prefill_create_new_file_form/

Maybe that will simplify the process a lot…

**Pull request merged**
