### PR TITLE
Extension to LambdaCase (\case2, \case3)

### PR DESCRIPTION
**Pull request by Icelandjack**
Extension to `LambdaCase` allowing `\case2`, `\case3` to define a function that takes two, three arguments and pattern matches on their product.

This lets you write

``` haskell
import Data.Reflection (foldBy)

data B = F | T

foldB :: Foldable f => f B -> B
foldB = foldBy (\case2 (T, T) -> T; _ -> F) T
```

rather than

``` haskell
foldB' :: Foldable f => f B -> B
foldB' = foldBy (\a b -> case (a, b) of (T, T) -> T; _ -> F) T
```

Ties in with proposal #19, `foldB` becomes:

``` haskell
foldB :: Foldable f => f B -> B
foldB = foldBy (\case2 T, T -> T; _ -> F) T
```

[Rendered](https://github.com/Icelandjack/ghc-proposals/blob/case2/proposals/0000-case-n.rst).

### CODE REVIEW

**Comment by Icelandjack** [comment]
```haskell
instance (Eq1 f) => Eq1 (Lift f) where
    liftEq eq (Pure x1)  (Pure x2)  = eq x1 x2
    liftEq eq (Other y1) (Other y2) = liftEq eq y1 y2
    liftEq _  _          _          = False
```

with #18 

```haskell
instance (Eq1 f) => Eq1 (Lift f) where
    liftEq eq = \case2
      (Pure x1,  Pure x2)  -> eq x1 x2
      (Other y1, Other y2) -> liftEq eq y1 y2
      _                    -> False
```

with #18 + #19 

```haskell
instance (Eq1 f) => Eq1 (Lift f) where
    liftEq eq = \case2
      Pure x1,  Pure x2  -> eq x1 x2
      Other y1, Other y2 -> liftEq eq y1 y2
      _                  -> False
```

**Comment by Ericson2314** [comment]
I too want multi-arg LambdaCase, but is there a way to be more consistent with top-level function notation? I was hoping maybe a `\cases` could require parens around every pattern just like top level notation so the number of arguments can be inferred.

**Comment by m0rphism** [comment]
@Ericson2314 I would also propose one `\case` for functions of arbitrary fixity.
The restrictions for when parentheses are required, can be the same as for function definition syntax sugar:

    append :: [a] → [a] → [a]
    append []     ys = ys
    append (x:xs) ys = x : append xs ys

    append :: [a] → [a] → [a]
    append = \case
      []     ys → ys
      (x:xs) ys → x : append xs ys

**Comment by Ericson2314** [comment]
@m0rphism that would be ideal. But I fear that `\cases` or similar is needed because:
```Haskell
myFn = \case
  Ctor a -> ... -- unclear if `a` is an argument to`Ctor`
```

**Comment by m0rphism** [comment]
@Ericson2314 I would argue that in this case `a` would be no argument to `Ctor`. But this indeed would be a breaking change to the previous behavior of `\case`. Using `\cases` is probably less invasive, but instead may cause conflicts with regular lambdas taking a variable named `cases`, e.g. the identity function `\cases → cases` ;-)

**Comment by Ericson2314** [comment]
I think it would be a big breaking change, so `\[case]` is the best I got.

**Comment by ElvishJerricco** [comment]
In terms of a `cases` like alternative, `case of` does not parse today.

```haskell
x = \case of
  (Just a) -> ...
  Nothing -> ...

y = \case of
  (Just _) T -> F
  _ _ -> T
```

**Comment by evincarofautumn** [comment]
I like `\case of` well enough. An alternative would be just `case of`, which is how I expected `LambdaCase` to work when I first heard about it.

```
case of
  (Just n) T -> F
  _ _ -> T
```

Basically sugar for:

```
let
  f (Just n) T = F
  f _ _ = T
in f
```

And presumably the number of patterns must be the same in all branches, as for function equations.

To propose yet another colour for the bikeshed:

```
fromFoo def = \ case
  Foo x -> x
  _ -> def

fromFoos def = \ case case
  (Foo x) (Foo y) -> x
  _ _ -> def
```

The number of `case`s in the lambda is the number of patterns that must appear in each branch.

**Comment by rwbarton** [comment]
Besides "just use a lambda and a `case`", you could also just use `uncurry $ \case`.

It's not clear to me that parenthesizing separate arguments (as in `\case (Foo x) (Foo y) -> x`) makes parsing easy (or even unambiguous) given that you can currently write things like `\case (Foo x) :+ (Foo y)`.

Granted I'm not a fan of LambdaCase in the first place, but this seems like a poor value/cost tradeoff to me. The syntactic space of a `case` expression is valuable enough that I think we should reserve it for things that increase expressiveness in a nontrivial way (e.g., or-patterns).

**Comment by goldfirere** [comment]
What if we're not backward-compatible? We could just have two extensions such that we disallow having both active at the same time. We could then deprecate the original extension according to some timeline that's slow enough not to offend people.

It's a shame that a feature as young as `LambdaCase` prevents us from designing the language the right way.

**Comment by simonmar** [comment]
```
foldB :: Foldable f => f B -> B
foldB = foldBy f T where f T T = T; f _ _ = F
```

is actually shorter and more readable (IMO) than your version with special new syntax. :)

I actually kind of wish we hadn't added `LambdaCase`, it's far less useful than I thought it would be at the time.

**Comment by simonmar** [comment]
To put things in perspective: `\` is an anonymous multi-argument single-equation function, `\case` is an anonymous single-argument multi-equation function.  The fact that we don't have a way to write an anonymous multi-argument multi-equation function seems like a hole or an inconsistency in the language, but I think you can equally argue that adding such a feature is a step too far, especially if it has special new syntax.

An old proposal that I think is worth considering is to add layout to `\` to allow multiple equations. e.g.

```
foldB :: Foldable f => f B -> B
foldB = foldBy (\T T -> T; _ _ -> F) T
```

This was considered during the `LambdaCase` debate but rejected.  I forget why... perhaps it was just that people wanted a way to write the cases without parentheses around the patterns, perhaps it was felt that the syntax is too quiet, or perhaps adding layout to `\` causes other problems.

**Comment by angerman** [comment]
Just to add another data point: I must admit I do like `LambdaCase`! However, I usually only use it like this only:

```
ma >>= \case
  ... -> ...
  _ -> ...
```

in the originally provided example, I actually prefer the readability of second code snippet, which is the one this tries to avoid. So ¯\_(ツ)_/¯.

**Comment by Ericson2314** [comment]
@rwbarton I don't see the problem. Your example would not be allowed either way just as is the case with top-level functions today.
```ghci
Prelude> data Foo = (:+) | Foo Int | Int :++ Int
Prelude> f (Foo x) :+ (Foo y) = 1

<interactive>:21:1: error: Parse error in pattern: f
Prelude> f (Foo x) :++ (Foo y) = 1

<interactive>:22:1: error: Parse error in pattern: f
```

**Comment by Ericson2314** [comment]
@goldfirere, great idea! Thank goodness we have the extensions to allow for such conflicting experiments.

**Comment by Ericson2314** [comment]
@simonmar with that old proposal, would this work?
```
myDef = something $ \
  A -> _
  B -> _
```
I always assumed that such syntax was irreconcilable with the rest of the grammar, hence the need for the `case` in `\case`.

----

Personally, I find any top level function sugar superfluous, and ours woefully repetitive with the function name on every line. I would exclusively use LambdaCase but for a) the lack of multiple arguments, and b) weird type inference issues (at least as for 7.10)

**Comment by simonmar** [comment]
@Ericson2314 yes, that example would work.  `\` would introduce a layout context, just like the `of` in a `case` expression.

Some things would break.  e.g. the old monad style

```
f = 
  action1 >>= \x ->
  action2 >>= \y ->
  return (x,y)
```

would break because the line beginning `action2` would terminate the layout context of the lambda in the line above.

**Comment by Ericson2314** [comment]
@simonmar Oh! that's quite nice then. It always felt unnatural to me to *not* require success indenting with the "old monad style", so I won't miss it.

**Comment by dolio** [comment]
I think it'd be unfortunate to have to choose between lambda case and unindented explicit binds, because they can go hand-in-hand. Many of the situations I'd use lambda case are when I think something can be written more nicely without do notation. But requiring indenting is like requiring every line of a do block to be indented more than the one before it, which is pretty bad.

I don't have a strong feeling about the original proposal. I don't think I've actually wanted multi-argument lambda case before; and I think the reason for this is that there aren't many functions that are designed to make it advantageous. There are a few commonly used functions that are set up to take a one argument 'body' as the last argument, and lambda case is nice there. Like:

```haskell
m >>= \case
    ...

for xs $ \case
    ...

xs <&> \case
    ...
```

But there aren't many of these function-argument-last combinators that take two (or more) argument functions; at least, not that I can think of/use. And these are the main situations I'd reach for lambda case, because I'd be unlikely to put a branching case statement as anything but the last applied argument, as they tend to take up more than one line.

**Comment by Ericson2314** [comment]
@dolio to be clear, `\case` already does and must use layout syntax. If you can already write it with lambda case, you can with Simon's proposal too.

**Comment by rwbarton** [comment]
@Ericson2314 I was probably unclear. You *can* write (assuming a suitable definition of `:+`)
```
f = \case (Foo x) :+ (Foo y) -> ...
```
already (of course, since you can write `case z of (Foo x) :+ (Foo y) -> ...` under Haskell 98).

So

* the parsing of `\case ALTS` cannot be to just stick an `f ` at the start of each alternative and treat it as a function definition, since that would wrongly reject the above example.

* the parsing of an alternative cannot be to just take each parenthesized thing as a separate argument, since that would also wrongly reject the above example.

Something new seems to be needed.

**Comment by Ericson2314** [comment]
@rwbarton Yeah the idea is break backwards comparability and stop allowing that in `\case` (`case _ of` would still allow it).

**Comment by rwbarton** [comment]
Well, `\case` being inconsistent with `case` sounds even less appealing TBH. Why complicate the language for so little benefit?

**Comment by Ericson2314** [comment]
@rwbarton Well you can also argue that `\case` is inconsistent with `\` as is, so it cuts both ways. I probably learn towards @simonmar's route, but I fear the breaking standardized `\` will be more controversial than breaking an extension like `\case`.

(Of course, in the near term nothing is actually broken as this would be another extension.)

**Comment by dolio** [comment]
I know `\case` uses layout. The point is that `\` doesn't even when `\case` is enabled, and it's nice to have access to both in the same code.

**Comment by Ericson2314** [comment]
@dolio ok that makes sense, I thought you wanted out style with `\case`. Also your 3 examples above I also use, but usually *in* a do block. I don't always use do-notation, but I do if the alternative is only expressible with non-indenting lambdas.

**Comment by Icelandjack** [comment]
These examples will only get more common, example from [Efficient Evaluation for Untyped and Compositional Representations of Expressions](http://www.cse.chalmers.se/~emax/documents/axelsson2014efficient.pdf) (in what ever style)

```haskell
class TypeRep t where
  typeEq :: t a -> t b -> Maybe (a :~: b)

instance TypeRep Type where
  typeEq :: Type a -> Type b -> Maybe (a :~: b)
  typeEq = \
    BType BType -> Just Refl
    IType IType -> Just Refl
    _     _     -> Nothing
```

and [Lennart](http://augustss.blogspot.is/2009/06/more-llvm-recently-someone-asked-me-on.html)

```haskell
test :: TTyp a -> TTyp b -> Maybe (a :~: b)
test = \
  TTBol       TTBol         -> return Refl
  TTDbl       TTDbl         -> return Refl
  (TTArr a b) (TTArr a' b') -> do
    Refl <- test a a'
    Refl <- test b b'
    return Refl
  _ _ -> mzero
```

Although one of the original motivation was to get rid of those parentheses, I would much rather trade one `,` for 4 fewer parens

```haskell
  TTArr a b, TTArr a' b' -> do
```

**Comment by phadej** [comment]
@Icelandjack I don't see how LambdaCase23 is an improvement over:
```hs
test :: TTyp a -> TTyp b -> Maybe (Equal a b)
test TTBol TTBol = return Eq
test TTDbl TTDbl = return Eq
test (TTArr a b) (TTArr a' b') = do
    Eq <- test a a'
    Eq <- test b b'
    return Eq
test _ _ = mzero
```

I don't see a point of complicating the parser, to save writing `test` or parentheses.

---

Yet I'm not really against lambda \ introducing a layout context. I guess then one could write also

```hs
for_ values $ \value -> 
    Just x  -> y + 1
    Nothing -> def 
  where
    def = largerExpression
```

Couldn't one?

**Comment by dolio** [comment]
I don't really find most of these examples terribly convincing, either. They make it seem like there aren't examples where multi-argument lambda case is the clearly best choice, and the only reason someone would use it is because they don't like using pattern matching support for top-level definitions.

Also, @phadej, I hope it wouldn't work that way, because that is not how where clauses work for `case`. They are attached to each of the cases, not to the whole expression. But that brings up the further point: what is the 'lambdas introduce layout' proposal? Is it that the thing after the `\` in a lambda is a `case` body with slightly different multiple argument syntax? Or does it not have most of the features of `case`? For instance, which of these are valid?

```haskell
  \x | p x -> ...

  \x -> y where y = x + x

  \x | p x -> y where y = x + x
   x -> z where z = x + x + x
```

Incidentally, if it were me, I'd probably investigate what I'd want for a multi-argument case statement, which could be useful in its own right. It probably isn't useful if you're confident in GHC's optimizations, but as a general Haskell language feature it makes sense. If we assume the syntax is something like:

```haskell
case x , y , z of
    C1, C2 w, C3 b | b -> ...
      where ...
    ...
```

Then it becomes, I think, obvious how `\case` should handle multiple arguments; we can tell from the body how many there are. Then there is a homogeneous syntax between case statements and lambda case, and all the features of case bodies are supported. And the new extension discussed in this proposal would be the combination of `LambdaCase` and `MultiCase`, or whatever you want to call the latter.

**Comment by Ericson2314** [comment]
Actually I think all of `case`, `\case`, and `\`-with layout, etc, should have an optional where clauses scoped over all pattern-arms with the same indent level as the pattern-arms themselves.

**Comment by Icelandjack** [comment]
Braindumping, `case`-ing on a function applied to the last argument is common

```haskell
-- index (a :< as) key = case viewl key of
--   EmptyL  -> a
--   k :< ks -> index (index as k) ks
index (a :< as) = \caseBy viewl
  EmptyL  -> a
  k :< ks -> index (index as k) ks

-- readQ s = case reads $ S8.unpack s of
--              (x, _):_ -> x
--             _        -> 1.0
readQ = \caseBy (reads . S8.unpack)
            (x, _):_ -> x
            _        -> 1.0

-- fixConvention k0 = runSharing k0 (zonk k0) >>= \k -> case preview _Convention k of
--   Just cc -> return cc
fixConvention k0 = runSharing k0 (zonk k0) >>= \caseBy (preview _Convention)
  Just cc -> return cc
```

Might be a fun extension to combine with `\case` with more than one argument, it might also be a great big mess.

**Comment by Wizek** [comment]
I'm surprised that so few people mentioned [`curry`](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/Data.Tuple.html#curry). To me it seems much cleaner, easier and safer to implement this on the library level by defining `curry3`, `curry4`, etc, instead of having to implement it on the compiler level as `\case3`, `\case4`, etc.

Then one could go as wild as their heart desires:

```haskell
curry5 $ \case
  (_, _, 1, _, Nothing) -> return Foo
  _                     -> return Bar
```

The original example becomes:

```haskell
foldB :: Foldable f => f B -> B
foldB = foldBy (curry $ \case (T, T) -> T; _ -> F) T
```

**Comment by erikd** [comment]
@simonmar wrote:

> @Ericson2314 yes, that example would work. `\` would introduce a layout context, just like the `of` in a `case` expression.
>
> Some things would break. e.g. the old monad style

I would be strongly against breaking old monad style layout for any possible gains this proposal may give.

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by nomeata** [comment]
Another ping. @Icelandjack, whither this proposal?

**Comment by nomeata** [comment]
Due to lack of activity, I am marking this proposal as [dormant](https://github.com/ghc-proposals/ghc-proposals/#what-is-a-dormant-proposal).

**Comment by tomjaguarpaw** [comment]
[@Wizek's suggestion](https://github.com/ghc-proposals/ghc-proposals/pull/18#issuecomment-266634157) seems the right one to me.

**Comment by Bj0rnen** [comment]
I'm throwing in one little idea, just because I never saw it. What if we introduce a layout context after `\`, but only if the `\` is directly followed by a newline (or, I suppose, a `;`)?

So you couldn't do:
```haskell
isJust = \Nothing -> False; (Just _) -> True
```
But this would work:
```haskell
isJust = \
    Nothing -> False
    (Just _) -> True
```
And this:
```haskell
isJust = \; Nothing -> False; (Just _) -> True
```
As for `>>=` without indentation in classical style, that would still work.

I think that newline after `\` must be uncommon in existing code. Here's something you would no longer be able to do:
```haskell
x = Just 1 >>= \
    a -> Just 2 >>= \
    b -> Just (a + b)
```

As for supporting multi-argument matching here, that's the next logical question. I feel it would make sense to, since the ordinary (single-line) `\` always has. For consistency, that would have to make the parentheses around `Just _` in my examples mandatory.

**Comment by int-index** [comment]
Re: https://github.com/ghc-proposals/ghc-proposals/pull/18#issuecomment-266634157

What about RankNTypes? Not everything can be put into a tuple, at least not until we have first class support for impredicative types.

**Comment by nomeata** [comment]
@Icelandjack,what’s the status of this? Has been marked dormant for a while.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Pull request closed without merging**
