### PR TITLE
Library-defined language extensions!

### PR DESCRIPTION
**Pull request by nomeata**
This is a rough first draft, and not near submission quality. I hope that the community will help me to flesh this out and detect and fix all the problems with it.

[Rendered](https://github.com/ghc-proposals/ghc-proposals/blob/lib-lang-exts/proposals/new-proposal.rst)

### CODE REVIEW

**Comment by int-index** [comment]
I love how this would allow custom preludes to define their own extension, since you included `imports` in the extension specification:

```
  custom-extensions:
    * name: MyPrelude
      extensions: NoImplicitPrelude
      imports: MyPrelude
```

Then one could just add `MyPrelude` to `default-extensions` in their project.

**Comment by 3noch** [comment]
Requiring package qualification seems like a good idea.

**Comment by 3noch** [comment]
Also I'm not sure that overloading `{- LANGUAGE .. -}` pragmas is the best way. Perhaps introducing a new pragma would be better.

**Comment by 3noch** [comment]
This could really alleviate the pain of not having an official, up-to-date language standard.

**Comment by nomeata** [comment]
> Also I'm not sure that overloading {-# LANGUAGE .. #-} pragmas is the best way. Perhaps introducing a new pragma would be better.

That is a valid point. Maybe `{-# LANGUAGE_SET … #-}`? OTOH, reusing the existing infrastructure for language extensions, e.g. `default-extensions` in `Cabal` is valuable, as @int-index’s example shows.

**Comment by yav** [comment]
I think that having something like this would be very nice!

**Comment by 3noch** [comment]
> OTOH, reusing the existing infrastructure for language extensions, e.g. default-extensions in Cabal is valuable,

That's true. Perhaps namespacing these differently would be enough.

**Comment by andrewthad** [comment]
I'm -1 on this because the motivation doesn't seem compelling to me. In a cabal file, it's already possible to specify a list of extensions that will apply to every module. To my understanding, there are two common reasons some people (emphasis on **some**, clear not all people) avoid this:

1. You cannot just look at a module to figure out what's enabled. You have to look at the cabal file.
2. It's harder to build a module with plain old GHC when some of the configuration is in the cabal file.

This proposal solves neither of these problems. It's still hard to figure out what's in a module just by looking at the module, and it's not possible to build a module that uses a `LANGUAGE_SET` with GHC.

Although I would never use this for library code, one thing that would actually compel me to use this in application code would be if we could do this:

    custom-extensions:
      * name: CustomQualifiedPrelude
        extensions: ...
        flags: ...
        imports:
          - module: Data.Map.Strict
            alias: M
          - module: Data.HashMap.Strict
            alias: HM
          - module: Data.Text
            alias: T

Dumping a bunch of qualified imports into scope would be awesome, as we currently have absolutely no way to avoid this boilerplate.

**Comment by nomeata** [comment]
>  In a cabal file, it's already possible to specify a list of extensions that will apply to every module

Sorry if that is not clear, but this feature allows you to export such a list to _users_ of your library! Defining it in the same package as the code that uses it can be convenient, but is not the main purpose of the proposal.

> You cannot just look at a module to figure out what's enabled. You have to look at the cabal file.

True, and even worse: “when some of the configuration is in _some_ Cabal file” (or, technically more precise, _some_ package configuration). This is clearly the biggest downside of any form of non-standard language extensions.

> It's harder to build a module with plain old GHC when some of the configuration is in the cabal file.

Not true. It is GHC that reads the language extensions from the _package database_, which exists independent of `Cabal`. Just like you can `import Test.QuickCheck` in a file and compile that with `ghc` without a `.cabal` file, you will be able to use this feature.

**Comment by nomeata** [comment]
> Perhaps namespacing these differently would be enough.

If there is a non-obtrusive way, maybe. Command line flags for plugins are namespaced (using `-fplugin-opt=The.Plugin.Module:foo` for the flag `foo` to the plugin `The.Plugin.Module). Which works and is technically the right thing, but abhorrently ugly. OTOH, there is conceptually not a big difference between a new language extensions that suddenly appears because you have installed GHC-8.4 and one that suddenly appears because you have installed `inspection-testing-0.1`, so drawing an artificial distinction might not be needed. We certainly do not distinguish between modules in `base` vs. modules in other packages!

**Comment by 3noch** [comment]
That's an interesting perspective. Indeed blurring the line might actually be "useful" in the sense that you could begin to push/pull things out/in of GHC itself without breaking libraries. It would be also very convenient if you could deprecate the extension itself.

**Comment by RyanGlScott** [comment]
It's worth giving a mention of [Trac #9642](https://ghc.haskell.org/trac/ghc/ticket/9642), as this proposal would fix it.

**Comment by nomeata** [comment]
Ha, good catch. An in fact I proposed essentially the same thing back then: https://ghc.haskell.org/trac/ghc/ticket/9642#comment:7. I keep having ideas that I had before…

**Comment by blamario** [comment]
If the goal is to quickly import a bunch of language extensions and imports, there is no need to lean on Cabal and package database. Just take an ordinary unqualified module import, and make it *thoroughly* import the module, bringing all its pragmas and imports together with its bindings into the scope of the importer. Basically like C's `#include`, except without requiring the source code.

The syntax could be

    import language My.Fancy.Prelude

but a pragma would also work.

**Comment by alexanderkjeldaas** [comment]
I'm not sure about this.

My main gripe with these kinds of things is that the cabal file is not composable.  I can't create a cabal file that "extends" another, or define a set of extensions under a name in cabal.

Similarly, it's not clear how to compose things in this proposal.

Given that some module defines language extensions `[X, Y, Z]` I need to be able to manipulate that set of extensions in some other module, and also manipulate the set of flags and default imports.  I don't see how that is solved here.

Maybe Haskell should be used for manipulating this, but it seems like this should be a separate phase from everything else.  It would be similar to replacing the `.cabal` file with a haskell expression that is evaluated by a haskell interpreter.

But then again it won't be declarative, so it will break all sorts of tooling.

Why not make the `.cabal` file support some sort of composition?  Make the language extensions list into a Monoid - use a difference list for example - something that's both declarative and composable.

**Comment by nomeata** [comment]
@alexanderkjeldaas, note that the proposal only discusses the package file so far, not how `Cabal` choses to expose this feature to the user of `cabal`. It might be feasible for `Cabal` to add additional features that allow you to compose or transform language extensions…

I am very weary of anything “executable” at this phase. We don’t have executable ways of transforming modules, either.

But can you give a more concrete of what you’d like to compose or manipulate?

**Comment by Warbo** [comment]
My initial instinct is against this proposal. Two things in particular put me off:

 - It moves more of a program's semantics outside the code and into some ambient environment (a project's `.cabal` file, or the `.cabal` file of some deeply nested dependency, or some `ghc-pkg` database living who-knows-where, etc.).
 - It seems a little short-sighted: solving a few particular use-cases now, but potentially introducing more difficulties (for a hint of this, see the discussions about namespacing and composition).

I wonder if these use-cases could be served in some conceptually-simpler, but more wide-ranging, way?

Perhaps improvements to Template Haskell may help? Template Haskell is currently unable to alter `import` lists; maybe if that limitation were addressed, some of these use-cases would be resolved? What if Template Haskell could generate pragmas, or (perhaps more cleanly) invoke those behaviours which currently require pragmas?

Would it make sense to do these things with a preprocessor? What requirements would that need? For example, CPP has access to various `ifdef` values, for checking GHC versions, etc. Could we define these "custom extensions" as new `ifdef` values, and have users of them include a CPP snippet which expands into them?

CPP is pretty ugly to use, since it can mangle Haskell syntax and causes problems for those wanting to parse files (e.g. linters, code formatters, etc.). Are there nicer preprocessors out there? If we use a preprocessor which runs Haskell code, and that code is able to import the dependencies of the current package, then these "language extensions" could be implemented as normal Haskell values. Libraries would expose them just like any other Haskell value, no changes would be needed for the Cabal format or ghc-pkg database, and users would just need to include a snippet of Haskell code for the preprocessor which imports the relevant module and spits out the neccessary code (pragmas, imports, etc.).

How might a standalone tool, like those from e.g. `tasty-discover`, do this job? Would it be cleaner or more extensible than altering GHC?

I'm not sure of the implications for each of these (they're just the first things that came into my head), but it would be nice to think about the possibilities and tradeoffs of each approach. Currently the 'Alternatives' section of the proposal doesn't actually present any alternatives; just doing/not-doing this proposal.

**Comment by nomeata** [comment]
Small status update: I still want this, but I would feel more confident about moving forward with this proposal if someone with more knowledge of the Cabal codebase and the Cabal-GHC-interaction would co-author it with me. Anyone who fits that bill excited by this proposal? @gbaz? @ezyang

**Comment by gbaz** [comment]
The motivation seems pretty good to me. In terms of co-authoring, do you mean, actually writing the code if accepted? I'm not very expert on these things, but I guess I'd be happy to lend a hand, especially since the provenance-qualification touches on some of the same areas of interaction anyway... Tbh the cabal bit seems easy, the tricky bit is flowing extra import information from the package database, I suspect.

**Comment by nomeata** [comment]
I am not yet talking about implementation, but making sure the proposal is sound with regard to the interplay of Cabal, package data base, and GHC.

**Comment by gbaz** [comment]
Ok, well, to my inexpert eyes it looks totally fine then, in terms of that interplay making sense. It does somewhat extend the "meaning" of the packagedb, but not in a way that I think should be objectionable. @ezyang or someone else who really knows this from the ghc side more deeply may think otherwise though...

**Comment by nomeata** [comment]
I still like the idea, but the committee is pretty loaded with proposals right now, and mine tend to just cause lots of discussion and then get rejected, and this might be no different … I will happily pick it up again if I find some co-authors or allies who’d help advocate for this.

**Pull request closed without merging**
