### PR TITLE
Explicit ForSome

### PR DESCRIPTION
**Pull request by VitWW**
**Explicit ForSome**

This proposal adds handiness and flexible control to scoped type variables by using `ExplicitForsome` .

Alternative (but they could coexist together) is "Modern Scoped Type Variables" [#448](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0448-type-variable-scoping.rst) (`ScopedTypeVariables` extension, which de facto is `ImplicitForsome`)

[Rendered](https://github.com/VitWW/ghc-proposals/blob/explicit-forsome/proposals/0000-explicit_forsome.rst)

[Rendered ReadDoc](https://ghc-proposals--643.org.readthedocs.build/en/643/proposals/0000-explicit_forsome.html)

Edit: I split this proposal. Second part: #646

### CODE REVIEW

**Comment by VitWW** [comment]
Ok, discussion has ebbed down.
And my Proposal is ready enough.

@adamgundry Let's submit this to the committee.

**Comment by adamgundry** [comment]
@VitWW I'm sorry, but I don't think this proposal is ready for submission to the committee. Please take a look at my comments at https://github.com/ghc-proposals/ghc-proposals/pull/646#issuecomment-2018941358. As far as I can see there hasn't been any discussion on this proposal, I suspect because it is difficult to understand exactly what is being proposed and why.

If I understand correctly, you are proposing it should be possible to write `forsome a .` as part of a type signature, to mark type variables that are used in the type but which come from an outer scope (e.g. because they were bound by `ScopedTypeVariables` or `TypeAbstractions`). It's not clear to me why this is useful, however, or how it provides an alternative to `ScopedTypeVariables`, given that using such type variables is currently supported without any syntactic marker at all.

Can you elaborate on what problem you are trying to solve?

**Comment by VitWW** [comment]
> @adamgundry If I understand correctly, you are proposing it should be possible to write `forsome a .` as part of a type signature, to mark type variables that are used in the type but which come from an outer scope

Yes, exactly!

> It's not clear to me why this is useful, however, or how it provides an alternative to `ScopedTypeVariables`, given that using such type variables is currently supported without any syntactic marker at all

1) I give a math proof (Ok, weak math proof), that `forsome` quantifier **is** a part of Type System:

- _if_ ∀a: f a _then_ ∀a: Əb, b ∈ a : f b

2) I found, that **every** type_variables in Haskell are either `forall a.` or `forsome a.` This is an **unification** and **generalization** of declaring type variables.

3) From this Proposal perspective `ScopedTypeVariables` becomes _de facto_  "Implicit rules to add a `forsome` quantifier to type variables if they are not explicitly quantified". But without my Proposal, `ScopedTypeVariables` are some magical additional rules how to read type signatures.

4) Explicitness is preferential in Haskell over implicitness. And this Proposal propose how to write `forsome` quantifier **explicitly**.

```haskell
f2 :: forall a. [a] -> [a]
f2 xs = ys ++ ys
   where
     ys :: forsome a. [a] 
     ys = reverse xs
```

> Can you elaborate on what problem you are trying to solve?

I hope, my explanations help to understand what do I mean.

I really don't understand what it is missing here.  

What `ExplicitForAll` resolves, if "using such type variables is currently supported without any syntactic marker at all". 

> **6.11.1. Explicit universal quantification (forall)**
> Haskell type signatures are implicitly quantified. When the language option `ExplicitForAll` is used, the keyword `forall` allows us to say exactly what this means.

The same for `ExplicitForSome` and `forsome`.

What do I need to add to Proposal to become clearer in understanding and to be ready for submission to the committee? Please could you help me?

**Comment by jvanbruegge** [comment]
The given example is perfectly fine even without scoped type variables:
```haskell
f2 :: [a] -> [a]
f2 @a xs = ys ++ ys
   where
     ys :: [a] 
     ys = reverse xs
```
So what would this change?

**Comment by VitWW** [comment]
@jvanbruegge Thank you!
First, Fresh playground said me "error: Type applications in patterns are only allowed on data constructors."

But, anyway: #448 has another examples. Could we in all of them avoid `ScopedTypeVariables` ?

**Comment by AntC2** [comment]
> **6.11.1. Explicit universal quantification (forall)**
> Haskell type signatures are implicitly quantified. When the language option `ExplicitForAll` is used, the keyword `forall` allows us to say exactly what this means.

Thanks @VitWW, let me try to explain what I don't understand -- from the point of view of a end-user Haskeller, rather than a language designer. ("exactly what this means" is one of those patronising phrases docos should avoid like the plague: who knows what it "means" to the readers?) The trouble with trying to build on or build around #448 is that it's a 'greatest hits album' where you need to understand how everything fits together. (It's also a bit naughty/against usual practice in that it's not self-contained -- but then it's quite explicit about all the places you have to go read.) You're proposing extra syntax and a new keyword into what is already a crowded design space. So I'd expect a high benefit : cost ratio.

The problem I see in reading code with `-XScopedTypeVariables` is not with the `-XExplicitForAll`, but that there's no _textual_/syntactic  demarking of which vars scope over what region of code:

```
f2 :: forall a. [a] -> [a]

-- ...

f7 :: forall a b. (Num a, Floating b) => a -> b -> a
f7 x y = ...  
        where z :: b
              z = ...

--  ... pages more code, declaring all sorts of other names, possibly more fresh uses of tyvar a

f2 xs = ys ++ ys
   where
     ys :: [b] 
     ys = reverse (xs :: [a])
```

What's that `b` in `ys :: [b]`? I have to look to the top of the module to see if `-XScopedTypeVariables` is switched on; if it is, I have to look potentially all over the module for a top-level signature for `f2` (and check it's using explicit `forall`); and then I might find that `b` doesn't appear there -- although it's useful to find `a` does. [I think you understand this, but your proposal doesn't explain it out loud where I'd expect it in the 'Motivation'.]

Personally, I avoid `-XScopedTypeVariables` because of all this scanning around. I simply do not want anything to scope outside the top-level syntactic construct it's declared in. I would (try to) write the example as

```
{-# LANGUAGE   NoScopedTypeVariables    #-}

f2 :: forall a. [a] -> [a]           -- of course I'd prefer to put this as close as poss to f2's equation(s)

--  ...

f2 (xs :: [a]) :: [a] = ys ++ ys
   where
     ys :: [b] 
     ys = reverse xs
```

in which the `a` in `f2`'s equation is fresh, merely punning on the name from the sig.

(Uses `-XResultTypeSignatures` -- in a way which I believe won't be allowed if the extension ever arrives; so put the result sig after the `ys ++ ys :: [a]`.)

I say "try to" because `ys :: [b]` tries to introduce a fresh `b` where in fact the inferred type is `[a]`, so this is trying to make `y`'s type too general, rejected by the compiler (`Couldn't match ... rigid type variable`). What is accepted is `ys :: [a]`.

Ok now you might find those annotations syntactically cluttered (plenty of people don't like that style -- @jvanbruegge's `@` is another possible style). To my mind it binds `a` in `(xs :: [a])` at the same place in `f2`'s equation as it binds `xs`. (And it annoys me immensely that I can't in GHC give `f2`'s result type also on the LHS amongst the bindings.)

And I think it achieves what you're trying for with `forsome`. (If not, please explain the usage `forsome` is aimed at.)

And it's available today; so doesn't need extra keywords. (Indeed pseudo-quantifier `forsome` seems to be unknown outside XML RDF -- and even there it seems to mean what everybody else would call `exists`.)

**Comment by VitWW** [comment]
First, about new possibilities.
#509 Type Function Proposal asks what to do with next types?
```haskell
p1 :: isDigit '0' :~: True
p1 = Refl

-- desugars into
p1 :: forall isDigit. isDigit '0' :~: True
-- not to
p1 ::                 isDigit '0' :~: True

-- with forsome quantifier
p1 :: forsome isDigit. isDigit '0' :~: True
```

Sure, if function could become promotional, this could be true.

**Comment by VitWW** [comment]
> And I think it achieves what you're trying for with `forsome`.

You understand it right!

>  [I think you understand this, but your proposal doesn't explain it out loud where I'd expect it in the 'Motivation'.]

@AntC2 Thank you very much!
I'm ready to add your name as coauthor (or at endorsement) of Proposal if you review it and make this proposal a bit better.

> You're proposing extra syntax and a new keyword into what is already a crowded design space.

Technically it is enough for `forsome` be pseudo-keyword, like `family`

> (Indeed pseudo-quantifier forsome seems to be unknown outside XML RDF -- and even there it seems to mean what everybody else would call exists.)

As for me `forsome` is shorter and simpler to write correctly then `forunique`.
But Ok, I'm ready to add alternative naming or even change to `forunique` if is needed.
And [Uniqueness quantification](https://en.wikipedia.org/wiki/Uniqueness_quantification) is a real math quantifier, usually is marked as "∃!" or "∃₌₁"

**Comment by AntC2** [comment]
#509 "introduces a new way to use term-level functions at the type level." (not to debate here the merits of doing that.) Then [`isDigit` is already a term-level function](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-Char.html#v:isDigit); I bring it into scope with `import Data.Char`. Why would I want the burden of some other binding mechanism?

And in general, top-level decls (like your `f2`) scope over the whole module, and any modules this module is imported into (with a suitable `import` statement). The obscurity with `-XScopedTypeVariables` is that `a` _doesn't_ scope anywhere at the top level (so its scope is not apparent with any parsing/editor tools/plugins), but only within expressions defining `f2`. (And even more confusingly, if I declare `f7 :: forall a ...`, that brings a completely unrelated `a` into scope only within expressions defining `f7`.)

I don't go/I don't want to go with term-level definitions:

```
f9 :: forsome isDigit. Char -> Bool
f9 = isDigit
```

Then why would I want to make special syntax for type-level function invocation, when the whole idea is to unify types and terms as far as possible? (not to debate here the merits of doing that. Nor to debate whether GHC's type-level expressions -- especially Type Family syntax -- is a shambles within context of a unified namespace that should just get nuked some day.)

**Comment by AntC2** [comment]
> I've found, that's totally Ok, to have `ys :: forone b. [b] ` signature

I suggest you keep well clear of the Logician's `forone`: we already have enough wild beasts in our zoo; and for our purposes, `forone` can be taken as a shorthand [~](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/equality_constraints.html):

```
f2 :: forall a. [a] -> [a]
f2 xs = ys ++ ys
   where
     ys :: forall b. b ~ a => [b]            -- ~
     ys = reverse xs
```

> Is it good "high benefit" ?

Thanks to this discussion, I now see better what you're trying to paint as 'the problem'. (Which is not stated in the Motivation.) And we seem to have identified several approaches to address those requirements using existing or soon-to-be GHC. Then sorry, I see no benefit, only cost. YMMV, depending on your take of the aesthetics of those approaches.

**Comment by VitWW** [comment]
> Moreover, one can already use `PartialTypeSignatures` to get a form of existential type variable:
> ....
> I think `forsome` may be something like partial type signatures with a different syntax for indicating wildcards, i.e. `ys :: forsome b . [b]` means the same as `ys :: [_b]`?

Wow! You are right! At first I wish to say "No", but yes!

If we write  `ys :: forsome a . [a]` then Compiler grab locally scoped `a` type variable, just like `ScopedTypeVariables`.
But if we write `ys :: forsome b . [b]`, then b is not locally scoped, then compiler must infer, just like `PartialTypeSignatures` do with holes, and finds that `b` is scoped `a`!

**Comment by AntC2** [comment]
> Wow! You are right!

Great! So we can close this proposal?

OTOH when I first read @adamgundry's suggestion, I was pretty sure it _wasn't_ going to achieve what was wanted. It's difficult to demonstrate with our running example, because given `f2`'s top-level signature, `f2 xs = ys ++ ys` forces `ys :: [a]` (assuming `ScopedTypeVariables`), there's no benefit from the embedded signature for `ys`. (Shows the danger of arguing for advanced type features whilst relying on simplistic examples. #448 and friends include some really convoluted nasties.)


> But if we write `ys :: forsome b . [b]`, then b is not locally scoped, then compiler must infer, just like `PartialTypeSignatures` do with holes, and finds that `b` is scoped `a`.

No that's not an accurate description. Adam used `_b`, not bare `b`. With bare `b` in Adam's example, you get `Couldn't match type 'b' with 'a'`; `'b' is a rigid type variable bound by   the type signature ...` Whereas `_b` says: unify `_b` with whatever type gets inferred for this expression; tell me what that is ===> ` Found type wildcard '_b' standing for 'a'`. 

To illustrate what can go wrong, I'll need to change the example quite a bit:

```
f2 :: [a] -> Int
f2 xs = length $ ys ++ ys
    where ys :: [_b]
          ys = [undefined]
```

Now it's not obvious from `f2`'s equation what is the type of `ys`. And putting `ys ::[_b]` says (in effect) I don't care what type `ys` gets, provided it's a list: `Found type wildcard '_b' standing for '_'`. **Note** not standing for `a`. So you've got to read the message closely to understand where you messed up. (In the midst of roughing out code, you might put `undefined` as a place-holder to get the program to compile/so you can see type warnings, meaning to come back to it later.)

--------

(Perhaps more to the point.) In order to see the useful  ` Found type wildcard '_b' standing for 'a'`, we need `a` from `f2`'s signature to be notionally in scope within `f2`'s RHS -- which discontinuous scope is what everybody [**] hates about `ScopedTypeVariables`.

[**] That is, everybody who's not happy with that extension as is/the motivation for #448 and friends.

The benefit from `PartialTypeSignatures`, as I see it, is where you put `:: _b` in more than one place in your equations, to say in effect: I expect these expressions to be same type (whatever that is); please unify the inferred types and tell me what that type is -- or reject the program if you can't unify.

**Comment by VitWW** [comment]
> Great! So we can close this proposal?

Thanks for discussion!

I see, that benefits from my Proposal is smaller then I expected.

But still I find fascination that all type variables in Haskell are *de  facto* either forall-quantified or forsome-quantified.

So, I decided not to close this proposal, but remain it in "discussion" period (do not promote it to the committee).

Everyone is still invited to react on this Proposal.

**Comment by AntC2** [comment]
> all type variables in Haskell are _de facto_ either forall-quantified or forsome-quantified.

At best this claim is unhelpful; at worst it's downright misleading.

Currently GHC has:

* Univerally quantified/polymorphic types -- and we might distinguish parametric polymorphic vs constrained polymorphic;
* [Existentially quantified types](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/existential_quantification.html). (Which are also declared with the `forall` keyword. Or GADTs.);
* Type Families/Associated types; and
* we're working towards [Dependent typing](https://en.wikipedia.org/wiki/Type_system#Dependent_types) (also Linear typing, a bit further down that page).

"forsome quantified" is not a thing in type theory, [as far as I can see](https://en.wikipedia.org/wiki/Type_system#Specialized_type_systems). So where your 'Motivation' section says

> this Proposal propose how to write `forsome` quantifier

it's not as if Haskellers have been itching to use `forsome` that they're familiar with from other languages. Rather, it's a whole new concept, that you need to explain first. For example:

* must a `forsome`-quantified variable exactly correspond to a single tyvar from outer scope?
* where does the scope of a `forsome`-quantification start from and extend to? (Especially if I want to use tyvars in annotations to expressions as well as stand-alone signatures -- see `-- ?? which a, b` below, where `a, b` from `f4`'s signature are not in scope because `NoScopedTypeVariables`.)
* Or can it turn out to correspond to some composed type with constructors and multiple outside tyvars?
* Can it be named same as a tyvar from outer scope? If so, must its inferred type be the same as that tyvar? 
* Note that in Logic and programming, a quantifier starts a new scope for the bound variable, which [shadows](https://en.wikipedia.org/wiki/Variable_shadowing) any same-named variable from outer scope. But beware the `where` construct, also from Logic and programming dating back at least to BCPL 1967 throws its scoping textually 'backwards' to the expression it's attached to.

(You could perhaps work through those questions for each of the alternative approaches suggested above.)

IOW is this to be allowed? (I've made it deliberately confusing):

```
{-#  LANGUAGE   NoScopedTypeVariables    #-}

f4 :: forall a b. a -> [b] -> [(a, b)]
f4 x ys = ( map f5 ys2 :: [(b, a)] )      -- :: [(a, b)]        -- expression annotation ?? which a, b
    where f5 :: forsome b a. a -> (b, a)
          ys2 = reverse ys
          f5 y = (x, y)
```

Extension `ScopedTypeVariables` doesn't introduce some new form of typing; it controls the textual scope of tyvars already introduced in a familiar way. I must admit `PartialTypeSignatures`/`NamedWildCards` is a bit funky when you try to relate it to familiar typing/scoping mechanisms.

**Comment by VitWW** [comment]
> > all type variables in Haskell are de facto either forall-quantified or forsome-quantified.
>
> At best this claim is unhelpful; at worst it's downright misleading.
> Currently GHC has ...

Good questions.
You are talking about "types", I was talking about "type variables".

And you're correct, Existentially quantified types in Haskell use forall-quantified type variables.
Linear Types - this is an *additional* control over **using** arguments. And all these efforts for wonderful coerce ability of Linear Types.
Depended types - ok, my proposal is formally belong here.
In my "Proof": *if* ∀a: f a *then* ∀a: Əb, b ∈ a : f b , pay attention on "b ∈ a" part - this is definitely a dependency. Ok, special dependency, but nevertheless. 

> "forsome quantified" is not a thing in type theory, [as far as I can see](https://en.wikipedia.org/wiki/Type_system#Specialized_type_systems).

1) I'm not responsible for those, who don't pay attention to some "boring" algebras.
Just like George Boole, who discover "boring" algebra in the middle of XIX century, which was already known since ancient Greeks.

2) Ok, let's dig deeper into Type System.
We have "Polymorphic" ∀a: f a types and "Existential " ∃a: f a types.

I have a question: can we "marry" those 2 types with synergy effect (new, additional property)?
And I found at least 2 interesting solutions:
1) *if* ∀a: f a *then* ∀a: ∃b, b ∈ a : f b
2) *if* ∀a: f a *then* ∃b: ∀a, a ≡ b : f b

Both have additional condition, a dependency from forall quantified type variable.
First is a uniqueness quantifier `forsome`
Second it truly Existential, Ok, Depended Existential, DownRanked Existential with `exists`  quantifier. See #642 for more details

> it's not as if Haskellers have been itching to use forsome that they're familiar with from other languages. Rather, it's a whole new concept, that you need to explain first.

Fair point.

> must a forsome-quantified variable exactly correspond to a single tyvar from outer scope?
> Or can it turn out to correspond to some composed type with constructors and multiple outside tyvars?

`forsome` is a *de facto* scoped or/and inferred quantifier (just from dependency "b ∈ a") and could consists any types (`Int`), type variables(`a`), injected type variable or variables(`Maybe a`, `f a`), but **not** `forall` quantifier. Technically it's a bit weaker, then `PartialTypeSignatures`

> Can it be named same as a tyvar from outer scope? If so, must its inferred type be the same as that tyvar?

If just shadows the name, then: No, No.
Otherwise: Yes if scoped, Yes it must. Just from dependency "b ∈ a"

> where does the scope of a forsome-quantification start from and extend to? (Especially if I want to use tyvars in annotations to expressions as well as stand-alone signatures -- see -- ?? which a, b below, where a, b from f4's signature are not in scope because NoScopedTypeVariables.)

Using `forsome` in standalone signatures is possible, but mostly useless
```haskell
-- b == a
idFaFs :: forall a. a -> forsome a. a  -- scoped
idFaFs :: forall a. forsome b. a -> b  -- inferred
idFaFs x = x
```
Remember, the next is true:
```haskell
f :: forall a. a -> a -> a -> a -> a -> a

-- means
f :: forall a. a -> forsome a. a -> forsome a. a -> forsome a. a -> forsome a. a -> forsome a. a
```

> which a, b below, where a, b from f4's signature

This is depended from convention.
From ordinary point of view it is definitely `f4 x ys = ( map f5 ys2 :: forsome a b. [(b, a)] )`. Writing this we say that result depends just from inputs.
But Haskell also allows to write result type as annotation to expression, to create a new scope space `f4 x ys = ( map f5 ys2 :: forall a b. [(b, a)] )` means that `x :: forall a. a, ys :: forall b. [b]` (Ok, from `TypeAplication` rules, more correctly to say  `x :: forall a b. a, ys :: forsome b. [b]`) and .... surprisingly `fs :: ..-> forsome a b. [(b, a)]` . 
You say it is a collision! 
But remember my discovery: "all type variables in Haskell **are already de facto** either forall-quantified or forsome-quantified"
Now Haskell have a preferential to 2nd variant from **implicit rules**. But if we write explicitly 1st variant, it is still should be Ok.

> Extension ScopedTypeVariables doesn't introduce some new form of typing; it controls the textual scope of tyvars already introduced in a familiar way. I must admit PartialTypeSignatures/NamedWildCards is a bit funky when you try to relate it to familiar typing/scoping mechanisms.

But do you see the common of both of them? They both do something with "tyvars already introduced".

**Comment by VitWW** [comment]
I wrote about ignoring "boring" algebras, but I also forget to add some "boring" rules, which satisfies:
1) Main rule: *if* ∀a: f a *then* ∀a: Əb, b ∈ a : f b
2) Second rule: *if* Əa: f a *then* Əa: Əb, b ∈ a : f b

Second, GHC compiler has not smart enough, so, it uses just simpler version of `forsome` quantifier - `forscope` (without inferring) quantifier for next occurrences of tyvar, which is not explicitly quantified.
That's why we expect to 
```haskell
--Error!
idAB :: a -> b
idAB :: forall a b. a -> b
idAB x = x

-- Ok
idAB :: forall a. a -> forsome b. b
idAB x = x


idAA :: a -> a
--"desugars"
idAA :: forall a. a -> forscope a. a
-- not "desugars" into
idAA :: forall a. a -> forsome a. a
idAA x = x
```

> >    Can it be named same as a tyvar from outer scope? If so, must its inferred type be the same as that tyvar?
>
> If just shadows the name, then: No, No.

Third. Even it not forbidden to have shadowed a name by `forsome` quantifier with non-same scope meaning in theory, I think it is contra-productive to have such ability in GHC.
I think - that forsome quantified tyvars could shadow same name **only for same scoping**!

With this forbidden ability GHC, a quantifier `forscope` (for `-> a -> a`) becomes just implicit `forsome` .  The goal is reached!
All tyvars in Haskell are already de facto either forall-quantified or forsome-quantified!

**Comment by AntC2** [comment]
> In my "Proof": _if_ ∀a: f a _then_ ∀a: Əb, b ∈ a : f b , pay attention on "b ∈ a" part

Well yes I was going to ask about that notation -- as and when I got a better idea of what you're trying to do. But so far I haven't. (You continue to talk is if "forsome-quantified" is a thing we all understand. Shouting "**de facto**" in front of something you haven't yet demonstrated as a fact, then sprinkling exclamation points around, is just irritating.)

`a` is a tyvar, `b` is a tyvar. Variables standing for some type. Types are not sets (although it's sometimes useful when explaining to newbies to acknowledge things like `Bool` or `Char` are sets; what species of set is `Char -> Bool` or `a -> b`?) Haskell's is a [Nominal (or Nominative) Type System](https://en.wikipedia.org/wiki/Nominal_type_system), which is how (for example) a `newtype` can denote/"contain" the same set of values as its based-on type whilst supporting distinct overloadings (`instances`).

`b ∈ a` uses 'element of'(?) In what sense can a tyvar denote something that's an element of what some other tyvar denotes? You want `b` to denote a value in `a` considered as a set? Then `f b` is ill-kinded: you can't apply a type-predicate to a value. Beware also that [Haskell supports empty types](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-Void.html) 'ex falso quodlibet'. Despite `f a`, there's no `b` s.t. `b ∈ a` -- but that doesn't matter under Nominative typing.

> They both [`ScopedTypeVariables`, `PartialTypeSignatures/NamedWildCards`] do something with "tyvars already introduced".

"do something" is unhelpfully vague.

Tyvars introduced via `PartialTypeSignatures/NamedWildCards` do not bear any necessary connection with "tyvars already introduced". Consider, with those extensions switched on:

```
-- f2 :: [a] -> [a]                   -- no signature given/no tyvars bound
f2 xs = ys ++ ys
   where
     ys :: _aa                       -- not [_a]
     ys = reverse xs

===>     * Found type wildcard `_aa' standing for `[a]'
                Where: `a' is a rigid type variable bound by
                       the inferred type of f2 :: [a] -> [a]
```

GHC found no signature for `f2`, so inferred one and invented tyvar `a` for it. Saw the type wildcard `_aa` and figured out it stood for `[a]`, _not_ for any tyvar already in scope.

So I'm not seeing "do something with tyvars already introduced". And despite the volume of words from you, I can't guess whether or how I can use `forsome` in place of `_aa`.

Ok I've put enough effort into this fruitless quest. I'm done. I suggest you withdraw this proposal and go away think what it is you're trying to achieve, and how to explain that to anybody beyond yourself. There are mountains of documents and proposals around Haskell's type system, and type systems for Functional Languages in general. Read some of them to get an idea of the terminology. Look at not proposal #448, but at the sub-proposals it's collecting together.

**Comment by VitWW** [comment]
> a is a tyvar, b is a tyvar. Variables standing for some type. Types are not sets (although it's sometimes useful when explaining to newbies to acknowledge things like Bool or Char are sets; what species of set is Char -> Bool or a -> b?) Haskell's is a [Nominal (or Nominative) Type System](https://en.wikipedia.org/wiki/Nominal_type_system), which is how (for example) a newtype can denote/"contain" the same set of values as its based-on type whilst supporting distinct overloadings (instances).

I'm prefer to focusing on required level of details. This Proposal is not about new variant of data / newtype, this Proposal about "new" quantifier and quantifiers are highly developed in Set Theory.

>  Consider, with those extensions switched on:
> GHC found no signature for f2, so inferred one and invented tyvar a for it. Saw the type wildcard _aa and figured out it stood for [a], not for any tyvar already in scope.

To be more correctly, there is no **named** tyvar already in scope, but sure, exists at least 1 **unnnamed** tyvar.

> Ok I've put enough effort into this fruitless quest. I'm done. 

Thank you very much!

**Comment by AntC2** [comment]
> [VitWW](https://github.com/VitWW) mentioned this pull request

Thank you for advising of the comment on 523. But I think better to continue discussion here. (And 523 is closed. Note the comment as the initiator closed it: " I tend to agree that the complexity isn't worth it.")

> I described a bit similar ideas ...

Your idea might be (a bit) similar, but since only you seems to understand your idea, that remark isn't helping anybody else.

It's true that sometimes it would be useful to create a local type synonym as shorthand for a more complex type expression. This might be binding local type variables or expressing the type for a local term-variable, so it can't be a top-level name. That's the `(c ~ Very Big Type a b) => ...` style example. (And your comment gives a shorthand `y` in `forall x. forsome y <- Succ x.  ...`

But there must be something further going on in your comment with this example:

```
id :: forall a. forsome b <- a. a -> b
id @a (x :: b)  = x
```

In what way is it useful to make `b` a 'shorthand' for `a`? It's not shorter; and you need a reserved word `forsome` and the binding arrow `<-` so the overall expression is much longer. How does the meaning/usage differ? from writing

```
id :: forall a. a -> a
id @aa (x :: aa)  = x     -- deliberately use a fresh type var name, to show this is not ScopedTypeVariables
```

(Note that the `@aa` TypeApplications syntax was not available at the time 523 was being discussed.)

In what way is the semantics or usage of the `forsome` version different from the `@aa` form? Are there usages you can express with `forsome` that you can't with `@aa`? Or are there (bad) usages with `@aa` that the `forsome` prevents?

Would this (again I'm guessing wildly) be a better example (using the `where type ...` syntax from 523, and using fresh tyvars at each scope to show I'm not `ScopedTypeVariables`):

```
baz :: forall a b. tbaz a b -> tbaz a b
baz @aa @bb (x :: tbaz aa bb) = ...
  where type tbaz aaa bbb = Very Big Type aaa bbb

--  or maybe type params 'bound in' by some magic

baz :: tbazab -> tbazab              -- forall a b. not available here, see discussion
baz @aa @bb (x :: tbazab) = ...
  where type tbazab = Very Big Type aa bb

```

An immediate problem I see is we want `tbaz` (or `tbazab`) to scope over both the definition and the stand-alone signature for `baz` -- and reach there from inside the `where` [**]. And yet this reintroduces exactly the obfuscated scoping from `ScopedTypeVariables` that we're trying to get rid of. A second difficulty is that because `tbaz` needs to appear in three places, it must be parameterised (because the arguments it takes in the signature for `baz` are not in scope in the definition of `baz` -- that is, unless we reintroduce exactly the obfuscated scoping from `ScopedTypeVariables`. (`tbazab` tries to avoid this, but then not only `tbazab` but also `aa` and `bb` somehow magically scope to the standalone `baz` signature.)

[**] We could avoid that by putting `tbaz`'s `type` decl at outer level, but then we've polluted the namespace at that level [***] -- which is exactly against what a local definition is avoiding. At outer level, we'd still need the type params. And we can already achieve that at top level with existing `type` synonyms. (But the `tbazab` form won't work.)

[***] To be fair, an outer decl might be called for anyway, so call sites can use `tbaz` in their signatures. IOW existing `type` synonym. Again it would need to be parameterised.

Have any of my guesses come close to what it is you're proposing? If so, I hope you can see "... the complexity isn't worth it."

**Comment by VitWW** [comment]
> Your idea might be (a bit) similar, but since only you seems to understand your idea, that remark isn't helping anybody else.
> .....
> Have any of my guesses come close to what it is you're proposing? 

I see  you understand my ideas quite well ))

> If so, I hope you can see "... the complexity isn't worth it."

And yes, I see why this Proposal has no future to Approve.

**Comment by VitWW** [comment]
I'm closing this proposal because it propose minimal benefits.
And exists several alternatives, which are already implemented to use them with GHC.

Thanks everyone for feedback!

**Pull request closed without merging**
