### PR TITLE
LLVM Bitcode Backend

### PR DESCRIPTION
**Pull request by angerman**
This proposal intends to change the current textual ir to a bitcode ir
for the llvm backend, which should reduce maintenance burden and allow
a wider range of llvm versions to be used with the produced output.

[Rendered](https://github.com/angerman/ghc-proposals/blob/prop/llvm-bitcode/proposals/0000-llvm-bitcode.rst)

### CODE REVIEW

**Comment by bgamari** [comment]
Hi @angerman!

I appreciate the proposal but I'm not entirely sure it meets the standard of user-facing feature or implementation change that we usually use for the proposal process. Perhaps this would be better suited for Trac?

**Comment by angerman** [comment]
@bgamari fair point. I'm not sure either, I wanted to put this here to get some feedback, also on the scope of the proposal process by example :-)

**Comment by michalt** [comment]
@bgamari One of the nice things of using github for things like that is that one can "watch" the whole `ghc-proposals` repo and see all new proposals. Maybe we could consider having simply a separate github repo for proposals like that (e.g., ghc-proposals-internal)?

@angerman Quick question: I thought that the "improved LLVM backend" idea [1] was to pin GHC to a single LLVM version and ship some LLVM tools with GHC to make sure everything always works. Is this proposal suggesting the opposite (i.e., support more versions of LLVM by using the bitcode?). Or do you see this more as a side benefit of this proposal?

[1] https://ghc.haskell.org/trac/ghc/wiki/ImprovedLLVMBackend

**Comment by angerman** [comment]
@michalt the improved llvm backend is a different story. That is basically a solution to how to fix the textual ir problem using additional tooling; while this proposal basically proposes to rewrite the whole backend with a different approach (namely bitcode instead of textual ir) to sidestep the required tooling; so yes this proposal is proposing something fundamentally different from the ImprovedLLVMBackend idea.

**Comment by nomeata** [comment]
> One of the nice things of using github for things like that is that one can "watch" the whole ghc-proposals repo and see all new proposals

I use the [ghc-tickets mailing list](https://mail.haskell.org/mailman/listinfo/ghc-tickets) to do that. New implementation proposals are easily spotted by not having a `Re:` in the subject line. Tickets of type task or feature request correspond to proposals (many of them internal to GHC).

**Comment by Ericson2314** [comment]
I'm very interested in seeing the non-backend parts of GHC made target-agnostic, for the very user-facing benefit of making GHCJS/CLaSH/HalVM/etc easier to build (and, less user-facing, develop). I'd think even if this change is purely internal, splitting the backend into a plugin is the first step along the path to that goal.

**Comment by cartazio** [comment]
Plugin is a tricky / overloaded word here :)

**Comment by Ericson2314** [comment]
@cartazio I assumed "plugin" meant http://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/extending_ghc.html#compiler-plugins . Is that not correct?

**Comment by angerman** [comment]
@Ericson2314 yes, this uses the same plugin interface, only slightly extended to allow hooking into the compilation pipeline.

I've talked to @luite during icfp2016, and learned that ghcjs takes off from stg, and comes with it's own intermediate representation instead of cmm, which retains more information. So some some additional adapation would be needed.

I have to admit, I have no idea how CLaSH exactly works, nor HalVM. However, the plugin interface in principle allows to bring in any library you want without being restricted to the set of blessed libraries that ship with ghc.

That notwithstanding, my intention here was to be able to iterate fast on the llvm backend, without having to recompile ghc over and over again; the ultimate goal however is to bring the llvm bitcode backend into ghc. Hence I've restricted myself to only the libraries available in ghc. However this approach theoretically would also allow to write a llvm bitcode plugin using the llvm bindings.

@cartazio could you elaborate on the tricky overloaded plugin wording so we can find non-overloaded versions?

**Comment by Ericson2314** [comment]
That reminds me, I wonder whether we can get rid this notion of blessed libraries now that GHC is pretty comfortable with multiple versions of a program abstracted. Cause it would be nice to use nature existing libraries like `llvm-general-pure`.

**Comment by Ericson2314** [comment]
Also, especially now that backpack is almost here, what would the feasibility of keeping the backend a separate library and using a shim executable to tie it all together?

I gather plugins are less than optimal to work with long term.

**Comment by bgamari** [comment]
> That reminds me, I wonder whether we can get rid this notion of blessed libraries now that GHC is pretty comfortable with multiple versions of a program abstracted. Cause it would be nice to use nature existing libraries like `llvm-general-pure`.

I'm afraid not without adversely affecting install plans for packages which link against the `ghc` package. I don't believe backpack helps with this but I could be wrong.

**Comment by Ericson2314** [comment]
Ah those were supposed to be separate thoughts. I meant backpack just for the sake of allowing the backend package to be swapped.

> I'm afraid not without adversely affecting install plans for packages which link against the `ghc` package.

Ah so Cabal is being restrictive even if GHC can handle it. I want to write a proposal for sound private dependencies (IIRC the solver now knows how but it isn't exposed).

**Comment by bgamari** [comment]
> Ah so Cabal is being restrictive even if GHC can handle it. I want to write a proposal for sound private dependencies (IIRC the solver now knows how but it isn't exposed).

@kosmikus has thought about this more than me, but I was under the impression that there exists no sound story here. I very well may be wrong, however.

**Comment by Ericson2314** [comment]
Hmm probably orphan instances.

**Comment by cartazio** [comment]
Abstracting things apart needs to pay for itself.  I suspect it'll be
trickier to split things up than you think

**Comment by cartazio** [comment]
What I mean is: can we keep this discussion in scope to the proposal

Irrespective of how this proposal goes, thank you angerman for taking the
time to do the ground work of prototyping this and such.

**Comment by thoughtpolice** [comment]
> That is basically a solution to how to fix the textual ir problem using additional tooling; while this proposal basically proposes to rewrite the whole backend with a different approach (namely bitcode instead of textual ir) to sidestep the required tooling; so yes this proposal is proposing something fundamentally different from the ImprovedLLVMBackend idea.

I may be misinterpreting you, but this proposal does NOT sidestep most of the concerns in the actual ImprovedLLVMBackend proposal. The only thing this addresses is actual textual IR representation being flaky; but that's mostly a red herring, not relevant to the real point(s) of the original proposal. It does NOT fix problems like users encountering vastly different behavior of the backend in the wild due to version changes, or things like distro inconsistency due to maintainers applying patches (this was a complete nightmare for the longest time on ARM, and could only be solved by manually compiling LLVM yourself). It does not make it any more possible to do things like augment our LLVM installation with plugins for GHC (such as Max's old plugin), or properly tune it for compile-time performance with controlled variables, etc. It's also unclear to me if this addresses any kind of problems with the actual evolution of IR semantics over time (e.g. just because the bitcode format is stable doesn't always mean it's going to behave correctly, from version to version, we may very well need to change the generator anyway to get LLVM to behave how we like).

If I'm misinterpreting this I apologize; I might be reading into "a solution to how to fix the textual ir problem" too much, but the original proposal is *very much* not about textual IR by itself.

These are all effectively QA assurances, and they are all substantially more important to reliability and maintainability than just fixing some textual IR generation stuff (which again, would be for a fixed LLVM version. It's slightly more cumbersome to generate text I guess, but when you completely control the toolchain, it's really not a huge burden.)

---

That said, this is all independent of the actual merits of *this proposal by itself*. It might very well be a good change despite only fixing some code quality issues. I'm basically fine with it, myself, to be honest (the LLVM backend sees little work outside maintainability due to it being a pain, and it's not clear to me if a bitcode will do much more than churn some code, but the reusability aspect is a bonus and I can approve of that. Some LOC numbers would be interesting.)

Probably the main complaint I do have is that you're going to have to add 4 more submodules to GHC (3 + `base16-bytestring`, one of your dependencies), and that will always be a pain. It also will have other impacts and increase the build time a bit, with some constant overhead from the packaging structure alone (e.g. `ghc-cabal` needs to now iterate over 4 more packages, configure them, get their dependencies, etc). That's not a dealbreaker, but I do want to bring it up. Why not just make a monolithic package? I kinda get why people don't like monolithic packages for certain libraries like `lens`, but these 4 libraries effectively are just in the category of "data structure manipulation, with an EDSL" and has effectively no dependencies outside what's available by default. Is there really a need to 'micropackage' something that's only less than 10 modules anyway?

**Comment by nomeata** [comment]
This proposal was not updated in two months. If you think this proposal is its final phase, please tag it as “Pending committee review” (or if it is no longer relevant, please close it.)

**Comment by bgamari** [comment]
Hi @angerman,

As we discussed in the past this proposal has few user-facing consequences and therefore isn't really in the scope of the proposal process. You are welcome to keep discussing this but I'm going to apply the "out-of-scope" label so we can easily sift through it.

**Comment by angerman** [comment]
Ack

**Comment by angerman** [comment]
Let's close this, to not clutter the proposals repo.

**Pull request closed without merging**
