### PR TITLE
Let-less proposal

### PR DESCRIPTION
**Pull request by Icelandjack**
[Rendered](https://github.com/Icelandjack/ghc-proposals/blob/c2e0803320e7651d8dd36f73517e327c07a8e410/let-less.rst).

Allow writing

```haskell
do
  let action :: IO ()
      action = times 5 $ do
          day :: Date <- today

          let adjustedDay :: Date
              adjustedDay = adjust day ...

          token :: SpecialToken <- getRequest adjustedDay

          let request :: SpecialRequest
              request = formRequest token ..

          sendRequest request
```

as

```haskell
do
  action :: IO ()
  action = times 5 $ do

      day :: Date
      day <- today

      adjustedDay :: Date
      adjustedDay = adjust day ...

      token :: SpecialToken
      token <- getRequest adjustedDay

      request :: SpecialRequest
      request = formRequest token ..

      sendRequest request
```

### CODE REVIEW

**Comment by ocharles** [comment]
I have loosely proposed allowing

```haskell
do
  x :: Int
  x <- foo
```

in the past, but it was rightly suggested that this is ambiguous. What if there was already an `x` in scope that was a monadic action? For a less (but still) contrived example:

```haskell
incrementCounter = ...

mkNewIncrementer :: IO (IO ())

foo = do
  incrementCounter :: IO ()
  incrementCounter <- mkNewIncrementer
  ...
```

might be somewhat confusing. I already have an `incrementCounter` in scope which I want to call. I then call `mkNewIncrementer` which performs `IO` and gives me back some `IO`. Thus this `do` block should be `incrementCounter >>= \_ -> mkNewIncrementer >>= ...`, but it seems that under your proposal it would desugar to `let incrementCounter = ... in ...`.

Am I correct in thinking that this is ambiguous?

**Comment by osa1** [comment]
> The change is to allow users to omit let-s when the bindings are not recursive

So if I have

```haskell
xs <- ...
xs = x : xs
```

will `xs` be an infinite list or not? From the proposal it seems like it won't, but that means removing lets may accidentally change semantics without breaking the code.

**Comment by Icelandjack** [comment]
> Am I correct in thinking that this is ambiguous?

Yeah you're right, we could add specific rules but this bums me out

**Comment by ocharles** [comment]
You and me both. 😢

**Comment by Icelandjack** [comment]
@osa1 I think a fair semantics is any time you want recursive bindings you need `let` (`let` becomes similar to `let rec`), so your example would would be `x` consed to the result of `xs <- ...`.

```haskell
-- Prints "hi"
do 
  str = ""
  str = 'i' : str
  str = 'h' : str
  putStrLn str
```

would equal

```haskell
do 
  let str  = ""
  let str1 = 'i' : str
  let str2 = 'h' : str1
  putStrLn str2
``` 

but letting you reuse the same variable name which helps with stuff like [this](https://www.reddit.com/r/haskell/comments/2cin7p/is_there_any_way_to_elegantly_represent_this/).

**Comment by Icelandjack** [comment]
@ocharles I have a few thoughts on how to progress, and I do think this case (running action (discarding value) with type annotation followed by monadic bind that binds the *same* variable name as the action) is rare. 

1. `a :: A` preceding a binding of the same name `a <- mkA` is always type signature

```haskell
do
  incrementCounter :: IO ()
  incrementCounter :: IO ()
  incrementCounter <- mkNewIncrementer

-- =

do
  incrementCounter :: IO ()
  incrementCounter :: IO () <- mkNewIncrementer
```

2. We could have some arbitrary restrictions (that I don't I like), like forcing a newline when the names are the same 

```haskell
do
  -- Annotates type
  incrementCounter :: IO ()
  incrementCounter :: IO () <- mkNewIncrementer


do
  -- Runs action
  incrementCounter :: IO ()

  incrementCounter :: IO () <- mkNewIncrementer
```

3. Introduce a shadowing restriction, "`do x :: (); x <- ...` won't work if `x` is in scope"

**Comment by Ericson2314** [comment]
@ocharles How about:
```
do
  x :: Int <- foo
```
?

Not the most ideomatic, but similar things are allowed with `-XScopedTypeVariables`

**Comment by andreasabel** [comment]
I strongly second this proposal (non-recursive `let` in a do block by omitting the `let` keyword). 
[I am not sure such a comment is in order here, but I did not find a another place to express support.]

**Comment by gridaphobe** [comment]
I also like this proposal a lot, but I'm concerned about the restriction to non-recursive `let`s. In Haskell, `let` binders are always recursive, even inside `do` blocks, so this restriction could be a confusing departure from the expected behavior of `let` binders. (I have mixed feelings about recursive `let` being the default, but I think consistency is important.)

Other than that, 👍

**Comment by andreasabel** [comment]
I think `let` should be non-recursive by default, to avoid looping bugs for shadowing gone wrong.  But of course, the existing `let` cannot be changed.  This proposal allows to at least have a non-recursive let in a `do`-block.  Which is consistent with the also non-recursive nature of the bind `x <- f x`.

**Comment by cartazio** [comment]
i just write 

```
x <- return $ foo
```
when i want let in do.

**Comment by andreasabel** [comment]
@cartazio I am aware of this workaround, and after years got used to it, but it is far from pretty.  It is one of the idiosyncrasies one learns, but in the beginning, I was very puzzled by this.

**Comment by cartazio** [comment]
why not have  <$- as the "applicative let"? :)
or something

**Comment by cartazio** [comment]
point being the type annotaiton based signalling idea sounds horrible

**Comment by Icelandjack** [comment]
Crazy idea

```haskell
do
  :: IO ()
  action = times 5 $ do

      :: Date
      day <- today

      :: Date
      adjustedDay = adjust day ...

      :: SpecialToken
      token <- getRequest adjustedDay

      :: SpecialRequest
      request = formRequest token ..

      sendRequest request
```

**Comment by Wizek** [comment]
> Crazy idea

Bold, if I do say so myself.
But I do like the potential of it reducing duplication of identifiers.

**Comment by Wizek** [comment]
> ```hs
> xs <- ...
> xs = x : xs
> ```
> will xs be an infinite list or not?

@osa1 I'm in favor of this this "desugaring" simply to:

```hs
xs <- ...
let xs = x : xs
```
That way there is no ambiguity.

And grouping desugared let bindings if and only if they are consecutive, like it is [discussed here](https://www.reddit.com/r/haskellquestions/comments/6jdgn1/why_do_we_need_let_inside_do_xallownolet_continued/djdj3ao/).

**Comment by ygale** [comment]
For reference, a [reddit discussion a year ago](https://www.reddit.com/r/haskellquestions/comments/3edtnb/why_do_we_need_let_inside_do/) (now closed), a [reddit discussion a month ago](https://www.reddit.com/r/haskellquestions/comments/6jdgn1/why_do_we_need_let_inside_do_xallownolet_continued/), and a [reddit discussion now](https://www.reddit.com/r/haskell/comments/6rubt9/any_chance_let_in_do_will_be_made_optional/).

**Comment by ygale** [comment]
So how about simplifying the proposal, as follows:

> Every consecutive sequence of one or more = bindings in a do block is treated as if it were wrapped in a single let.

This explicitly removes type signatures from the proposal, because they clash with existing legal syntax in do blocks.

It also now allows recursive bindings, mainly because it makes both statement of the proposal and its implementation much easier. And I'm not sure why it would be so bad to allow it, if the syntax and semantics are clear.

And it now explicitly includes pattern bindings. I'm not sure if those were intended to be included or not previously, but why not?

**Comment by cdsmith** [comment]
Removing the requirement for `let` in equations seems (at my first glance) fine.  It would be a shame if the change broke the equal sign at the same time by making it non-recursive.  That would be enough of a wart that I imagine the community advice would soon be to avoid that misfeature and use `let` anyway.

I don't see a compelling answer to the fact that:

    x = putStrLn "A"
    main = do x :: IO ()
              x = putStrLn "B"
              return x

is ambiguous.  Should this print "A" followed by "B"?  Or just "B"?

**Comment by ygale** [comment]
@cdsmith Under my proposal this would print "A" followed by "B". My proposal only changes the meaning of `=` bindings, which are invalid syntax currently. Everything else remains as before so that no currently valid programs change their meaning.

In particular, if you want to specify an explicit type signature, use an explicit `let`.

**Comment by nomeata** [comment]
While I agree with the motivation of this proposal, I find that the result has a few warts, so I am undecided. 

It seems to me that making let-less bindings non-recursive is a bad choice, for the following reasons:

 * We would lose the ability to explain this feature by a simple syntactic transformatoin to `let`s.
 * If it is non-recursive, I would expect people to want to write

    ```
    do = env = foo env
            env = bar env
            …
    ```
    but this interacts non-intuitively with the provision “When they define a group of declarations of the same name, promote them to the same let binding”
 * It would disallow useful idioms with locally defined local functoins like
    ```
    do = x <- foo

            go 0 = x
            go n = bar (go (n-1))

            …
    ```
  * Unless you are willing to break existing programs, then a line `foo :: IO ()` must be interpreted as a statement (and not a type signature for `foo`). I am unhappy about this conclusion, but it seems inevitable. But this means, as others have pointed out, that if you need to add a type signature to your binding, you have to promote it to a real `let`. If `let`-less bindings are non-recursive, then this is not always possible (without renaming) to do that.

If we’d design the language from scratch, and added this feature from the start, we probably would have made `foo :: IO ()` a type signature (just like as it is on the top level, despite the collision with TH spice syntax.

**Comment by goldfirere** [comment]
Perhaps it would be helpful if someone, say, searched through Hackage for code that would be broken. (This isn't all that easy to do, because you'd need to parse the code.) I don't imagine that type annotations on single-identifier statements in `do` blocks are all that common.

**Comment by ygale** [comment]
@goldfirere Yes, and in fact it's not just single-identifier statements, is it? More than that can appear on the LHS of a type signature. Unless we add "single identifier" as an *ad hoc* limitation. The proposal is not precise in its specification about how to recognize either of the two cases of type signature promotion.

I don't think the type signature features are the central part of the proposal. It would already be quite useful without them, and then the proposal would be completely backwards compatible. Perhaps the type signature features should be split off into a separate proposal that would require more careful study.

**Comment by ygale** [comment]
Here is a motivating example for my proposed modification to the equal-binding part of the proposal:

    do
      evens (x:xs) = x : odds xs
      evens _      = []
      odds = evens . drop 1
      return $ evens [0..10]

The current proposal would desugar as:

    do
      let evens (x:xs) = x : odds xs
          evens _      = []
      let odds = evens . drop 1
      return $ evens [0..10]

resulting in an error. My modified rule would desugar as:

    do
      let evens (x:xs) = x : odds xs
          evens _      = []
          odds = evens . drop 1
      return $ evens [0..10]

which would give the expected result.

**Comment by andreasabel** [comment]
That does not seem to give much benefit except for saving `let` and the indentation.  We already have a recursive let, no need for another one.
I see this proposal as a way to get a non-recursive let into the language.

**Comment by cartazio** [comment]
Why don't we just have an explicit no Rec let instead of this proposal?

**Comment by andreasabel** [comment]
Psychologically, people would not write `let nonrec x = bla` since it is longer than `let x = bla` (and uglier).  Having the right defaults is the art of IT designs of all kinds.  The `do x = bla` non-recursive let proposal gives the right default and less to write.

**Comment by cartazio** [comment]
i dont really care what, but it seems a shame to make the syntax more
complex

**Comment by cdsmith** [comment]
All declarations in Haskell are recursive today.  Why would we want just this one instance to have a different behavior?  If you truly believe that non-recursive let should be the default, perhaps there's a migration path you could propose to get there (though I would disagree).  But this seems like a situation where having *both* depending on where the declarations occur is the worst of all possible worlds.

**Comment by cartazio** [comment]
yeah, either way i'm not in favor of this proposal :)

**Comment by andreasabel** [comment]
> All declarations in Haskell are recursive today.

Nah.  Declarations in a `do` block are not recursive by default: `x <- f x` is not recursive, you need to be explicit about recursion here.

**Comment by cartazio** [comment]
Yeah I do that style all the time.

x <- return $ f x

**Comment by cdsmith** [comment]
Indeed, monadic bindings in `do` blocks are non-recursive.  This is only a question of terminology: following the Haskell Report, I would have called them statements, but not declarations.  There are good reasons why monadic bindings must be non-recursive, though, and a syntax was chosen that is strongly suggestive of the direction.  Neither applies in a declaration.

**Comment by andreasabel** [comment]
Well, then call `x = bla` a statement in a `do` block and all is fine.

**Comment by nomeata** [comment]
What is the status of this proposal? Can it move forward?

**Comment by andreasabel** [comment]
> What is the status of this proposal? Can it move forward?

I'd love to have a non-recursive non-monadic binding construct.

**Comment by nomeata** [comment]
Discussion seemed to have ebbed down. The reactions were mixed… @Icelandjack, do you want to move forward, or withdraw that proposal?

**Comment by Wizek** [comment]
I'd like if we could move forward somehow. It seems the most urgent question at hand is deciding how to deal with some ambiguity, IIRC related to type declarations. Maybe one of us could round up and list the different variants of the proposals we have mentioned in the comments so far, and say if they suffer from ambiguity or not. If no one else does this, I might end up writing this up myself.

**Comment by Wizek** [comment]
I've been thinking about this proposal on and off, and I've just got an idea. Couldn't we resolve much (if not all) of the ambiguity around type signatures with this simple change?

```hs
{-# LANGUAGE LetLessDo #-}

main = do
  foo

  (bar :: IO ())

  qux :: IO ()
  qux = print 1

  qux 

bar = print 2
foo = print 3
```

When the extension is active, just require parentheses around non-declarations that have an explicit type signature.

**Comment by andreasabel** [comment]
Why would you want to allow type signatures like for `bar` to be placed in a different scope than the corresponding definition?

**Comment by ocharles** [comment]
> When the extension is active, just require parentheses around non-declarations that have an explicit type signature. While disallowing parentheses around type declarations for bindings.

That is extremely subtle. I don't know anywhere else where simply adding parenthesis complete changes the parse tree.

**Comment by ocharles** [comment]
> Why would you want to allow type signatures like for bar to be placed in a different scope than the corresponding definition?

That is not what @Wizek is trying to do, it's a response to the ambiguity I raised [here](https://github.com/ghc-proposals/ghc-proposals/pull/62#issuecomment-315142193). The `(bar :: IO ())` is actually a call to `bar`, not giving it a type signature.

**Comment by goldfirere** [comment]
It *is* subtle, but I also think it is relatively uncommon. One could argue that a statement of the form `expr :: type` is ambiguous. What this new proposal says is that we resolve the ambiguity by always treating such a statement as a type signature. When you put parentheses around it, the ambiguity goes away.

I'm still somewhat ambivalent about the proposal overall, but this new suggestion might make sense.

**Comment by ocharles** [comment]
> One could argue that a statement of the form `expr :: type` is ambiguous

Assuming you are referring to Haskell2010 - how?

**Comment by goldfirere** [comment]
No, I'm not. I'm saying that it would be if we could omit `let`, under this proposal.

**Comment by ocharles** [comment]
Ok, I see what you're saying. I still think parenthesis to disambiguate something from a type signature to an expression is pretty unprecedented and very surprising.

**Comment by andreasabel** [comment]
This way of using parentheses seems too subtle.  Rather require the `let` for type signatures, as in:
```haskell
{-# LANGUAGE LetLessDo #-}

foo = print 1
bar = print 2

main :: IO ()
main = do
  foo

  bar :: IO ()

  let qux :: IO ()
  qux = print 3
  
  qux

  let baz :: ()
  baz <- print 4

  return baz
```

**Comment by nomeata** [comment]
>  Rather require the let for type signatures, as in:

It’s an improvement, but it’s weird to have the type signature inside the let and the binding outside. Taking this to its conclusion would lead to:

```
main :: IO ()
main = do
    foo = 43                   -- if no type signature is needed

    let bar :: IO ()           -- if a type signature is needed, then one simply has to
        bar = return 42        -- use let both for the value and the signature.

    (baz :: IO ()) = return 42 -- alternative way
```
I.e. the `let`-less bindings simply cannot have type signatures, and if you want want, you either have to use `let` as before, or use a signature on the pattern.

**Comment by cdsmith** [comment]
Since this would be an explicitly enabled language extension, I don't think it's disqualifying to go the route of resolving ambiguities in favor of a type signature.  As @goldfirere says, this is probably rare anyway.  If this were considered for inclusion in Haskell2025, then you'd need a long deprecation cycle in which GHC warns about ambiguous cases when the extension isn't enabled.

If this proposal is coming back to life, I'm more concerned about the situation with non-recursive bindings.  The syntax

    foo :: Int
    foo <- [1 .. 5]

looks really weird when `foo` isn't even in scope at the point of its type annotation.  What about this one, where `bar`'s type annotation doesn't even directly precede its binding?

    foo, bar :: Int
    foo <- [1 .. 5]
    bar <- [1 .. foo]

Or this one, where `foo` *is* in scope, but will later be shadowed?

    let foo = 27
    foo :: Char
    foo <- "abcdefg"

How far are we willing to push toward putting type annotations in places where their names aren't even meaningful?

**Comment by Wizek** [comment]
> @cdsmith: Since this would be an explicitly enabled language extension, I don't think it's disqualifying to go the route of resolving ambiguities in favor of a type signature. As @goldfirere says, this is probably rare anyway.

Yes, thanks for putting this into words @cdsmith and @goldfirere. That was my thinking exactly: With this syntax, let's favor the more common use case (declaring a value with an explicit signature) to the much less common one (using a value in a monadic context and giving it an explicit signature at the same time). And we can favor the much more common usecase by allowing it to have a lighter syntax. I think that makes tremendous sense. And as you also point out, it's also not a problem if this is a small breaking change since it is all hidden under this language extension anyway. (And for all the modules that don't sport any such uncommon syntax it's not even a breaking change.)

> @andreasabel: This way of using parentheses seems too subtle. Rather require the let for type signatures, as in
> 
> ```hs
>   bar :: IO ()
>
>   let qux :: IO ()
>   qux = print 3
>   
>   qux
> 
>   let baz :: ()
>   baz <- print 4
> ```

This would go against the above idea of favoring the most common usecase with the lighter syntax. @andreasabel, do you perhaps agree with that principle, even if you are not sold on any concrete solution path yet?

> @cdsmith: If this proposal is coming back to life, I'm more concerned about the situation with non-recursive bindings. The syntax
> 
> ```hs
> foo :: Int
> foo <- [1 .. 5]
> ``` 
>
> looks really weird when foo isn't even in scope at the point of its type annotation. What about this one, where bar's type annotation doesn't even directly precede its binding?
>
> ```hs
> foo, bar :: Int
> foo <- [1 .. 5]
> bar <- [1 .. foo]
> ```
>
> Or this one, where foo is in scope, but will later be shadowed?
>
> ```hs 
> let foo = 27
> foo :: Char
> foo <- "abcdefg"
> ```
> 
> How far are we willing to push toward putting type annotations in places where their names aren't even meaningful?

You raise some very valid questions in your code examples, thank you for thinking them up and sharing them!

However, if my thinking is correct, this seems like it only complicates implementation, and does not introduce any ambiguity. My thinking on another train of thought was going in this direction: Let's try to present the user with the same/very similar syntax and semantics as with top level declarations. So I'd argue they should work exactly as a new or even seasoned Haskell developer would expect them to work. As in, all of your ideas type check in the list monad. Even the 3rd snippet is unambiguously correct.

If we wanted that middle line refer to the line above, we could do this, again, unambiguously:

```hs 
let foo = [1, 2]
(foo :: [Int])
foo <- [3, 4, 5]
```

Your second code snippet might pose the most challenge in terms of implementation, but still I don't see any ambiguity in terms of semantics or expectation: to me it seems the user clearly intends both `foo` and `bar` to have the type `Int`.

And I think I am slightly in favor of having recursive bindings (for pure declarations anyway, consecutives to form groups), so that might be an answer. Again, to keep it similar to top level declarations. For monadic bindings this may be a bit trickier in a non-MonadFix context; but just to stress my point once more, this seems to me to be only an implementation difficulty, not a semantic ambiguity. What do you think?

**Comment by nomeata** [comment]
Not much happening here, marking as “dormant” for now.

**Comment by nomeata** [comment]
Dormant for a while; I’m closing this (but it can be reactivated of course)

**Pull request closed without merging**
