### PR TITLE
Optional tuple parenthesization

### PR DESCRIPTION
**Pull request by Icelandjack**
Allow writing 

``` haskell
case (f', x') of
  (Done g,        Done y       ) -> ...
  (Done g,        Blocked cr c ) -> ...
  (Blocked br c,  Done y       ) -> ...
  (Blocked br1 c, Blocked br2 d) -> ...
```

as

``` haskell
case (f', x') of
  Done g,        Done y        -> ...
  Done g,        Blocked cr c  -> ...
  Blocked br c,  Done y        -> ...
  Blocked br1 c, Blocked br2 d -> ...
```

Ties in with proposal #18.

[Rendered](https://github.com/Icelandjack/ghc-proposals/edit/noparen/proposals/0000-no-parens.rst).

### CODE REVIEW

**Comment by gridaphobe** [comment]
I'm pretty strongly against this, as I think it is one of the worst syntactic worts of OCaml. For example, you would presumably allow

```
let x, y = 1, 2 in ...
```

which does look a bit nicer than the parenthesized version, but now how do we parse

```
let x = [1, 2] in ...
```

Clearly this should be a list containing two `Int`s, but with the optional parentheses you could argue instead (as in OCaml) that it should be a list containing a single **pair** of `Int`s. To OCaml's credit, they at least use a semicolon do separate list elements so there's no ambiguity, it's just unintuitive.

This is presumably why the proposal says to only allow optional parens "where unambiguous", but the grammar needs to not only be unambiguous to the parser, it needs to be intuitive to users. And I don't think this will be intuitive.

**Comment by trofi** [comment]
@Icelandjack, have you already tried by chance modifying parser to accept the grammar?
I wonder how many new happy conflicts will arise. That should be a good quantitive estimation
on how invasive the extensions is.

**Comment by erikd** [comment]
Sorry, I'm not keen on this. I don't think the (IMO very minor) benefits are worth the initial effort and the ongoing maintenance burden.

**Comment by cartazio** [comment]
I guess one question is then x,y,z would correspond to one of three possible tuples. If this were an infix operator or data constructor it would have to be binary only. 

I guess one point is that Haskell has, in a pretty fundamental way that I kinda like, arity > 2 tuples.  This is especially true of how ghc is designed

This proposal makes these higher arity tuples second class

**Comment by simonmar** [comment]
It doesn't seem worth complicating the syntax and making parsing harder (both by humans and computers) for little benefit.  -1 from me.

**Comment by jstolarek** [comment]
Tuples without parentheses is one of the worst features of OCaml. I'm strongly against bringing it to Haskell.

**Comment by bgamari** [comment]
I agree with -1s above; this complicates parsing and reasoning in the
name of a very questionable "aesthetic" benefit.

**Comment by treeowl** [comment]
I suspect many of the problems others have mentioned would go away if you replaced special syntax for pattern matching on a tuple with special syntax for matching on more than one value in a single `case`. One seemingly reasonable flavor:

```haskell
case f', x' of
  Done g, Done y -> ...
  Done g, Blocked cr c -> ...
  Blocked br c, Done y -> ...
  Blocked br1 c, Blocked br2 d -> ...
```

Another question to consider: will people want to borrow something like Agda's `with` syntax once `DependentHaskell` shows up? How might that affect other extensions of pattern matching syntax?

**Comment by crabmusket** [comment]
@Icelandjack I don't mean to be rude but it might be a good idea to follow the [proposal template](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0000-template.rst) recommended in #1. This might help people understand the reasoning behind your proposed changes and engage with it in a deeper way.

**Comment by goldfirere** [comment]
I like @treeowl 's suggestion a good deal. It pains me when I have to use tuples just when I want multi-case. And the syntax is simple and unambiguous.

In answer to this (asked also by @treeowl ):
> will people want to borrow something like Agda's with syntax once DependentHaskell shows up? How might that affect other extensions of pattern matching syntax? 

I see Agda's `with` syntax as something that would be just as useful today, without dependent types, as tomorrow. It's a small bit of sugar... is it worth it? Perhaps. In any case, one big reason it's so prevalent in Agda is that Agda has no `case`, supporting only function-definition-by-pattern-matching. So I don't think we have to get too worried about `with` in Haskell.

**Comment by treeowl** [comment]
The piece missing from my idea is a way to pattern match on a record constructor (or several such) and then immediately inspect the fields.

```haskell
case r1, r2 of
  R1 foo bar, (baz, quux) ->
    case foo, bar, baz, quux of ...
```

seems a bit awkward. If not for the ambiguity of explicit type application, I'd suggest

```haskell
case r1@R1 foo bar, r2@(baz, quuz) of
  Pfoo, Pbar, Pbaz, Pquux
```

but maybe some other variation on this will work.

**Comment by treeowl** [comment]
(And I do think that the multi-value case would be useful, even without extra record-unpacking syntax, for the reasons Richard expressed.)

**Comment by goldfirere** [comment]
I'm afraid I don't follow your recent remarks, @treeowl. I don't see any record constructors (with record syntax `{ field = value, ... }`). Could you write out a full example that perhaps seems verbose and explain how you might shorten/simplify it? Thanks!

**Comment by Ptival** [comment]
I like @treeowl 's original suggestion. In fact, Coq does this, and lets you write something like:

```
Definition foo :=
  match 1, 2 with
  | a, b => (b, a)
  end.
```

Where the remaining parentheses are mandatory.

**Comment by cartazio** [comment]
Possibly dumb question: would unboxed tuples have the right semantics here?

**Comment by nomeata** [comment]
The link to the rendered version is wrong, should be <https://github.com/Icelandjack/ghc-proposals/blob/noparen/proposals/0000-no-parens.rst>.

**Comment by treeowl** [comment]
@cartazio, that would be the translation of my suggested modification. The ability to use non-`*` kinds would be an additional benefit of that modification. @Icelandjack, I'd love to hear what you think about my suggestion.

**Comment by cartazio** [comment]
Can we already use unboxed tuples in that way?


There is a gotcha to this: what is the match / evaluation order in the multi arg case?

In the presence of eg dependent types this actually comes up for pattern matching. Which is why recent agda only accepts matching equations that can be desugared to what I believe is called an "exact splitting tree". Roughly we need to articulate what the semantics of evaluation order are for a pair of thunks.  

In function pattern matching we do left to right, but it also gets kinda tricky. 

I guess a flip question is that for boxed tuples, do we have a semantics for the order we match on the fields in a case?

**Comment by nomeata** [comment]
This proposal was not updated in two months. If you think this proposal is its final phase, please tag it as “Pending committee review”.

**Comment by treeowl** [comment]
@nomeata, it seems there's more support for my modified version than the original. What's the appropriate protocol for dealing with that? @cartazio, I refer you to Haskell 2010, sections 3.17.2 and 3.17.3.

**Comment by nomeata** [comment]
>  The ability to use non-* kinds would be an additional benefit of that modification.

This may be the single most convincing point about this proposal.

> @nomeata, it seems there's more support for my modified version than the original. What's the appropriate protocol for dealing with that?

I suggest you write your variant up as a proposal and start a new pull requests. They are different after all. If @Icelandjack thinks yours is better than this, then he can close this pull request.

**Comment by bgamari** [comment]
@Icelandjack, note that this proposal is one week from the end of its four-week long discussion period. At the end of this time we will ask you to summarize the discussion and optionally bring the proposal to the steering committee for consideration.

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by nomeata** [comment]
Another ping. @Icelandjack, whither this proposal?

**Comment by nomeata** [comment]
Due to lack of activity, I am marking this proposal as [dormant](https://github.com/ghc-proposals/ghc-proposals/#what-is-a-dormant-proposal).

**Comment by nomeata** [comment]
This has been dormant for a long time. @Icelandjack, is this abandonned? In that case, please consider closing it.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Pull request closed without merging**
