### PR TITLE
Pointer Rep

### PR DESCRIPTION
**Pull request by andrewthad**
[Rendered link](https://github.com/andrewthad/ghc-proposals/blob/pointer_rep/proposals/0000-pointer-rep.rst)

### CODE REVIEW

**Comment by rrnewton** [comment]
This seems like the rare proposal that doesn't add complexity and yet cleans up existing problems and results in stronger types for primops.  If there's a downside, it has eluded me.  Looks great!

(Personally, I'm also excited about the ability to put unlifted pointer types in IORefs and MVars -- slowly, slowly, we are getting that efficient imperative/strict language hiding inside Haskell 😉.)

**Comment by andrewthad** [comment]
Thanks! Also, if anyone's got any other good examples of where it's useful to put something unlifted inside an `IORef` or a `MVar`, I'd be happy to include them in the proposal. I want this from time-to-time in my own code, but I had a hard time finding any good "in the wild" examples of where this would be benefits.

**Comment by andrewthad** [comment]
cc @treeowl I suspect you and interested in this, and I would appreciate any feedback you have.

**Comment by chessai** [comment]
Strong +1 from me

**Comment by simonpj** [comment]
> This proposal does not loosen any of the restrictions around where representation polymorphism can be used. 

I'd like this to be more explicit.  Specifically, the current restriction on any lambda-bound variable is that it may not have a type whose kind is `TYPE r` where `r` is a variable; it must have `TYPE IntRep` or `TYPE LiftedRep`, with no variables.

Here one might wonder: can you have a term `/\(l :: Levity) (a::TYPE (PtrRep l)). \(x :: a). blah`?  You might think "yes" because the representation of `x` is a pointer.  But we can't tell whether or not it's a _lifted_ pointer, and that's vital for the correct strictness semantics.

So the rule for levity polymorphism becomes that a lambda-bound variable must have a type whose kind is `TYPE rtr`, where `rtr` is a runtime-rep that has no variables (`RuntimeRep` variables or `Levity` variables).

Could make that 100% explicit.  Feel free to steal language from the levity-polymorphism paper.

**Comment by andrewthad** [comment]
@simonpj I've modified that section to be more explicit. Let me know if it now has everything you are looking for.

**Comment by goldfirere** [comment]
When we designed levity polymorphism, we wondered if the proposed design here was the right way to go. I think we hadn't identified any use cases for it. Now that you have, I think this is a good direction.

**Comment by cartazio** [comment]
I like the flavor of this proposal ..  but why can’t unlifted and lifted reps be type or pattern synonyms under the proposal ? 

Also ... what type do I give instead of LiftedRep and unliftedRep

Ptr Lifted and Ptr unlifted?  

On the face of it this looks to be a good design though.  

It would be good to access what / if any knock on breakage it might trigger though.  Even though most code shouldn’t be impacted by this, it’s a very core / fundamental cleanup and it’s worth understanding impact.

**Comment by andrewthad** [comment]
I’ve  updated the proposal with an explanation of why using type synonyms for LiftedRep and UnliftedRep doesn’t work out totally well.

**Comment by treeowl** [comment]
I would hope you'd *generalize* weak references along the other axis, allowing keys to be associated with *values* of different levities.

```haskell
mkWeak# :: forall {vu :: Levity}  {vb :: Levity} (u :: TYPE ('PtrRep vu)) (b :: TYPE ('PtrRep vb)) (c :: Type).
  u -> b -> (State# RealWorld -> (#State# RealWorld, c#)) -> State# RealWorld -> (#State# RealWorld, Weak# b#)
mkWeakNoFinalizer# :: forall {vu :: Levity} {vb :: Levity} (u :: TYPE ('PtrRep vu)) (b :: TYPE ('PtrRep vb)).
  u -> b -> State# RealWorld -> (#State# RealWorld, Weak# b#)
```

Side note: `with#` can *already* be generalized along another axis, so you might as well make it

```haskell
with# :: forall {vu :: Levity} {vr :: Levity} (u :: TYPE ('PtrRep vu)) (s :: Type) (r :: TYPE ('PtrRep vr)).
  u -> (State# s -> (# State s, r #)) -> State# s -> (# State# s, r #)
```

**Comment by treeowl** [comment]
Note to email followers: my last comment has been edited.

**Comment by treeowl** [comment]
Edited twice, now.

**Comment by andrewthad** [comment]
I was hoping it was possible to generalize `Weak` further as you've suggested. That's good to know. And I agree that `with#` should be fully representation-polymorphic in the return value. Does anyone know if `StableName#` and `StablePtr#` are able to support unlifted types? I suspect that they are, but I'd like something more familiar with their implementations to confirm this.

**Comment by treeowl** [comment]
@andrewthad, yes, they certainly can! The fussy bits of stable names and pointers have to do with storage management; they really don't care about lifted vs. unlifted. That reminds me that I should turn back to my interrupted project to replace both of those systems, but that's entirely orthogonal.

**Comment by andrewthad** [comment]
For sure, the  mutable constructor fields  proposal blows up MutVar.   Most high-performance code using MutVar  would be better suited by mutable constructor fields. But all of the other types generalized by this proposal  are still just as useful  in a post mutable constructor fields world.

It’s good to know that about stable names and stable pointers.  I will update the proposal to include their generalization as well.

**Comment by andrewthad** [comment]
I've incorporated @treeowl's changes. My only remaining question is about painting the bikeshed. What's a better name for this: `PtrRep`, `HeapRep`, `ManagedRep`? The weird thing about `PtrRep` is that we have something else called `AddrRep`. The latter is for memory that may not be managed by GHC's runtime, and the former is for things that are definitely managed by GHC's runtime. I don't feel strongly on this, and I'll probably just punt this decision to the committee as part of the proposal, but if anyone has any thoughts, they can certainly be taken into consideration.

**Comment by simonpj** [comment]
I like `PtrRep`.

**Comment by iamrecursion** [comment]
I’ve nothing against `PtrRep`, but the potential for confusion with `AddrRep` is a good point. If I had to pick another name, I’d probably go with `ManagedRep`. It’s more explicit than `HeapRep` to me.

**Comment by cartazio** [comment]
No matter the name, it’s gonna be something that you need to follow the
docs on

**Comment by iamrecursion** [comment]
Very true, which is why I don’t feel like the exact choice of name is a big problem.

**Comment by andrewthad** [comment]
We've now had a chance to have the bikeshedding discussion, and it appears that there are no more substantive issues (everyone seems to be on board with the question of "is this actually sound?"). I'd like to submit this proposal to the committee, requesting as well that thte committee decide the name of the new data constructor.

**Comment by treeowl** [comment]
@nomeata, that means you.

**Comment by nomeata** [comment]
Technically, I usually prefer to wait for at least about a week of silence before going to the next state. But given that this is positively received, and mostly a low-level change, I’m find with finding a shepherd directly.

**Comment by cartazio** [comment]
I do think it would be good to experimentally identify if there’s
unexpected breakage from this change , though it eeems fine

**Comment by andrewthad** [comment]
I'm documenting this here so that I don't forget it, but oddly `readTVarIO` doesn't generalize like all of the other `TVar` operations do. The problem is that it is implemented in cmm as:

```
stg_readTVarIOzh ( P_ tvar /* :: TVar a */ )
{
    W_ result;

again:
    result = StgTVar_current_value(tvar);
    if (%INFO_PTR(result) == stg_TREC_HEADER_info) {
        goto again;
    }
    return (result);
}
```

Since it expects an info table pointer, this only works with lifted types.

**Comment by andrewthad** [comment]
Actually, there's some conditional code for `readTVar` as well that does some `UNTAG_CLOSURE` and `GET_INFO`. This may be the real problem. I think that supporting unlifted pointers in `TVar`s is beyond my ability, so I may need to retract that part of the proposal.

**Comment by nomeata** [comment]
Accepted as Proposal 45.

**Comment by simonpj** [comment]
> oddly readTVarIO doesn't generalize like all of the other TVar operations do. 

I'm no expert here, but this smells odd to me.  I'd like us to understand why it doesn't generalise, rather than just accept that (on the surface) it doens't.   Maybe there are some GHC-STM experts out there.  See who committed the code you point to.  Etc.

**Comment by simonmar** [comment]
I don't see any problem here, @andrewthad what is it you're concerned about with `readTVar` and `readTVarIO`?

**Comment by andrewthad** [comment]
Sorry, I'd been playing around with `TVar`s with boxed unlifted payloads in [primitive-unlifted](https://github.com/andrewthad/primitive-unlifted), and I accidentally used `readTVar#` where I should have used `readTVarIO#`. I've fixed this, and as everyone expected, there is not actually a problem with generalizing this primitive.

**Comment by sgraf812** [comment]
I'm a little late to the game, but here are my comments:

> What's a better name for this: PtrRep, HeapRep, ManagedRep? The weird thing about PtrRep is that we have something else called AddrRep.

Yes, *very* much! In fact, I got hung up about this in the past, too: See the 3 comments starting at https://gitlab.haskell.org/ghc/ghc/issues/9279#note_159956.

@goldfirere already made precedent in his levity polymorphism work and wrote a function called [`isGcPtrRep`](https://gitlab.haskell.org/ghc/ghc/blob/b1613985252990600a2c7d789054c74470260959/compiler/types/TyCon.hs#L1419). So why not call it `GcPtrRep`? It's shorter than `ManagedRep`, which I'd prefer otherwise. Managed/Unmanaged are terms I'm very familiar with, coming from a C# background ([example](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getmanagedthunkforunmanagedmethodptr?view=netframework-4.8#System_Runtime_InteropServices_Marshal_GetManagedThunkForUnmanagedMethodPtr_System_IntPtr_System_IntPtr_System_Int32_)). Anything, but please don't just call it `PtrRep`.

Nit: In the proposal you write

> It is possible to loosen the binder restriction, but this proposal does include such a change since it would make implementation more difficult.

But I think you specifically mean that this proposal does *not* include such a change.

Is there an MR somewhere?

**Comment by andrewthad** [comment]
Unfortunately, I don't have an MR for this. A few months ago, I spent an hour or two working through all the weird `RuntimeRep`-like types that give it its wired-in magic, and I've not picked it back up since then. I don't think implementing this should be hard. It just requires having a block of maybe ten or fifteen hours to sit down and just grind through it. I've not been able to find that time. I hope to find the time at some point over the holidays, but I may not, so if anyone else wants to give this a try, go for it.

Concerning the naming, I don't know what the procedure is. I defer entirely to the committee on this issue. The committee approved the name `PtrRep`, and I don't what the procedure is for changing a proposal that has already been approved. (Perhaps you could open a PR that modifies the existing proposal?) For what it's worth, I don't particularly like `GcPtrRep`. I find it strange to mention garbage collection (an implementation detail) in the name of a type or kind. Come to think of it, I cannot believe I didn't consider the name `BoxedRep` earlier. This name actually fits in rather nicely with the existing literature around GHC. For example, this name scheme can be seen in the [Levity Polymorphism](https://www.microsoft.com/en-us/research/publication/levity-polymorphism/) paper, where Figure 1 is a four-quadrant table that illustrates the boxed vs unboxed and lifted vs unlifted distinctions.

**Comment by andrewthad** [comment]
The committee has included a procedure for amending a proposal in https://github.com/ghc-proposals/ghc-proposals/pull/299. @sgraf812 Let me know what you think of `BoxedRep`. I'm inclined to amend this.

**Comment by sgraf812** [comment]
I think `BoxedRep` is better, but I tend to associate "pointer" with "box". Which is probably wrong when you don't know what you point to. What's wrong about `ManagedPtr`? If that's a no go, I'd be fine with `BoxedRep`.

**Comment by andrewthad** [comment]
`ManagedPtr` (which would actually need to be `ManagedRep` or `ManagedPtrRep`) is alright, but I like `BoxedRep` more because it's (1) shorter and (2) much more consistent with the language that GHC uses. The word "boxed" is already used on the GHC wiki, in published papers, and all throughout the GHC source code. The word "managed" is entirely absent from the Levity Polymorphism paper, doesn't show up in the wiki's [discussion of unboxed types](https://wiki.haskell.org/Unboxed_type), and shows up less frequently in the GHC source.

**Comment by sgraf812** [comment]
Alright, `BoxedRep` it is!

**Comment by sgraf812** [comment]
While implementing the unlifted datatypes proposal, I realised that this proposal leaves open the question of whether to default inferred `Levity` type variables to `Lifted`.

Should we or shouldn't we default `Levity`? Or is that a question that is out of scope for this proposal, because there is no language construct (to my knowledge) that allows us to observe defaulting?

**Comment by simonpj** [comment]
Good point.   I think we should default, else we risk getting unexpectedly complicated types.  (Same with linearity I think.)

Examples would help.

**Comment by sgraf812** [comment]
In https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2218#note_336453, I argue that we should not default `Levity`.

**Comment by nomeata** [comment]
According to https://well-typed.com/blog/2022/02/ghc-2021-12-2022-01/ this is completely implemented now. Can someone confirm that it is complete, and which GHC will contain these changes?

**Pull request merged**
