### PR TITLE
Namespace specifiers

### PR DESCRIPTION
**Pull request by goldfirere**
This proposes using `type` and `data` liberally in programs to specify namespaces where desired. It also hypothesizes a way forward toward dealing with the Dreaded Namespace Problem when imagining dependent types in Haskell.

[Rendered](https://github.com/goldfirere/ghc-proposals/blob/namespaces/proposals/0000-namespaces.rst)

### CODE REVIEW

**Comment by int-index** [comment]
On the main proposal: I fully support it, and I think it doesn't go far enough. Let's also deprecate `'` as a namespace specifier because we need it for TemplateHaskell name quoting, which is currently impossible on the type level. By the way, we use `'` for quoting names in the data namespace and `''` for quoting names in the type namespace. What do you imagine we should use for the `module` namespace? What about `data '`, `type '`, and `module '` quoters? For example, `makeLenses (type 'Foo)` instead of `makeLenses ''Foo`.

On the annex: I don't understand the motivation behind a new `default` namespace. Just pick `type` or `data` as the default namespace and don't introduce a new entity. If anything, we need less namespaces, not more.

**Comment by int-index** [comment]
Here's my take at the issue from https://github.com/ghc-proposals/ghc-proposals/pull/106#issuecomment-400936000:

* Add a new extension,` -XConsistentNamespaces`, that enables the new behavior.
* Prohibit ticks as namespace specifiers, so given `data Nat = Zero | Succ Nat` and `data P a = MkP`, writing `P 'Zero` is illegal, `P Zero` is legal.
* In modules where `-XConsistentNamespaces` is enabled, warn when declaring data constructors and type constructors with the same name. `data Proxy a = Proxy` will continue to work, but cause a warning.
* Make the data constructor namespace the default in both terms and types. Today the data constructor namespace is the default in terms, but in types it is not and we need ticks to override. With `-XConsistentNamespaces` we just don't need ticks.
* In case there's a namespace conflict, use the `type` qualifier to resolve it. So given `data Proxy a = Proxy`, writing `Proxy` always means the data constructor (regardless of context), and writing `type Proxy` always means the type constructor. Under `-XConsistentNamespaces`, `fn :: Proxy a -> ..` becomes `fn :: (type Proxy) a -> ..`, possibly without the parentheses. 
* A few more examples. `[Int]` becomes `(type [] Int)`, and `'[Int]` becomes just `[Int]`. `()` becomes `type ()` and `'()` becomes just `()`. We also define type `List = type []` and `type Unit = type ()` in `base` to avoid verbose qualifiers.

I really like that with the `type` namespace qualifier, a type synonym

```
type A = ...
```

looks just like a term level definition!

```
a = ...
```

as if it was merely a matter of the namespace (because with DependentHaskell it will actually become just a matter of namespace).

Other advantages of this approach:

* Haskell98 code continues to work, and take advantage of two namespaces
* code that needs `-XDataKinds`, `-XDependentHaskell`, and the like, can enable `-XConsistentNamespaces` and reap the benefits of having no ticks and having very simple namespacing rules: it is always the data namespace except when the `type` qualifier is used.

What other syntactic harmonies does it create? Consider associated type families:

```
class Container c where
  type Elem c :: Type

```

This does look like simply adding another method to `Container`, modulo namespaces!

```
class Container c where
  elem :: Type
```

(There is a bit of inconsistency as to whether the `c` type parameter goes to the left of `::`, but we'll have to deal with this too, I think #148 provides a way forward).

----

>  If we always prefer the data namespace, then the type of `[True, False]` becomes `type [Bool]`. That's terrible.

No, that's perfect! One can define `type List = type []` and write the type of `[True, False]` as `List Bool`. I've argued for this arrangement in https://int-index.com/posts/haskell-punning (see also the [Reddit discussion](https://www.reddit.com/r/haskell/comments/aliohu/termtype_punning_in_haskell_the_hidden_cost_of/)).

**Comment by nomeata** [comment]
Nice! Especially the summary of the state of affairs. Say, who designed this language???

> Calling a function, such as (+) a data is awkward. Yet it is simply too tempting to use data here, due to its status as a keyword.

Not worried about this. Functions are first class values in a functional language. We can stress this!


What still bugs me is that after
```
data Foo = Foo
```
I can write `data Foo` and it refers to the thing on the right of the `=`!

But I see a nice way out: If you drop the rule that namespace quantifiers may not be used in binding positions, I can write
```
data type Foo = Foo
```
which is, like, perfect, because we call `Foo` a data type!

(Maybe forbid `type type Age = type Int`, and just re-interpret `type Age = type Int` as what it is)

**Comment by simonpj** [comment]
Could you extend the proposal with a raft of examples, including  a representative sprinkling of all the current contexts?

Suppose
```
f :: forall a -> a -> Int
```
then it seems noisy to write
```
f (type TYPE (type LiftedRep)) True
```
I'd prefer to write
```
f (type (TYPE LiftedRep)) True
```
Does a namespace qualifier followed by an open-paren cover the entire parenthesized thing?  I hope so.

**Comment by nomeata** [comment]
> Does a namespace qualifier followed by an open-paren cover the entire parenthesized thing? I hope so.
Yes, it does!

**Comment by simonpj** [comment]
Currently with
```
data T = MkT
```
I can write
```
f :: S MkT -> blah
```
and since there is no `MkT` in the type namespace, GHC tries the term namespace.   You propose to stop that, correct?  So we'd ave to write
```
f :: S (data MkT) -> blah
```

**Comment by simonpj** [comment]
Bikeshed: choices for the value-space keyword
* `data`
* `value`
* `term`
Each has some merit.  I'm actually not stressed about stealing the use of "value" as an identifier.  I have never used it, and it's easy to avoid.  (In contrast I sometimes want `in`, as in `i1`, `i2`... `in`.)

**Comment by simonpj** [comment]
> Does a namespace qualifier followed by an open-paren cover the entire parenthesized thing? I hope so.  Yes, it does!

It's hard to tell for sure without seeing some BNF syntax.  Could that be added?  Currently there is just a highly cryptic note:  "A namespace specifier describes the namespace for all names used in its scope. (This scope may contain multiple names if a ( follows the namespace specifier.)"

**Comment by int-index** [comment]
> then it seems noisy to write `f (type TYPE (type LiftedRep)) True`

I think it should be written `f (TYPE LiftedRep) True`, the `type` / `data` namespace qualifiers are only needed when there's ambiguity.

**Comment by int-index** [comment]
>  I'm actually not stressed about stealing the use of "value" as an identifier

Not a good option, it's used widely: https://hoogle.haskell.org/?hoogle=value

**Comment by int-index** [comment]
> Does a namespace qualifier followed by an open-paren cover the entire parenthesized thing? I hope so.

It doesn't sound like a good idea to me, as it creates more context-sensitivity when reading code. Imagine reading something that alternates between `data` and `type`!

```
type F = type [Proxy (data [type Proxy, type Identity])]
```

Just writing it out gave me a headache.

**Comment by goldfirere** [comment]
I have updated the proposal:

* Add treatement of TH quotes in new mechanism.

* Raise question about deprecation of `'` in types.

* Examples added.

* New part of proposal about module-level `ANN` pragmas.

**Comment by int-index** [comment]
The proposed change specification says only this:

> A namespace specifier may prefix a name any place a name can occur. It states what namespace the name belongs to. 

But then in "Effect and Interactions" there's a stronger claim:

> Namespace specifiers can now scope over a region of code, for convenience.

I don't see how it follows, and it's also not clear if this is a good idea because of the additional context-sensitivity that it creates, as I mention in https://github.com/ghc-proposals/ghc-proposals/pull/214#issuecomment-473211051. Inclusion of this "convenience" feature also encourages the style of code where names require disambiguation, while making namespace specification cumbersome encourages using names that don't require disambiguation, so I feel that it creates undesirable incentives. Can we make that a separate proposal?

**Comment by int-index** [comment]
What's the treatment of variable names under this proposal? The motivation section lists visible dependent quantification in terms, so can I write this?

```
id :: forall a. a -> a
id a = id_vdq (type a) (data a)

id_vdq :: forall a -> a -> a
id_vdq _ x = x
```

I would much prefer if we unified the term/type variable namespaces instead, so let's mention it explicitly in the proposal that namespace specifiers cannot be applied to variables.

**Comment by simonpj** [comment]
Thanks for the changes.   Can we please see the change to Haskell's BNF syntax?

**Comment by simonmar** [comment]
>  Each has some merit. I'm actually not stressed about stealing the use of "value" as an identifier...

We do use `value` as an identifier in quite a few places in GHC, e.g. https://gitlab.haskell.org/ghc/ghc/blob/master/compiler/simplCore/CoreMonad.hs#L643 

Sure it's easy to fix in simple local variables like this, but some of the uses in the wild are in APIs that have many users, such as https://www.stackage.org/haddock/lts-12.19/aeson-1.3.1.1/Data-Aeson-Parser.html#v:value

**Comment by Ericson2314** [comment]
This also opens the door to `(type MySum).constructor` and `(type MyConstructor).field`, which is a side effect I'm quite fond of.

**Comment by AntC2** [comment]
If we're thinking about naming conventions, and anticipating dependent Haskell ...

I've always found it weird that if functions at the term level start lower-case, why do functions at the type level (i.e. Type Families) start upper-case? Presumably Type Family names are included in the **Background/Namespaces** point 4. 'Types and type constructors'. But Type Families are not Types, neither are they in general 'constructors', because they're not injective -- that always throws me when reading signatures.

Is there some reason Type Families couldn't start lower-case? If we could begin afresh, I'd want injective TFs to start upper-case (like pattern synonyms), non-injective to start lower.

**Comment by goldfirere** [comment]
I have updated the proposal to add some BNF syntax and to recast namespace specifiers to be like module prefixes, requiring a `.`. Feel free to suggest that the old version of the proposal was better, but this new version seems simpler.

One thing lost in the new version is the ability to scope a namespace specification over several names. In its place, I have added a "Future Work" section that suggests that we find some syntax for importing a whole bunch of type names into terms and vice versa.

In response to specific points above:
- Variable (local) names are treated like any other names. I do not wish to merge the type and data namespaces here, as I want this proposal to be only about specifiers, not changing any other behavior. (Note that merging the namespaces for local variables would be a breaking change.)

- The challenge with making type families lower-case is that implicit quantification of type variables would then have to be changed to make it work only over type variables that are not spelled like a type family. This actually isn't so bad, but there is a reason type families are upper-case. I hope that, in the future, type families are gone entirely, replaced by functions that can be used in types, making this problem moot.

**Comment by int-index** [comment]
The new version is great. `type.` and `data.` clearly apply to a single name and reuse the familiar dot-syntax of qualified names. I feel this syntax reuse is justified because module names in `ModName.f` and namespace specifiers `data.f` solve the same problem, they disambiguate where the name comes from.

> Variable (local) names are treated like any other names.

Does this mean that I can write this?

```
id a = data.a
```

**Comment by goldfirere** [comment]
> Does this mean that I can write this?
>
> ```
> id a = data.a
> ```

Yes.

**Comment by int-index** [comment]
How do export lists look under the new version?

```
module (type T, module Mod) where  -- Option (A)
module (type.T, module.Mod) where  -- Option (B)
```

**Comment by goldfirere** [comment]
I think it should be (B). I will clarify in the proposal. But we will continue to be backwards compatible with the standard.

**Comment by int-index** [comment]
Under this proposal, do we still need top-level kind signatures as a separate syntactic construct? We could say that this is merely a matter of the namespace and say things like this

```
type.Id :: forall k. k -> k
type family Id x where
  Id x = x
```

Note the dot.

**Comment by goldfirere** [comment]
> Under this proposal, do we still need top-level kind signatures as a separate syntactic construct?

That's a very interesting suggestion. I suppose we could. But what do we think about this?

```
foo :: forall k. k -> Type
data foo a = MkFoo
```

Here, `foo` would be in the data namespace, and it has a lowercase identifier. Including this possibility isn't directly implied by your idea, but it seems a natural consequence.

Indeed, why do we distinguish between upper-case identifiers and lower-case ones at all? I can think of only one reason: they allow us to easily spot what's a binding site and what's an occurrence site. For example, if I write

```
bar x = ...
```

that could mean several things (allowing for no distinction between upper-case and lower-case identifiers): It could be a function `bar` pattern-matching on a constructor `x`, it could be a pattern-binding for `x` after matching on a constructor `bar`, it could be a function `bar` binding the variable `x`, and it could be a (useless) pattern-match against `bar x` (where both are constructors). Right now, we know which of these it is because both identifiers are lower-case. But if we allow mixing of cases, we'd have to look to see what's in scope already to interpret. Worse, we'd have to determine whether, e.g., `x` is bound as a constructor or a variable: if it's a variable, then this new `x` shadows the old one.

While nothing in the paragraph above is at all difficult for GHC to sort out, it's very annoying for us mere humans. So, as we imagine blurring the lines between namespaces, it seems we want to keep the lines between cases. This could be enforced by GHC (as it is now) or by convention. For now, at least, I favor having GHC give us a hand here by enforcing it.

So, these musings all lead to this proposed design rule:
 * Upper-case identifiers (including symbols that begin with a `:`) are *matchable* (in the sense of my [thesis](https://repository.brynmawr.edu/cgi/viewcontent.cgi?article=1074&context=compsci_pubs), section 4.2.4), while lower-case identifiers are not necessarily.

Note that we already violate this rule by allowing, e.g., `+` to be a type-level matchable symbol. But we rarely bind symbolic names locally, so perhaps that's why this doesn't bite all that badly. (Still, we may wonder about repairing it.)

None of these musings directly affect the proposal, nor do they really respond to @int-index's comment.... but once we start blurring lines, we need to know which ones we want to keep.

Thus, I support @int-index's thought here and would be happy allowing such declarations even if the name is at the data level (albeit capitalized).

**Comment by int-index** [comment]
>  they allow us to easily spot what's a binding site and what's an occurrence site

They are not sufficient for this. Imagine we promote functions to the type level, then what is the meaning of this signature?

```
lookup :: foreach (xs :: [a]) -> Fin (length xs) -> a
```

Do we treat `length` the same way we treat `a` and implicitly quantify it?

```
lookup :: forall a length. foreach (xs :: [a]) -> Fin (length xs) -> a
```

That's not what the user probably meant! Instead, we want this:

```
lookup :: forall a. foreach (xs :: [a]) -> Fin (length xs) -> a
```

How do we know to do this? That's because `length` is already in scope, I say. So I'm not convinced that using capitalization to determine binding sites works in general.

**Comment by iamrecursion** [comment]
> So I'm not convinced that using capitalization to determine binding sites works in general.

In designing Luna's new syntax we ran into this problem and you're right that it doesn't work in general, unless we missed something. We ended up using the following scoping rule: names get looked up in the context (module scope, in most cases), and if introduced in the scope of the signature we then quantify them. 

Using that, like you mentioned, would yield the correct result, where `length` is a function. 

```hs
lookup :: forall a. foreach (xs :: [a]) -> Fin (length xs) -> a
```

**Comment by goldfirere** [comment]
Thanks for pointing out the problem with type signatures. My understanding is that Idris also follows the rule @iamrecursion describes in Luna. If we did that, too, that would defeat some of my argument about capitalization. Somehow, I'm not as bothered in a type signature as I am by having this problem in a pattern.... though I can't quite articulate why it seems better in a signature.

It might be worth having a new extension `-XRequiredForAll` that never does implicit lexical generalization in types, just to avoid this problem. Then, people could easily opt out of this behavior. (Such an extension would also be useful today, for that matter, as type signatures nested within functions can both implicitly quantify type variables and also use type variables brought into scope somewhere else. There is no local way to tell the difference.)

**Comment by iamrecursion** [comment]
> It might be worth having a new extension `-XRequiredForAll` that never does implicit lexical generalization in types, just to avoid this problem. Then, people could easily opt out of this behavior. 

It really _would_ have to be an opt-out, though. Nevertheless, I can see why this extension would be useful. Worth a separate proposal?

**Comment by goldfirere** [comment]
I've addressed the recent round of comments in an update, including the change from `type T ::` to `type.T ::`.

**Comment by int-index** [comment]
TLKSs apparently have a syntactic conflict with associated types. Consider `C`:

```
class C a where
  type F :: Type -> Type -- TLKS
  type F a :: Type       -- type family header
```

We can tell the TLKS apart from the type family header by the presence of binders on the LHS. We can't do this for nullary type classes:

```
class N where
  type F :: Type  -- TLKS?
  type F :: Type  -- type family header?
```

Fortunately, this proposal resolves this issue:

```
class N where
  type.F :: Type  -- TLKS.
  type F :: Type  -- type family header.
```

I have a prototype implementation of TLKSs, so I urge we submit this proposal to the committee to resolve this issue.

**Comment by goldfirere** [comment]
This is ready for submission to the committee, @nomeata. Thanks!

**Comment by simonpj** [comment]
Top level kind signatures means just that!  Shouldn't we have
```
type C :: Type -> Constraint    -- TLKS
type F :: Type -> Type          -- TLKS

class C a where
  type F a :: Type       -- type family header
```
And now this is no ambiguity

**Comment by int-index** [comment]
@simonpj Yes, however this is not what the accepted proposal says:

> Associated types may be given kind signatures within their classes.

It is the "within their classes" bit that creates trouble. Relevant discussion here: https://mail.haskell.org/pipermail/ghc-steering-committee/2018-August/000750.html

**Comment by simonpj** [comment]
Ok, well, I'm questioning that aspect of the TLKS proposal.   The simple, clear thing is for top level kind signatures to be, well, top level.

@goldfirere ?

**Comment by goldfirere** [comment]
Personally, I think the kind signature for an associated type should be within the class. This is simple in a different way: a kind signature for a datatype is in the same enclosing construct as the definition. Perhaps the name "top-level" kind signature is the problem. If we just say "kind signature", the problem melts away. Note that if this proposal is accepted, then the clash @int-index describes goes away. If this proposal is rejected, perhaps we'll have to re-think.

**Comment by simonpj** [comment]
For some definition of "melt away" :-).   I am not looking forward to explaining this to newcomers:
```
class N where
  type.F :: Type  -- TLKS.
  type F :: Type  -- type family header.
```
It's very strange.  After all, the name-space specifier is just that, about name spaces. So presumably I couls also write
```
class N where
  type.F :: Type  -- TLKS.
  type type.F :: Type  -- type family header.
```
Moreover, in the presence of scoped type variables, the very meaning of a TLKS in a nested scope is strange.
```
class N a b where
  type F :: a -> b
  type.F :: b -> a
```
where the latter perhaps means `type.F :: forall b a. b -> a`, which is indeed a good signature.  Do we have a "hole in the scope" of the tyvars from the class header.  

It seems so much simpler just to have a separate, top level signature.  Less elegant, I grant you, but simple, unambiguous.

**Comment by nomeata** [comment]
Richard, did you ponder the possibility of having
```
modid ->{conid .} conid
      | {conid .} conid . [namespace_specifier .
      |  namespace_specifier
```
rather than
```
modid -> [namespace_specifier .] {conid .} conid
      |  namespace_specifier
```
i.e. put the namespace specifier last?

The small reason why this might be preferrable? If you see code like
```
… type.Prelude.Maybe … data.Prelude.Just …  data.Prelude.id …
```
then it looks like there are two different name spaces, and in each there is a module `Prelude`. In other words, it looks like there are two prelude modules that may or may not have something in common! But with 
```
… Prelude.type.Maybe … Prelude.data.Just … Prelude.data.id …
```
it is clear that there is _one_ module that contains things in different namespaces.

Oh, and it also makes it easier to write 
```
… module.Prelude.type.Maybe … module.Prelude.data.Just … module.Prelude.data.id …
```
should one feel inclined to namespace-qualify all the things, including module names.

**Comment by int-index** [comment]
@nomeata This thought has crossed my mind, I agree with this:

> then it looks like there are two different name spaces, and in each there is a module `Prelude`.

Indeed, `Prelude.type.Maybe` looks better to me than `type.Prelude.Maybe` for this exact reason. Thanks for articulating it!

I am less convinced of the value and validity of `module.Prelude.type.Maybe`. This double qualification looks suspicious (is starts with the `module` namespace specifiers but in the end it refers to a `type`), and I see no use for it.

But changing `type.Prelude.Maybe` to `Prelude.type.Maybe` would be good.

**Comment by int-index** [comment]
@simonpj I agree that it is simpler to put the TLKS on the top level. It also need not be limited to associated types, as there's already an extended proposal in this spirit https://github.com/ghc-proposals/ghc-proposals/pull/148 (which is, ironically, by @goldfirere, who argues against this design :)

**Comment by simonpj** [comment]
Here's a possible principle:

* At _binding sites_ the syntactic context should determine the name space
* At _occurrence sites_ we may use a namespace qualifier to distinguish

So currently in Haskell we have
```
gendecl  ::= vars :: [context =>] type
```
Note `vars` not `qvars`.  You can say `f :: Int -> Int` but not `M.f : Int -> Int`.

So I say that the decl
```
f :: Int -> Int
```
means a term-level signature, and you should write
```
type T :: Type -> Type
```
if you want a kind signature.

_Occurrences_, in terms, types, or export lists, are a different matter.

Does that principle make sense to others?

**Comment by simonpj** [comment]
The proposal says

> However, we could not then use it in contexts like terms and types; it could never replace ', for instance.

I don't understand that.  It seems to me that this namespace qualifier notation can (and arguably should) replace the quote notation in TH.

**Comment by int-index** [comment]
> So I say that the decl `f :: Int -> Int` means a term-level signature, and you should write `type T :: Type -> Type` if you want a kind signature.

@simonpj It runs contrary to one of my goals, which is to collapse these two constructs into one. In particular, I'd like to write things like:

```
not, type.Not :: Bool -> Bool

not True = False
not False = True

type family Not b where
  Not True = False
  Not False = True
```

**Comment by yav** [comment]
I am in agreement that it would be nice to unify the terminology for specifying namespaces in ambiguous contexts, but I am unconvinced that this proposal has the right approach at present.  Here are some concrete thoughts:

  * I fully agree with @simonpj that we shouldn't need this at binding sites.

  * I would go further, and say that we only need special notation for use sites
    in ambiguous contexts (e.g., import/export lists, pragmas, etc.).  However,
    in terms, type signatures, data/class declarations (i.e., what we write
    most of the time!) we shouldn't need this notation.

  * I think restricting the contexts where we need this would allow us to have
    a more readable notation.  Does anyone really plan on writing things like
    `a data.: b data.: data.[]`?  The notation used by `ExplictNamespaces`
    (which I think this proposal started with?) seems quieter and more readable.

  * To me, the ambiguity due to datatype promotion
    (I mean that need to write `'`) suggests that we may want to revisit some
    of the design choices related to that extension, rather than adding more
    syntax to work around the resulting issues.

  * I much prefer the original notation for top-level kind signatures.

**Comment by int-index** [comment]
> At binding sites the syntactic context should determine the name space
> At occurrence sites we may use a namespace qualifier to distinguish

Note that this principle means that we still get to write `type.T :: ...` for a TLKS, because a signature is an occurrence site, not a binding site! Why is it not a binding site? Consider:

```
x = 1

y :: Int
y = 1
```

`x` has no type signature, but it is bound. Thus a definition is a binding occurrence. But then do we say that `y` is bound in the signature or the definition? I cannot justify giving a different answer here, thus I would say that both `x` and `y` are bound by their definition, and the signature for `y` simply mentions this definition.

On the other hand, can we bind names by signatures without definitions? Yes, in `.hs-boot` and `.sig` files. So this binding/occurrence separation becomes suspiciously inconsistent.

What about a different principle: namespace specifiers are allow anywhere. That's simple and gives good control. We have already seen the desire for this control in https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0032-type-data.rst and if we allow namespace specifiers anywhere, they would subsume that proposal. And I find it elegant that a single design addresses many issues at once.

**Comment by goldfirere** [comment]
See #227 about the change to top-level kind signatures in-class vs out-of-class.

**Comment by goldfirere** [comment]
Actually, the proposal *does* address `'[]` and tuples in the fourth "effect and interaction" and in the final "alternative". I have nothing more to add there.

**Comment by goldfirere** [comment]
NB: Comment https://github.com/ghc-proposals/ghc-proposals/pull/214#issuecomment-490502363 was actually made at around 10:30am EDT (1430 GMT) on May 8. GitHub gave it the wrong timestamp, confusingly misordering the comments. I've reported a bug to GH.

**Comment by yav** [comment]
I still remain quite unconvinced that this is the right design:

  1.  syntactically---the notation is quite noisy, and it introduces a 3rd interpretation for `.` (in addition to being an operator and a module-qualified name).  On the above point:

> Does anyone really plan on writing things like a data.: b data.: data.[]? 
> > I hope no one writes that! But I also see no reason to forbid it. Note that, because it is not ambiguous, we can write type Cons a b = a : b today

Well, perhaps this indicates that we should use a different approach more along those lines---when would you recommend one should use these explicit qualifiers in a code, say, to improve readability?

   2. I think treating data constructors as a separate 3rd name space is a mistake, and we don't need to dig ourselves deeper in that direction.   I find it quite unsatisfactory that if I write `data.X` that might be a type or it might be a value, and I can't specify which one I mean.

**Comment by goldfirere** [comment]
Thanks for shepherding, @yav.

1. Yes, the notation is noisy. Each namespace qualification takes an extra 5 characters, and I agree that this is a lot. But I worry that anything shorter will steal too much syntax and/or be context-dependent. There are so many places we need namespace disambiguation, and the goal is unification.

2. I'm not sure what you mean by a 3rd namespace for data constructors. Could you elaborate?

**Comment by int-index** [comment]
For the record, I voiced my support for this proposal before (by saying "I fully support it") but my thinking on the matter has evolved. I, too, find these namespace specifiers unpleasant, and I have an alternative design in mind.

**Comment by yav** [comment]
@goldfirere I got confused:  in the beginning of the proposal data constructors are listed as a separate namespace, and so when I was looking at `data.T` in the examples I thought we were refereeing to *that* namespace.

Now I see that there are only two specifiers: `type` and `data` (not counting the `module` one, which seems quite orthogonal to the whole discussion) and `data` is used to refer to all value level things.  But also promoted data constructors, which are actually types. I find this quite confusing.

I think that, really, my main objection to the proposal (apart from the syntax) is the treatment of promoted constructors.  I think that the notation should emphasize *what* a thing is, and not how the thing happened to be defined.  To me, using the notation `data.C` for a type, is similar to saying that we should use `primitive.Int` to refer to built-in types.

**Comment by int-index** [comment]
> and I have an alternative design in mind

To follow up on that, I briefly described this alternative idea, namespace-qualified imports, in #236:

```
import Data.Proxy type qualified as T
import Data.Proxy data qualified as D

a = f T.Proxy   -- refers to the type constructor
b = f D.Proxy   -- refers to the data constructor
```

I will see how the discussion evolves there and write a full proposal if the overall plan is met with agreement.

**Comment by simonpj** [comment]
I am very sympathetic to the goal of solving the infelicities described so well in the proposal.

But I can't say I find the propsed solution satisfying.  It's noisy, and (although I understand the reasoning) I alwsy find that `data` makes me think of data type declarations (especially when juxtaposed with `type`) rather than of the term level namespace.

I wonder if a simpler (albeit still not great) alternative might be to use single-quote to mean "the other namespace".  So in types, the quote means the term namespace (as now), but the change would be to make ti work the other way around.   So `f 'Int` woudl apply `f` to a Required `Int` argument.

I'm inclined to say "wait" on this proposal.  As in, let's wait for a better idea to come along.

**Comment by simonmar** [comment]
I dislike the single quote:
* it looks ugly
* syntax highlighters almost always get it wrong
* the bad interaction with lexing of characters that @goldfirere points out in the proposal

So I'm in favour of deprecating the single quote in favour of a complete and regular way to specify namespaces. 

I actually don't find this current proposal too noisy, but it seems sensible to hold fire while @int-index 's alternative poposal is being discussed.

**Comment by LeanderK** [comment]
To give the perspective from a "normal" user: I really don't like the single quote because it makes haskell very hard to understand if you don't know whats going on. Especially if dealing with the namespaces will become more common. To comment on @int-index: I think namespace-qualified imports are usable because it gives you a hint what's happening and somewhere to start if you want to ask what the heck this code is doing ("why are there type and data imports in this code?").

I don't want to comment on the technical point of view for @goldfirere proposal, only for the usability from the point of view as an interested observer. I think what the proposal gets right is that the resulting code can be dealt with as a ordinary user. I think if you glance over the problem, the code is somewhat intuitive and can be understood without deep knowledge of the namespace problem (because it's very explicit). Also, if you don't understand what the code is doing, there's a clear, unambiguous question you can ask ("what's the data in false = data.not (data.True)?"). If the syntax can appear in another context it's way hard to ask a question about it. Although I agree that it seems very noisy.

I think beside elegance, there should still be possibility for someone not familiar with the extension to understand it or at least ask a question about it. Otherwise you create a language that only those already familiar with it can use.

**Comment by goldfirere** [comment]
@LeanderK's observations made me realize that I would use this new syntax when teaching Haskell, emphasizing the difference in the `T`s in `data T = T`. (No, I don't use types like that in my own code when teaching, but `aeson` is very very useful, and it has lots of punning.)

I agree that this proposal may be suboptimal and am happy to let it sit dormant while other proposals in this space mature. I would hope, though, that other proposals seek to unify the mess that's elaborated in this proposal.

**Comment by monoidal** [comment]
> Introduce a new proposal for -XRequiredForAll that disables GHC's habit of implicit lexical generalization in types. 

This could be called `-XNoImplicitForAll`; it's feels consistent with `-XNoImplicitPrelude` and `-XExplicitForAll`. Furthermore, "required" forall might cause ambiguity with required variables (as opposed to inferred/specified). One downside is that this extension would probably imply ExplicitForAll, and we don't have a negative flag implying a positive one yet.

(I know, this is only a possible future direction, not strictly a part of the proposal.)

**Comment by yav** [comment]
I think this proposal is ready to go to the "Committee discussion" phase and I will label it as such.  I would kindly ask that further comments are limited to members of the committee.

**Summary**  Names in Haskell are organized in two namespaces---values and types---and some language constructs may contain members of either namespace.   This presents a problem when a name which inhabits both namespaces is used in such a context.   At present, different language constructs have different ways of addressing this ambiguity, many of which look similar but differ in what are probably unimportant ways.   This proposal aims to address this problem by allowing names to be qualified with an explicit namespace qualifier: for example `data.T` would refer to the name in the value namespace, while `type.T` would refer the type namespace.

**Recommendation** I think that the problem which this proposal aims to address is important and worth addressing.  However, I do not like the proposed solution, for the following reasons:
   * I find the notation to be quite noisy, and can't honestly think of situations where I'd use it
   * I find the use of `data` for the value namespace to be quite confusing, as in Haskell it is already strongly associated with declaring datatypes.   I could probably be retrained on this, but I don't think it is great design to use the same notation with rather different meaning---the notation does not seem intuitive and is likely to be confusing to users not familiar with it.
   * I find it unsatisfying that `data.T` may be either a type or a value. I understand that we are just saying we mean `T` in the value namespace, which due to design choices in `DataKinds` can actually be a type, but it is still very confusing.

Based on this I'd say that we should table this for now, but continue thinking of ways to solve the underlying issue.

**Comment by simonpj** [comment]
Thanks Iavor.

My current view ([elaborated above](https://github.com/ghc-proposals/ghc-proposals/pull/214#issuecomment-498045198)): I'm inclined to say "wait" on this proposal. As in, let's wait for a better idea to come along.

**Comment by goldfirere** [comment]
I'm happy to wait, as well, especially in light of #236.

**Comment by yav** [comment]
Ok.  We don't have a "wait" status, but I'll re-label it as "needs revision" for now (as opposed to "reject") indicating that we'd still like to solve the underlying problem.    Depending on what comes out of the other proposals we can re-activate this or just close it later.

**Comment by goldfirere** [comment]
My enthusiasm for this has waned, as #236 suggests that better designs exist. I retreat to rejoin the fight another day.

**Pull request closed without merging**
