### PR TITLE
Add more primops for creating arrays

### PR DESCRIPTION
**Pull request by treeowl**
The current primops for creating arrays of pointers are
insufficient for implementing some important operations
efficiently. I propose we add more to cover those.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/array-creation/proposals/0000-array-creation.rst)

### CODE REVIEW

**Comment by cartazio** [comment]
The current proposal could use a few more details.

Which reminds me: a current issue with ghc array/vector primops is that
they can’t yield to the scheduler while working on very large arrays. (Eg a
mem copy on a 100gb hypothetical array ). But perhaps they should every
million elements / millisecond or so? Or something like that.

Yielding to the scheduler ever once in a while is neeed from a gc safety
perspective

With respect to the gc issue alluded to in this issue: what about zero
initialized pointers? How does the rts handle those nulls? Why can’t we
zero initialize arrays of pointers or something ?

**Comment by cartazio** [comment]
Phrased differently: in high concurrency workload, we actually want to
enforce that all long running primops yield to the scheduler every once in
a while for safety / responsiveness (otherwise all the cpus idle till that
last compute yields to scheduler to run a gc )

**Comment by treeowl** [comment]
@cartazio The whole point of this proposal is to *reduce* the number of situations where the runtime needs to initialize arrays. Initializing array elements to a "null pointer" might very well be useful, but it's entirely opposed to what I'm trying to accomplish here. (Are there pointers whose tags let the GC know it doesn't need to follow them? If so, it would be rather useful to know, today, what those are.)

Yielding occasionally to the scheduler sounds like a good thing, but it's (almost?) entirely orthogonal. The only interaction I can think of is that we need the array creation primitive to keep each of its arguments live until the entire operation is complete and the garbage collector is permitted to see that the array is full of pointers that it needs to trace. Fortunately, I suspect that's the *easiest* way to do it.

**Comment by treeowl** [comment]
Actually, no, yielding to the scheduler is much more complicated than that. It's still a separate issue. It requires a way to tell the GC *which parts* of an array have been initialized and which haven't.

**Comment by cartazio** [comment]
Hrmm... what about in the header? We can probably spare a bit in the rts
header for array and small array for a “not setup yet” link right?

Then it’s merely a question of making sure we can still point the gc at the
heap value we’re using to intialzie the array to make sure it’s still live
after the gc.  But that should be pretty straight forward I think ?

**Comment by treeowl** [comment]
We need more details to yield. My second to last comment was wrong. Suppose we are copying from a `old :: MutableArray# String` to a fresh `new :: MutableArray# String`. Suppose we've copied the first 1000 elements, and still have 1000 to go. Now we yield to the scheduler. Another thread modifies the 7th element of `old` to point somewhere else, leaving `new` as the *only* thing pointing to the 7th string. The garbage collector needs to know that it must collect the first 1000 (and only the first 1000) elements of `new`. I don't know what's involved in that, but I do know it's not related to the present proposal.

**Comment by treeowl** [comment]
@cartazio, I've added a lot of details to the proposal.

**Comment by winterland1989** [comment]
Bear in mind that `memset` is very fast these days due to SIMD, so the first step may be to use it on large arrays when doing `stg_newArrayzh..`?

Even without SIMD, looping copy a register into an array which almost always live in cache line is cheep, so can you setup a benchmark to show the overhead introduced by this extra init loop?

**Comment by treeowl** [comment]
@winterland1989, I tried to make a benchmark. Strangely enough, my *very* informal tests show that when trying to make a fresh copy of a mutable array it's faster to create an array with `newArray#` and then copy into it with `copyMutableArray#` than to use `cloneMutableArray#` to do the job directly. Either something is fishy about my tests, or something is very wrong with the implementation of `cloneMutableArray#`.

**Comment by winterland1989** [comment]
Read through the [`copyArray`](https://github.com/ghc/ghc/blob/20cbb0165e4d18df510e707791e761942d3c10f0/includes/Cmm.h#L837) code, It seems the only difference is that `stg_newArrayzh` manually inline `allocate`, while `cloneArray` use `allocateMightFail`, maybe an extra call is too expensive here?

**Comment by simonmar** [comment]
Can you quantify the benefit of being able to inline these? My guess is that it's not large.

For "non-cmm-based backends" are you referring to GHCJS, or is there anything else? Would it be possible to port array-primops to use GHCJS primitives?

**Comment by treeowl** [comment]
@simonmar, see [this pull request](https://github.com/tibbe/unordered-containers/pull/165) to `unordered-containers`, and especially [this comment](https://github.com/tibbe/unordered-containers/pull/165#issuecomment-321506669) by @AndrasKovacs. It looks like there is a significant difference for very small arrays of the sort used for `HashMap`.

**Comment by simonmar** [comment]
@treeowl there was a significant difference when measuring *just the primitives*, but what's the overall benefit for `unordered-containers` benchmarks?

**Comment by AndrasKovacs** [comment]
@simonmar there was 5% improvement with out-of-line primops, however, the "unsafe" inline primops (which appear significantly faster) weren't tested with `unordered-containers`.

**Comment by simonmar** [comment]
Right, I'm actually interested in the delta between using `array-primops` and the unsafe inline primops, since that's what we stand to gain from this ghc proposal.

**Comment by nomeata** [comment]
@treeowl, whither this proposal?

**Comment by andrewthad** [comment]
For what it’s worth, I really like the functions described in section 2, and I would like to see those added because I need them from time to time. I’m not so sure about the stuff in section 3.  The names are weird, and it seems like a bit of a grab bag for things needed by unordered-containers. For these, I’m more interested in the (admittedly complicated) solution described in the alternatives section.

**Comment by nomeata** [comment]
Inactive for many months, marking as dormant.

**Comment by nomeata** [comment]
Closing this due to inactivity, but it can be reopened when necessary.

**Pull request closed without merging**
