### PR TITLE
Propose MultiCase

### PR DESCRIPTION
**Pull request by treeowl**
This is my alternative to #19

### CODE REVIEW

**Comment by phadej** [comment]
[Rendered](https://github.com/treeowl/ghc-proposals/blob/multi-case/proposals/0000-multi-case.rst)

**Comment by phadej** [comment]
An alternative:

```hs
f x y = mcase x y of
  (A a) y -> e1
  x (B b) -> e2
  x y -> e3
```

```hs
f x y = mcase x (g y) of
  (A a) y -> e1
  x (B b) -> e2
  x y -> e3
```

**Comment by treeowl** [comment]
Excellent point, Oleg.

**Comment by Ericson2314** [comment]
`mcase` and `\mcase` would make me happy. I still like just changing lambda like https://github.com/ghc-proposals/ghc-proposals/pull/18#issuecomment-252411627 but I think this would be more palatable / a good first step.

**Comment by treeowl** [comment]
I think I'll change the proposal to mcase instead. One minor downside is
that the syntax error for forgetting to enable the extension will be a bit
weird: it'll trip up on `of`.

**Comment by phadej** [comment]
@treeowl not worse then

```
> proc x -> f -< x+1

<interactive>:8:8: error: parse error on input ‘->’
> unpack "foo"

<interactive>:9:8: error:
    • Couldn't match expected type ‘Text’ with actual type ‘[Char]’
    • In the first argument of ‘unpack’, namely ‘"foo"’
      In the expression: unpack "foo"
      In an equation for ‘it’: it = unpack "foo"
```

**Comment by simonmar** [comment]
I'm not a huge fan of this due 

```
f x y = case x, y of
          A a, y -> e1
          x, B b -> e2
          x, y -> e3
```

Due to the inconsistency (pointed out in the drawbacks).  And I'm not convinced that `mcase` would be worthwhile given that it's not hard to write

```
f x y = match x y 
  where
    match (A a) y = e1
    match x (B b) = e2
    match x y = e3
```

and this works fine with unlifted types and doesn't require learning new syntax.

Some "omissions" in the language just aren't worth fixing!

**Comment by erikd** [comment]
The name `mcase` was also proposed on the libraries list as candidate function for `Data.Maybe`:
```
mcase :: Maybe a -> b -> (a -> b)
```
In my day job we have `mcase` (as well as `ecase` for `Either` ) in our custom prelude and I use `mcase` far more often than the `maybe` function.

I was moderately negative on the previous proposal (#19) and I don't think this improves on it much.

**Comment by phadej** [comment]
@erikd, You probably mean `mcase :: Maybe a -> b -> (a -> b) -> b` ?

**Comment by erikd** [comment]
@phadej Yes, thanks for the correction. I wrote that before my morning coffee :)

**Comment by ocharles** [comment]
As much as I hate throwing bike shed colours around, perhaps `cases` instead of `case`.

**Comment by deepfire** [comment]
@ocharles, do you think it's still worth in the context of the point raised by Simon?

**Comment by ocharles** [comment]
@deepmind On the fence about that, just a slightly better keyword :)

**Comment by simonpj** [comment]
Like others, I'm unconvinced that the cost of the extra syntactic sugar is justified by the benefit. Both costs and benefits are small, but every little extra piece does carry its costs.  e.g. new error messages for mis-matched arities in mcase patterns.   If there was a storm of support from salivating users I'd tihink again, but as it stands I'm mildly -1.

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by treeowl** [comment]
Since this is a low priority for me, and lead implementers seem largely uninterested, I'm going to close it. If others disagree, feel free to pipe up.

**Comment by andreasabel** [comment]
I think the original proposal was reasonable:
```haskell
case a , b of
  p1 , q1 -> e1
  p2 , q2 -> e2
```
But the `mcase` syntax is misleading (confusing function application with pairing).  I think the `mcase`-bikeshedding destroyed this proposal.

**Comment by ChShersh** [comment]
An alternative using current syntax with pattern synonyms:

```haskell
pattern T2 :: a -> b -> (a, b)
pattern T2 a b <- (a, b)
  where
    T2 a b = (a, b)

f x y = case T2 x (g y) of
  T2 (A a) y -> e1
  T2 x (B b) -> e2
  T2 x y -> e3
```

**Pull request closed without merging**
