### PR TITLE
Add support for class-based reflection

### PR DESCRIPTION
**Pull request by treeowl**
Allow libraries like `reflection` to work better with GHC.
Specifically, remove the need for them to use `unsafeCoerce`, making
them robust against compiler changes and allowing code that uses
them to be optimized more aggressively.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/magic-reflection/proposals/0000-magic-reflection.rst)

### CODE REVIEW

**Comment by goldfirere** [comment]
Looks good to me. +1

I'll also note that this is extensible to classes with multiple methods, once we figure out a way to do so.

**Comment by RyanGlScott** [comment]
While the idea seems solid, I'm rather confused on some of the particulars of this proposal:

> Furthermore, these packages rely on single-method classes being represented as newtypes.  Furthermore, there is talk among GHC developers of changing that representation, which would break all the packages.

Wait, what? When was this proposed?

> then we would like to be able to write functions like
> 
> ```haskell
> reifyUnaryNat :: forall n r. SNat n -> (KnownUnaryNat n => r) -> r
> ```
> 
> Note the difference in quantification: whereas `reifyNat` takes a function polymorphic in the natural number, the inherent coherence of the `KnownUnaryNat` class allows `reifyUnary` to accept a monomorphic value.

What is `reifyUnary` here? Should that be `reifyUnaryNat`?

> Given
> 
> ```haskell
> class TheClass a where
>   method :: T
> 
> deriving instance Reflectable (TheClass a)
> ```
> 
> we would produce an instance
> 
> ```haskell
> instance Reflectable (TheClass a) where
>   type DictRep (TheClass a) = T
>   reify# = ...
> ```
> 
> Operationally, `reify# f x` will package up `x` in a dictionary and pass that dictionary to `f`. Currently, that means `reify#` will actually just be a coercion. Later, it may mean something else.

I'm confused by a couple things here.

1. I feel like you should more formally specify how `DictRep` instances are generated, since at the moment I'm quite mystified as to how this would work in the general case. For instance, how would this work for a class like:

   ```haskell
   class Foo a where
     foo :: a -> b -> a
   ```

   where the method mentions a type variable that isn't scoped over by the class variables? Naïvely, it seems that `DictRep` would be created:

   ```haskell
   instance Reflectable (Foo a) where
     type DictRep (Foo a) = a -> b -> a
   ```

   But this won't work, since `b` isn't bound anywhere.
2. Could you give a concrete example of how `reify#` would be implemented (e.g., for `TheClass a`)? Will it use `unsafeCoerce` for now?

> The above-described mechanism can implement singleton reflection directly. We could simply write, for example,
> 
> ```haskell
> deriving instance Reflectable (KnownUnaryNat n)
> 
> reifyUnaryNat :: forall n r. (KnownUnaryNat n => r) -> SNat n -> r
> reifyUnaryNat = reify# @(KnownUnaryNat n)
> ```

A minor point, but the presentation of `reifyUnaryNat` here reverses the order of arguments from before.

In the [We can implement what we want](https://github.com/treeowl/ghc-proposals/blob/f66d6514dd1c26357f0b1e2f3be4f1a5f86bc224/proposals/0000-magic-reflection.rst#we-can-implement-what-we-want) section, it would be helpful to write out the code that would be generated for each derived `Reflectable` instance. In particular, it took me quite a bit of staring to realize what was going on in the `Reflectable (Reifies s a)` example.

> My main concern with regard to implementation has to do with specialization in the `reflection` case.

By "`reflection` case", do you mean the earlier `Reifies s a` example? If so, it would be helpful to clarify this, since the word "reflection" is somewhat overloaded in this proposal (it can refer the current, general reflection technique involving `unsafeCoerce`, the `reflection` library, or code from the `reflection` library itself, such as `Reifies`).

> `reify` desugars to a term that uses `$fReflectableReifies @ Any @ a`. It's critical that the specializer never specializes this; `Any` must not equal `Any` in this context!

Maybe I'm not understanding this sentence correctly, but the phrase "`Any` must not equal `Any`" seems inscrutable to me. Doesn't `Any` trivially equal `Any`? Perhaps there's a couple details missing that would clarify what you meant.

> The proposed mechanism allows users to subvert class coherence by implementing fundamentally illegitimate functions like `give`.

What is illegitimate about `give`?

**Comment by treeowl** [comment]
@RyanGlScott, I think my latest (fairly substantial) commit should address most of your points. In light of the polymorphism issue you raised, I think a (newly refined) version of the data family alternative may actually be the best approach. What do you think?

**Comment by nomeata** [comment]
> I'll also note that this is extensible to classes with multiple methods, once we figure out a way to do so.

If we don’t, it might also make people start to use the following idom:

```
data MonoidDict a = { mempty_ :: a; mappend_ ::  a -> a -> a }
-- look, a single-method class
class Monoid a where monoidDict :: MonoidDict a
mempty :: Monoid a => a
mempty = mempty_ . monoidDict
mappend :: Monoid a => a -> a -> a
mappend = mappend_ . monoidDict
```

which happens to be operationally equivalent to the usual definition, and might create opportunities for interesting program patterns that I cannot forsee right now. Instance factory methods :-)

**Comment by cartazio** [comment]
Isn't the usual definition strict in the methods?

**Comment by treeowl** [comment]
No, the usual definition is definitely not strict in the methods.

**Comment by RyanGlScott** [comment]
@treeowl, looking better.

I do think the data family approach would be better suited here. That being said, I'm a bit perplexed by your current design:

```haskell
class s ~ ConName c => Reflectable (s :: Symbol) (c :: Constraint) where
  data MethodData c :: *
  type ConName c :: Symbol
  reify# :: (c => r) -> MethodData c -> r
```

I'm not really sure what `ConName` is actually accomplishing here, aside from clutter. Couldn't this be served equally as well with the following simpler definition?

```haskell
class Reflectable (s :: Symbol) (c :: Constraint) | c -> s where
  data MethodData c :: *
  reify :: (c => r) -> MethodData c -> r
```

We'd probably need an extra check when deriving `Reflectable` to ensure that `s` is a concrete `Symbol` to avoid non-sense like `deriving instance Reflectable s (Foo a)`, but what's a little extra magic among friends? :)

Also, I'd hate to bikeshed, but I'm really not a fan of the name `MethodData`, which sounds terribly nondescript. Might I suggest `Reflected` instead? This adopts the pseudo-naming convention present in `reflection` (e.g., [`ReflectedMonoid`](http://hackage.haskell.org/package/reflection-2.1.2/docs/Data-Reflection.html#t:ReflectedMonoid) and [`ReflectedApplicative`](http://hackage.haskell.org/package/reflection-2.1.2/docs/Data-Reflection.html#t:ReflectedApplicative)).

> Such a change was considered in a previous version of [Separate Constraint from Type](https://github.com/ghc-proposals/ghc-proposals/pull/32) but seems to have been rejected.

Ah, thanks for the link to refresh my memory. In particular, [this comment on Trac #11715](https://ghc.haskell.org/trac/ghc/ticket/11715#comment:64) is quite relevant, so perhaps it would be beneficial to link to that.

**Comment by RyanGlScott** [comment]
> If we don’t, it might also make people start to use the following idom:
> 
> `data MonoidDict a = { mempty_ :: a; mappend_ ::  a -> a -> a }`

Funny enough, @nomeata, people are _already_ using that idiom. ;) See [`ReifiedMonoid`](http://hackage.haskell.org/package/reflection-2.1.2/docs/Data-Reflection.html#t:ReifiedMonoid) in `reflection` for an example of this.

**Comment by nomeata** [comment]
> Funny enough, @nomeata, people are already using that idiom.
Not surprised. But it’d get more useful with this proposal, because the extra power of single-methods type classes.

**Comment by treeowl** [comment]
@RyanGlScott The purpose of `ConName` is to prevent the data family and the `reify#` method from taking the symbol (uselessly!) as a type argument. It's hard enough plumbing types around at use sites without that nonsense. The symbol is only for deriving and users shouldn't have to mess with it after. A previous draft indicated that `s` must be a literal symbol; that got lost later but I'll put it back. Bikeshed away; I don't care about the names very much.

**Comment by RyanGlScott** [comment]
> The purpose of `ConName` is to prevent the data family and the `reify#` method from taking the symbol (uselessly!) as a type argument. It's hard enough plumbing types around at use sites without that nonsense.

Certainly!

> The symbol is only for deriving and users shouldn't have to mess with it after.

If this is true, then why bother expressing it as an associated type family? The fundep version I sketched out in https://github.com/ghc-proposals/ghc-proposals/pull/69#issuecomment-320515440 accomplishes the same goal of avoiding the need to put `s` into `reify#` and avoids type inference ambiguities just as well as a type equality superclass, without the need to allocate an extra top-level name `ConName`.

**Comment by treeowl** [comment]
@RyanGlScott with the fundep, inference works out just fine, but `s` is still there cluttering the type and getting in the way of visible type application. The module system can bury the type family name if we like. The only real advantage of the fundep over the type family is that it makes it easier to write `Reflectable` instances *by hand*. I didn't really consider that possibility very carefully, because it's a bit hard to see the point.

**Comment by RyanGlScott** [comment]
> with the fundep, inference works out just fine, but s is still there cluttering the type and getting in the way of visible type application.

Of course. You could swap the order in which `a` and `s` appear in `Reflectable`:

```haskell
class Reflectable (c :: Constraint) (s :: Symbol) | c -> s where
```

So that you could more easily write `reify# @(Foo a)`, if you wish.

> The module system can bury the type family name if we like.

Well, you could, but that once again raises the question: if you're going to define `ConName` only to never to use it again, why bother? Let's just cut out the extra step and use a fundep.

> The only real advantage of the fundep over the type family is that it makes it easier to write `Reflectable` instances _by hand_. I didn't really consider that possibility very carefully, because it's a bit hard to see the point.

Ah, good thought. I suppose it would be worth writing a blurb in the proposal about hand-written `Reflectable` instances (regardless of which `Reflectable` design we ultimately decide on). In particular, it's worth noting that in hand-written `Reflectable` instances, you can instantiate `s` with whatever you want.

**Comment by treeowl** [comment]
@RyanGlScott Reordering the class parameters gets `s` out of the way of `c`, but not out of the way of `a` or `r`. I'd really prefer to see it gone, even if that means people writing instances by hand have to dig the type family out from the back of the store.

**Comment by RyanGlScott** [comment]
@treeowl, I'm really not sure what you're even arguing for at the moment. You say that you'd prefer to see `s` gone, but this design:

```haskell
class s ~ ConName c => Reflectable (s :: Symbol) (c :: Constraint) where
  data MethodData c :: *
  type ConName c :: Symbol
  reify# :: (c => r) -> MethodData c -> r
```

Doesn't accomplish that! So I'm quite lost.

**Comment by treeowl** [comment]
@RyanGlScott It gets rid of it to the greatest extent possible without needing to add special syntax. It's still a parameter of `Reflectable`, but it's nowhere to be seen in the type of `reify#`. Using your fundep, we get

```haskell
reify#
  :: forall {s :: Symbol} {c :: Constraint} {r}.
     Reflectable s c =>
     (c => r) -> MethodData c -> r
```

Using my type family, we get

```haskell
reifyDF#
  :: forall {c :: Constraint} {r}.
     Reflectable (ConName c) c =>
     (c => r) -> MethodData c -> r
```

Look Ma, no `s`!

**Comment by treeowl** [comment]
Oh wait, that doesn't actually work right, does it? Blast!

**Comment by RyanGlScott** [comment]
@treeowl, I'm not sure how you can up with the visibilities for the tyvar binders for `reify#` and `reifyDF#`, but they're wrong. Using `-fprint-explicit-foralls` and `:type +v` (NB: don't ever use `:type` to infer visibility, as discussed [here](http://git.haskell.org/ghc.git/blob/a267580e4ab37115dcc33f3b8a9af67b9364da12:/docs/users_guide/glasgow_exts.rst#l9520)), you get the following:

```
λ> :set -fprint-explicit-foralls
λ> :type +v reify#
reify#
  :: forall (s :: Symbol) (c :: Constraint).
     Reflectable s c =>
     forall r. (c => r) -> MethodData c -> r
λ> :type +v reify# @"Foo"
reify# @"Foo"
  :: forall (c :: Constraint).
     Reflectable "Foo" c =>
     forall r. (c => r) -> MethodData c -> r
```

**Comment by treeowl** [comment]
The *method* will always have the `s` but with the type family approach, we can write a `reify##` wrapper function that doesn't take that.

**Comment by RyanGlScott** [comment]
> The _method_ will always have the `s` but with the type family approach, we can write a `reify##` wrapper function that doesn't take that.

Ah, thank you for elaborating. I wasn't aware that you intended to expose something other than `reify#` to users! In that case, your proposed design makes sense (and the order in which `s` and `a` appear in `Reflectable` becomes inconsequential).

Please do update the proposal with this tidbit. And call the wrapper something else besides `reify##`! ;)

**Comment by treeowl** [comment]
@RyanGlScott, yeah, I did that wrong. Here's a way that works:

```haskell
class Reflectable (s :: Symbol) (c :: Constraint) where
  data MethodData c :: *
  type ConName c :: Symbol
  reify# :: (c => r) -> MethodData c -> r

reify## :: forall (c :: Constraint) r. Reflectable (ConName c) c => (c => r) -> MethodData c -> r
reify## = reify# @(ConName c)
```

**Comment by treeowl** [comment]
@RyanGlScott I didn't *intend* it until you pointed out that what I was doing the first time was wrong! You've been a tremendous help refining this proposal.

**Comment by int-index** [comment]
Why would one want to mess with name generation using `Symbol`s if the type family approach works? There are two advantages listed:

* We no longer need to prohibit the method type from quantifying over type variables
* The constraint in question is fixed by the newtype constructor, so it does not have to be given using visible type application.

The first one can be achieved with a simple newtype (not a newtype/data family). I.e.

```
type family MethodData' c :: *
newtype MethodData c = MkMethodData (MethodData' c)
```

And second can be achieved with a type-refined pattern synonym for `MkMethodData` (user-defined).

This avoids the messy business with name management and extra parameters.

**Comment by treeowl** [comment]
@int-index, I don't understand your suggestions. Can you give a concrete example of what they would look like for a class with a polymorphic method? And how are pattern synonyms going to help with type inference?

**Comment by int-index** [comment]
### Class definition

Proposed design (type family).

```
class Reflectable (c :: Constraint) where
  type MethodType c :: *
  reify# :: (c => r) -> MethodType c -> r
```

Alternative design (data family).

```
class Reflectable (s :: Symbol) (c :: Constraint) where
  data MethodType s c :: *
  reify# :: (c => r) -> MethodType s c -> r
```

My design (type family + newtype).

```
newtype MethodType c = MkMethodType (MethodType' c)

class Reflectable (c :: Constraint) where
  type MethodType' c :: *
  reify# :: (c => r) -> MethodType c -> r
```

As you can see, the input to `reify#` is the `MethodType` newtype, it's injective/generative, so type inference is good.

### Instance definitions

Proposed design (type family).

```
deriving instance Reflectable (SingI n)

withSingI :: forall n r. (SingI n => r) -> Sing n -> r
withSingI = reify# @(SingI n)
```

Alternative design (data family).

```
deriving instance Reflectable "MkSingI" MyClass

withSingI :: forall n r. (SingI n => r) -> Sing n -> r
withSingI s = reify# (MkSingI s)
```

My design (type family + newtype).

```
deriving instance Reflectable "MkSingI" MyClass

pattern MkSingI :: Sing n -> MethodType (Sing n)
pattern MkSingI = MkMethodType

withSingI :: forall n r. (SingI n => r) -> Sing n -> r
withSingI s = reify# (MkSingI s)
```

**Comment by RyanGlScott** [comment]
OK, but this doesn't at all address the point of contention: how will your proposal address deriving a `Reflectable` instance for a class like this?

```haskell
class Foo a where
  foo :: a -> b -> a
```

I don't see how your approach works there. (Please show the code that would be generated too, because that part is non-obvious.)

**Comment by int-index** [comment]
> for a class with a polymorphic method?

Ah, I see the issue now, I was under the false impression that a type family can reduce to a polymorphic type (because a type synonym can).

**Comment by RyanGlScott** [comment]
> Ah, I see the issue now, I was under the false impression that a type family can reduce to a polymorphic type (because a type synonym can).

@int-index: Sadly, no. See [GHC Trac #13901](https://ghc.haskell.org/trac/ghc/ticket/13901).

**Comment by treeowl** [comment]
@RyanGlScott I made some more changes based on your recent remarks, including making the data family version primary. Let me know if you have more suggestions!

**Comment by treeowl** [comment]
This proposal has some loose connections to #32.

**Comment by RyanGlScott** [comment]
I'll look over it in a minute.

BTW, the link you give in the top-level comment of this PR (https://github.com/treeowl/ghc-proposals/blob/ab25664ddd7b375534e6a67fca7e37f8c3387576/proposals/0000-magic-reflection.rst) refers to an old commit. Can you change it to https://github.com/treeowl/ghc-proposals/blob/magic-reflection/proposals/0000-magic-reflection.rst instead?

**Comment by treeowl** [comment]
@RyanGlScott Ah, I didn't know how to link to the rendered view of the branch tip! Fixed!

**Comment by RyanGlScott** [comment]
This is looking pretty nice. There's really only one detail I'm still not sure about: what language extension will enable `deriving` support for `Reflectable`? I think it'd be wise to mention that in the [Proposed Change Specification section](https://github.com/treeowl/ghc-proposals/blob/ab25664ddd7b375534e6a67fca7e37f8c3387576/proposals/0000-magic-reflection.rst#proposed-change-specification), along with ways that make deriving of `Reflectable` instances different from other classes, such as:

1. It only works with `StandaloneDeriving`
2. The last argument to `Reflectable` must be a type class (as opposed to every other stock derivable class, where the last argument must be a data type)
3. The first argument to `Reflectable` must be a concrete `Symbol` literal

**Comment by treeowl** [comment]
@RyanGlScott (3) is already covered. I'll take care of the rest. But I had one more thought (following up on something I've been chewing over for a bit). I haven't been terribly satisfied with the way the current proposal uses the same class for `reify`-style reflection as for singleton reflection. They have rather different meanings, and `reify` needs special care from the optimizer. I think I finally came up with a way to write the class for `reify`-style reflection:

```haskell
class name ~ ConNameR c => ReflectableR (name :: Symbol) (c :: k -> Constraint) where
  data ReflectedR c :: *
  type ConNameR c :: Symbol
  reifyR# :: forall (q :: k). (forall s. c s => r s) -> ReflectedR c -> r q
```

This would be derivable for a class whose method is phantom in the last type parameter. This basically guarantees that `r` is also phantom in that parameter (or that all functions passed in will always produce bottom).

`ReflectedR` allows super-clean instances for classes *similar* to `Reifies`:

```haskell
-- Poly-kinded Const
newtype Const a (s :: k) = Const a

class FlipReifies a s | s -> a where
  flipReify :: Const a s

deriving instance ReflectableR "FR" (FlipReifies a)

flipReify :: forall a r. (forall (s :: *). FlipReifies a s => Const r s) -> a -> r
flipReify f a = getConst $ reifyR# (undefined :: forall s. FlipReifies a s => Const r s) (FR a) 
```

`reify` itself can be implemented quite legitimately using `reifyR#`, but it needs several adapters to deal with the fact that parameters are in the wrong order:

```haskell
newtype Flip (f :: j -> k -> *) (a :: k) (b :: j) = Flip {unflip :: f b a}

class f b a => FlipC f a b
instance f b a => FlipC f a b

-- This formulation requires a slight extension allowing Reflectable
-- to be derived for a class with no methods and exactly one superclass
-- which itself has exactly one method (etc.) I imagine that should be
-- possible. Alternatively, we could probably use
--
-- class FlipC f a b where
--   unflipC :: Dict (f b a)
-- instance f b a => FlipC f a b where
--  unflipC = Dict

deriving instance ReflectableR "Hoop" (FlipC Reifies a)

flippy :: ReflectableR name (FlipC c a)
       => (forall s. c s a => r s p) -> ReflectedR (FlipC c a) -> r q p
flippy f = unflip . reifyR# (Flip f)

reifyR :: forall a r. (forall (s :: *). Reifies s a => Tagged s r) -> a -> r
reifyR f a = unTagged $ flippy f (Hoop a)
```

There are two big questions:

1. Is this separation worth the trouble from a cleanliness standpoint?
2. Would it be any easier to make the necessary optimizer adjustments using this form?

**Comment by treeowl** [comment]
@RyanGlScott My last comment had a mistake where `undefined` appeared in place of `f`. If you're reading this by email, make the substitution.

**Comment by treeowl** [comment]
@RyanGlScott I think I've resolved all your stated concerns. I also added the `ReflectableR` idea in the Alternatives section, since I'm now fairly convinced that it will make a cleaner interface for `reify`-style reflection.

**Comment by RyanGlScott** [comment]
@treeowl, the main body of the proposal looks quite nice.

I confess that I don't really understand the `ReflectableR` section at all. Some things that confused me were:

> It's a bit awkward to expose the issue of manually instantiating the quantified type variable when defining `reify`

Which quantified type variable (and which function—`reify#`?) are you referring to here?

> and perhaps needing them to instantiate it to a specific known type family.

I'm not even sure what type families have been discussed in this proposal! There's `ConName`, but is that you're talking about here?

> ```haskell
> class name ~ ConName1 c => Reflectable1 (name :: Symbol) (c :: k -> Constraint) where
>   data Reflected1 c :: *
>   type ConName1 c :: Symbol
>   reify1# :: forall (q :: k). (forall s. c s => r s) -> Reflected1 c -> r q
> ```

Where is the `r` variable coming from in the type signature for `reify1#`?

> The type checker could instantiate `s` to the special type of its choice, rather than making the user do so manually.

Hm, is `s` the variable you were referring to earlier in the phrase "manually instantiating the quantified type variable"?

> Unfortunately, implementing `reify` itself with this mechanism is really quite ugly, requiring an auxiliary class to "flip" `Reifies` and a newtype to flip `Tagged`. But the cleanliness may well be worth the inconvenience.

That does seem ugly. And as I've noted above, I don't see at all what this extra machinery buys you. Perhaps I'm missing something fundamental here.

**Comment by nomeata** [comment]
What is the status of this proposal?

**Comment by treeowl** [comment]
I need to make a small revision. I will try to do it by next week.

**Comment by nomeata** [comment]
> I need to make a small revision. I will try to do it by next week.

Ping :-)

**Comment by int-index** [comment]
I don't have a good alternative design, but honestly, I just dislike this `Symbol` parameter so much. It simply doesn't feel right. For instance:

* if I add ```Reflectable "Foo" c``` to a function context, I don't get `Foo` (a constructor) in scope
* this would be the first precedent where `deriving` takes up the namespace

**Comment by int-index** [comment]
The proposed design does not eliminate the need for `unsafeCoerce` if the reflectable class has an associated type family.

As motivation, I have a project where I implemented lightweight reflection with a type family ([link](https://github.com/int-index/slay/blob/697b7e15cfb6c9a004ebb05e00d2bdcc41617d8e/core/src/Slay/Core.hs#L217)):

```
data Extents = Extents Int Int

type View e a = e -> (Extents, a)

class HasView s e | s -> e where
  type Element s
  getView :: View e (Element s)

data ElementRefl s a where
  ElementRefl :: ElementRefl s (Element s)

withView :: (forall s. HasView s e => ElementRefl s a -> r) -> (View e a -> r)
withView wv view = unsafeCoerce (WithView wv) view ElementRefl
```

Initially, the class was declared with two functional dependencies:

```
class HasView s e a | s -> e, s -> a where
  getView :: View e a
```

but using a type family `Element` I eliminated a type parameter, and it is a substantial improvement to the API.

Notice that in my use case, `unsafeCoerce` performs a dual role: it converts `=>` to `->`, but it also conjures up a type equality `Element s ~ a` via `ElementRefl`.

Since the goal of the current proposal is to eliminate `unsafeCoerce` in use cases for `reflection`, I feel that the issue of associated type families must be addressed properly.

**Comment by nomeata** [comment]
Marking this as dormant until @treeowl does the promised review (or closes this as abandoned).

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Pull request closed without merging**
