### PR TITLE
Default-only methods

### PR DESCRIPTION
**Pull request by treeowl**
Allow users to indicate that certain class methods should not
be stored in instance dictionaries.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/c75edc4254fdf6af8a1bd07c8fa4141de360bef4/proposals/0000-default-only-methods.rst)

### CODE REVIEW

**Comment by goldfirere** [comment]
I was surprised by the comment that in an instance declaration, the user-specified definition would be in scope. Could you elaborate? This suggests that instances can write an implementation for a `DEFAULT_ONLY` method, but that this implementation would be utterly ignored anywhere outside the instance declaration itself. This interpretation seems dangerously unintuitive to me.

**Comment by treeowl** [comment]
@goldfirere, I think that's pretty important for the backwards-compatibility story. Suppose a user has (for whatever reason) decided to write

```haskell
instance Traversable t where
  sequenceA xs = ...
  traverse f = sequenceA . fmap f
```

If the custom `sequenceA` is ignored within the instance declaration, this will effectively be translated to

```haskell
instance Traversable t where
  traverse f = sequenceA . fmap f
```

which is an infinite loop.

Unfortunately, I just realized that there's another nasty complication. Suppose someone's written

```haskell
defaultTraverse :: (Traversable t, Applicative f) => (a -> f b) -> t a -> f (t b)
defaultTraverse f = sequenceA . fmap f

instance Traversable T where
  traverse = defaultTraverse
  sequenceA = ...
```

then we again have a loop, because `defaultTraverse` isn't in the class. Hmm....

**Comment by RyanGlScott** [comment]
Aside from the issues already mentioned, I don't think the `GeneralizedNewtypeDeriving` motive is an especially strong one. The reason being is that the issue of GND's interaction with roles is a much larger story, and this proposal won't completely sidestep that (for instance, you still wouldn't be able to derive `Traversable` for newtypes, even after this change).

This feature might still need to _interact_ with GND in some way for the sake of correctness, but I don't think it's vital to mention GND in the motivation.

**Comment by treeowl** [comment]
It would be possible using `travThen :: Applicative f => (t b -> r) -> (a -> f b) -> t a -> f r`. But as discussed, there are serious concerns already....

**Comment by simonpj** [comment]
What is the difference between a "default-only" method and a top-level declaration?  E.g.
```
square :: Num a => a -> a
square x = x*x
```
is effectively a default-only method of `Num`.

So far I see no gain, and quite a bit of pain.  Cost/benefit ratio not good!  But maybe I'm missing something.

**Comment by treeowl** [comment]
As there is no clear path toward specification as yet, let alone implementation, I am going to close this for now.

**Pull request closed without merging**
