### PR TITLE
Levity polymorphic lift

### PR DESCRIPTION
**Pull request by harpocrates**
[Rendered.](https://github.com/harpocrates/ghc-proposals/blob/levity-polymorphic-lift/proposals/0000-levity-polymorphic-lift.rst)

Credit goes to @RyanGlScott and @goldfirere for fleshing out most of these ideas in the discussion of https://github.com/ghc-proposals/ghc-proposals/pull/175.

### CODE REVIEW

**Comment by goldfirere** [comment]
It's disappointing that this proposal forces `lift` to remain in `Lift`. If we could somehow declare `lift = unTypeQ . liftTyped` and force GHC to inline it everywhere, we'd be fine. (Well, we wouldn't be fine on higher-order uses of `lift`. Blast those functional languages.)

Otherwise, I'm strongly in support.

**Comment by simonpj** [comment]
> The main drawback is that uses of lift, TExp, unType, unTypeQ, and unsafeTExpCoerce which have visible type applications will be broken (since the type argument would now refer to the runtime rep).

Could the runtime-rep arg be Inferred, leaving the other as Specified?  That would resolve this niggle

**Comment by simonpj** [comment]
Generally, I'm supportive of this proposal.  But I'm not sure why it's focused on `Lift`. One could make a very similar proposal for `Num`, and other classes, as the original paper about levity polymorphism says.

**Comment by harpocrates** [comment]
> Could the runtime-rep arg be Inferred, leaving the other as Specified? That would resolve this niggle

Doesn't this require the [Explicit specificity in type variable binders](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0026-explicit-specificity.rst) proposal to be implemented though? If not, could you perhaps include an example of how this could be done?

> Generally, I'm supportive of this proposal. But I'm not sure why it's focused on `Lift`. One could make a very similar proposal for `Num`, and other classes, as the original paper about levity polymorphism says.

I was hoping `Lift` could serve as a first real-world guinea pig. It is nicely suited to that role because `template-haskell` users will be more tolerant of breakage than users of `base` (so we can even continue to tweak `Lift` in coming GHC releases). Besides, I think there is already [another proposal taking aim at the more ambitious goal of making `Eq`, `Num`, etc. levity polymorphic](https://github.com/ghc-proposals/ghc-proposals/pull/30).

**Comment by simonpj** [comment]
> Doesn't this require the [Explicit specificity in type variable binders](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0026-explicit-specificity.rst) proposal to be implemented though?

Hmm, yes perhaps it does. But then, please point this out in the proposal; i.e. that breakage can be avoided if we do the other proposal.

> I was hoping `Lift` could serve as a first real-world guinea pig. I

Again, call that out explicitly and point to the other proposal

**Comment by harpocrates** [comment]
> > Doesn't this require the [Explicit specificity in type variable binders](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0026-explicit-specificity.rst) proposal to be implemented though?
>
> Hmm, yes perhaps it does. But then, please point this out in the proposal; i.e. that breakage can be avoided if we do the other proposal.

I do call this out in the unresolved questions section.

> > I was hoping `Lift` could serve as a first real-world guinea pig. I
>
> Again, call that out explicitly and point to the other proposal

It seems a bit excessive to justify paths _not_ taken by this proposal. This is a bit of a special case though, so I'll amend the proposal.

**Comment by Ericson2314** [comment]
@goldfirere tangential, but I wish us *not* to desugar `lift` now, because typed template Haskell is somewhat hostile to cross compilation, where we wish (and do today via hacks) run TH on a different platform so the types are the wrong ones.

**Comment by mpickering** [comment]
I think `Lift` is a bit different to `Eq` and `Num` because the compiler could implement logic to solve instances automatically for the majority of data types. This makes it even more annoying when it's impossible to write an instance for a unlifted type.

**Comment by harpocrates** [comment]
@nomeata Could we submit this to the committee for review? Discussion seems to have died down and I don't think there are any outstanding concerns.

**Comment by gridaphobe** [comment]
This is somewhat tangential to the actual proposal, but the example in the motivation

```
main = print =<< runQ (unTypeQ [|| I# $$e ||])
  where e = [|| 1# ||]
```

seems like it must be a bug in GHC. 

If I query GHC for the type of the splice, I get

```
> :t [|| 1# ||]
[|| 1# ||] :: Q (TExp Int#)
```

But this doesn't make any sense, because, as the proposal points out, `TExp Int#` is ill-kinded.

**Comment by simonpj** [comment]
> seems like it must be a bug in GHC.

Could you, or someone, file a bug report?

**Comment by simonpj** [comment]
Generally I'm happy with this proposal.

But, before implementation, I do think that we should first decide about the [explicit specificity proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0026-explicit-specificity.rst).  If that proposal was in, we'd probably choose to make `lift` etc have an inferred runtime-rep parameter.

We don't want to get people change their libraries to add extra `@_` parameters, and then change them again to take it out!

**Comment by gridaphobe** [comment]
> Could you, or someone, file a bug report? 

https://ghc.haskell.org/trac/ghc/ticket/16384

**Comment by gridaphobe** [comment]
@simonpj the Explicit Specificity Proposal appears to be accepted already (though perhaps not yet implemented?).

So perhaps @harpocrates can change the proposal such that `lift` takes an inferred RuntimeRep, and the GHC patch can be merged once Explicit Specificity is implemented.

**Comment by harpocrates** [comment]
> So perhaps @harpocrates can change the proposal such that lift takes an inferred RuntimeRep, and the GHC patch can be merged once Explicit Specificity is implemented.

Sure, I'll update the proposal.

@goldfirere is there anything blocking the implementation of the explicit specificity proposal? I see it was accepted 8 months ago, yet it doesn't have an associated Trac issue.

**Comment by goldfirere** [comment]
No -- nothing blocking that proposal, other than the lack of time to implement it. If you want to make a Trac ticket (and update the accepted proposal text to point to it), I'd be grateful. I'd be even more grateful if you wanted to take a stab at implementing it! :) Shouldn't actually be all that hard.

**Comment by harpocrates** [comment]
> No -- nothing blocking that proposal, other than the lack of time to implement it. If you want to make a Trac ticket (and update the accepted proposal text to point to it), I'd be grateful. I'd be even more grateful if you wanted to take a stab at implementing it! :) Shouldn't actually be all that hard.

Sounds good. I'd be open to implementing it, provided you can provide some pointers along the way. I'll make a Trac issue, CC you, and let's discuss there. 😄

**Comment by RyanGlScott** [comment]
I must be missing something. How will explicit specificity help here? Reading [the explicit specificity proposal](https://github.com/ghc-proposals/ghc-proposals/blob/e310040d496a827aa78b5de532dc4a999081f4c2/proposals/0026-explicit-specificity.rst), it doesn't seem to suggest a syntax for controlling whether type variables in class declarations are inferred or not. The closest thing I could find is one mention in the [Unresolved questions section](https://github.com/ghc-proposals/ghc-proposals/blob/e310040d496a827aa78b5de532dc4a999081f4c2/proposals/0026-explicit-specificity.rst#unresolved-questions):

> How will this interact when we have visible type application in types (proposal #80)? For example, consider
> 
> ```haskell
> class C (a :: Proxy k) where ...
> ```
> 
> I want `C` to have only one required argument, `a`. But I also want an explicit binding site for `k`, so I can choose `k`'s kind. A nice new piece of syntax would be
> 
> ```haskell
> class C @(k :: Maybe Bool) (a :: Proxy k) where ...
> ```
> 
> This was suggested by @Saagar-A in the commentary. What if the author wanted `k` to be _inferred_? Then they would have to use a top-level kind signature, as proposed in #54. This last case should be rare enough that making it inconvenient should be OK.

Doesn't that suggest that in order to make the `r` in `lift :: forall r (a :: TYPE r). a -> Exp` inferred, we'd actually need to implement top-level kind signatures first?

**Comment by harpocrates** [comment]
Good point. Really, we'd need both top-level kind signatures and explicit specificity. Assuming I'm reading both proposals right, that's

```haskell
type Lift :: forall {r :: RuntimeRep} (t :: TYPE r). t -> Constraint
class Lift (t :: TYPE r) where { ... }
```

What a mouthful.

**Comment by gridaphobe** [comment]
@harpocrates sorry for the delay!

The committee is concerned about the backwards compatibility story with giving `lift` and `liftTyped` mutually recursive default definitions. This change would break existing empty `Lift` instances, as the new defaults would be non-terminating, and unfortunately the `MINIMAL` pragma issues a warning rather than an error. We had the same concern during the discussion of #175 but had decided in favor of making `liftTyped` the sole method, which is no longer a possibility as of this proposal.

So, what we propose instead is to simply not provide a default implementation of `liftTyped`. This does mean that existing empty instances would have to be modified to implement `liftTyped`, but they could also just switch to `DeriveLift`.

How does that sound to you?

**Comment by harpocrates** [comment]
> So, what we propose instead is to simply not provide a default implementation of `liftTyped`. This does mean that existing empty instances would have to be modified to implement `liftTyped`, but they could also just switch to `DeriveLift.`

Sounds reasonable to me, I'll update the proposal (that might take a couple days - I'm on a trip).

**Comment by nomeata** [comment]
> Sounds reasonable to me, I'll update the proposal (that might take a couple days - I'm on a trip).

Ping! :-)

**Comment by nomeata** [comment]
@gridaphobe now a ping to you :-)

**Comment by gridaphobe** [comment]
Thanks for updating the proposal, this looks good to me. Let's merge @nomeata.

**Pull request merged**
