### PR TITLE
Relax qualified import syntax

### PR DESCRIPTION
**Pull request by cblp**
[Rendered](https://github.com/cblp/ghc-proposals/blob/patch-2/proposals/0000-relax-qualified-import-syntax.rst)

### CODE REVIEW

**Comment by ivan-m** [comment]
Slight drawback  (but overall I think I like this): it can still be hard to spot the `qualified` keyword when mixed in with lines containing explicit vale imports.

**Comment by cblp** [comment]
Usually people use qualified imports \`xor\` explicit import lists (see @tibbe's style guide). So, qualified import are simply those without parentheses.

**Comment by ivan-m** [comment]
I mean when that when one line has an explicit import list and the next has a qualified import.

**Comment by niteria** [comment]
Other not immediately obvious costs of this change:
* syntax highlighters for all the editors may need to be updated
* `ghc-exactprint` will have to distinguish between different forms of qualified imports to be able to put it back in the same way
* beginners will see both forms in the wild and wonder if they mean different things

See also https://mail.haskell.org/pipermail/ghc-devs/2016-October/013036.html for related proposals.

**Comment by cblp** [comment]
@niteria 

> - syntax highlighters for all the editors may need to be updated

Yes, I mentioned it in *Drawbacks* section.

> - ghc-exactprint will have to distinguish between different forms of qualified imports to be able to put it back in the same way

No, there is no semantic difference, so we can just choose one of forms as canonical, like I sometimes see `(+) a b` in GHC errors instead of `a + b`.

**Comment by niteria** [comment]
@cblp 
Ok, let me elaborate on the `ghc-exactprint` point. `ghc-exactprint` is the workhorse of `apply-refact` a tool for applying refactorings. It is **not** used by GHC internally.

The point of `ghc-exactprint` is that you can do some source level change like refactoring `concat . map f` to `concatMap f` in the file without changing how the code is laid out anywhere else. If `ghc-exactprint` took one form as canonical, it would make unnecessary and unwelcome changes to your file.

**Comment by jsdw** [comment]
I like the general feel of this change, but the thing that bugs me more is having to double up on lines for almost every import. If I was being more drastic, I'd want "qualified" to be the default, as it's normally the right thing to do. I basically think Elm nailed this, something like:

```
import Data.ByteString as ByteString exposing (ByteString)
```
meaning "import Data.ByteString under the namespace ByteString, exposing Data.ByteString.ByteString".

a less drastic addition to the current proposal however that cuts the line count down nicely would look more like:

```
import Data.ByteString qualified as ByteString (ByteString)
```

where I omit the "exposing" to be similar to existing syntax for bringing specific names into scope:

```
import Data.ByteString (ByteString)
```

**Comment by tolysz** [comment]
Is there anything from:
https://ghc.haskell.org/trac/ghc/ticket/9977
We could include?

**Comment by cblp** [comment]
@jsdw @tolysz I tried to avoid messing with "short import" proposals. This proposal has different goal.

**Comment by cartazio** [comment]
1 small smell test: have you tried changing the GHC grammar etc to see if the the # of shift reduce conflicts etc changes?

**Comment by cblp** [comment]
@cartazio I haven't yet, but I'm going to try. What conflicts are you talking about?

**Comment by cdsmith** [comment]
Here's a much simpler proposal, though the benefits are further removed in time.

1. Start giving compiler warnings for programs that use `import Foo as F`, and then refer to symbols from Foo unqualified.  Practically no one does this on purpose anyway.
2. After a suitable time, start treating such imports as qualified, which is a breaking change.  At the same time, warn on uses of the `qualified` keyword.
3. After a suitable time, remove the `qualified` keyword.

**Comment by Lemmih** [comment]
@cdsmith I do that on purpose from time to time. :-/

**Comment by cblp** [comment]
@cdsmith would you mind to open another proposal? Looks taking much longer time to get to life, but interesting!

Just a little proposal to your proposal:
1a. Warning is disabled by default, and enabled with `-Wall`.
1b. Warning is enabled by default.

Your and my proposals may be implemented independently.

**Comment by chreekat** [comment]
The proposal lists two ways of writing imports, both of which are painful. However, it did not mention a third. All my import pain went away when I started bunching `import qualified` separately:

```haskell
import Text.Jasmine (minifym)
import Yesod.Default.Util (addStaticContentExternal)
import qualified Data.List as List
import qualified Data.Text as T
import qualified Yesod.Core.Unsafe as Unsafe
```

This sorts lexicographically, and hardly causes any trouble when visually scanning for module names. Further, it makes qualified imports dead easy to spot, which the proposal fails to do.

I think this style should be considered before changing the language.

**Comment by ezyang** [comment]
Is there any further motivation beyond aesthetic whitespace issues on import lists?

**Comment by int-index** [comment]
If this gets implemented, it should be an extension that disables the old syntax. I'd hate to ever encounter an import list that uses both the old and the new syntax.

**Comment by alexanderkjeldaas** [comment]
The proposal doesn't mentioned restricted qualified imports:
```
import Data.Map (A, B, C) qualified as Map
```

**Comment by mpickering** [comment]
-1 from me. I agree with the motivation that is nice to have but small changes to syntax cause cognitive overhead and make languages messier if the old behaviour remains.

**Comment by barrucadu** [comment]
It's mentioned in the unresolved considerations, but I feel like the difference this would introduce between `qualified`, `source`, and `safe` imports is particularly bad. Special-cases in language syntax are not good, particularly when there's no obvious reason why it shouldn't be `import Foo safe` given that `import Foo qualified` would be fine.

**Comment by erikd** [comment]
This is a very simple syntactic change that has a low risk of inducing unwanted extra complexity or maintenance burden, but provides some real benefit. I'm :+1: on this.

**Comment by cblp** [comment]
@chreekat splitting imports of the same module is even more painful.

**Comment by cblp** [comment]
@ezyang aesthetics and readability is the only motivation of this proposal.

**Comment by cblp** [comment]
@int-index hindent will help us

**Comment by cblp** [comment]
@alexanderkjeldaas 
> The proposal doesn't mentioned restricted qualified imports

Should it?

**Comment by cblp** [comment]
@int-index I think of warning in case when both are used.

**Comment by cblp** [comment]
@mpickering: @cdsmith has [proposal](https://github.com/ghc-proposals/ghc-proposals/pull/21#issuecomment-253557334) how to eliminate old syntax

**Comment by cblp** [comment]
@barrucadu Let's do the safe for "source" and "safe" labels. I've updated text.

**Comment by cdsmith** [comment]
@cblp I don't feel strongly enough to start a new proposal or champion the idea.  A bunch of people already have opinions about import syntax, and most of them better informed than mine.  I was just sharing ideas.

I do think this proposal sounds like a small incremental improvement.  So don't interpret my comment as disagreement.  I don't have a strong opinion either way, to be honest.

**Comment by bgamari** [comment]
Hi @cblp,

While strictly speaking this proposal is one week from the end of its discussion period, we can keep the period open for a few more weeks if you would like to solicit further feedback from the community. Otherwise we would ask you to either bring the proposal to the steering committee for consideration at the end of next week or close the request.

Thanks to everyone who has contributed thusfar!

**Comment by mchakravarty** [comment]
I am against adding redundant syntax. If we could change the language to only use the new syntax, that might be worth a thought (but obviously we can't do that). Having two different ways to write the exact same thing adds costs without any real benefit. The new syntax might look nice, but the fact that different modules will use different syntax and might even mix it makes the language overall worse.

**Comment by cblp** [comment]
I'm not sure I what this proposal to be implemented. I'd better open another one taking into account all the feedback this one got.

**Comment by bgamari** [comment]
Sounds good. I'll go ahead and close it in that case. Thanks for your efforts on this!

**Pull request closed without merging**
