### PR TITLE
Resurrect PatternSignatures

### PR DESCRIPTION
**Pull request by nomeata**
[Rendered](https://github.com/ghc-proposals/ghc-proposals/blob/patternsignatures/proposals/new-proposal.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
Here is a user who was confused by having to use `ScopedTypeVariables` to get pattern signatures: https://stackoverflow.com/q/29395265/946226 
And here is a (decate old) rant about this on a mailing list: https://mail.haskell.org/pipermail/haskell-cafe/2009-April/059519.html

**Comment by JacquesCarette** [comment]
The proposal I'm really looking for is the one that makes `ScopedTypeVariables` an official part of Haskell the language rather than some language option to turn on.  Where would that one be?

**Comment by parsonsmatt** [comment]
@JacquesCarette I think anything that modifies "Official Haskell" is going to have to be wrapped into the next Haskell Report. I don't know how that process is going. I do agree that would be awesome.

**Comment by ocharles** [comment]
I believe that's outside the scope of this repository, that's really a
haskell prime prosoal.

**Comment by nomeata** [comment]
> I believe that's outside the scope of this repository, that's really a haskell prime prosoal.

That’s correct. It might be that the Haskell Prime committee will consider `ScopedTypeVariable` to be “too big” or not uncontroversial enough; in that case I hope that at least the much more mundane `PatternSignatures` can become available by default.

**Comment by JacquesCarette** [comment]
Right -- https://prime.haskell.org/ticket/67 seems to be the ticket.

**Comment by gbaz** [comment]
That's actually the reason for my conservatism on this too. My feeling is this is all part of a class of "obviously these should be the default" extensions and having more granularity about them seems to be swimming against the stream, since it would be nicer to not have to add any of them at all :-)

**Comment by nomeata** [comment]
I am all for having both by default! But this discussion here is “what world to we want after the next GHC release”, not “what world do we want if Haskell prime happens”, which maybe much further in the future. Don’t let perfect be the enemy of good.

**Comment by JacquesCarette** [comment]
@nomeata Good point.  +1 from me on this, for that reason.

**Comment by gbaz** [comment]
> Don’t let perfect be the enemy of good.

Wait? Is this the ghc-proposals tracker? I must be lost :-P

**Comment by tomjaguarpaw** [comment]
Is there somewhere a proposal for `-XOptionsWeAllLove` which includes all of our favourite options?  That seems like it would be a pragmatic approach for getting something accepted into the report.

**Comment by AntC2** [comment]
Thanks @nomeata, it's not clear to me whether you're just complaining `ScopedTypeVariables` is a misleading name; or that you deliberately _don't_ want type variable scoping but _do_ want pattern signatures.

For myself, I find it far too confusing to give local signatures inside `let/where` or instance decls that have tyvars same named as the top level signature, but not being the same. So I always have `ScopedTypeVariables` switched on; and use distinct tyvar names in local signatures. Then this proposal is no use to me. (Arguably it was an omission in Haskell 98 not to scope type variables; so it shouldn't even need an extension, as @JacquesCarette says. Arguably also we should be able to put a type signature on any variable or pattern wherever it appears. Then would you be happy?)

If the complaint is just about a misleading name; well ghc extensions have lots of them. Perhaps "confused users" just have to get used to it?

**Comment by adamgundry** [comment]
> That's actually the reason for my conservatism on this too. My feeling is this is all part of a class of "obviously these should be the default" extensions and having more granularity about them seems to be swimming against the stream, since it would be nicer to not have to add any of them at all :-)

I think `PatternSignatures` (as proposed here) "obviously" should be the default, but that `ScopedTypeVariables` should not. I'd much rather be able to bind type variables using explicit type abstractions (parallel to explicit type applications, cf. #96). Perhaps one day there will be an extension that allows me to! In the meantime, being able to turn on `PatternSignatures` alone would allow me to use them while knowing that my code does not rely on funky type variable scope rules. Thus I support this proposal.

**Comment by tomjaguarpaw** [comment]
Does anyone know the reason that `PatternSignatures`'s behaviour is not default?  Was it just an oversight in the original report or is there some more important reason?

**Comment by treeowl** [comment]
Let me be the dissenting voice. I *always* want `ScopedTypeVariables`. Anything that suggests to me that it is enabled without actually enabling it leads me to confusion and wasted type-debugging time. Without this proposal, seeing a pattern signature is proof positive that my type variables are scoped. With it, it's just as confusing as `ExplicitForAll`. I understand some people think we should have explicit type abstraction instead. I think they're probably right, in the *absence* of explicit type application. But in the presence of explicit type application, I would have to jump through even more hoops to avoid signaling to users that my function has an intentional explicit type application interface they can count on.

**Comment by tomjaguarpaw** [comment]
@treeowl Let me see if I understand you correctly.  You are against an extension to enable syntax like

```haskell
let x :: Int = 0
```

because you currently use the presence of such syntax to deduce that `ScopedTypeVariables` is on?

**Comment by treeowl** [comment]
@tomjaguarpaw, it's not that I do so intentionally. But I probably do so subconsciously, so I predict this change would make me more likely to get confused. I'm not actually dead-set against the proposal, but I do think the proposal text should include the potential for confusion in the appropriate section. I'd also like to see more discussion of how we can get the power we want from `TypeApplications` and `ScopedTypeVariables` without the wild API flux of the former or the potential confusion in the latter over what is being bound vs. what is being specified. I don't know whether this is the appropriate place for that discussion.

**Comment by simonpj** [comment]
The "proposed spec" says

> The language extensions PatternSignatures is no longer deprecated. If enabled, it allows all signatures on patterns that do not bind type variables.

What does that mean?  Suppose I have with `-XPatternSignatures` but not `-XScopedTypeVariables`.  If I write
```
f (x :: [a]) = b.ah
```
is that allowed or not-allowed?  Perhaps it is allowed, but does not bring `a` into scope?  Please say.

**Comment by nomeata** [comment]
It’s not allowed. I clarified the proposal.

**Comment by simonpj** [comment]
> It’s not allowed. I clarified the proposal

Why not?  It seems like a free design choice to allow or not-allow.  And not-allowing means you simply can't use a pattern signature in places you might really want to.

**Comment by nomeata** [comment]
> Why not? It seems like a free design choice to allow or not-allow. And not-allowing means you simply can't use a pattern signature in places you might really want to.

I must admit I did not think about this yet, thanks for bringing it up.

It seems that there are three options what to do in the absence of `ScopedTypeVariables`

 1. `foo (x :: a) = …` is interpreted like a signature on the RHS: Every type variable is abstracted over inside the pattern, i.e. equivalent to `foo (x :: forall a. a) = …` (with `ExplicitForAll`)
 2. `foo (x :: a) = …` is interpreted like with `ScopedTypeVariable`, and the `a` may unify with any (possibly internal) type variable in scope.
 3. `foo (x :: a) = …` is disallowed.

Both 1 and 2 have their merits: 1 is more consistent with how signatures are treated in general, while 2 is closer to what we get when we turn on `ScopedTypeVariables`.  But since they disagree, 3 is a safe  common denominator, and the user can disambiguate by either turning on `ScopedTypeVariables` or by spelling out the `foralls`.

But I don't feel strongly about this and am happy to yield to other people’s wisdom here.

**Comment by simonpj** [comment]
By (2) do you mean "behaves like pattern signatures do today, but without bringing any type variables into (lexical) scope"?   If so, that's the obvious one to choose, because it means that

* `-XPatternSignatures` behaves uniformly, regardless of `-XScopedTypeVariables`.
* The difference when switching `-XScopedTypevariables` on and off whether or not a type variable is brought into scope, no more and no less.

**Comment by goldfirere** [comment]
But what would `foo (x :: Either a a)` mean? If there's no lexical scope here, those `a`s would be *different*. That behavior seems baffling to me.

**Comment by nomeata** [comment]
> But what would `foo (x :: Either a a)` mean? If there's no lexical scope here, those as would be different. That behavior seems baffling to me.

There is still a lexical scope, it just doesn’t extend beyond the type signature… :-)

I’d say: Let’s keep things simple. `PatternSignatures` is for those people who are confused by their programs and want to add type signatures everywhere to find where they got their simple types wrong. These are likely not the people who virtuously juggle polymorphic functions – those probably should head to `ScopedTypeVariables` straight away, and would be told so by GHC.

**Comment by cartazio** [comment]
To chime in:
Scoped type variables is pretty uncotnroversial for the h2020 committee.
Everyone’s pro making that default in h2020.  I forget who’s owning that
one

Making it the default for ghc would be too :)

**Comment by simonpj** [comment]
> I’d say: Let’s keep things simple

Yes, I agree.  For me "simple" means

* `PatternTypeSignatures` allows pattern type signatures
* `ScopedTypeVariables` brings lexically-scoped type variables into scope under particular circumstances

The less they interact the better.

Re `f (x :: Either a a) = e`, yes those a's are the same, just as they are in 
```
g :: Either a a
```
We always have a tiny implicit lexical scope for each type, even in H98.

**Comment by cartazio** [comment]
Fair point. I guess I’d favor that too as a better and friendlier option.

**Comment by nomeata** [comment]
I changed the proposal to reflect Simon’s suggestion – this point is too marginal to have a long discussion about.

**Comment by nomeata** [comment]
> this point is too marginal to have a long discussion about.

Changed my mind :-]

For one target audience of this extensions (confused beginners who want to add type signatures to every subterm, whether left or right of the `=`, to hunt down type error) the rules around type variables in patterns are certainly far too confusing. Also, it would be strange to forbid

    id :: a -> a
    id x = (x :: a)

but allow

    id :: a -> a
    id (x :: a) = x

I feel that rejecting a program with a message that essentially says “you are doing something non-trivial, please use `ScopedTypeVariables` like the grown-ups” is going to be more helpful than doing something that only people understand who want `ScopedTypeVariables` anyways.

**Comment by nomeata** [comment]
> Is that OK? Because that pattern signature does have some (invisible) kind variables.

Hence my phrasing: “Does not bind type variables”. It is a pure renamer check: Is there a type variable in the pattern that is not already in scope? Then the program needs `ScopedTypeVariable`! No need to wait for the type checker to decide that, and the type checker code is unaffected by this proposal.

(I guess without `ScopedTypeVariables` there is really never ever a type variable in scope in a pattern… at some point I believed that in type classes their type variables are in scope, but I was wrong … anyways, if someone finds a way to have a type variable in scope, then an occurrence of such a variable would be allowed.)

> It sounds to me like the best way forward is to treat pattern annotations exactly like expression annotations, where any type variables are locally bound by a `forall`. 

I see the consistency, but it would be incompatible with `ScopedTypeVariables`, which is, I believe not helpful.

But still thanks for your point, because the contention only supports the plan to pass such programs right back to the user for clarification :-)

**Comment by treeowl** [comment]
My concern is magnifying. The proposed extension offers very little power, and there's a tremendous amount of disagreement about what exactly it should mean. If this gets added, someone will have to work out how each new (and more powerful) feature needs to interact with it. My general thinking is that having an extension like this that supports completely monomorphic signatures (no type variables) should be acceptable. Beginners will be able to use that without any trouble, and everyone else can just ignore it. Once type variables come in, my vote goes from "don't care much" to "please don't".

**Comment by simonpj** [comment]
> It sounds to me like the best way forward is to treat pattern annotations exactly like expression annotations, where any type variables are locally bound by a forall

(I assume you mean with `-XPatternSignatures` but `-XNoScopedTypeVariables`. )  No, we definitely could not do what you suggest, because the meaning would change radically when you switched on `-XScopedTypeVariables`.  That would be truly gruesome.  Joachim's proposal that a pattern signature cannot mention any type variable not already in scope is less terrible.

I'm inclined to agree with David -- it's really not worth the effort to make the distinction between these two extensions.

**Comment by nomeata** [comment]
David says

> My general thinking is that having an extension like this that supports completely monomorphic signatures (no type variables) should be acceptable.

which is what the proposal currently says!

Well, not quite: it says “binds no type variables“, which amounts to, and could be rephrased as, ”has no free type variables”. This intentionally allows `(x :: forall a. a -> a)`, which is useful with `RankNTypes`:
```
Prelude> :set -XRank2Types  -XPatternSignatures
Prelude> let foo (reorder :: (forall a. [a] -> [a])) = reorder "hello"
Prelude> :t foo
foo :: (forall a. [a] -> [a]) -> [Char]
```
But I assume this part is uncontroversial.

Are we in agreement that `PatternSignatures` without `ScopedTypeVariables` ought not have any free type variables.

**Comment by simonpj** [comment]
> Are we in agreement that PatternSignatures without ScopedTypeVariables ought not have any free type variables.

No -- I argue that `PatternSignatures` should pave precisely the same semantics as today, except not bringing type variables into scope.   That way the two are 100% orthogonal.

But that's just my opinion.

**Comment by nomeata** [comment]
The proposal doesn’t seem to receive support in the committee anyways, so this discussion somewhat futile now, but I am happy to address some your points (if I understand them correctly, I am notsure)

Because of

> Then they are surprised that with ScopedTypeVariables the explicit forall on a function signature (or RHS expression) changes the semantics of the program.

I want to forbid pattern signatures that have free type variables, and have the compiler tell the user “Either close the type signature with `forall a.`, or add `ScopedTypeVariables`, to disambiguate”.

If `PatternSignatures` treats free type variables in the same way as `ScopedTypeVariables`, then it just a synonym for `ScopedTypeVariables` (status quo). If it treats them differently, then it is not compatible, which would be bad.

**Comment by AntC2** [comment]
> The proposal doesn’t seem to receive support in the committee anyways, ...

Thanks @nomeata. As the proposal currently stands, I'd agree it has low power to weight. I was looking for a way to give more power (and particularly thinking of helping "confused beginners").

>> Then they are surprised that with ScopedTypeVariables the explicit forall on a function signature (or RHS expression) changes the semantics of the program.

> I want to forbid pattern signatures that have free type variables, ...

One of your complaints was that `ScopedTypeVariables` is a misleading name when you only want to put pattern signatures. Then `PatternSignatures` is a misleading name if you can't put pattern signatures with `tyvar`s -- as you can usually in a signature.

> If PatternSignatures treats free type variables in the same way as ScopedTypeVariables, then it just a synonym for ScopedTypeVariables (status quo). If it treats them differently, then it is not compatible, which would be bad.

I think I've steered a course between Scylla and Charybdis: this is not status quo, because I suggest binding fresh `tyvars` by introducing them in pattern signatures. (I suspect a lot of the use cases for `ScopedTypeVariables` can be written this way _without_ needing explicit `forall` on some distant signature.) It is compatible with/orthogonal to `ScopedTypeVariables`/explicit `forall` because `tyvars` introduced this way must be fresh/not already in scope.

**Comment by nomeata** [comment]
>  Then PatternSignatures is a misleading name if you can't put pattern signatures with tyvars -- as you can usually in a signature.

Oh, you still can; you just have to put in the `forall`’s to clarify your intent (I see the argument for implicit quantification in patterns; it would be a straight analogue to type annotations in terms, but – to me – compatibility with `ScopedTypeVariables` trumps that argument.)

> I suggest binding fresh tyvars by introducing them in pattern signatures

`ScopedTypeVariables` support precisely that!

**Comment by AntC2** [comment]
> Oh, you still can [put pattern signatures with `tyvars`]; you just have to put in the `forall`’s to clarify your intent 

? Your option 1. above shows `f (x :: forall a. a) = ...`, in which `a` is useless because it's not scoped to rhs of the `=`. (Or if it is, that's not said anywhere.) You do allow `forall` for a `RankNType`, which is somewhat more useful.

If we're thinking about "confused beginners", putting explicit `forall` is what they find confusing. (And if they're using `RankNTypes` (or existentials) they're not beginners.)

Then it appears I've been labouring under a misunderstanding. Thank you for pointing this out:

>> I suggest binding fresh tyvars by introducing them in pattern signatures

> `ScopedTypeVariables` support precisely that!

OK. Then I'm proposing that bit of `ScopedTypeVariables` (additional to your proposal) be included in `PatternSignatures` -- good! So it is compatible. 

What's confused me is the User Guide 10.16.4 saying "pattern type signatures are not implicitly generalised. The pattern in a pattern binding may only mention type variables that are already in scope." It goes on to discuss binding for existentials: "in this situation (and only then)" is just false. "If all this seems a little odd, ..." that I quote above is just false. Neither the User Guide nor your proposal have any dead-simple examples like:

    -- no signature for bar, baz; aa is not in scope
    bar (x :: aa) = x :: aa        -- } no explicit forall
    baz (Just (y :: aa)) = y :: aa -- } currently only valid with ScopedTypeVariables [Note **]

And [your comment](https://github.com/ghc-proposals/ghc-proposals/pull/119#issuecomment-385704811) -- my `bar` is your `id` in that comment -- is also warning against odd behaviour.

> With `ScopedTypeVariables`, if you use a type variable in a pattern that is not already in scope, it will be brought into scope right there. It sounds like you were proposing that behavior?

Yes. Hooray! Where is that behaviour described? And why wouldn't you want it included in `PatternSignatures`?

So I'm proposing `PatternSignatures` (in the absence of `ScopedTypeVariables`) does not imply `ExplicitForall` -- but neither does it contradict that.

[Note **] I'm getting weirded out: that `bar, baz` appears to be valid in Hugs (and works). Does that mean it's H98 and ghc is not compliant? No I don't think so. If it's in Hugs, I rest my case about "confused beginners".

**Comment by nomeata** [comment]
This proposal was rejected for insufficient merit.

**Comment by goldfirere** [comment]
Just in case anybody ever wanders back here: I just wanted this feature.

I'm writing a Haskell application which I will use in a class that teaches a very limited amount of Haskell. For it to actually get work done, I sadly need a stack of monad transformers. I won't be requiring students to edit that code, but I want *some* guidelines for the intrepid. At one point, I have

```
  result <- flip evalStateT initialState $ runMaybeT $ runExceptT $ runMyMonad thing_inside
```

Even I go cross-eyed on that line. So I modified it to be

```
  result :: Maybe (Either String ())
         <- flip evalStateT initialState $ runMaybeT $ runExceptT $ runMyMonad thing_inside
```

Much better -- now I know what I'm working with. But silly GHC won't accept this without `-XScopedTypeVariables`. I certainly don't *want* scoped type variables for this. But, today, I get them whether I want it or no. And now, my students may see that extension and get more than they bargained for. (Though, perhaps, if they're bargaining with a stack of monad transformers, they've already lost the bargain.)

I'm not trying to reverse a decision, but just laying out an additional use case I just ran into for posterity.

**Comment by AntC2** [comment]
... or persuade that `PatternSignatures` should always have been part of the language, and get it into the Haskell 2020 standard.

**Comment by nomeata** [comment]
> ... or persuade that PatternSignatures should always have been part of the language, and get it into the Haskell 2020 standard.

That was my other motivation: By giving the extension a name in the first place we can talk about it on the way to a new standard.

**Pull request closed without merging**
