### PR TITLE
DuplicateRecordFields simplification

### PR DESCRIPTION
**Pull request by adamgundry**
[Rendered](https://github.com/adamgundry/ghc-proposals/blob/duplicaterecordfields-simplification/proposals/0000-duplicaterecordfields-simplification.rst).

### CODE REVIEW

**Comment by AntC2** [comment]
Thanks @adamgundry, count me amongst the "disappointed", but I see where you're coming from.

Do you have a feel for how much uptake there has been for `DuplicateRecordFields`? (You say "relatively limited use".) I don't see much traffic about it; but then perhaps I lurk on the wrong forums. Are folks using it to declare same-named fields in the same module, but then accessing those fields by other means (such as via lenses)? If so, this change won't affect them.

For those examples which are currently accepted but will be rejected by this proposal, is it possible to put alongside what's needed to get them to work -- extra type annotations, or especially if it can use the `HasField` approach? So that we can see the impact suffered for code that will break.

We always knew that name resolution would fail in a significant number of cases where the answer was "obvious". We might "increase the use of type inference" as you mention in **Alternatives**, but I think that'll just duplicate what you can achieve with `HasField` -- which is really the way forward.

I'll do some head-scratching about `PatternSynonyms`.

**Comment by cartazio** [comment]
so is this only impacting users of duplicate record fields FOR record update syntax? 

it seems is mostly motivated by ghc encouraging/favoring names to be resolved before type checking, right? hrmmm... isn't this exactly what type classes are for?

**Comment by cartazio** [comment]
it does seem unfortunate to loose bidirectionality though. (granted, the way i use duplicate record syntax theres always a top level type sig to push info down, but i'm wondering/worrying if that might not be enough?)

**Comment by simonpj** [comment]
I'm in favour of this.  My design principle is: do the simplest thing first, and make it more complicated only if actual use demonstrates that something more complicated will have a major payoff.

DuplicateRecordFields is an experimental change at the moment; I don't think we need worry too much about about back-compat.  In any case the workarounds are easy.

If we'd proposed DRF using the GHC proposals process (it slightly predated it) I doubt it'd have been accepted in its present form.

Despite seeming quite innocuous, the whole DRF thing turned out significantly more complicated than I feel comfortable with, principally in the renamer's data structures.  But I did talk to Adam quite a bit at the time and I don't have any solid suggestions for making it simpler.  But that's the direction I'd like to go in!

**Comment by AntC2** [comment]
This is annoying. 

>    e x = (x :: T) { foo = 3 }   -- by rule 5
>
>    g :: T -> T
>    g x = x { foo = 3 }          -- by rule 6       

Rule 6 to be replaced, so `g` will not work. Then:

    g' (x :: T) = x{ foo = 3 }   -- GHC complains foo is ambiguous, at GHC v6.0

What's the principle whereby `e` works but `g'` doesn't? (By rule 5, `x` does have an explicit type signature -- it's just on the ther side of the `=`.)

**Comment by AntC2** [comment]
Re `PatternSynonyms`, can you be more precise what's not satisfactory? [And should we discuss it here or on Trac #11228? That ticket's description is about ORF, and there's a fix to do with `DisambiguateRecordFields`. So _not_ `DuplicateRecordFields`?]

The details on that ticket are to do with GHC internals/definition of the field labels. How does it impact what programs you can('t) write?

I can declare a `PatternSynonym` whose rhs is a datatype with `DuplicateRecordFields`. That pattern (and its fields) seems to work OK for both selecting and updating.

What I can't do (as the ticket says) is:

* declare a `PatternSynonym` with fields same-named as another pattern; nor
* declare a `PatternSynonym` with fields same-named as some datatype;
* including you can't name the pattern's fields same as the underlying datatype's.

That last point seems to me very sensible: how on earth could you hope to resolve that ambiguity? You'd need the pattern's data constructor to appear everywhere, not just to know the datatype.

So what's the use case for those first two points?

Anyway, it seems to me that's a restriction for `PatternSynonyms`; not a limitation of `DuplicateRecordFields`(?)

**Comment by AntC2** [comment]
For `DuplicatePatternFields`, perhaps we can make up some rules to address the above madness. (Some ideas below.) But it all gets horribly complicated and fussy; and I doubt it will close all the loopholes. I'm inclined to agree with @simonpj 

> do the simplest thing first, and make it more complicated only if actual use demonstrates that something more complicated will have a major payoff.

I suggest closing Trac #11228 'wontfix'. Concentrate efforts on the bigger prize of ORF/DRF.

Making rules for `DuplicatePatternFields` is complicated by needing to cater for both datatypes/data constructors defined with field names and those defined without. (Possibly the same datatype might have some constructors with; some without. And the same field name used on different constructors.)

* If (some of) a `PatternSynonym`'s field names are same as its underlying datatype's, they must map same name-to-name.
* If (some of)  a `PatternSynonym`'s field names are same as some other data constructor's, then
  * either that constructor must belong to a type distinct from this pattern's based-on<br/>so ambiguity can be resolved by datatype;
  * or (same type) the duplicate fields must map same name-to-name.
* If (some of)  a `PatternSynonym`'s field names are same as some other `PatternSynonym`'s, then
  * either the two synonyms must be over distinct datatypes<br/>so ambiguity can be resolved by datatype;
  * or (same type) the duplicate fields must map same name-to-name.<br/>If both constructors are defined without field labels, that means same between the two patterns' names.

I'm far from convinced. Consider

    data T4 = MkT1{ foo :: Int, bar :: Char, boo :: Int }
            | MkT2{ foo :: Int, baz :: String }
            | MkT3 Int                   -- anonymous foo?
            | MkT4 Char                  -- anonymous bar?

    pattern MkT3p{ foo } = MkT3 foo
    pattern MkT4p{ bar } = MkT4 bar

    pattern MkT1p{ foo, babble } = MkT1{ foo = foo, bar = babble }    -- babble distinct, so ok

So we also need a rule (same as for ordinary field labels) that if the patterns are for different constructors in the same datatype, same-named fields must have the same field type.

How about this?

    pattern MkT3pboo{ boo } = MkT3 boo   -- MkT3's field both foo and boo

**Comment by Ericson2314** [comment]
I assume this has been discussed the death in the past, but could we namespace fields and constructors with the type, and them import by default for backwards compat? The tick in `x { 'Foo.foo = 3 }` could disambiguate type `Foo` from module `Foo`.

**Comment by adamgundry** [comment]
Thanks folks.

@AntC2 you've convinced me that the interaction with `PatternSynonyms` is even worse than I thought, and that we should steer well clear for now!

@cartazio 
> so is this only impacting users of duplicate record fields FOR record update syntax?

No, it affects uses of selectors as well. But it won't affect users who use an alternative method for accessing fields, e.g. lenses, as @AntC2 observed.

> it seems is mostly motivated by ghc encouraging/favoring names to be resolved before type checking, right? hrmmm... isn't this exactly what type classes are for?

Yes. The overall principle here is to resolve duplicate record field usages before type-checking, since type class based approaches (e.g. `HasField`) are better for resolving names during type-checking.

> it does seem unfortunate to loose bidirectionality though. (granted, the way i use duplicate record syntax theres always a top level type sig to push info down, but i'm wondering/worrying if that might not be enough?)

A top level signature will not be enough, the proposal as it stands requires an expression type signature.

@Ericson2314 
> I assume this has been discussed the death in the past, but could we namespace fields and constructors with the type, and them import into the defining module for backwards comparability?

We could. Specifying the details would require quite a lot of work on an independent proposal I think, and I'm not convinced the pay-off is good enough.

**Comment by AntC2** [comment]
@Ericson2314 
> could we namespace fields and constructors with the type, ...

The trouble is we might have the same field name in different constructors for the type. Furthermore if we allowed Duplicate Names with `PatternSynonyms`, that's a virtual data constructor. So we would need to namespace by constructor rather than (or as well as) type.

    bamboozle x = 'MkT.foo x + 'Tbarfoo.foo x            -- is a befuddling way to write
    bambam (MkT{ foo, bar }) = foo + bar                 -- using NamedFieldPuns

That's befuddling only for the human reader.

(I'm rather leary of using the tick prefix -- it's in danger of overuse. Perhaps `#` somehow, since Adam's already using that for record fields?)

Thinking a bit more about `DuplicatePatternFields`: All of the ambiguity goes away if we use the field names inside the presence of the data constructor -- either as a pattern on lhs; or as an explicit record constructor.

It's these stand-alone selector functions that cause the headaches. I'll say again we should [experiment with not generating them](https://ghc.haskell.org/trac/ghc/wiki/Records/DeclaredOverloadedRecordFields/NoMonoRecordFields).

**Comment by nomeata** [comment]
Not much has happend here in a while. Marking it as dormant, to reflect the lack of discussion. This label can be removed when discussion picks up again. If this is abandonned, @adamgundry, please close it.

**Comment by adamgundry** [comment]
I'm planning to come back to this, but time is ever limited. In the meantime, [this Reddit discussion](https://www.reddit.com/r/haskell/comments/8693a3/usefulness_of_duplicaterecordfields/) is relevant to the proposal. In particular, dtellerulam mentions an idiom for using DRF that would be broken by this proposal:

```hs
r :: (r -> a) -> r -> a
r f = f

r @Foo someField
r @Bar someField
```

**Comment by AntC2** [comment]
>  @dtellerulam mentions an idiom

Ooh! Wish I'd thought of that. Thank you

Why doesn't this similar idea work?

    x = someField @Foo y

    ===> Ambiguous occurrence 'someField'

Explicitly applying the selector to a datatype's type seems even more immediate (and less verbose) than the current Rule 1 (explicit signature for the argument). Also means we could partially apply it -- less verbose than `(someField :: Foo -> _)` (assuming `PartialTypeSignatures`).

I'm guessing because `someField` is not really a function, and not really polymorphic/doesn't have type parameters. Drat! Can we cheat?

**Comment by AntC2** [comment]
>    r f = f

Makes `r` just `Prelude ($)`. Putting the record first could also be useful (and works)

    rf :: r -> (r -> f) -> f        -- 'record first'; 'r flipped'
    rf = flip ($)

    rf @Foo someRec someField       -- OOP style Record.Field

You can't use this either `r` or `rf` infix, nor create equivalent operators (because `@` must appear immediately after a prefix function). And it's fragile: one small typo and all you get is `Ambiguous occurence someField` -- I guess because the disambiguation runs as an early compiler pass/part of lexing. For example if your data type has a type parameter, but you forget

    r @Baz someField                -- complains ambiguous. You meant
    r @(Baz Int) someField

I can see why @adamgundry wants to simplify this.

**Comment by AntC2** [comment]
We need only to set the datatype as domain to the selector, because the selector can then tell us the field's type. So I propose as well as/instead of rule 3:

3. b. If the selector is immediately type-applied to a  datatype, use that datatype.

(If `TypeApplications` is not switched on, rule 3b. won't find anything to do. You can still use Rule 1, or rule 3 possibly with wildcard `_` and `PartialTypeSignatures`.)

To compare:

currently/proposed  | accepted              | by rule 3b.
------------------|--------------------|--------------------
by rule 1          |  `d x = foo (x :: T)`        | `d x = foo @T x`
by rule 2, 3    | `e = foo :: T -> Int`<br/> `e = foo :: T -> _`       | `e = foo @T`
by 2, **not** 3  | `f :: T -> Int` or `:: T -> _`<br/> `f = foo`             | `-- f :: T-> Int`<br/> `f = foo @T`
 ditto given `k :: (T->_)->_`   | `g = k foo`                | `g = k (foo @T)`
by 2, **not** 3<br/> per reddit<br/> @dtellerulam | `r :: (r -> a) -> r -> a`<br/> `r f = f`<br/> `r @T foo`                                 | `foo @ T`

Type-applying a non-duplicate record field is rejected, because its signature has no free type variables.

What to do for update is still problematic. The following I suppose follows rule 3b.; and could be used for the `g`, `h` examples that are to be rejected. But looks weird

    f x = x { foo = 3 } :: T     -- accepted by rule 6 (to be retired) and proposed new 7
    f x = x { foo @T = 3 }       -- ? by rule 3b.

Inside the update `{ }` is special syntax; a field label's appearance is not first-class.

**Comment by adamgundry** [comment]
> 3. b. If the selector is immediately type-applied to a datatype, use that datatype.

I sympathise with the desire for a less noisy syntax here, especially as we really only need the type constructor name, not the full type of the selector. However, a problem with this is that enabling `DuplicateRecordFields` would no longer be conservative. For example, if we have `data T a = MkT { foo :: a }` then `foo :: forall a . T a -> a` so normally `foo @(T Int) :: T (T Int) -> T Int`, but with this proposed rule we instead get `foo @(T Int) :: T Int -> Int`. This violates the design principle that enabling the extension (or introducing a potential name ambiguity) should not change the meaning of an existing program.

**Comment by nomeata** [comment]
This has been dormant for a while; I’m closing this (but it can be reactivated of course).

**Pull request closed without merging**
