### PR TITLE
Extension to Infix Syntax, inspired by PureScript

### PR DESCRIPTION
**Pull request by chessai**
This is a simple proposal to extend Haskell's `infix` syntax to have similar capabilities as PureScript's.

[Rendered](https://github.com/chessai/ghc-proposals/blob/infix-as/proposals/0141-infix-as.rst)

### CODE REVIEW

**Comment by simonpj** [comment]
How does this proposal improve over
```
infix 5 <>
<> = app
```
OK, so it's two lines instead of one, but that's not a big deal is it?

**Comment by gbaz** [comment]
For backward-compat reasons alone, I don't think we can ever get rid of the current syntax, just augment it. As such, this doesn't give the benefit of forcing a "non-symbol" name for every infix operator. Anyone opting-in would be doing so because they want to write in this style anyway, so I don't see this as being a sufficient win. That said, I do agree with the sentiment that giving operators a canonical pronunciation/spelling is a good thing in general, and if we were to have a haskell-from-scratch we'd probably want it.

**Comment by ChShersh** [comment]
When I was title I thought that this proposal is about extended infix operators in PureScript, like this:

```haskell
allGifts = list1 `unionWith mappend` list2
```

But yeah, in it's current form it doesn't really worth it to introduce new syntax. Creating operator manually is not that much longer.

**Comment by chessai** [comment]
I have updated the proposal to reflect what @taktoa has said, as I think it makes more sense than the more  shallow complaints that were previously present.

**Pull request closed without merging**
