### PR TITLE
NoIfThenElse

### PR DESCRIPTION
**Pull request by strake**
[Rendered proposal](https://github.com/strake/ghc-proposals/blob/no-if-then-else/proposals/0004-no-if-then-else.rst)

### CODE REVIEW

**Comment by strake** [comment]
I believe i lack authority to add the "Under discussion" label.

**Comment by nomeata** [comment]
> The alternatives are to not use these names or to fork Haskell.

Quite some dramatic choice of words. It is also questionable whether `then` and `else` are good names for variables.

The convincing point for me is that `if _ then _ else` is a bit of odd syntax indeed, and we should give the power to, say, educators to have a variant of Haskell that does not have this bit of syntax.

Also, introducing this as a Pragma gives the Haskell prime committee a way forward to removing this `if _ then _ else _` from the language (should they ever desire to do so).

(Feel free to add this point to the proposal.)

A downside of the pragma is that when one imports names  like `if` then any module trying to use these names also has to enable the pragma. Not severe, but should also be mentioned.

**Comment by bitemyapp** [comment]
@nomeata alternately, add Agda-style mixfix and make `if-then-else` something you can hide from Prelude.

**Comment by nomeata** [comment]
> Bonus: Agda users stop asking for mix-fix.

I like that :-). But would be a different proposal.

**Comment by mchakravarty** [comment]
Why would anybody want that? Sure, you cannot use the keywords as identifiers. That's true for any keyword. It is irrelevant that you can define a conditional expression as a function. if-then-else is syntactic sugar — i.e., it is for convenience. y your reasoning, we could remove all syntactic sugar from the language, program in core and gain even more identifiers and user-defined symbols.

You write, the cost is zero. The cost is never zero. Every additional line of code to GHC carries a cost.

I am strongly against this proposal.

**Comment by phadej** [comment]
@mchakravarty but `if _ then _ else _` is questionable syntax. I'd as happy to use `if :: Bool -> a -> a -> a` function. Also `case con { True -> con; False -> alt }` isn't that much longer. I see the similar tension between beauty and utility as with prefix `-` and *n + k*-patterns.

**Comment by rrnewton** [comment]
I read the proposal and also the [wiki article](https://wiki.haskell.org/If-then-else#Advocacy), but I'm a bit at a loss for why one would feel strongly about this.  We already have `RebindableSyntax` for repurposing if/then/else, but that's not the goal of this proposal.  The proposal seems more about a design stance that if/then/else was a bad addition to the language.

As a schemer, I wrote `(if _ _ _)` for decades, and it does save a bit of space I suppose.  But Haskell already has a relative keyword-light syntax compared to languages with keyword delimiters like SML.

The point seems essentially to be pedagogical.   Why present a feature to language learners that is not essential?  (Again, minimalism was a Scheme tenant, pre-R6 at least.)  But isn't it even worse to present new users with both feature A and its alternative and a flag to switch between them?  I'd rather support whole hog removal of if then else, than this complication!  Especially as there's already *so* many extensions...

I'm not keen on this proposal.

**Comment by strake** [comment]
@nomeata:
> It is also questionable whether ``then`` and ``else`` are good names for variables.

``else``, i agree; ``then``, i think would be a good infix name of some function with sequential semantics of some kind, like ``(*>)`` for a hypothetical non-``Applicative`` type.

@mchakravarty:
> Why would anybody want that?

I give my reasons in the proposal.

> if-then-else is syntactic sugar — i.e., it is for convenience. y your reasoning, we could remove all syntactic sugar from the language

Well, yes, we **could**. I'm not arguing we **ought** to. This proposal is about if-then-else alone.

I am arguing if-then-else is not very convenient, so it fails to serve the purpose of syntactic sugar and we ought to scrub it to regain these identifiers.

> You write, the cost is zero.

I write, the cost **of development**, not of upkeep, is zero. I explicitly note adding another flag to GHC as a drawback.

@rrnewton:
> The proposal seems more about a design stance that if/then/else was a bad addition to the language.

*ding ding ding* ☺

> I'd rather support whole hog removal of if/then/else, than this complication! Especially as there are already so many extensions...

So would i! Alas, this would break much code.

**Comment by gracjan** [comment]
> The development cost should be zero

The development cost to support such a syntax change in Emacs will not be zero.

**Comment by simonmar** [comment]
Let's not do this.  Where does it end?  `NoCase`, `NoWhere`, `NoLet`, `NoLambda`, etc.

Extensions are warranted when they add some new expressive power; this just lets the programmer reuse some keywords.  Thumbs down from me!

**Comment by strake** [comment]
@simonmar:
> Where does it end? ``NoCase``, ``NoWhere``, ``NoLet``, ``NoLambda``, etc.

This cuts both ways: special syntax for 2-valued types (i.e. if-then-else), special syntax for 3-valued types, special syntax for 4-valued types, etc.

This proposal is ascending one slope or descending another, and i have no reason to believe the latter is slippery.

**Comment by gracjan** [comment]
@bitemyapp: or in `.ghci` or in `stack.yml` or in `{-# LANGUAGE Haskell2048 #-}` or some random `Makefile`.

**Comment by mchakravarty** [comment]
@phadej wrote,

> but if _ then _ else _ is questionable syntax. I'd as happy to use if :: Bool -> a -> a -> a function. Also case con { True -> con; False -> alt } isn't that much longer. I see the similar tension between beauty and utility as with prefix - and n + k-patterns.

I don't agree at all with anything of this.

**Comment by bitemyapp** [comment]
Speaking for myself, it took me ages to stop forgetting the order `maybe`, `bool`, and `either`'s arguments. Of them, `bool` was the worst because I had no hope of a type error and had to run `bool 0 1 True` to remind myself.

Now I know use the silly mnemonic `first-is-worst` for the cata functions but I think in general `if-then-else` is going to trigger fewer pauses for people.

An if function that takes arguments in reverse order with no reminder like `then` and `else` seems strictly worse as it's not participating in a larger family of functions. It also adds no functionality beyond what `bool` currently does.

**Comment by michalt** [comment]
I'm also strongly against this proposal. From my POV it brings no real benefits.

Furthermore, I believe that every single GHC extension has a non-trivial cost. Not only in terms of the complexity of the compiler, but also in the mental overhead imposed on other programmers trying to understand the code (just think of all the various combinations of extensions that can be used already today).

And finally, allowing to redefine `if`, `then` and `else` could be *extremely* confusing for everyone used to the fact that they are language keywords with very specific meaning.

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by nomeata** [comment]
Another ping. @strake, whither this proposal?

**Comment by nomeata** [comment]
Due to lack of activity, I am marking this proposal as [dormant](https://github.com/ghc-proposals/ghc-proposals/#what-is-a-dormant-proposal).

**Comment by nomeata** [comment]
This has been dormant for a long time. @strake, is this abandonned? In that case, please close it.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Pull request closed without merging**
