### PR TITLE
White-box interface files

### PR DESCRIPTION
**Pull request by michaelpj**
[Rendered](https://github.com/michaelpj/ghc-proposals/blob/white-box-interface-files/proposals/0000-white-box-interface-files.rst)

### CODE REVIEW

**Comment by simonmar** [comment]
This sounds like a good idea. 

I'm still not sure about using fat interface files to implement Backpack ("Backpack-that-was"). The rationale is all in the other thread that you linked to: https://gitlab.haskell.org/ghc/ghc/issues/10871

But I don't think this is your main motivation, right? The idea is to support full introspection of the compiler's internal representation for a previously compiled module. In that respect fat interface files are fine.

I prefer to put extra information into the `.hi` file itself, to avoid needing changes in external tooling.

One thing worth remembering is that we can't just defer all compilation until link time, due to `TemplateHaskell`. And we might have foreign code that depends on Haskell code, that is called by more Haskell code, that is called at compile time by `TemplateHaskell`.... essentially it's very difficult to disentangle compilation from Cabal at this point. That doesn't affect your goal of better introspection though.

**Comment by michaelpj** [comment]
> I'm still not sure about using fat interface files to implement Backpack ("Backpack-that-was"). The rationale is all in the other thread that you linked to: https://gitlab.haskell.org/ghc/ghc/issues/10871
>
> But I don't think this is your main motivation, right?

That's right. I'm not at all qualified to judge whether Backpack-that-was would have been a good idea, and anyway that ship has definitely sailed. I mainly wanted to note that this is a feature of sufficient power that it would have let us implement it.

> One thing worth remembering is that we can't just defer all compilation until link time, due to TemplateHaskell.

Thanks, that's a good point. So any system which did want to do this thoroughly would have to have either a single-module mode or a core interpreter, as suggested [elsewhere](https://github.com/ghc-proposals/ghc-proposals/issues/162).

All the existing approaches get around this by working alongside normal codegen so we can use that for TH. This is not a bad approach (and for e.g. Plutus it is actively desirable), but something like GRIN might well eventually want to be the sole codegen output.

**Comment by gridaphobe** [comment]
I like this proposal, but I think that (1) we should extend the `.hi` file rather than introduce another file, and (2) what we should really do is implement the alternate proposal for extensible (AKA fat) interface files.

The proposal already motivates the extensible interface files with GRIN; the main proposal would not address GRIN's issue as GRIN produces its own metadata that needs to be provided to downstream modules. Extensible interface files would also solve a long-standing pain point for using LiquidHaskell across packages, which faces the same problem as GRIN.

**Comment by simonpj** [comment]
I'm sympathetic to the goal of having GHC spit out more info, useful to downstream clients of various kinds.  Some thoughts:

* I'm very unconvinced about making a distinction btween HIE files, HI files, and "whitebox" files.  They all do essentially the same thing -- albet with different goals leading to different kinds of information being stored.  Let's go for "fat interfacee files". Much easier conceptually, adn much easier engineering-wise -- e.g. no need to fiddle with Cabal.   (Conceptually, all this should be in the .o file, and technically that is possible, but I'm not arguing we shoulud go that far.)

* You state the goal of "serialise ModGuts"; but that's exactly what HI files are: the signature of `mkIface` is
  ```
  mkIface :: ... -> ModGuts -> IO (ModIface, Bool)
  ```
  So `mkIface` does precisely serialise most of `ModGuts` already!  Perhaps we should serialise more of it. That's a fine goal: let's just specify what "more" rather than invent a new mechanism.

* The `ModGuts` slogan is ambiguous, because `ModGuts` changes as you go down the compilation pipeline.  Do you want the program just after desugaring, or after optimisation, or somewhere in the middle?  I believe this matters in the Plutus case.

* The more you serialise, the more often the fat interface file will change, so the more recompliation will be triggered.  Mind you, GHC is carefult to track which _parts_ of the interface file it uses, and aborts compilation if the relevant bits haven't changed.  (You could argue that multiple interface files might reduced this problem, but I think the cure is worse than the disease.)

**Comment by angerman** [comment]
@simonpj 
> (Conceptually, all this should be in the .o file, and technically that is possible, but I'm not arguing we shoulud go that far.)

@simonmar mentioned that as well, the other day. I am not absolutely sure this is true. For traditional object files yes. But what if our object files are not traditional object files, but say javascript files? IR files? ...

I'm all for making `.hi` files extendable by turning them into a bunch of sections. (E.g. serialise something of type `String -> ByteString` or similar and have every tool/consumer be responsible for coding/decoding their own section).  I am not convinced that we should force this capability into object files as we have way less control over the format/constraints object files for new architectures may lay upon us. For `.hi` files we have all the control we want.

**Comment by simonpj** [comment]
>  I am not convinced that we should force this capability into object files

Yes I wasn't seriously suggesting doing so.   But I am suggesting that we should trreat that as the "right" plan, and keep as close to it as possible by putting all our own stuff into one fat .hi file, not several.

**Comment by Ericson2314** [comment]
I generally like the "one extensible format" idea. I'd want to leverage trees that grow perhaps for this, e.g. for the different varieties of mod guts. My only concern is we don't end up in a postel's law mire of "the section you want might be missing, and you should be robust to that." Let's have everything just fail fast; we will need Cabal to be aware of the flags that change the sections as cache-invalidating, for example.

For using external build systems that work on the file system level, having separate files is preferable, but perhaps we can easily write something to split up the sections into additional files and recombine them again. Then we don't need to force multiple files or big files on any tool.

**Comment by simonmar** [comment]
One reason we didn't put the contents of `.hi` files into a section in the `.o` file is that the timestamps on these two files can diverge - if we compile a module and its `.hi` file doesn't change, then we don't want to touch it, so that the build system won't recompile modules that depend on it, but we do want to touch the `.o` file to indicate that we ran the compiler. Of course this only applies to build systems that use GHC in one-shot mode, and anyway timestamps are really the wrong way to do this and we should be using content hashes or something else, but nevertheless this is one reason why we can't just combine the two files today.

**Comment by michaelpj** [comment]
Okay, it sounds like there's a consensus that "fat" `.hi` files are the way to go. Great - I thought that might be unpopular, but I agree that it's a nicer solution.

Should I make a separate proposal for that, or should I incorporate it into this one?

I do think there is content to this proposal beyond just having fat interface files, because I still want to teach GHC to emit this particular kind of interface section. (As an alternative, one could imagine allowing plugins somehow to add things to interface files, but then you have to arrange for all your dependencies to depend on and activate the plugin.)

Regarding recompilation, at least for the use-cases I've listed, I think recompiling if any part of the interface has changed is the right behaviour. If you depend on the "white-box" interface content, then you definitely want to be re-run if that changes. Now, this may mean that if you ask for white-box content you're setting yourself up for more frequent recompilation, but that seems okay to me.

Perhaps a sufficiently clever compiler would be able to only update the white-box content and skip later stages, but I don't think we should rely on that.

> You state the goal of "serialise ModGuts"; but that's exactly what HI files are

I meant *faithfully* serializing `ModGuts`, i.e. serializing it in such a way that we can read back the original value. Current `.hi` files  aren't a faithful serialization, since you only get back a `ModIface`.

> The ModGuts slogan is ambiguous, because ModGuts changes as you go down the compilation pipeline. Do you want the program just after desugaring, or after optimisation, or somewhere in the middle?

Ugh yes, this is just an omission. I meant just after desugaring.

The reason for picking this point is that tools which want access to later stages can recover that by running the compilation pipeline again after loading the file. So the heuristic is "as soon as possible after the frontend is done".

I know John is interested in emitting code at other points too, but I think being able to get the code at the start of the pipeline and run forwards from there is a good starting point.

> My only concern is we don't end up in a postel's law mire of "the section you want might be missing, and you should be robust to that." Let's have everything just fail fast; we will need Cabal to be aware of the flags that change the sections as cache-invalidating, for example.

I certainly agree that changing sections should be cache-invalidating.

I think failing if the section you require is not present is reasonable. That does put it on the user to ensure that all their dependencies have been compiled with the right flags, and maybe eventually we'd want to teach Cabal about that.

**Comment by gridaphobe** [comment]
I think it makes sense to extend the current proposal to include the fat interface file change.

**Comment by nomeata** [comment]
> Regarding recompilation, at least for the use-cases I've listed, I think recompiling if any part of the interface has changed is the right behaviour. If you depend on the "white-box" interface content, then you definitely want to be re-run if that changes. Now, this may mean that if you ask for white-box content you're setting yourself up for more frequent recompilation, but that seems okay to me.
>
> Perhaps a sufficiently clever compiler would be able to only update the white-box content and skip later stages, but I don't think we should rely on that.

Currently, GHC has the very nice property that even if a dependency changes, it will not recompile a downstream module that only uses unchanged definitions from the changed module. Will this now be gone a soon as there is any additional data in the interface file?

**Comment by michaelpj** [comment]
> Currently, GHC has the very nice property that even if a dependency changes, it will not recompile a downstream module that only uses unchanged definitions from the changed module. Will this now be gone a soon as there is any additional data in the interface file?

In the particular case of white-box content, you should be able to abort compilation in the same circumstances, since if the definitions it uses are unchanged then the white-box content it produces should be the same.

But I'm not sure this is safe for *consumers* of white-box content: a plugin that used white-box content could look at definitions that *weren't* directly used, and so might require recompilation even if apparently unused definitions are used. 

In fact, this seems like it might already be true today: what happens if a plugin looks at e.g. the unfoldings of a binding that is otherwise unused in the module being compiled? Will we get incorrect recompilation avoidance? Perhaps the problem is plugins!

**Comment by simonpj** [comment]
> Current .hi files aren't a faithful serialization, since you only get back a ModIface.

...and you can typecheck that ModIface to get a ModDetails.  If you look
at ModDetails vs ModGuts you'll see that the latter is pretty much a superset of
the latter.   So to achieve what you want, it might be just a question of
beefing up what we have already, to serialse/deserialse a bit more.

> Ugh yes, this is just an omission. I meant just after desugaring.

Ah, now this is a *much* bigger difference from current .hi files.  Current .hi files have stuff
from the *end* of compilation, and must do.  You want stuff from somwhere
near the beginning.  Why?

And "near the beginning" is vague.   The desugarer generates lots of
junk, which is removed by a run of `CoreOpt.simpleOptPgm`.  You probably
don't mean "right after the desugarer"; you probably mean "after the simple
optimiser".  But why is that step magic?   Why not after further optimisation?

And other clients might want the bindings after some (but perhaps not
all) optimisation passes.

Somehow it seems a bit ad hoc to store three copies of the program in the .hi file:
* the original source code (I think, for IDE tooling)
* just after desugaring (for Plutus)
* after optimisation (for GHC separate compilation)

**Comment by ndmitchell** [comment]
FWIW, the DAML Compiler (which isn't a million miles away from Plutus) definitely does want the output just after desugaring, before running `simpleOptPgm`. DAML uses the GHC API to get that, and does its own compilation driver, but a fat `.hi` could enable lots of things like TemplateHaskell that are otherwise tricky.

**Comment by Ericson2314** [comment]
I am having second thoughts about the "one extensible file" idea. If the interesting bits are caching and cache invalidation and other compilation manager concerns. Putting everything in one file doesn't so much abstract over unimportant details as shove the all the important details under the rug! Interfaces vs definitions (including today's unfoldings) are invalidated and accessed differently. More files simplifies this by eliminating the dynamism in the dependency graph before parsing.

Remember, the whole raison d'etre of the proposal was that loading core from whitebox compilation files to finish compilation should be simpler. This does including GHC itself loading core, not just Plutus and other tools. We don't want to load a bunch of hi files, realize they all contain complete core for all deps, and then wildly change the compilation plan.

Thinking back to #245 we already have serious issues that the behavior (let alone implementation) of `ghc --make` is very complex and hard to specify. I want to leverage more files *statically* to break things up into smaller, more numerous, but simpler steps. If we use big extensible files, it's just too tempting to not statically decide which sections those files should contain, but see what they actually do contain make numerous of dynamic planning decisions.

**Comment by Ericson2314** [comment]
Take https://gitlab.haskell.org/ghc/ghc/merge_requests/1633#note_219575 (the PR and @mpickering's) comment in particular. I too an confused by the `-fno-code` + `-fwrite-interface` interaction; I think modifying generated interface files would wreck havoc on `ghc --make` alternatives, but putting this post-code-gen info in a separate file is the best of both worlds:

 - Get information as soon as possible (only wait for type checking when relevant)

 - No mutation of files (good for file-based incremental computation)

 - In conjunction with this proposal supports highly incremental file-based builds:

   1. GHC invocation 1: parse, type check, desugar, serialize

   2. GHC invocation 2: load core, stg, cmm, code gen, write caf info / lf info / etc.

**Comment by angerman** [comment]
@Ericson2314 note that fat/white-box interface files and extendable interface files are not necessarily the same. While you can model some form of fat interface files with extendable interface files, extendable interface files let you just attach additional data in `.hi` files. What you do with that is completely up to you. If it's a good fit for your specific use case or not, is up to you in the end. Are extendable interface files the ultimate solution? I have my doubts, but I think it's a minimal invasive change to ghc, that provides additional avenues to explore and experiment with.

**Comment by Ericson2314** [comment]
I'd agree with that, but with the caveat that "minimally invasive" isn't necessary good.

Based on this discussion, #245, and my refactoring for multi-package and fixing some backpack bugs, I'm starting to think that the underlying tech debt that's entangled with all of this is that ModuleGraph is too course grained. Instead of leveraging the dependency graph as much as possible for caching, we have lots of ad-hoc incrementality cache invalidation code. More dependency nodes  naturally works well woth more files, with all the benefits I mentioned above. I might write a proposal for this.

So back to the extensible interface files, it is a small change, but one that further combinatorially grows the possible work denoted by the one dependency node. I worry it would be harder to remove once it's introduced too, and what logic might spring up downstream in support of it. Conversely if we can add new functionality *while* clarifying the monster that is `ghc --make` so other build systems can better immitate it, I'm willing to take a risk making a bigger up front change.

**Comment by michaelpj** [comment]
After some discussion, we've decided that this isn't a good fit for the proposal process. I've started a [GHC wiki page](https://gitlab.haskell.org/ghc/ghc/wikis/Core-interface-section) which has an updated version based on the idea of having a new section of interface files with the Core in it.

**Pull request closed without merging**
