### PR TITLE
Hierarchical modules

### PR DESCRIPTION
**Pull request by hsyl20**
This is a proposal renaming GHC's modules to introduce a hierarchy.

[Rendered](https://github.com/hsyl20/ghc-proposals/blob/hierarchical-modules/proposals/0000-hierarchical-modules.rst)

### CODE REVIEW

**Comment by simonpj** [comment]
I'm OK with this.  I'm not eager, because it'll impose some costs on me.  But if it'll reduce costs on others, I'm willing.

But I'd like to hear other saying "yes this would improve my life".

One particular thing: I'd much prefer to get rid of the IR layer, so we have `GHC.Core` not `GHC.IR.Core`.

**Comment by erikd** [comment]
I'm in favor of this. I don't do a lot of GHC hacking at the moment, but when I get back to it, this will make mt life easier.

**Comment by bgamari** [comment]
Thanks again for driving this, @hsyl20!

In general I think it is helpful for beginners if GHC looks more like an idiomatic Haskell package. It's rather hard to say just *how* helpful, especially compared to the costs, but if the majority of frequent developers have no objection then I think we should move ahead with this, especially if @hsyl20 is willing to do the GHC refactoring.

A few notes about the particular renaming:

* `GHC.Program`: this seems like a rather amgiuous name. Perhaps `Driver` would be more appropriate?
* `GHC.IR.*`: This feels like a strange division; these representations are really the core of compiler and it makes sense to me at least if they sit at top level.
* `GHC.Entity.*`: I'm not sure the `Entity` bit here contributes much. Why not just `GHC.Var`, etc? Afterall, these are all quite ubiquitous things.
* `GHC.Compiler.HaskellToCore`: The same argument as above, although I'll admit that I'm beginning to warm to the consistency that this brings with the other IR-to-IR translations.
* Where did the subsystem-specific common modules (e.g. `SimplMonad`, `RnEnv`) end up? I don't see them mentioned here.
* In general I'm on the fence regarding whether splitting the renaming logic up by source representation is really the right choice. There are benefits to the current "thematic" organization.

**Comment by Mistuke** [comment]
I'm not really a fan of this change as I don't see it really adding anything. Aside from the rebase pain (which is only small for patches that don't do cross cutting changes and split modules) a very real technical issue is that making these modules (and so the path) so verbose eats valuable real-estate from the ANSI Windows path limit. We're already very close to this limit.

GHC on Windows uses ancient APIs and so is limited by these old constraints.

**Comment by simonpj** [comment]
Ah yes: simply making module names longer has a cost in itself.   But we do manage to compile Hackage package with pretty deep module hierarchies.  How does that work?

**Comment by Mistuke** [comment]
I think those are also hit and miss, both stack and cabal (especially the newbuild stuff) are hitting this limit more and more https://www.fpcomplete.com/blog/2015/08/stack-ghc-windows https://github.com/commercialhaskell/stack/issues/1145 and https://github.com/haskell/cabal/issues/3972 just to name a few. The sandboxing behaviour greatly pushes the path length with the new path stylings. Mostly the solution so far has been to check out the directory in a short a path as possible and pray.

Even @bgamari has been hitting the limit with our current GHC build on the new Jenkins setup. There's also the caveat of how `directory` handles file copies, e.g. first creates a temp file, then renames the file. The temp file can have a longer name so the copy can fail for no apparent reason.+

Git has the same issue, though git has added long path support https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path but it's off by default.

When compiling GHC, if it can read the file, outputs the assembly in a temp file, this temp file will always fit since we ask the OS for it. This is why GHC will work, if we can get it to read the file. GCC is another story entirely :) The complication for GHC and specifically our build system is that we do in tree building. So for every module `foo.hs` we generate `foo.hi` `foo.o` `foo.p_o` etc. So the file path grows, which is why make hits the length limit even though you were able to check it out.

**Comment by Mistuke** [comment]
To be fair to the proposal at hand, I should make it more explicit.

There's work under way to solve the `MAX_PATH` issue once and for all. However I don't expect to be finished before `8.4`. And we won't really be able to solve it with Make (unless we patch make). So if the proposal is accepted. I just ask that we do it for `8.6` instead of `8.4` so we don't make the situation on Windows more dire...

**Comment by simonmar** [comment]
I'm in favour of moving to a module hierarchy, but I think the current proposal is too deep.  Optimising too much for new users at the cost of repeated friction for regular developers is not the right tradeoff - I'd like to shift the balance a little more in favour of developers by flattening the hierarchy.

Taxonomy is not an exact science, there are often multiple ways to group things, and you could go on for a long time rearranging the tree. There's no single best solution, so we should just pick something that offers a reasonable compromise.

Concretely I suggest:

* Get rid of the `IR` layer
* Instead of `GHC.Entity`, how about `GHC.Types`, or pull these things out to the top level as @bgamari suggested.  I like the idea of being able to import `GHC.Var`, `GHC.Name`, `GHC.Class`, `GHC.Type`, etc.  These are very central types and I don't think it really helps to put them in a category.
* Replace `Program` with `Driver`, as @bgamari suggested
* Squash `GHC.Program.Mode` into `GHC.Driver`
* Squash `GHC.Core.Analyser` and `GHC.Core.Transformer` into `GHC.Core`.  Because `GHC.Core.Transformer.Simplifier` is getting too deep, and that's a hot spot.  @simonpj do you think `GHC.Core.Simplifier` is ok, or still too deep?
* Similarly squash `Analyser` and `Transformer` out from other parts of the hierarchy.
* I think `GHC.Make` can be a module (instead of `GHC.Driver.Make`)

Where did `HscTypes` go?  This is a very central module, and contains a lot of stuff because splitting it would result in a lot of cyclic dependencies.  Perhaps `GHC.Types.Base`?

Also `HscMain`?  Perhaps `GHC.Compiler.Module`? (reflecting the fact that it deals with compiling one module)

Where did `SysTools` go?  It probably belongs under `GHC.Driver`.

Not sure if `Finder` belongs under `GHC.Utils`, it's more of a driver thing.

**Comment by ocharles** [comment]
While it's already mentioned in the proposal, I'd like to re-iterate this point:

> Ambiguous names: some module names used by GHC are common (e.g., Parser, Lexer, Name, Types, Core, Format, Debug). They could easily lead to name clashes when used with GHC-API. Additionally, it is not obvious that GHC provides some of them (Bag, Llvm, Check, FastString, Bitmap, Encoding). Using at least a "GHC" namespace would be more conventional and would avoid these ambiguities.

I'm not a GHC hacker (though really, I should get into that!), but I am certainly a GHC user. I've found it very frustrating to have `Parser` conflict with my own `Parser` (for example). Even if the entire hierarchy just got namespaced under `GHC.`, things would be better, but I do think more organisation would make the API easier to navigate.

**Comment by osa1** [comment]
> I've found it very frustrating to have Parser conflict with my own Parser (for example).

I agree that this is frustrating, but you can solve this without having to modify GHC, using `-XPackageImports`:

```
$ cat test.hs
{-# LANGUAGE PackageImports #-}

import "ghc" Parser as GHC.Parser

main = return ()

$ ghc test.hs -package ghc
[1 of 1] Compiling Main             ( test.hs, test.o )
Linking test ...
```

This works pretty good even in ghci, e.g. `:t GHC.Parser.parseDeclaration` just works.

**Comment by ocharles** [comment]
Yes, that's what I do at the moment. It's not particularly satisfying though, is it?

**Comment by osa1** [comment]
> It's not particularly satisfying though, is it?

I don't know, but you can't solve this problem by changing GHC, instead maybe we should design and implement "qualified exports" (I actually have a proposal for this, not submitted yet) or another library that just re-exports GHC API in a module hierarchy. No library author can come up with naming that pleases every single user. I'm pretty sure no matter what module hierarchy we'll come up with here some people won't find it great for their purposes.

---

I don't feel too strongly (mostly because I'm not actively working on GHC these days although I wish could) but I'll vote against this. It's great that devs/contributors who are most actively working on GHC are OK with this, but for the rest of us this will mean le-learning quite a lot of things for very little (if any) gain. So I think this has potential of alienating contributors who aren't working on GHC every day. As someone in this category I think it'd be frustrating for me.

Of course if active developers find this helpful (rather than "not harmful") that's probably the most important thing here.

**Comment by mboes** [comment]
I think this a change in the right direction. The module hierachy doesn't just reflect the organization of the code inside GHC, it's part of the GHC API. Right now the lack of proper organization of most modules, which have been named according to shifting common practices over the course of many years, is a superficial but important deterrent to potential users of the GHC API, because it's the first thing people see. Because it's always very difficult to find what modules are relevant entry points for the neophyte, and I for one find it more of a pain to navigate the GHC API Haddock index than the index for `base`, which is pretty good.

None of the suggestions of @bgamari and @simonmar get in the way of that, so those all make sense to me as well.

**Comment by bgamari** [comment]
> The module hierachy doesn't just reflect the organization of the code inside GHC, it's part of the GHC API. 

This is another can of worms that we perhaps shouldn't get too deep into, but I think there is an important distinction to be drawn between the modules exposed by the `ghc` library (which we change with reckless abandon) and the GHC API (e.g., currently just the `GHC` module, in which we try to maintain interface stability).

Of course, the problem with this picture is that it's nearly impossible to write a useful API consumer using only the `GHC` module. Consequently the lines delimiting the "GHC API" often seem quite blurry. In principle we request that API users communicate with us when they find things that ought to be exposed in `GHC`. However, in practice this seems to rarely happen.

I'm not entirely sure of the right way to deal with this; it's clearly important that the compiler be able to evolve freely. On the other hand, having a woefully incomplete API doesn't do anyone any favors.

With respect to the hierarchical modules proposal, perhaps we could designate a `GHC.API` namespace where we can place modules which re-export things which come with some stability guarantees. On the other hand, given how `GHC` generally languishes without updates, perhaps this is unrealistic.

**Comment by bgamari** [comment]
@hsyl20, what is the status of this?

**Comment by hsyl20** [comment]
@bgamari Sorry for the delay

Thanks everyone for the feedback, I have updated the proposed renaming. The full mapping between the old names and the new ones can be found here: https://github.com/hsyl20/ghc-api-compat/blob/master/ghc-api-compat.cabal

**Summary:**


Changes from the original proposal:
* Rename GHC.Program into GHC.Driver
* Squash GHC.Driver.Mode into GHC.Driver
* Move Finder into Driver
* Remove IR level
* Rename GHC.Entity into GHC.Types
* Rename HscTypes into GHC.Types.Base
* Squash Transformer and Analyser levels

Various answers:
* SysTools[.Terminal] currently is in GHC.Utils and not in GHC.Driver because it is used by:
    * GHC.Compiler.CmmToLlvm.CodeGen
    * GHC.Interactive.Linker
    * GHC.Config.Flags
    * GHC.Driver.Pipeline
    * GHC.Driver.MakeDepend

* Where did modules go:
   * SimplMonad -> GHC.Core.Simplifier.Monad
   * RnEnv      -> GHC.Haskell.Renamer.Environment
   * HscMain    -> GHC.Driver.Main
   * Full list: https://github.com/hsyl20/ghc-api-compat/blob/master/ghc-api-compat.cabal

Not done (to avoid overcrowding the top-level or for consistency):
  * Move GHC.Driver.Make into GHC.Make (why this one only?)
  * Squash GHC.Types (formerly GHC.Entity) into GHC (there are a lot of modules in GHC.Types)
  * Move GHC.Compiler.HaskellToCore into GHC.HaskellToCore (consistency)

I have rebased the patch against GHC's master branch with the updated renaming: https://github.com/hsyl20/ghc/tree/T13009

There is still the issue of the MAX_PATH ANSI limit on Windows.

**Comment by bgamari** [comment]
Great work!

> There is still the issue of the MAX_PATH ANSI limit on Windows.

I'll probably end up eating these words at some point, but I'm not sure that the Windows path length limit is of immediate concern. Afterall, most of the paths don't increase in length by *that* much. The only time that I have encountered this limit during a GHC build is while compiling `Cabal`, which has module names nearly 50 characters long (e.g. `Distribution.PackageDescription.Configuration`, in addition to the `libraries/Cabal/Cabal/` path prefix). As long as none of the `ghc` modules are longer than limit I don't think this proposal should cause any trouble.

**Comment by takenobu-hs** [comment]
Longer words are easier for newcomers to understand.
But, if the length of the path becomes a problem, how about using abbreviations?
For example, here is the abbreviations collection for GHC.
(https://ghc.haskell.org/trac/ghc/wiki/Commentary/Abbreviations)

Because the abbreviations are generally used in GHC source code, newcomers need to be familiar with them at a later date.

**Comment by simonmar** [comment]
Thanks for doing the revision! Here are some more suggestions:

Big things:

* `GHC.Types.DataConstructor` since we're not changing the type, let's keep using `DataCon` for the type.  Afer all we're not changing `Id` to `Identifier`, or `Var` to `Variable`, so: `GHC.Types.DataCon`, and similarly for `TyCon`.  I suggest this as a general rule: if the module name matches a type name, keep them the same.  If we decide to rename the types later we can change the module name too.
* There was some concern from from @treeowl about turning verbs (`Simplify`) into nouns (`Simplifier`).  It doesn't look like this has happened consistently, e.g. we have `FloatOut`, `Lint`, `LayoutStack`, etc., so I'd be happy to go back to verbs (`Simplify`, `TypeCheck`, `Rename`, `Vectorise`, `Load`, `Tidy`, etc.).  The verbs are one character shorter and unambiguous.

Smaller things:

* Maybe `ClassInstance` should be just `Instance`.
* `GHC.Types.Symbol` is too generic, let's keep `CLabel`
* `GHC.Cmm.Dataflow` I think should be `GHC.Cmm.Hoopl`
* `GHC.Compiler.CoreToStg.Prepare` is a core-to-core pass, so it should be `GHC.Core.Prepare`
* `GHC.Data.Bool.Formula` I would just make that `GHC.Data.BoolFormula`, we aren't using the `Bool` layer for anything else
* `GHC.Data.Tree.OrdList` just `GHC.Data.OrdList`
* `GHC.Types.CostCentre.Initialise` I think we can safely abbreviate "Initialise`, so `GHC.Types.CostCentre.Init`
* `GHC.Utils.Identifier` should be `GHC.Utils.Lexeme`
* `GHC.Utils.Unify` isn't really a util, it's tightly woven with the type machinery, so probably `GHC.Haskell.TypeCheck.Unify`. (@simonpj please check)
* `GHC.Types.Unique.FiniteMap` this is a data structure, also it matches the type name, so `GHC.Data.UniqueFM`.  If we rename the type later we can change it.  Similarly for the other `GHC.Unique` modules.

**Comment by hsyl20** [comment]
I have updated the renaming (full list: https://github.com/hsyl20/ghc-api-compat/blob/master/ghc-api-compat.cabal). The patch is updated, rebased on head and validating.

@takenobu-hs and @bgamari 
I wouldn't like to use abbreviations just because Win32 API can't handle long paths. Hopefully it seems that there is some hope: according to [this page](https://msdn.microsoft.com/en-us/library/aa365247.aspx#paths), we can use "\\\\?\\" prefix to get support for long paths. Also "Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior."

@simonmar 
Thanks, most of your suggestions have been applied.

Remarks:
* There are two "Unify" modules: GHC.Haskell.TypeCheck.Unify (formerly typecheck/TcUnify) and GHC.Utils.Unify (formerly types/Unify). Indeed the latter is not really a util but it is used by modules in GHC.Types, GHC.Interactive.ClosureInspect and in GHC.Haskell.TypeCheck, and it only imports modules from GHC.Types, GHC.Data and GHC.Utils.
Hence I think it doesn't really belong to GHC.Haskell.TypeCheck. I have renamed it to GHC.Types.Type.Unify (similarly to GHC.Types.Coercion.Optimise).

* I haven't renamed GHC.Cmm.Dataflow into GHC.Cmm.Hoopl as the dependency on Hoopl has been removed and I think it's going to be confusing. https://mail.haskell.org/pipermail/ghc-devs/2017-May/014255.html

* According to your first big point, I have renamed GHC.Types.{DataCon,TyCon,ConLike}. Tell me if you think some other modules should be renamed.

**Comment by simonpj** [comment]
Could we move `GHC.Haskell.Typecheck.X` to `GHC.Typecheck.X`, and similarly `GHC.Haskell.Syntax`?  The deeper names are not buying us much.

**Comment by bgamari** [comment]
> according to this page, we can use "\\?\" prefix to get support for long paths.

This is true, but we're not yet in a position to be able to use this new support. As the documentation says, it's opt-in and opting in will require that GHC provide a manifest file. I believe that @Mistuke is working in this direction, but it will take time.

**Comment by simonpj** [comment]
Also `GHC.Compiler.CmmToAsm.X` to `GHC.CmmToAsm`.  I suppose then that `CmmToLLVM` could go under `CmmToAsm`; LLVM is just another target machine code.  Similarly `CmmToC`.

`GHC.Compiler.CmmToAsm.Register.Allocator.X`  to `GHC.CmmToAsm.RegAlloc.X`

Generally my goal is to flatten the hierarchy to avoid long module names.  It makes it 10% less consistent but 90% more usable.  I may not have hit all the cases, but let's start with these.

**Comment by simonmar** [comment]
I think `CmmToLLVM` and `CmmToC` should live at the same level as `CmmToAsm` - they're distinct compilation paths all starting from Cmm.

**Comment by goldfirere** [comment]
If I may submit tweaks, here is what I suggest:

* `HaskellToCore` doesn't do compilation, as I generally think of compilation. It's much simpler. I don't think it belongs under `Compiler`. (I also favor renaming this to `Desugar`, which is a standard term in compiler construction, IIUC. Yes, this loses some consistency. But we don't rename `Parser` to `TokensToHaskell`, which we theoretically could.)

* `TemplateToHaskell` also doesn't do compilation. I'd put it under `GHC.Haskell`.

* Some of the `GHC.Core` modules are about specific passes. I'd make this distinction clearer, making `GHC.Core.CallArity` to `GHC.Core.Pass.CallArity` but keeping `GHC.Core.Rules` as is, because this latter module doesn't define a pass.

* Rename `Utils` modules to `Util`. All other names are singular.

* `GHC.Core.Substitution` could be `GHC.Core.Subst`. Note that `Util` and `Expr` are abbreviated, and I think `Subst` is pretty unambiguous.

* `GHC.Data.List.SetOps` could be just `GHC.Data.List`.

* `GHC.Data.TrieMap` should really be `GHC.Core.TrieMap`.

* `BackPack` should be spelled `Backpack`. In my vernacular, at least, it's one word.

* `....Binding` should be `....Bind`. It's about the noun, not the verb.

* Why does `TcRnMonad` get distinguished as `GHC.Haskell.TypeCheck`? I would call it `GHC.Haskell.TypeCheck.Monad`. Perhaps the old `TcRnDriver` could be `GHC.Haskell.TypeCheck`.

* `GHC.Haskell.TypeCheck.Constraint.*` should become `GHC.Haskell.TypeCheck.Solver.*`. The old `TcFlatten` should go here, too.

* `GHC.Haskell.TypeCheck.Constraint.Solve` should be `GHC.Haskell.TypeCheck.Solver.Monad`.

* Move `GHC.Haskell.TypeCheck.Constraint.Simplify` out to the `TypeCheck` level.

* You have both `ClassDeclaration` and `Instance`. It should either be `Class` and `Instance` or `ClassDeclaration` and `InstanceDeclaration`. I prefer the former.

* `GHC.Haskell.TypeCheck.Matches` should be `...Match`, using the convention of singular nouns.

* All in `GHC.Haskell.TypeCheck`:

```
Type --> Util.CoreType
MutableType --> Util.Monadic
Types --> Util
UserType --> Type
TypeAndClassDeclaration --> TypeDeclaration
```

* `GHC.Interface.Types` --> `GHC.Interface.Type`

* What's the difference between `GHC.Data` and `GHC.Types`? I take it this is derived from the `util` directory vs the `basicTypes` directory, but I've never fully grokked that distinction either.

* These modules should be in `GHC.Core`, not `GHC.Types` (or `GHC.Data`): `Class`, `Coercion` (with its submodules), `ConstructorLike`, `CostCentre` (with its submodule), `DataCon` (why not `DataConstructor`?), `Demand`, `FieldLabel`, `ForeignCall`, `Id` (with submodules), `Kind`, `Literal`, `TyCon`, `TypeAndCoercion` --> `Type.Internal`, `Type`, `Type.Unify` --> `Unify`.

* The old `FamInstEnv` and `InstEnv` really should be in `GHC.Haskell.TypeCheck`, perhaps as `GHC.Haskell.TypeCheck.FamilyInstance.Pure` and `GHC.Haskell.TypeCheck.Instance.Pure`. Relatedly, the old `Inst` module is actually an unholy combination of `Instantiation` and `Instance` and should probably be broken up. (I suppose this kind of confusion is what you're trying to avoid!) But that's not your problem.

I know this list is fairly detailed, but it looks like the comments above were more broad-brush. I'd love for others (@simonpj, in particular) to review my suggestions.

Thanks!

**Comment by simonmar** [comment]
I like @goldfirere's suggestions on the whole, a few comments:

> What's the difference between GHC.Data and GHC.Types

The former are generic (not GHC-specific) data structures, while the latter are ... not.  It's a slightly flimsy distinction, I agree, but not entirely unreasonable.

>  I'd make this distinction clearer, making GHC.Core.CallArity to GHC.Core.Pass.CallArity

Haha, there used to be this layer in an earlier version of the proposal (it was `Transformer` instead of `Pass`) but I argued to remove it, mainly because it put the Simplifier too deep for something that's a very central part of the compiler.  We also had this layer for the other intermediate representatinos (Cmm, Stg etc.) too.  Perhaps doing it just for Core makes sense?  I don't feel strongly here, so long as @simonpj doesn't mind typing `GHC.Core.Pass.Simplify`.

The `GHC.Compiler` part of the hierarchy is the part I'm least comfortable with.  There is a logical consistency to it, but I'm not sure how much that is buying us.  @simonpj argued to move `GHC.Compiler.CmmToAsm` to `GHC.CmmToAsm`, and @goldfirere wants to move `GHC.Compiler.HaskellToCore` to `GHC.Desugar`.  Should we just get rid of the `GHC.Compiler` layer then?

**Comment by simonpj** [comment]
Less deep layering!  Yes!

**Comment by bgamari** [comment]
> `GHC.Data.TrieMap` should really be `GHC.Core.TrieMap`.

Not to nit-pick, but is this really true? I believe `TrieMap` itself is quite general (although admittedly many of the uses are on core expressions and types).

> `GHC.Data.List.SetOps` could be just `GHC.Data.List`

Frankly I think we should keep the `SetOps` naming as it makes the user think "oh, maybe I should be using a proper set". Frankly, I suspect that many of these functions should disappear entirely.

**Comment by goldfirere** [comment]
I suppose that's true about `TrieMap`. But then we should have a `GHC.Data.TrieMap` defining the class and `GHC.Core.TrieMap` defining the Core-related instances.

And perhaps you're right, @bgamari, about the list stuff. The only function from that module that I use is `getNth`, which should probably be moved to `Util`.

**Comment by bgamari** [comment]
@hsyl20, what is the status of this?

**Comment by hsyl20** [comment]
@bgamari I have to find some time in the coming weeks to perform the changes proposed by @goldfirere and to rebase. (I had to work on other things before going on vacation, hence the delay).

**Comment by bgamari** [comment]
Sylvain Henry <notifications@github.com> writes:

> @bgamari I have to find some time in the coming weeks to perform the
> changes proposed by @goldfirere and to rebase. (I had to work on other
> things before going on vacation, hence the delay).
>
Sure, no worries! Will you be at ICFP by any chance? HIW would be a
great opportunity to hash this out in person.

**Comment by hsyl20** [comment]
@bgamari Sadly not, I don't attend ICFP this year.

**Comment by nomeata** [comment]
While everyone is happy to discuss a reorganization of GHC’s module structure here, I do not think that this is a matter for the steering committee, as it does not affect users of GHC-the-compiler. Marking it as  “out-of-scope”, but feel free to discuss it here.

**Comment by hsyl20** [comment]
I've finally found some time to work on this. I've taken most remarks into account (see the details below), especially to reduce the tree depth (e.g., no more Compiler level, etc.).

The updated tree (rebased yesterday, successfully built): https://github.com/hsyl20/ghc/tree/T13009-20171017/compiler/GHC
The updated compatibility package which gives a good overview of the renaming: https://github.com/hsyl20/ghc-api-compat/blob/master/ghc-api-compat.cabal


Done:
* GHC.Core.Substitution                 -> GHC.Core.Subst
* Utils -> Util
   * GHC.Utils
   * GHC.Haskell.Rename.Utils
   * GHC.Haskell.Parser.Utils
   * GHC.Haskell.Derive.Utils
   * GHC.Haskell.Utils
   * GHC.Core.Simplify.Utils
   * GHC.Core.WorkerWrap.Utils
   * GHC.Core.Vectorise.Utils
   * GHC.Core.Utils
   * GHC.StgToCmm.Utils
   * GHC.HaskellToCore.Utils
   * GHC.Cmm.Utils
   * GHC.Interface.Utils
   * GHC.Stg.Utils
   * GHC.Builtin.Utils
   * GHC.Interactive.Debugger.Utils
* s/BackPack/Backpack
* Binding -> Bind
   * GHC.Haskell.TypeCheck.Binding
   * GHC.Haskell.Rename.Binding
   * GHC.Haskell.Syntax.Binding
   * GHC.Compiler.HaskellToCore.Binding
   * GHC.Compiler.StgToCmm.Binding
* GHC.Interface.Types -> GHC.Interface.Type
* Old TcRnMonad (GHC.Haskell.TypeCheck) -> GHC.Haskell.TypeCheck.Monad
* GHC.Haskell.TypeCheck
   * .Matches                 -> .Match
   * .ClassDeclaration        -> .Class
   * .Constraint              -> .Solver
   * .Flatten                 -> .Solver.Flatten
   * .Solver.Solve            -> .Solver.Monad
   * .Solver.Simplify         -> .Simplify
   * .Type                    -> .Util.CoreType
   * .MutableType             -> .Util.Monadic
   * .Types                   -> .Util
   * .UserType                -> .Type
   * .TypeDeclaration         -> .TypeDeclUtil (better name? Does analysis, rec sel generation, etc.)
   * .TypeAndClassDeclaration -> .TypeDecl
* GHC.Types.TypeAndCoercion -> GHC.Types.Type.Internal
* GHC.Types -> GHC.CoreTypes
   * I'm reluctant to move GHC.Types.* into GHC.Core because many of these
     modules are used in other places (e.g., GHC.Haskell.*, GHC.Compiler.CmmToAsm.*, etc.)
* GHC.Compiler.* -> GHC.*
* GHC.TemplateToHaskell -> GHC.Haskell.Template
* GhcPrelude -> GHC.Prelude
* SysTools.* -> GHC.Util.SysTools.*
* GHC.CmmToAsm.Register.Allocator -> GHC.CmmToAsm.RegAlloc
* GHC.Haskell.Syntax -> GHC.Syntax
* GHC.Haskell.TypeCheck -> GHC.TypeCheck


Not done:
* GHC.Data.List.SetOps -> GHC.Data.List: cf discussion above
* Adding a "Pass" level (e.g., GHC.Core.Pass.CallArity): cf discussion above
* GHC.Data.TrieMap -> GHC.Core.TrieMap (it is used in the type-checker, in STG's CSE, etc.)
* "The old FamInstEnv and InstEnv really should be in GHC.Haskell.TypeCheck,
  perhaps as GHC.Haskell.TypeCheck.FamilyInstance.Pure and
  GHC.Haskell.TypeCheck.Instance.Pure.": I think it would be better to do this
  after some refactoring/splitting because for now they are respectively
  imported by 31 and 16 modules outside of GHC.Haskell.
* GHC.HaskellToCore -> GHC.Desugar: name clash with GHC.Desugar into base.
   

Various:
* "DataCon (why not DataConstructor?)": that was my original proposal but we
  chose to use the data type name as a name for this module IIRC.

**Comment by amigalemming** [comment]
If we think about splitting GHC into multiple packages: How about choosing module directories according to these packages?

**Comment by bgamari** [comment]
> If we think about splitting GHC into multiple packages: How about choosing module directories according to these packages?

Indeed there is a strong incentive to avoid shuffling things about too often. However, I suspect that the only split that is on the horizon is to break out `hsSyn` (and perhaps `types`). It seems like this would be a pretty non-invasive change to make after this proposal has been implemented so I'm not sure any changes to the proposal are necessary.

**Comment by AndreasPK** [comment]
After recently looking for the deriving code I can say "yes this would improve my life".

**Comment by hsyl20** [comment]
For a follow-up on this proposal, see: https://gitlab.haskell.org/ghc/ghc/issues/13009

**Review by Newxhack — COMMENTED** [review]
How to save it

**Pull request closed without merging**
