### PR TITLE
LANGUAGE stability proposal

### PR DESCRIPTION
**Pull request by nomeata**
[Rendered](https://github.com/ghc-proposals/ghc-proposals/blob/stable-extensions/new-proposal.rst)

### CODE REVIEW

**Comment by goldfirere** [comment]
I'm +1 on this proposal.

One variation I wonder about is this: when marking an extension as stable, I think we should require a reasonably water-tight specification (to the level of formality of the Report) of the extension. Many (most?) extensions lack such a tight specification, and I think writing these will be beneficial all around.

**Comment by nomeata** [comment]
That is a good point, I have been wondering about it. Maybe we should look at some language extensions that we expect to be marked stable first – would requiring a spec raise the bar too much? 
Certainly feasible for syntactic stuff like `MagicHash`. But anything involving types? E.g. `ExistentialQuantification`, `MultiParamTypeClasses`? You can better assess the state there.

**Comment by goldfirere** [comment]
And this is one reason why standardization has proved so difficult. Perhaps we make standardizing an existing extension a "payment" to get commit bits? :)

`ExistentialQuantification` I think we could do. `RankNTypes` also, thanks to "Practical Type Inference". I've no idea how to do `GADTs` other than "if you put lots and lots of type annotations in, it will surely work. But most of those annotations can be left out in practice".

**Comment by Ericson2314** [comment]
I hope this is a first step towards language levels!

**Comment by nomeata** [comment]
> If so, should all current language extensions be considered experimental until further review?

Correct. This just sets the framework. We might have then one proposal to stabilize an initial set of extensions. I’ll clarify that.

**Comment by treeowl** [comment]
I am -1 on this. I would be weakly +1 on the versioned language feature alternative, although that could be hard to manage. Some thoughts:

1. How do we decide whether or when a language feature should be considered "stable"? Yes, there are a very few that might be generally accorded that status: `MagicHash`, `BangPatterns`, `ExistentialQuantification`, `RankNTypes`, `MultiParamTypeClasses`, `FlexibleContexts`, and `FlexibleInstances` come to mind. But see point 2!

2. Sometimes new developments suggest a change to a long-stable language feature.

  * Now that we have `TypeFamilies`, there has been a good bit of discussion about potentially using type families to desugar the venerable `FunctionalDependencies` extension. That change would not be entirely backwards compatible, thanks to the interaction with overlapping instances.

  * The creation of `TypeInType` led to the need to re-evaluate how to handle parsing `*`, which has now led to a well-justified proposed change to the long-stable `TypeOperators` extension.

  * Looking back in time a bit, the `OverlappingInstances` and `IncoherentInstances` features, which had been stable for many years, have now been deprecated in favor of per-instance pragmas. These features are likely to face even more serious changes.
  
The key point is that it's very hard to really know for *sure* whether a future development might destabilize a language feature, whether blatantly or just subtly. With versioned "stable" language features, we at least have some hope. If we can reasonably maintain *both* versions, then we can do so. Otherwise, modules that specify an explicit version that is no longer supported will at least fail fast; this will give their authors the chance to review the changes between the versions to ensure their code still means what they intended.

**Comment by AntC2** [comment]
In theory I'm in favour of marking specific features as stable/blessed. Newbies and writers of educational materials can confidently build their competence. Except the set of features everybody thinks of as stable (because they've been in place _de facto_ since ~1998), aren't. @treeowl identifies them.

> there are a very few that might be generally accorded that status: ..., `MultiParamTypeClasses`, ... `FlexibleInstances` 

Once we allow `FlexibleInstances`, we allow instances that overlap. Then allowing `MultiParamTypeClasses` all hell breaks loose.

> * Now that we have `TypeFamilies`, there has been a good bit of discussion about potentially using type families to desugar the venerable `FunctionalDependencies` extension. That change would not be entirely backwards compatible, thanks to the interaction with overlapping instances.

Arguably GHC's implementation of FunDeps + Overlaps + `UndecidableInstances` -- stable since ~2004 -- is bogus [(SPJ's word)](https://ghc.haskell.org/trac/ghc/ticket/10675#comment:15) and unprincipled (doesn't implement the semantics given in the papers). Then `TypeFamilies`, including `ClosedTypeFamilies` is doing the Right Thing. (But has weaknesses, per @goldfirere+Morris's Partiality paper.)

> * Looking back in time a bit, the `OverlappingInstances` and `IncoherentInstances` features, which had been stable for many years, have now been deprecated in favor of per-instance pragmas. These features are likely to face even more serious changes.

Ooh er, "even more serious changes"? Certainly there's plenty of code using overlaps. (`IncoherentInstances` not so much, I hope.)

If we can't mark `MultiParamTypeClasses` as stable (which is essentially why it didn't advance to Haskell 2010 in the Haskell prime process), I'm not seeing that this proposal is going to help any.

Oh, and a [small plug](https://github.com/ghc-proposals/ghc-proposals/pull/56) for how to make this whole mess stable and principled. (Sorry, another Proposal.)

**Comment by nomeata** [comment]
Ok, plenty of evidence that some proposals are not going to be marked as stable. That’s ½ of what we need to establish that a distinction is useful, so that’s good!…

Are there proposals that we can agree on are good candidates for stable ones? `MagicHash` probably is, but that is somewhat trivial. Are there “large” ones, maybe beyond type systems? `ForeignFunctionInterface`? `Safe`? `UnboxedTuples`?

**Comment by treeowl** [comment]
Isn't ForeignFunctionInterface already Haskell 2010? I believe Simon
Marlowe very recent proposed a change to UnboxedTuples, so that's right
out. Safe seems almost certain to evolve through interactions with other
extensions.

On Oct 19, 2017 7:02 PM, "Joachim Breitner" <notifications@github.com>
wrote:

Ok, plenty of evidence that some proposals are not going to be marked as
stable. That’s ½ of what we need to establish that a distinction is useful,
so that’s good!…

Are there proposals that we can agree on are good candidates for stable
ones? MagicHash probably is, but that is somewhat trivial. Are there
“large” ones, maybe beyond type systems? ForeignFunctionInterface? Safe?
UnboxedTuples?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ghc-proposals/ghc-proposals/pull/85#issuecomment-338061515>,
or mute the thread

**Comment by goldfirere** [comment]
@mboes recently made some comments in a different forum that pertain to this proposal. I wonder if he might like to summarize his points here...

**Comment by yav** [comment]
I am quite uncertain of the benefits of this proposal: it seems to be mostly a matter of policy, rather than an actual mechanism that would achieve much.   Also, I am doubtful that we can actually pick many meaningful extensions to actually mark as stable.

For what it's worth, some language extensions that I consider more or less stable are various syntax ones: `RecordWildCards`, `NamedFieldPuns`, `OverloadedStrings`, `TupleSections`; from the type ones probably `RankNTypes` and `ExistentialQunatification`, `(No)MonomorphismRestriction`, maybe `TypeSynonymInstances` too.

Overall, I would much prefer to simply consider changes on a case by case basis, and be reasonable and not break things without a good reason.

**Comment by simonmar** [comment]
On balance I think this is extra bureaucracy that doesn't provide much practical benefit.  I suspect we'd get into situations where we had marked an extension as stable, and then discovered a better design that justified changing it, and then we'd be stuck with having to create a new extension and supporting the old one. Or else we keep too many extensions as experimental, and then the extra bureaucracy isn't benefiting anyone.

It feels like the wrong solution to the problem to me. Either extensions should be stable, or they shouldn't. If we have some mixture of the two, then we get (almost) none of the benefits in exchange for extra work and complexity.

So -1 from me.

**Comment by nomeata** [comment]
> So -1 from me.

I am a bit surprised, given that your comment in <https://mail.haskell.org/pipermail/ghc-steering-committee/2017-September/000197.html> sparked the whole discussion. Personally, I am happy to avoid any bureaucracy that can be avoided.

> Either extensions should be stable, or they shouldn't.

I think this discussion, both on the committee list and here, shows that extensions – at least in general – just are not stable. That seems to rule out the former, and leaves us with the latter, which is the status quo…

**Comment by simonmar** [comment]
> I am a bit surprised, given that your comment in https://mail.haskell.org/pipermail/ghc-steering-committee/2017-September/000197.html sparked the whole discussion. Personally, I am happy to avoid any bureaucracy that can be avoided.

You're right, I should explain this a bit more. Designating some extensions as stable doesn't provide the properties that I mentioned in that thread - we don't get to know the grammar of the file from its LANGUAGE pragma. Even if the module only requires stable extensions, it might be using older versions of those extensions before they became stable.

That was the basis for my -1 - the effort in terms of process seems to outweigh the benefits.

However, I have been somewhat persuaded by Manuel's arguments (on the email thread) that stable extensions are akin to the Haskell Prime process, and could replace it. Especially if this entailed properly specifying the extensions at the level of detail needed for the Haskell Report, I think there would be a lot of value in doing that.

**Comment by nomeata** [comment]
> Even if the module only requires stable extensions, it might be using older versions of those extensions before they became stable.

True. Does the `-Wexperimental-extension` flag help? If you specify `-Werror=experimental-extensions`, then you are limiting yourself to Haskell+Stable extensions, and get the guarantee that you want, right?

**Comment by simonmar** [comment]
It would be better if this were a LANGUAGE pragma, e.g. `{-# LANGUAGE NoExperimentalExtensions, ... #-}` because people tend to put things like `-Werror` outside of source files.  But in practice I think few people would actually do this.

**Comment by nomeata** [comment]
Ah, I didn’t think about making it an extension that is on by default; good idea.

> But in practice I think few people would actually do this.

Right. But then they don’t get to complain :-)

OTOH, there are surprisingly many people who turn on all as much safeguards as the compiler allows (`-Wall -Werror`) to a sometimes silly extent. So maybe people will be using it. Just like now some people take pride in writing Haskell98-only code.

**Comment by BardurArantsson** [comment]
Is the NoExperimentalExtensions extension itself to be considered experiemental or non-experimental? ;)

**Comment by nomeata** [comment]
> Is the NoExperimentalExtensions extension itself to be considered experiemental or non-experimental? ;)

I gave that some thought. At first I thought it has to be stable, to not be non-contradictory. But I got it wrong: When it’s enabled, it allows experimental extensions. So it does not matter :-)

**Comment by nomeata** [comment]
I think this was a helpful discussion which indicated that we cannot predict the future and hence cannot usefully designate some extensions as stable.

**Pull request closed without merging**
