### PR TITLE
Levity-Polymorphic Type Classes

### PR DESCRIPTION
**Pull request by Icelandjack**
Original Trac ticket: [#12708](https://ghc.haskell.org/trac/ghc/ticket/12708).
[Reddit submission](https://www.reddit.com/r/haskell/comments/5hmk4e/ghc_proposal_levity_polymorphic_type_classes/).

 Lets us define instances like `Num Int#`

```haskell
{-# Language InstanceSigs #-}

class Num (a :: TYPE rep) where
  (+) :: a -> a -> a
  (*) :: a -> a -> a
  fromInteger :: Integer -> a

instance Prelude.Num n => Num (n :: Type) where
  ...

instance Num Int# where
  (+) :: Int# -> Int# -> Int#
  (+) = (+#)

  (*) :: Int# -> Int# -> Int#
  (*) = (*#)

  fromInteger :: Integer -> Int#
  fromInteger (fromInteger -> I# int#) = int#

instance Num Double# where
  (+) :: Double# -> Double# -> Double#
  (+) = (+##)

  (*) :: Double# -> Double# -> Double#
  (*) = (*##)

  fromInteger :: Integer -> Double#
  fromInteger (fromInteger -> D# dbl#) = dbl#
````

and

```haskell
class Show (a :: TYPE rep) where
  show :: a -> String

instance Prelude.Show a => Show (a :: Type) where
  show :: a -> String
  show = Prelude.show

instance Show Int# where
  show :: Int# -> String
  show int# = show (I# int#) ++ "#"

instance Show Double# where
  show :: Double# -> String
  show dbl# = show (D# dbl#) ++ "#"
```

[Rendered](https://github.com/Icelandjack/ghc-proposals/blob/patch-1/proposals/0000-type-class-levity.rst).

### CODE REVIEW

**Comment by Icelandjack** [comment]
@goldfirere this fails with `-dcore-lint`.

**Comment by andrewthad** [comment]
This is interesting, but without an unlifted data types extension, I don't see a good motivation for doing this. Making `Eq` and `Ord` work for `Int#`, `Word#`, etc. is the only thing I can see where there is an immediate gain from this. To me, the drawback mentioned in the proposal (causing problems for `TypeApplications`) seems to outweigh this benefit. So I would say that I am opposed to this change unless there is some certainty that an unlifted data types extension is coming to GHC with it. For me, that would tip the scales, since I would really want to be able to `fmap` over an unlifted `Maybe`.

**Comment by Icelandjack** [comment]
Interestingly `Applicative` doesn't work, but

```haskell
class Functor m => Monoidal (m :: TYPE UnboxedTupleRep -> TYPE rep) where
  unit :: () -> m (##)
  mult :: m a -> m b -> m (# a, b #)
``` 

does, it is not possible to go from that to the `Applicative` interface using the usual route (as it should, since `<*>` shouldn't be levity polymorphic). I think @goldfirere will fix this in the future, `(##)` and `(# a, b #)` should have different kinds.

**Comment by Icelandjack** [comment]
Stuff

```haskell
class Semigroup (s :: TYPE rep) where
  (<>) :: s -> s -> s

instance Semigroup m => Monoid (m :: TYPE rep) where
  mempty :: () -> m

data Const :: Type -> forall rep. TYPE rep -> Type where
  Const :: e -> Const e a 

class Functor (f :: forall rep1. TYPE rep1 -> TYPE rep2) where
  fmap :: (a -> a') -> (f a -> f a')

class Functor f => Applicative (f :: forall rep1. TYPE rep1 -> TYPE rep2) where
  pure  :: a -> f a
  (<*>) :: f (a -> b) -> (f a -> f b)

instance Functor (Const e) where
  fmap :: (a -> a') -> (Const e a -> Const e a')
  fmap _ (Const e) = Const e

instance Monoid m => Applicative (Const m) where
  pure :: a -> Const m a
  pure _ = Const (mempty ())

  (<*>) :: Const m (a -> b) -> (Const m a -> Const m b)
  Const m₁ <*> Const m₂ = Const (m₁ <> m₂)
```

**Comment by RyanGlScott** [comment]
Aside from the fact that this stuff barely works today in GHC HEAD (an issue which will eventually be resolved, I imagine), I feel like I'd need a lot more user testimony about actually _using_ these classes in practice before I can be swayed to change our long-established class hierarchy to accommodate levity polymorphic definitions. For instance, how would many type signatures would stop being inferred because of these changes? What effect does it have on the average readability of error messages?

I'll echo @goldfirere's comments [here](https://ghc.haskell.org/trac/ghc/ticket/12708#comment:14): I think an important first step is to create a separate library that fully implements all of these ideas so that folks can experiment with it. While the numerous examples you've provided are nice to look at, actually being able to get my hands on something I could tinker with would go a long way in persuading me that this is a good idea.

**Comment by bgamari** [comment]
I agree that this may be a bit premature. As mentioned by others, I think we will really want more experience working with levity polymorphic classes (e.g. via an alternative `Prelude` and `RebindableSyntax`) before we start generalizing `base`.

**Comment by Icelandjack** [comment]
If I create a library should 

```haskell
class Functor (f :: forall rep1. TYPE rep1 -> TYPE rep)
class Functor f => Applicative (f :: forall rep1. TYPE rep1 -> TYPE rep2)
class Applicative f => Monad (f :: forall rep1. TYPE rep1 -> TYPE rep2)
```

be included for experimenting with and what's a good name? This is the only levity-polymorphic `Applicative`, `Monad` I can think of.

**Comment by goldfirere** [comment]
You mention a core-lint error. Is this posted as a bug somewhere?

I actually think that this would not cause problems with type inference. I'd want experience to be sure, but I believe all will be well. In particular, inferred types will still be levity-monomorphic because GHC will never infer levity polymorphism. This means that, with this proposal, if you write

```
myPlus = (+)
```

the `myPlus` would be levity-monomorphic, unlike `(+)`. (This is true even without the monomorphism restriction. Indeed, you can view the levity-monomorphism restriction as a relative of the traditional monomorphism restriction that can never be disabled.)

**Comment by Icelandjack** [comment]
@goldfirere My Internet situation has been zonky — I made [a ticket (`#12987`)](https://ghc.haskell.org/trac/ghc/ticket/12987). I'm glad inference doesn't seem to be a problem.

If I understand correctly, the most general constructors `Functor`, `Pointed`, `Applicative`, `Monad` accept are

```haskell
Functor     :: (TYPE rep₁ -> TYPE rep₂) -> Constraint
Pointed     :: (TYPE rep₁ -> TYPE rep₂) -> Constraint
Applicative :: (Type      -> TYPE rep)  -> Constraint
Monad       :: (Type      -> TYPE rep)  -> Constraint
```

but if `Monad` includes `join` it must be constrained to 

```haskell
Monad :: (Type -> Type) -> Constraint
```

Is this meaningless or does it have deeper implications? Everyone please share cool levity-polymorphic classes you can think of!

**Comment by bgamari** [comment]
Note that this proposal is roughly one week from the end of its four week long discussion period. At the end of this period we ask @Icelandjack to summarize the discussion and bring the proposal to the GHC committee for consideration. Thanks!

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by nomeata** [comment]
Another ping. @Icelandjack, whither this proposal?

**Comment by nomeata** [comment]
Due to lack of activity, I am marking this proposal as [dormant](https://github.com/ghc-proposals/ghc-proposals/#what-is-a-dormant-proposal).

**Comment by nomeata** [comment]
This has been dormant for a long time. @Icelandjack, is this abandonned? In that case, please consider closing it.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Comment by noughtmare** [comment]
Now that unlifted data types are implemented, should this proposal be reconsidered?

**Comment by goldfirere** [comment]
I think it indeed may be time to reconsider this. But I think the first step would be creating a whole library full of levity-polymorphic classes to experiment with.

**Comment by Ericson2314** [comment]
Well, https://github.com/ekmett/unboxed is thing I recently heard about.

**Comment by BurningWitness** [comment]
After playing around with `UnliftedDatatypes` to write a tree strictly, it feels like `GHC.Exts` would profit immensely from having extra magic sugar, however my vision doesn't align with the original one from this proposal.

None of the existing `base` classes align in meaning with their magic counterparts:
- `Ord#` doesn't need `compare`, `min` or `max`;
- Numeric hierarchy would be different, and would only include primitive operations; 
- `Bits#` would only include primitive operations.

Since all of the operations are primitive I'd also expect hard inlining on all the functions (though that's probably how it would behave out of the box anyway).

---

Note that I don't know what the grand vision for unlifted datatypes is. I perceive it as the ability to write C in Haskell, and as such I would love to see extra conveniences like `if# _ :: Int# then# _ else# _` and a proper module for primitives instead of `GHC.Exts`.

**Comment by noughtmare** [comment]
> Note that I don't know what the grand vision for unlifted datatypes is.

This is a good point. Perhaps we should develop a more complete vision of Unlifted Haskell before we continue with smaller incremental changes.

Personally, I'd like to see a future where you can program almost normally as you can today, but using unlifted data types exclusively. Thus basically carving out a strict subset of Haskell. That's why I'd like to see the classes that we have today generalized to support unlifted types. A bit further in the future, I'd like to see a way to combine both lifted and unlifted programs in an ergonomic way. That would require easy conversion functions between lifted and unlifted versions of data types like maybe, tuples, and lists.

For me it is not that important to have full representation polymorphism. And a big problem with unboxed representations is that they cannot be bound at the top level, so you can't have a method like `mempty` from the `Monoid` class return an unboxed value (unless you can somehow guarantee that the uses are always inlined).

**Comment by BurningWitness** [comment]
> a future where you can program almost normally as you can today, but using unlifted data types exclusively.

I admit this may be a programming approach thing, but I'm completely fine with regular Haskell programs always relying on lifted types. I don't think regular users need the power to skip a few thunk checks, especially when GHC is free to optimize the boxes away anyway . The library writers on the other hand specifically want to be unambiguous about what is strict and what isn't, even at the cost of harder to read code.

From my perspective the two universes never have to overlap, there merely needs to be a way to put unlifted datatypes inside other datatypes (which `UnliftedDatatypes` provides) and some sugar so that code isn't all `case longFoo# (extremelyLongBar# _) of 0# -> _; _ -> _`. The only other thing I can think of is proper levity-polymorphism so that my `RadixTree# Word8# a` shares the foundation with `RadixTree# Char# a`, but I imagine it's not as easy as it sounds.

**Comment by noughtmare** [comment]
> I don't think regular users need the power to skip a few thunk checks

I'd agree if it was just about thunk checks (as an aside, [that point has been significantly weakened due to tag inference](https://github.com/ghc-proposals/ghc-proposals/pull/265#issuecomment-1691658098)). 

For me it is much more important to have the guarantee that my values don't contain any surprise computations which may make my program take a lot more space and time than I expect. Instead of wondering if I should use a bang pattern at every binding (and then you still sometimes have to [use `$!` for some function applications](https://gitlab.haskell.org/ghc/ghc/-/issues/19022)), with unlifted data types you only have to make that decision once per data type.

**Comment by tomjaguarpaw** [comment]
> For me it is much more important to have the guarantee that my values don't contain any surprise computations which may make my program take a lot more space and time than I expect

If there are examples of this issue that are solved by unlifted types but not by [Make invalid laziness unrepresentable](http://h2.jaguarpaw.co.uk/posts/make-invalid-laziness-unrepresentable/) then I would like to know about them!

**Comment by BurningWitness** [comment]
> important to have the guarantee that my values don't contain any surprise computations

I feel like this is a separate problem within the same area of interest: whether it's possible to rearrange Haskell types in such a way that a function may define the levity of the value it consumes. The average user experience shouldn't change much from an addition like this.

**Comment by noughtmare** [comment]
@tomjaguarpaw that approach works if your values are in a data type, but sometimes there are not data types involved. For example that second link in my previous comment:

```haskell
foldr' _ z []     = z
foldr' f z (x:xs) = f x (foldr' f z xs)
```

You would need to manually remember to use `$!`:

```
foldr' _ z []     = z
foldr' f z (x:xs) = f x $! foldr' f z xs
```

An example on your blog:

```
example_Strict = Data.List.foldl' f (Strict (0, 0)) [1..1000]
    where f :: Strict (Int, Int) -> Int -> Strict (Int, Int)
          f (Strict (n, s)) i = Strict (n + 1, s + i)
```

If you accidentally forget that `'` then you still get a leaky program:

```
example_Strict = Data.List.foldl f (Strict (0, 0)) [1..1000]
    where f :: Strict (Int, Int) -> Int -> Strict (Int, Int)
          f (Strict (n, s)) i = Strict (n + 1, s + i)
```

@BurningWitness it's already possible to specify the levity of function arguments:

```haskell
import GHC.Exts (UnliftedType)
id :: forall (a :: UnliftedType). a -> a
id x = x
```

**Comment by tomjaguarpaw** [comment]
I'm not convinced that `foldr'` is a good example. The strict version leaks stack space.

`foldl'` *is* a good example, but I'm not sure it's a point in favour of unlifted types, or at least, I think it requires a lot of further consideration. It's certainly correct that forgetting to use `foldl'` and using `foldl` instead, with a lifted type, will lead to a space leak, whereas if you'd used an unlifted type `foldl` will work fine[^0]. But that doesn't seem to be a point directly in favour of unlifted types. It seems to be a point in favour of not defining functions incorrectly.

Then the question becomes, do unlifted types help us define our functions correctly? We might be tempted to say "yes": if I give my accumulator an unlifted kind then I'm getting the fold correct by construction. Because `b :: UnliftedType` I know I won't have a space leak:

```haskell
foldl'1 :: forall a (b :: UnliftedType). (b -> a -> b) -> b -> [a] -> b
foldl'1 _ z [] = z
foldl'1 k z (x : xs) = foldl' k (k z x) xs
```

But the problem with this argument is that you still have to remember to do that. It doesn't seem any easier to remember to make an argument's kind unlifted that it is to make that argument strict:

```haskell
foldl'2 :: forall a (b :: LiftedType). (b -> a -> b) -> b -> [a] -> b
foldl'2 _ z [] = z
foldl'2 k !z (x : xs) = foldl' k (k z x) xs
```

It's not immediately clear how unliftedness is helpful in writing `foldl'1` correctly above and beyond writing `foldl'2` correctly. Arguably, one point in the favour of unliftedness is that it will become obvious at call sites if we haven't defined `foldl'` to take an unlifted accumulator. Whilst true, that seems rather roundabout.

So my preferred approach, which I am yet to be convinced can be bettered by unlifted kinds, is to [Make invalid laziness unrepresentable](http://h2.jaguarpaw.co.uk/posts/make-invalid-laziness-unrepresentable/) and make sure that some small surface area of critical functions (`foldl'`, `modifyIORef'`, the `State` monad operations, etc.) are defined to be sufficiently strict.

[^0]: but `foldl` *will* work fine with a lifted type at `-O1`

**Comment by noughtmare** [comment]
> But that doesn't seem to be a point directly in favour of unlifted types. It seems to be a point in favour of not defining functions incorrectly.

The point I'm trying to make is not that it becomes easier to define the right function, but that the compiler will error when you use an unlifted type where a lifted type was expected and vice versa.

I don't agree a strict right fold leaks stack space. The stack space is simply necessary to perform that operation. For example, you can't define a "non leaking" `map` over a strict list. So a strict right fold is acceptable in that case:

```haskell
type List :: UnliftedType -> UnliftedType
data List a = Nil | Cons a (List a)

map f xs = foldr' (\x xs' -> Cons (f x) xs') Nil xs
```

Using a left fold here will reverse the list, which you don't want.

And I don't want to give the impression that this is limited to just folds. There are many functions with strict variants where it is much less straightforward when you should use which version.

**Comment by tomjaguarpaw** [comment]
> The point I'm trying to make is not that it becomes easier to define the right function, but that the compiler will error when you use an unlifted type where a lifted type was expected and vice versa.

Right, I thank that was my final point: "is that it will become obvious at call sites". I don't find that particularly compelling, but maybe I'm failing to see something that you can see.

> I don't agree a strict right fold leaks stack space. The stack space is simply necessary to perform that operation. 

Not really. You can reverse and `foldl'`, for example.

> There are many functions with strict variants where it is much less straightforward when you should use which version.

OK, it would be good to collect some examples, because I'm not aware of any situations where this is in doubt in principle (as opposed to in practice, where it is indeed in doubt: witness the absurd plethora of `foldl`, `foldl'`, `foldr`, `foldr'` in `Foldable` for example).

**Comment by noughtmare** [comment]
> Not really. You can reverse and foldl', for example.

That now leaks heap space, which is worse. And reversing takes extra time.

> OK, it would be good to collect some examples

The first thing that came to my mind was `iterate` vs `iterate'`. Both are clearly useful in different cases. If you have plain integers then `iterate'` is usually what you want, while if you have lazy lists then you probably want `iterate`.

**Comment by tomjaguarpaw** [comment]
> >  Not really. You can reverse and foldl', for example.
>
> That now "leaks" heap space, 

Hmm, we may be talking at cross purposes. I'm trying to explain why it never makes sense to write

```haskell
foldr' _ z []     = z
foldr' f z (x:xs) = f x $! foldr' f z xs
```

If `f` is strict in its second argument then the `$!` is redundant and if it's lazy then you've leaked stack space. Am I missing something here?

> The first thing that came to my mind was `iterate` vs `iterate'`

`iterate'` is hardly worse on lazy lists than `iterate`. I find it hard to believe that `iterate` is every truly necessary, just like I've never seen a real use case for `foldl`.

----

Perhaps this is getting too far off the topic of this proposal. Maybe if you'd like to continue you can open a Discourse post?

**Comment by BurningWitness** [comment]
> it's already possible to specify the levity of function arguments

Yes, but you can't defer the resolution of said levity to the consuming function. Think roughly something like

```haskell
data Foo = Foo Int (Int :: TYPE IntRep)

foo :: IOGenM StdGen -> IO Foo
foo g = do
  a <- uniformM g
  b <- uniformM g
  pure $ Foo a b
```

> If `f` is strict in its second argument then the `$!` is redundant and if it's lazy then you've leaked stack space

Your input/output `z` is not the same as the intermediate one:

```haskell
foldr' :: forall (a :: Type levity) (b :: Type levity'). (a -> b -> b) -> b -> [a] -> b
foldr' _ z []     = z
foldr' f z (x:xs) = lift $ unlift z (\z' -> f x $ go z' xs)
  where
    go :: forall (c :: Type Unlifted). c -> [a] -> c
    go t []     = t
    go t (x:xs) = f x $ foldr' t xs
    
lift :: Type Unlifted -> Type levity
lift = coerce

lift :: Type levity -> (forall a. (Type Unlifted -> a) -> a)
lift (x :: Type Lifted)   = \f -> x `seq` f (coerce x)
lift (x :: Type Unlifted) = ($ x)
```

**Comment by tomjaguarpaw** [comment]
> Your input/output `z` is not the same as the intermediate one

Is that directed at me? If so, I'm sorry, I don't understand. That definition of `foldr'` leaks stack space in all cases (or would if it were possible to define it thus).

**Comment by BurningWitness** [comment]
To fold a cons-list starting from the bottom you must first reach said bottom and that means making a thunk chain as long as the list itself. This has nothing to do with strictness, it's the price for doing this operation on this data structure. [`reverse`](https://hackage.haskell.org/package/base-4.19.0.0/docs/src/GHC.List.html#reverse) does this too (and even directly uses `foldl` in the report).

Symmetric data structures have equal complexity for folds in either direction, see [`Set.toDescList`](https://hackage.haskell.org/package/containers-0.7/docs/src/Data.Set.Internal.html#toDescList).

Levity polymorphism would not change anything in how we reason about folds, it would merely allow operating on unlifted datatypes smoothly instead of constantly sequencing lifted ones.

**Comment by noughtmare** [comment]
I've opened a discourse thread to continue this discussion: https://discourse.haskell.org/t/unlifted-types-vs-strict-wrapper/8045

**Pull request closed without merging**
