### PR TITLE
OverloadedDo 

### PR DESCRIPTION
**Pull request by Tritlo**
[Rendered](https://github.com/Tritlo/ghc-proposals/blob/patch-1/0000-generalized-do-notation.rst).

Greetings!

I've written up my idea on Generalized Do-Notation, and await comments. This is my first proposal, so please comment on how I could improve the proposal itself as well.

### CODE REVIEW

**Comment by nomeata** [comment]
Welcome!

You should definitely discuss how this is better or different than `RebindableSyntax`.

Also, note that type class inference does not backtrack. So if you add the instance
```
instance Applicative f => ApplicativeDoable f where
```
you can have no other instance (without `OverlappingInstances`).

**Comment by Tritlo** [comment]
Good point. Does `RebindableSyntax` work with the `ApplicativeDo` extension? If it does, then this is pretty much subsumed by that, I suppose.

**Comment by nomeata** [comment]
I don’t know. Even if it does not, there might be mertis to this: `RebindableSyntax` affects more than do-notation, for example.

**Comment by Tritlo** [comment]
I've updated the proposal to take your comments into account, though there are still quite a few unanswered questions.

**Comment by goldfirere** [comment]
The updated proposal addresses `RebindableSyntax`, but I still think it is missing several necessary elements:

* Does `RebindableSyntax` work with `ApplicativeDo`? Understanding why or why not it does would be helpful in evaluating this proposal.

* Several concrete, worked-out examples of how this would work would be very illuminating. I do see how `SizedMonad` is good motivation, but I'd love to see a full example using this -- as well as at least one other example.

* The proposal still does not mention the fact that your two default instances need to be `{-# OVERLAPPABLE #-}`. Overlapping instances have some unfortunate consequences that I'd like to see addressed.

* I'm not sure at all how type inference would work. Your classes are strangely shaped, in that none of the methods in the class refer to the class variable. With `AllowAmbiguousTypes`, this is allowed, and with `TypeApplications`, this can be useful. However, given a concrete user-written `do` block, how would GHC know which `Doable` to use?

* This proposal has a similar flavor to `OverloadedLists` and `OverloadedStrings`, which allow class-based overloading without the no-holds-barred behavior of `RebindableSyntax`. Would this proposal fit right alongside those (so that it should really be called `OverloadedDo`)? `OverloadedLists`, in particular, puts some constraints on the types of overloaded lists, so that, e.g., `HList :: [Type] -> Type` doesn't work. It seems you're trying to avoid this limitation in your formulation, but I'm worried you've gone too far (leading to my comment about type inference). It would be nice to have an understanding of how the design of this feature compares to the design of `OverloadedLists` so we can evaluate the likelihood of adoption of this feature by comparison to that one.

I know I'm asking a lot here, but I, for one, am unconvinced by this proposal. By drawing out the points above, you will make a more convincing argument. Regardless, thanks for posting!

**Comment by Tritlo** [comment]
Thanks for your comments, Richard. I like the name `OverloadedDo`. I agree that the no-holds-barred might be too much, though I'd like to have it as open as possible while still having some sanity checks. I'll look into that further, and rework the proposal.

`RebindableSyntax` does work with `ApplicativeDo`, so the end user can still gain the benefits of the algorithms used there without this proposal. This however must be done on a module-by-module basis, and makes interleaving of various do-notations for different types a bit repetitive and not as clean. This proposal would definitely improve that story.

**Comment by Tritlo** [comment]
Sorry about the accidental closing!

Thanks for your comments, Richard. I like the name `OverloadedDo`. I agree that the no-holds-barred might be too much, though I'd like to have it as open as possible while still having some sanity checks. I'll look into that further, and rework the proposal.

`RebindableSyntax` does work with `ApplicativeDo`, so the end user can still gain the benefits of the algorithms used there without this proposal. This however must be done on a module-by-module basis, and makes interleaving of various do-notations for different types a bit repetitive and not as clean. This proposal would definitely improve that story.

I agree that a more detailed example is in order, and I'll make sure to include some in the next version. I'm currently working on a project in which this would be of great use, so additional examples should be forthcoming.

I also agree that having overlapping instances is probably not the way to go. I'll give it more thought on how they could possibly be avoided, or otherwise motivate why they should be.

I'll give more thought into the type inference as well, I admit I hadn't given it much thought during the writing of the proposal.

Thank you for all your comments! I see now that I'll need to put in a lot more effort (as I suspected), but having your comments as a guide will help a lot. I still think this extension could be of use to the community and especially library writers, and I hope I'll be able to make a good case for it.

**Comment by AntC2** [comment]
As @goldfirere says,
> * Your classes are strangely shaped, in that none of the methods in the class refer to the class variable.

I'm totally weirded out by that: how does type inference (or the programmer) know which Functor it's dealing with? (For the methods in `Monad`, `Applicative`, `Functor`, the class variable is a constructor in their result.)

To avoid the incoherence that comes with `OVERLAPPABLE` and especially separate compilation, could you use Closed Type Families? (Figuring out why/why not could help explain the type inference needed.)

**Comment by nomeata** [comment]
What is the status of this proposal? Looks like @goldfirere  and @AntC2 raised some questions that should be addressed…

**Comment by Tritlo** [comment]
I'm still working on refining my proposal, sorry about that! I'll update it with (hopefully good) answers to @goldfirere's and @AntC2's questions.

**Comment by nomeata** [comment]
> I'm still working on refining my proposal, sorry about that! 

No need to be sorry, and thanks for working on the refinement!

**Comment by Tritlo** [comment]
So I've been hacking a bit on this proposal, and I'm having a really hard time defining a class for `Doable` and `ApplicativeDoable` in a way that allows both indexed monads (like my SizedMonads) and also things like `IOL` from the Linear Types paper, where you don't even have the same function arrow! I'm open for any suggestions.

**Comment by m0ar** [comment]
@Tritlo In my linear streams project, me and a few guys at Tweag tried to create an umbrella monad class that's polymorphic in the function arrow. This was very difficult (suspected impossible) in GHC currently, and this should be a relatively similar situation if I understand it correctly. I'm not amazingly well-versed in the topic, and there may be alternative approaches too but anyway.

The main issue was that the monad type family gets unfolded too late in the type checking process. Because of this, the multiplicity of the arrows are still just polymorphic when the type checker needs to select a certain instance to get an actual function arrow; the multiplicity data is simply not available yet since the type family hasn't been unfolded.

**Comment by Tritlo** [comment]
So after putting more thought into this, I've come up with the following example that I believe would work, if [Trac #9269](https://ghc.haskell.org/trac/ghc/ticket/9269) were implemented:

```haskell
{-# LANGUAGE RebindableSyntax #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE DuplicateRecordFields #-}

module Main where

import Prelude
import qualified Prelude as P

import GHC.TypeLits
import Data.Proxy

import Sized

type PView t = t

class ApplicativeDoable f p ap | f -> p ap where
  data Pure f
  data Ap f

  type PureT f
  type ApT f

  doPure :: p
  unPure :: p -> PureT f

  doAp   :: ap
  unAp :: ap -> ApT f

class  ApplicativeDoable m p ap => Doable m p ap b | m -> p ap b where
  data Bind m
  type BindT m

  doBind :: b
  unBind :: b -> BindT m


instance {-# OVERLAPPABLE #-} (p ~ PureT f , ap ~ ApT f, Applicative f) => ApplicativeDoable f p ap  where
  data Pure f = ApPure { unApPure :: forall a. a -> f a }
  data Ap f = ApAp { unApAp :: forall a b. f (a -> b) -> f a -> f b}

  type PureT f = forall a. a -> f a
  type ApT f = forall a b. f (a -> b) -> f a -> f b

  doPure = ApPure P.pure
  unPure = unApPure

  doAp   = ApAp (P.<*>)
  unAp   = unApAp


instance {-# OVERLAPPABLE #-} (b ~ BindT m , ApplicativeDoable m p ap, Monad m) => Doable m p ap b where
  data Bind m = MBind { unMBind :: forall a b . m a -> (a -> m b) -> m b }

  type BindT m = forall a b. m a -> (a -> m b) -> m b

  doBind = MBind (P.>>=)
  unBind = unMBind

instance {-# OVERLAPPING #-} (p ~ PureT f , ap ~ ApT f , SizedApplicative f) => ApplicativeDoable f p ap where
  data Pure f = SizedPure { unSizedPure :: forall a. a -> f 0 a }
  data Ap f = SizedAp { unSizedAp :: forall a b k i j . k ~ Max i j => f i (a -> b) -> f j a -> f k b }

  type PureT f = forall a. a -> f 0 a
  type ApT f = forall a b i j k. k ~ Max i j => f i (a -> b) -> f j a -> f k b

  doPure = SizedPure spure
  unPure = unSizedPure

  doAp   = SizedAp (|<*>)
  unAp   = unSizedAp

instance {-# OVERLAPPING #-} (b ~ BindT m
                             , ApplicativeDoable m p ap
                             , SizedMonad m) => Doable m p ap b where
  data Bind m = SizedBind { unSizedBind :: forall a b i j . m i a ->  (a -> m j b) -> m (i+j) b }

  type BindT m = forall a b i j. m i a -> (a -> m j b) -> m (i+j) b

  doBind = SizedBind (|>>=)
  unBind = unSizedBind

one :: () -> SizedIO 1 ()
one _ = wrapWithCost (Proxy :: Proxy 1) $ putStrLn "one"

two :: () -> SizedT IO 2 ()
two _ = wrapWithCost (Proxy :: Proxy 2) $ putStrLn "two"

three :: () -> SizedIO 3 ()
three _ = wrapWithCost (Proxy :: Proxy 3) $ putStrLn "three"

t0a :: SizedIO 6 ()
t0a = do { x <- one ()
         ; y <- two x
         ; z <- three y
         ; () |<$ return (x,y,z)}
    where return = unPure @SizedIO (doPure @SizedIO)
          (<*>)  = unAp @SizedIO (doAp @SizedIO)
          (>>=)  = unBind @SizedIO (doBind @SizedIO)

t2 :: IO ()
t2 = do { x <- putStrLn "hey"
        ; print @() x }
     where return = unPure @IO (doPure @IO)
           (<*>)  = unAp @IO (doAp @IO)
           (>>=)  = unBind @IO (doBind @IO)

main :: IO ()
main = do { t2
          ; runSizedT t0a }

```

Then new instances could be added by writing e.g. 

```haskell
instance {-# OVERLAPPING #-} (p ~ PureT f , ap ~ ApT f , LApplicative f) => ApplicativeDoable f p ap where
  data Pure f = LPure { unLPure :: forall a. a ->. f a }
  data Ap f = LAp { unLAp :: forall a b. f (a ->. b) ->. f a ->. f b }

  type PureT f = forall a. a ->. f a
  type ApT f = forall a b. f (a ->. b) ->. f a ->. f b

  doPure = LPure Linear.pure
  unPure = unLPure

  doAp   = LAp (Linear.<*>)
  unAp   = unLAp

instance {-# OVERLAPPING #-} (b ~ BindT m
                             , ApplicativeDoable m p ap
                             , LMonad m) => Doable m p ap b where
  data Bind m = LBind { unLBind :: forall a b. m a ->.  (a ->. m b) ->. m b }

  type BindT m = forall a b. m a ->. (a ->. m b) ->. m b

  doBind = LBind (Linear.>>=)
  unBind = unLBind
```

However, I'm having a hard time getting around [Trac #9269](https://ghc.haskell.org/trac/ghc/ticket/9269).

**Comment by nomeata** [comment]
Not much happening here, marking as “dormant” for now.

**Comment by nomeata** [comment]
Dormant for a while; I’m closing this (but it can be reactivated of course)

**Pull request closed without merging**
