### PR TITLE
Dynamic typing

### PR DESCRIPTION
**Pull request by goldfirere**
This proposal describes a way we can opt out of Haskell's pesky type system, in a bid to increase both our expressiveness and overall popularity.

[Rendered](https://github.com/goldfirere/ghc-proposals/blob/dynamic/proposals/0000-dynamic-types.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
Can we finally have a decent JavaScript FFI story in GHCJS now?

**Comment by gbaz** [comment]
> Perhaps we want -XDynamicTypes to also defer scoping errors.

That sounds like a terrible idea! Scope errors are very important, and it goes against the spirit of this proposal to defer them instead of handling them properly. We should have a complimentary extension, `-XDynamicScope`.

**Comment by Ericson2314** [comment]
Can `TYPE any` choose a register at run time? I think we could avoid GC then.

**Comment by gary12377** [comment]
lgtm 👍

**Comment by goldfirere** [comment]
Dynamic kinding works today, though it's inconvenient:

```
{-# LANGUAGE ExplicitForAll, PolyKinds, DataKinds #-}

module DynamicKind where

import Prelude hiding ( ($), (.) )
import GHC.Exts

class Rep r where
  ($) :: forall (r2 :: RuntimeRep) (a :: TYPE r) (b :: TYPE r2). (a -> b) -> a -> b
  (.) :: forall (r3 :: RuntimeRep) (a :: TYPE r) (b :: TYPE r) (c :: TYPE r3).
         (b -> c) -> (a -> b) -> a -> c

instance Rep LiftedRep where
  f $ a = f a
  (f . g) x = f (g x)

instance Rep UnliftedRep where
  f $ a = f a
  (f . g) x = f (g x)

instance Rep IntRep where
  f $ a = f a
  (f . g) x = f (g x)

instance Rep DoubleRep where
  f $ a = f a
  (f . g) x = f (g x)

twice :: forall (a :: TYPE r). Rep r => (a -> a) -> a -> a
twice f = (f $) . (f $)
```

It would take an extension of this proposal to handle such things more idiomatically. The (almost) above is because both kinds in the type of `.` are the same, but this could probably be worked out with more sweat.

**Comment by treeowl** [comment]
I think correctable scoping errors should produce runtime warnings. I also suspect there are a lot of other potential applications for runtime instance lookup; that idea might be worth fleshing out in a paper.

**Comment by nomeata** [comment]
> I think correctable scoping errors should produce runtime warnings

The program should just pause and ask the user for what to do. TeX has been doing that for years!

**Comment by mstksg** [comment]
This proposal is very well thought-out from a design and engineering standpoint, and I'd be (truly) happy to see this in GHC.  It's a good demonstration of how sound everything is even from a dynamically typed standpoint.

**Comment by gbaz** [comment]
Actually, on consideration I tried to derive a segfault and couldn't. So I think that this doesn't really give the expressive power I'm looking for in a dynamic typing extension.

**Comment by int-index** [comment]
What about dynamic pattern matching? The proposal must be extended to handle this code:

```
f 5 = True
f "hello" = True
f _ = False
```

**Comment by goldfirere** [comment]
> It's a good demonstration of how sound everything is even from a dynamically typed standpoint.

It indeed scared me to think how easy it would be to implement this. And I actually think it would work swimmingly, and would probably beat the performance pants off other dynamically typed languages, especially if we added a few `RULES` that eliminated redundant `wrapDyn`/`fromDynamic` pairs. This would mean GHC's type checker would figure out which dynamic checks could be performed statically.

> Actually, on consideration I tried to derive a segfault and couldn't.

Good point -- but we already have this feature: just type `unsafeCoerce True False`.

> What about dynamic pattern matching? 

This is not spelled out in the proposal, but this case is implicitly covered. The function `f` would take a `Dynamic` and then do runtime checks in its patterns, induced by the type mismatch that would ensue.

-----------------------------

It's sad to say, but the sunlight of another day has diminished my enthusiasm for this proposal, despite the great response it received. I withdraw it. But do reopen if you feel otherwise. :)

**Comment by gbaz** [comment]
> would probably beat the performance pants off other dynamically typed languages

I think the more serious lisp compilers do this sort of thing whenever possible already actually :-)

**Comment by iamrecursion** [comment]
It's a touch terrifying just how feasible this proposal is.

**Pull request closed without merging**
