### PR TITLE
Add `liftTyped` to the `Lift` typeclass

### PR DESCRIPTION
**Pull request by harpocrates**
[Rendered](https://github.com/harpocrates/ghc-proposals/blob/lift-typed/proposals/0000-lift-typed.rst).

### CODE REVIEW

**Comment by yallop** [comment]
This looks useful.  We use [a similar definition of `typedLift` in `frex`](https://github.com/yallop/haskell-frex/blob/19e5802caf5bc05a0ad1ce33f2fe5fe1258226d4/src/Data/PartiallyStatic.hs#L30-L31); it'd be better to have it as a method.

A second useful step: change the translation of splices to use `typedLift` instead.  At present, code like this

```haskell
f x = [|| x ||]
```

is (roughly speaking) translated into


```haskell
f x = unsafeTExpCoerce (lift x)
```

but it could instead be translated into

```haskell
f x = typedLift x
```

**Comment by gridaphobe** [comment]
The proposal doesn’t specify any changes to `DeriveLift`, so I assume the intention is to continue deriving the untyped `lift` and use the default implementation of `liftTyped`. Wouldn’t it be better to derive `liftTyped` instead?

**Comment by RyanGlScott** [comment]
What does "derive `liftTyped`" mean exactly? I ask since, AFAICT, there's no way to construct values of type `TExp a` besides (1) using typed TH quotes, or (2) using the `unsafeTExpCoerce :: Q Exp -> Q (TExp a)` function. As one example, if you write this:

```haskell
{-# LANGUAGE DeriveLift #-}
import Language.Haskell.TH.Syntax

data Pair a = MkPair a a deriving Lift
```

Then this is the `Lift` instance that would be generated under the hood (slightly cleaned up):

```haskell
instance Lift a => Lift (Pair a) where
  lift (MkPair a1 a2) = conE 'MkPair `appE` lift a1 `appE` lift a2
```

What would a derived implementation of `liftTyped` look like for `Pair`? I'm having trouble envisioning what it would be except for `unsafeTExpCoerce (conE 'MkPair `appE` lift a1 `appE` lift a2)`, but at that point, you might as well just use the proposed default implementation for `liftTyped`.

**Comment by gridaphobe** [comment]
I assumed it would use the typed quotes, e.g. right now I can write

```haskell
data Pair a = MkPair a a

liftTyped :: Lift a => Pair a -> TExpQ (Pair a)
liftTyped (MkPair x y) = [||MkPair x y||]
```

which is exactly what I would want GHC to derive.

**Comment by RyanGlScott** [comment]
Ah, I see what you mean. I think I ruled out that idea when originally implementing `DeriveLift` because at the time, using the TH quote syntax required enabling the `TemplateHaskell` language extension, which would have prevented the use of `DeriveLift` on compilers that didn't support `TemplateHaskell` (such as stage-1 or cross-compiled GHCs). But thankfully, there now exists a `TemplateHaskellQuotes` extension that only enables the use of TH quoting syntax without enabling the other parts of the `TemplateHaskell` extension (such as splicing) that certain compilers have trouble with.

If we simply have `DeriveLift` enable `TemplateHaskellQuotes` when typechecking the code that it generates, then the approach in https://github.com/ghc-proposals/ghc-proposals/pull/175#issuecomment-427480743 would be quite feasible. In fact, it might even _simplify_ the current implementation of `DeriveLift`, since we wouldn't need to refer to any combinators from `Language.Haskell.TH.Lib` in generated `Lift` instances. Among other things, this would make it easier to implement [this proposal](https://ghc.haskell.org/trac/ghc/ticket/14030), which I postponed implementing since I ran into annoying import cycle issues due to trying to import things from `Language.Haskell.TH.Lib` from `Language.Haskell.TH.Syntax` (since the former imports the latter as well).

**Comment by RyanGlScott** [comment]
I was curious to see if the code-generation strategy in https://github.com/ghc-proposals/ghc-proposals/pull/175#issuecomment-427480743 was feasible, so as an experiment, I modified `DeriveLift` to generate code for `lift` using TH quotes. Happily, I found that it worked almost flawlessly.

...almost. There's one gotcha: currently, `DeriveLift` has some special smarts to allow deriving `Lift` instances for constructors that have fields with certain unlifted types. For example, if you write this:

```haskell
{-# LANGUAGE DeriveLift #-}
{-# LANGUAGE MagicHash #-}
module Foo where

import GHC.Exts (Int#)
import Language.Haskell.TH.Syntax

data Foo = MkFoo Int# deriving Lift
```

Then this instance will be generated:

```haskell
instance Lift Foo where
  lift (MkFoo i) = conE 'MkFoo `appE` litE (intPrimL (toInteger (I# i)))
```

Notice that this doesn't `lift` the field of `MkFoo`, but rather uses some special smarts involving `litE` and `intPrimL`. If we were to attempt to generate the `Foo` instance like so:

```haskell
instance Lift Foo where
  lift (MkFoo i) = [| MkFoo i |]
  -- lift (MkFoo i) = conE 'MkFoo `appE` lift i
```

Then this won't typecheck:

```
Foo.hs:12:20: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        t0 :: *
        Int# :: TYPE 'GHC.Types.IntRep
    • In the first argument of ‘lift’, namely ‘i’
      In the expression: lift i
      In the expression:
        [| MkFoo i |]
        pending(rn) [<i, lift i>]
   |
12 |   lift (MkFoo i) = [| MkFoo i |]
   |                    ^^^^^^^^^^^^^
```

This is because `lift` expects its argument to have a lifted type (i.e., a type of kind `Type`), whereas `i` has type `Int#`, which has kind `TYPE IntRep`, not `Type`. This problem also applies for the proposed `liftTyped` method–in fact, the problem is even worse for `liftTyped`, since the _only_ mechanism we have for directly constructing `TExp` expressions is through TH quotes.

I can see two potential ways to resolve this issue:

1. Stop supporting the special cases for unlifted types in `DeriveLift` entirely. This would be a breaking change, but it's unclear to me how many people would be affected by this in practice.
2. Tweak `Lift` and `TExp` slightly to support unlifted types. We could leverage levity polymorphism and redefine them like so:

   ```haskell
   class Lift (a :: TYPE r) where ...
   newtype TExp (a :: TYPE r) = ...
   ```

   If we did this, then instead of hardcoding support for `Int#` _et al._ directly into `DeriveLift`, we could simply give `Lift` instances for the types that we support directly:

   ```haskell
   instance Lift Int# where
     lift i = litE (intPrimL (toInteger (I# i)))
   ...
   ```

   Once that's done we could simply derive a `Lift` instance for `Foo` above like so:

   ```haskell
   instance Lift Foo where
     lift (MkFoo i) = [| MkFoo i |]
     -- liftTyped (MkFoo i) = [|| MkFoo i ||]
   ```

   And it would Just Work™ without any further changes. It would require tweaking the definitions of `Lift` and `TExp` more, however.

What do people think of this?

**Comment by gridaphobe** [comment]
Are there any downsides to option 2, aside from making the types a bit more involved? It seems like a very sensible solution to me.

**Comment by RyanGlScott** [comment]
> Are there any downsides to option 2, aside from making the types a bit more involved?

Based on the feedback in #30 (a similar proposal about levity polymorphic type classes), the main concerns were:

1. Current uses of `lift` in combination with visible type application will be broken due to the introduction the `rep` type variable.
2. It's not clear what effect this would have on error messages involving `lift`.

That being said, the situation here is a bit different in that (a) this isn't a type class in `base` we're changing, so we don't have to butt heads against the Haskell Report, and (b) there's something actually depending on `Lift` becoming levity polymorphic in order to work here (as opposed to #30, which felt like somewhat of an unforced change).

That being said, I think I've wildly sidetracked from @harpocrates' original goal, which was to just introduce a new method to `Lift`. I'm not sure if it's worth updating the proposal to include all of this extra hullabaloo about changing `DeriveLift`—it could just as well be its own proposal.

**Comment by harpocrates** [comment]
It seems to me that typed quotes are already sneakily leaking some levity polymorphism into `TExp` (so perhaps we could consider making `Lift` levity polymorphic as just a bug fix? seriously though... 😃).

    ghci-8.6.1> import Language.Haskell.TH.Syntax
    ghci-8.6.1> import GHC.Exts
    ghci-8.6.1> :set -XMagicHash -XTemplateHaskell +t
    ghci-8.6.1> e = [|| 1# ||]
    e :: Q (TExp Int#)
    ghci-8.6.1> e = [|| 1# ||] :: Q (TExp Int#)   -- GHC suddenly catches on... :)

    <interactive>:5:27: error:
        • Expecting a lifted type, but ‘Int#’ is unlifted
        • In the first argument of ‘TExp’, namely ‘Int#’
          In the first argument of ‘Q’, namely ‘(TExp Int#)’
          In an expression type signature: Q (TExp Int#)

In fact, I may even have personally (accidentally) taken advantage of this before, because you can still use `e :: Q (TExp Int#)`:

    ghci-8.6.1> e' = [|| I# $$(e) ||]
    e' :: Q (TExp Int)

NB: this is not just a GHCi thing.

```haskell
{-# LANGUAGE MagicHash, TemplateHaskell #-}

import GHC.Exts
import Language.Haskell.TH.Syntax

main = print =<< runQ (unTypeQ [|| I# $$e ||])
  where e = [|| 1# ||] -- :: Q (TExp Int#)
```

**Comment by goldfirere** [comment]
If we had https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0026-explicit-specificity.rst, then we could do option (2) without the drawbacks. I actually advocate for doing option (2) with the drawbacks. TH users get a certain amount of breakage. This will be a smaller amount than usual, and the breakage will be in the form of a fairly-easy-to-understand kind error (`RuntimeRep /= Type`). (That is, this is easy to understand by the kinds of people who do visible type application in `Lift` instances.)

**Comment by simonpj** [comment]
> we could do option (2) without the drawbacks. I actually advocate for doing option (2) with the drawbacks.

How so, precisely?  I think you mean that the runtime-rep argument can be specified as `Inferred`, so that it never appears in a visible type application?  Or did you mean something else?

Regardless, this looks like a (good) separate proposal: use levity polymorphism to make `Lift`, and perhaps TH quotes themselves, work at unlifted types.

**Comment by goldfirere** [comment]
> How so, precisely? I think you mean that the runtime-rep argument can be specified as Inferred, so that it never appears in a visible type application? Or did you mean something else?

Yes, exactly.

**Comment by harpocrates** [comment]
I went ahead and tried to implement option (2), following what @RyanGlScott outlines in https://github.com/ghc-proposals/ghc-proposals/pull/175#issuecomment-427611846. I have a working prototype which works fine for unlifted types, but ran into some other non-trivial issues:

  1. default implementations of methods don't work (eg. `lift x = unTypeQ (liftTyped x)`), presumably since GHC would actually have to make a different `lift` method for each runtime rep
  2. writing `class Lift (t :: TYPE r) where ...`, `instance Lift Int# where ...`, etc. requires having `ghc-prim` be a dependency of `template-haskell`

Point 1 might be relevant to the original proposal here; unless there is some sort of path forward towards making 1 possible, perhaps it is better to move `lift` out of the `Lift` typeclass... Thoughts?

**Comment by RyanGlScott** [comment]
Point (2) doesn't sound too bad. `base` depends on `ghc-prim`, so `template-haskell` already depends on `ghc-prim` transitively.

I don't understand point (1). Can you provide more details on what isn't working? I would have expected something like `lift x = unTypeQ (liftTyped @r @a x)` to work (assuming that this is a default method of `class Lift (a :: TYPE r)`).

**Comment by harpocrates** [comment]
> I don't understand point (1). Can you provide more details on what isn't working? I would have expected something like `lift x = unTypeQ (liftTyped @r @t x)` to work (assuming that this is a default method of `class Lift (t :: TYPE r)`).

Here is a reduced example of the problem. Also, is there somewhere else we should move this discussion?

```haskell
{-# LANGUAGE KindSignatures, PolyKinds, RankNTypes #-}
module Foo where

import GHC.Types

class Foo (t :: TYPE r) where
  foo :: t -> t
  foo x = x

-- Foo.hs:8:7: error
--﻿      A levity-polymorphic type is not allowed here:
--       Type: t
--       Kind: TYPE r
--     In the type of binder ‘x’
--   |
-- 8 |   foo x = x
--   |       ^
```

**Comment by harpocrates** [comment]
Maybe that wasn't such a problem after all. There is somewhat satisfactory workaround using `Defaultsignatures`.

```haskell
class Lift (t :: TYPE r) where
  lift :: t -> Q Exp
  default lift :: (r ~ 'LiftedRep) => t -> Q Exp
  lift = unTypeQ . liftTyped

  liftTyped :: t -> Q (TExp t)
  default liftTyped :: (r ~ 'LiftedRep) => t -> Q (TExp t)
  liftTyped = unsafeTExpCoerce . lift
```

That means that unlifted instances of `Lift` will have more boilerplate, but that gets limited to `template-haskell`. The main unpleasantness is going to be the more complex types in the generated Haddocks.

How would folks feel about this? Unless someone voices an objection (or I find some other issue), I'm going to modify the initial proposal, since the definition of `Lift` listed above is quite different from what was initially proposed.

**Comment by goldfirere** [comment]
That definition is awfully advanced. I understand why we want it, but we'll need to document very carefully. It makes me wonder if that should be `RRLift` and keep `Lift` to be simple.

**Comment by harpocrates** [comment]
I've implemented a levity-polymorphic `TExp`, quotes, and `Lift` (along with simplifications in `DeriveLift`) in https://phabricator.haskell.org/D5220. Shall I wait until (if?) this proposal is accepted to open a new one about the levity polymorphism changes?

**Comment by harpocrates** [comment]
Could you submit this to the committee for review @nomeata? It seems everyone who has replied is in support and there are no unresolved questions.

Most of the discussion has revolved on additional enhancements we could make to `Lift`, and that discussion belongs in a separate proposal.

**Comment by harpocrates** [comment]
I was mostly concerned with backwards compatibility, but if the committee has any opinion on the matter I’d be happy to amend the proposal!

**Comment by bgamari** [comment]
I am happy to report that this proposal has been accepted by the steering committee! Thanks, @harpocrates!

**Comment by RyanGlScott** [comment]
Does this mean that this can be merged now?

**Comment by nomeata** [comment]
There was some question about which version on the mailing list:
https://mail.haskell.org/pipermail/ghc-steering-committee/2019-February/000917.html
So maybe @bgamari wanted to groom the proposal before merging?

**Comment by nomeata** [comment]
I have learned that this proposal was subsumed by #209, thus closing. Thanks @harpocrates for kicking off this discussion!

**Pull request closed without merging**
