### PR TITLE
Allow `do` etc. to be used as function arguments without a $

### PR DESCRIPTION
**Pull request by takano-akio**
This is a proposal adding a new syntactic language extension that allows `do` expression etc. to be placed directly in an argument position within an expression, without parentheses or a `$`.

[Rendered](https://github.com/takano-akio/ghc-proposals/blob/argumentdo/proposals/0000-block-arguments.rst)

### CODE REVIEW

**Comment by glaebhoerl** [comment]
Oh yes please. My own personal style conventions include "avoid `$` unless the alternative is parentheses spanning multiple lines": with this, it could be shorter.

**Comment by goldfirere** [comment]
I'm +1, and I'd like to thank you for putting together such a well-written, thorough proposal.

**Comment by Icelandjack** [comment]
+1 from me

**Comment by gridaphobe** [comment]
I think this is a great idea for `do`, but I'm less convinced about other expressions like lambdas.

> For example, `f \a -> a b` will be parsed as `f (\a -> a b)`, not as `f (\a -> a) b`.

I can see the logic behind this, and it mirrors the intuition about how `$` parses, but something about it just doesn't sit right with me. Not that I like the alternate parse tree any better. 

The expression just looks very ambiguous to me, and I think it's because there's no clear end delimiter. With `do` you can use braces or the layout rule to delimit the body, both are very clear.

**Comment by nomeata** [comment]
> The expression just looks very ambiguous to me

No more than `f g x` looks ambiguous to someone who is not used to function-application-by-juxtaposition, I’d say. Every syntax change looks strange at first. The important bit is whether the underlying rule (which needs to be learned in any case) is easy to understand and apply. And the “Stuff extends to the right as far as possible” is a simple rule that easily disambiguates this.

**Comment by andrewthad** [comment]
I am +1 on this. I agree with the note at the end of the proposal about `ArgumentDo` being is misleading name for the extension. I can't think of a better name though.

**Comment by nomeata** [comment]
Throwing out random ideas here: `LongArguments`? `BlockArguments`? `HeraldArguments`? `MoreArguments`?

**Comment by Wizek** [comment]
I like `BlockArguments` as the name. Most accurate so far.

**Comment by treeowl** [comment]
I believe the proposal should mention the fact that GHC gives `$` an impredicative type in order to avoid the need for parentheses around a `do` block used as an argument to `runST`. Do you think that hack should be removed if this proposal goes in?

My main concern about this proposal is that it doesn't *obviously* pull its weight. Yes, this should probably have been permitted from the beginning, but is it important enough to be worth the weight of an extra extension? It may well be, but I'd like to see more evidence in the proposal.

You mention the possibility of difficulties with parsing (shift/reduce conflicts). I don't know much about parsing; do you think you could expand on what practical impact that could have? Poor performance? (Even) worse parse error messages? Do you have a plan to avoid or mitigate the problem? Do you think the extension should be added if you fail to do so?

**Comment by treeowl** [comment]
You tack on the ability to apply a `do` or similar block directly to an argument, as in `do {...} x`. While this seems a legitimate thing, I don't see how it's a consequence of the rest. And there doesn't seem likely to be as much demand for it. How much extra complexity does that bit add? How much potential for errors? Is it worth it? It seems likely to be very rarely useful for `case` and `let` expressions, and occasionally for `do` expressions for `((->) a)`.

**Comment by vagarenko** [comment]
How the following would parse

````
data Foo = Foo (A -> A) (B -> B)

foo =
  Foo
    \a -> a
    \b -> b
````
?

What about

````
data Foo = Foo (M A) (M B)

foo =
  Foo
    do pure A
    do pure B
````
?

**Comment by nomeata** [comment]
Judging from the example in “Effect and Interactions”, this will parse in the expected way that leads to a type correct result, i.e. `Foo (\a -> a) (\b -> b)` and `Foo (do pure A) (do pure B)`.

**Comment by vagarenko** [comment]
But then
````
data Foo = Foo (A -> A) (B -> B)
foo =
  Foo
    \a -> a \b -> b
````
would be a type error.
So it is different from `$` operator, it is not " extends to the right as far as possible"

**Comment by nomeata** [comment]
I never wrapped my head around the layout rule enough to explain it, but the “as far as possible” is still within the layout rule, so in your first comment with separate lines, it’s the layout rule that limits how far the `do` construct reaches. In your second comment, no layout is used, so I expect it to parse unsurprisingly as
```
foo = Foo (\a -> a (\b -> b))
```

**Comment by goldfirere** [comment]
I respectfully disagree with @nomeata here.

```
Foo
  \a -> a
  \b -> b
```

would parse as `Foo (\a -> a (\b -> b))`, not what you intended. There is no layout at play here, of any sort, so the newline is ignored.

I agree that the second example would work.

**Comment by nomeata** [comment]
Oh, there is a difference between `do` and `\` here? How unfortunate.

**Comment by goldfirere** [comment]
`do` introduces layout; `\` does not. This proposal does not change either of these facts.

**Comment by yav** [comment]
I am also +1 on this.  I like `BlockArguments` for the name.  I agree that `ArgumentDo` is confusing, given that this work for other things also.

**Comment by int-index** [comment]
Now that an alternative was added to the proposal of allowing only `do` and not `\` in argument position, I want to voice my support for it.

> A problem with this alternative is that it seems hard to justify the special-casing of ```do```. Users may end up having to remember one more arbitrary rule

I don't think that's a problem because there's a property of `do` that distinguishes it — `do` introduces layout.

Furthermore, it's valid to write something like this (in today's Haskell):

```
Prelude> (do \x -> x * 2) 10
20
```

With this proposal in place, one could always use `do \` instead of `\` to use a lambda in argument position, correct?

**Comment by takano-akio** [comment]
@gridaphobe

> I think this is a great idea for do, but I'm less convinced about other expressions like lambdas.
> 
> For example, f \a -> a b will be parsed as f (\a -> a b), not as f (\a -> a) b.
> I can see the logic behind this, and it mirrors the intuition about how $ parses, but something about it just doesn't sit right with me. Not that I like the alternate parse tree any better.
> 
> The expression just looks very ambiguous to me, and I think it's because there's no clear end delimiter.  With do you can use braces or the layout rule to delimit the body, both are very clear.

Than you for your feedback. I added the possibility of only allowing `do`s in the Alternative section.

It seems a little difficult to justify special-casing `do`. Should `case` expressions be also allowed, since their end is also clearly marked? But then, is it strange that `if` is not allowed when `case` is?

FWIW, personally I'd like lambdas to be allowed, not just because it's more consistent, but also because it will be useful. The sequence `$ \` comes up a lot in my code, and I don't think `$` is adding much to the readability here.

**Comment by takano-akio** [comment]
I took the suggestion by @nomeata and others to rename the extension to `BlockArgument`.

**Comment by takano-akio** [comment]
@treeowl 

> I believe the proposal should mention the fact that GHC gives $ an impredicative type in order to avoid the need for parentheses around a do block used as an argument to runST. Do you think that hack should be removed if this proposal goes in?

I don't think merely having the `BlockArguments` extension justifies this (breaking) change. Perhaps it can be dropped (with a deprecation period) if and when `BlockArguments` is turned on by default? Even then I do not know if the benefit of removing the hack is larger than the cost of breaking user code.

> My main concern about this proposal is that it doesn't obviously pull its weight. Yes, this should probably have been permitted from the beginning, but is it important enough to be worth the weight of an extra extension? It may well be, but I'd like to see more evidence in the proposal.

Such evidence would be nice indeed, but I don't know of a good way of generating some. Perhaps I could count the number of +1's and -1's at the end of the discussion.

> You mention the possibility of difficulties with parsing (shift/reduce conflicts). I don't know much about parsing; do you think you could expand on what practical impact that could have? Poor performance? (Even) worse parse error messages?

The only problem I can think of is some maintenance overhead. If someone makes some change to the parser, and finds that the number of shift/reduce conflicts has unexpectedly increased by the change, the 
shift/reduce conflicts added by `BlockArguments` may make it more difficult to investigate the problem.

> Do you have a plan to avoid or mitigate the problem? Do you think the extension should be added if you fail to do so?

If desired, the change can be implemented in a way that adds no shift/reduce conflicts. However it would make the parsing rules significantly more involved.

> You tack on the ability to apply a do or similar block directly to an argument, as in do {...} x. While this seems a legitimate thing, I don't see how it's a consequence of the rest.

It is a consequence of treating `do` etc. in the same way as atomic expressions like a variable reference. Also, there currently is no syntactic class that's allowed in the RHS of a function application but not in the LHS. Incidentally this is how a left-associated operator usually behaves.

> And there doesn't seem likely to be as much demand for it. How much extra complexity does that bit add?

In terms of grammar, *not* allowing it would add some complexity (unless I'm missing a good way of doing this).

> How much potential for errors?

I think it will be very rare that a progam with this kind of error typechecks, because you'd need a context which accepts both types `A -> B` and `B`. However, the fact that such an error is reported by the type checker rather than the parser will make it significantly more complicated to decipher.

 > Is it worth it? It seems likely to be very rarely useful for case and let expressions, and occasionally for do expressions for ((->) a).

I'm not sure. I'm leaning towards just allowing them for simplicity, but I do see the benefit of disallowing them. I'll add this possibility under the Alternatives section.

**Comment by takano-akio** [comment]
@int-index 

> Now that an alternative was added to the proposal of allowing only do and not \ in argument position, I want to voice my support for it.
> 
> > A problem with this alternative is that it seems hard to justify the special-casing of do. Users may end up having to remember one more arbitrary rule
>
> I don't think that's a problem because there's a property of do that distinguishes it — do introduces layout.

I feel that this is not obvious enough. For example, what about `case`? It doesn't technically introduce layout (`of` does), but the end of a `case` expression is clearly marked with a layout or a `}`. Conversely, `let` does introduce a layout, but the end of a `let` expression is not explicitly marked. Also, what about `\case`?

> Furthermore, it's valid to write something like this (in today's Haskell):
>
> ```
> Prelude> (do \x -> x * 2) 10
> 20
> ```
> With this proposal in place, one could always use do \ instead of \ to use a lambda in argument position, correct?

Yes, although the layout rule may get in the way, depending on your style. For example, the following code will be valid under the current proposal:

```haskell
withForeignPtr fptr \ptr ->
  c_memcpy buf ptr size
```

You cannot simply replace the `\` with `do \` like:

```haskell
withForeignPtr fptr do \ptr ->
  c_memcpy buf ptr size
```

because the `do` block terminates at the end of the first line.

**Comment by int-index** [comment]
Alright, I'm convinced that it's better to have no special cases.

**Comment by nomeata** [comment]
I like the constructive discussion happening here! Good job everyone.

**Comment by takano-akio** [comment]
I believe that this proposal is ready for review by the committee (ping @nomeata).

Summary of the discussion so far:

* Two variants of the proposal have been suggested. They are listed under the Alternative section. They both seem like viable alternatives, but neither of them seems to have received a strong support.

* @treeowl pointed out that it is not obvious that this proposal pulls its weight. This is true, and I don't have objective evidence about usefulness of the proposed extension. However I'd like to mention that much of the feedback on this pull request (comments and emoji reactions) have been supportive.

* I believe all other major points have been incorporated into the proposal text.

**Comment by nomeata** [comment]
The proposal was meet with great enthusiasm in the committee and got accepted.

Enjoy implementing it!

**Pull request merged**
