### PR TITLE
Module Export Deprecation Pragmas

### PR DESCRIPTION
**Pull request by alanasp**
This is a proposal to add support deprecating export pragma.
Link to readable version of the proposal:
https://github.com/alanasp/ghc-proposals/blob/patch-2/proposals/deprecating_exports_proposal.rst

### CODE REVIEW

**Comment by treeowl** [comment]
Please incorporate the "two proposed designs" into the proposal text. Linking to the Trac thread (and especially the specific relevant comments) is good, but we shouldn't have to read the whole thing to know what you're talking about.

**Comment by treeowl** [comment]
I'd like to see an optional field indicating where the export has moved. If this field is present and the explanatory string is empty, we should do something sensible.

**Comment by erikd** [comment]
@chessai Just so you know, @alanasp is a GSoC student being mentored by Matthew Pickering and myself and this is part of his GSoC project.

**Comment by treeowl** [comment]
Picky details aside, I'm very much in favor. `containers` currently jumps through some mightily annoying hoops to accomplish this sort of thing.

**Comment by alanasp** [comment]
Thanks to everyone for comments. I've added both designs from the ticket and the name, hopefully, is clearer now.

**Comment by mpickering** [comment]
Looks good to me. Is this ready to be submitted to the committee @alanasp ?

**Comment by alanasp** [comment]
I hope so, as far as I checked, this should satisfy the basic ghc proposal requirements.

**Comment by mpickering** [comment]
@nomeata take it away!

**Comment by yav** [comment]
Here are a few questions, that I think should be answered by the text in the proposal:

1. Can I deprecate a `module A` export.   I think the answer to this should be no, as it is quite coarse, and `mode A` exports often times don't mean what people think they mean.
2. Can I deprecate data constructors?    For example, if a module exports `C(A)`, can I write deprecate only `A`?  If so, how would that distinguish from the type `A`?  Alternatively, if not, would writing `DEPRECATE C(A)` deprecate only `A` or both `C` and `A`?
3. Related to (2), can I write `DEPRECATE C(..)`?  More generally, does the DEPRECATE pragma expect a name, or some other construct (perhaps an export entity specification?).
4. Similarly, should it work with the ExplicitNamespaces extensions (i.e., are `DEPRECATE type A` and `DEPREACTE pattern A` ok?)
5. Would using a deprecated export in a hiding clause cause a deprecation warning?   (e.g., `import A hiding (x)` where `x` is a deprecated export of `A`)
6. I assume that the main difference between writing the deprecating pragma in the export list, as opposed to the declaration, is that sometime you may wan to deprecate the export of something declared in another module.  Is that the main motivating example?  If so, this should be added to the proposal's description.
7. How do deprecated exports interact with module re-exports?   Here is an example:

        module A( {-# DEPRACATE x #-} x) where { x = True }
        module B (module A) where { import A }

    The questions raised by this example are:
         7.1 Should we emit a deprecation warning in module B?
         7.2 Is the `x` exported from `B` deprecated or not?

**Comment by goldfirere** [comment]
I think a lot of the ambiguities @yav points out would be solved by a simple change in syntax:

```
module Data.List (
  ...
  , {-# DEPRECATED "reason" #-} lines
  , ...
  ) where
```

Note that I've removed the comma between the pragma and the export. The `DEPRECATED` pragma (I agree with @simonmar that we shouldn't unnecessarily introduce a new pragma name for this) applies to the export it sits before. This doesn't work well if there are a whole batch of exports that one wishes to deprecate, but it's unclear that the original syntax works with lists of exports, anyway.

**Comment by tejon** [comment]
With a little module shuffling, batch deprecations shouldn't be too hard either. Even in the case where deprecated things depend on non-exported members of the module, I'm pretty sure you can do it with a single indirection:

```haskell
module Foo
  ( module Foo.Internal
  , {-# DEPRECATED "reason" #-}
    module Foo.Deprecated
  ) where

import           Foo.Internal hiding (A, B, C) 
import qualified Foo.Internal as Foo.Deprecated (A, B, C)
```

**Comment by yav** [comment]
@tejon The `module Foo.Deprecated` export declaration doesn't actually export anything.

I like having the `DEPRECATED` pragma on the actual export declaration as @goldfirere fire suggests.

**Comment by alanasp** [comment]
Thank you all for comments and feedback. I think the syntax proposed by @goldfirere greatly simplifies some of the trickier use cases and answers many of the important questions raised by @yav. 

To answer the other questions:
1. Yes, I think you should be able to deprecate module re-export and it is one of the features but I am open to discussion regarding this one. 
5. Based on the basic syntax description, it would fire a warning because you are explicitly referring to the imported `x` in the `hiding(x)` syntax. 
6. Yeah, this would be one of the main use-cases. It also is kind of reflected in the example given where `lines` is supposed to be imported from `Data.String` from now on. 
7.1. I don't think that you would have a DEPRECATION warning for `B` because you are importing the whole `A` and not specifying `x` explicitly. Also, you are not referring to the imported `x` in `B` anywhere. 
7.2. I believe that because of 7.1, we have to cascade the deprecation along the import tree for you to actually get the warning whenever you refer to `x` explicitly.

**Comment by goldfirere** [comment]
I think

```
module A ( {-# DEPRECATED "blah" #-} x ) where { x = True }
module B where { import A hiding (x) }
```

should *not* emit a warning. One of the guidelines with warnings is that it should always be easy to rewrite the code to avoid the warning. But if importing `A` causes a name clash, then the `hiding` is necessary (omitting it would avoid the warning but would induce ambiguity errors). So what's the author of `B` to do? Note that hiding a declaration that's not exported leads to a *warning*, not an error. Thus, if `A` were to stop exporting `x` in the future, `B` doesn't suddenly break -- it just gets a warning. So I think that the deprecation pragma needn't bother the author of `B` in this example.

I also have a separate question: what if a module exports the same symbol more than once? While this sounds silly, it might be useful if you want to deprecate only one constructor. For example:

```
module C ( {-# DEPRECATED "blah" #-} T(K2), T(K1) ) where ...
```

An importer of `C` should be able to use `T` and `K1` without warnings but get a warning upon the use of `K2`. Here's the rule I propose: if all the ways a symbol is imported are deprecated, then you get a warning (followup question: what if there are multiple different deprecation strings?). If, on the other hand, there is an import of the symbol that's not deprecated, then there is no warning. Note that `T` is exported twice from `C` -- one with a deprecation and one without. So, according to my rule, `T` could be used without a warning.

May I suggest incorporating the rule above into the proposal? And the proposal should also address the situation of having one symbol be imported deprecated with several different deprecation strings.

**Comment by howtonotwin** [comment]
According to the current wording, if I have

```haskell
module A(x)
module B({-# DEPRECATED "foo" #-} x) where { import A }
module C where { import A; import B; oops = B.x }
```

I get no warning. In `C`, the entity referred to by the name `B.x` is imported from `A` and `B`, and `A`'s export is not deprecated.

I think the wording should be changed to be explicitly about *names*, not symbols. When an export is imported, it may get multiple names. If the export is deprecated, every name that it is imported as is "tainted." If an export is not deprecated, then every name it is imported as is "clean." Cleanliness overrides taint. Usage of a tainted name within the body of the importing module prints (which?) deprecation messages.

In the above, in `C`, this means that the name `A.x` is clean, because the export is not deprecated. The name `x` is tainted by `B` and cleaned by `A`, so it also causes no deprecation messages. The name `B.x` is tainted by `B` and will trigger the message.

**Comment by nomeata** [comment]
alanasp, do you keep tabs on all the refinements suggested here, and either integrate them into the proposal, or discuss them here? There is valuable feedback here that we must not lose.

**Comment by alanasp** [comment]
@nomeata Yeah, I am trying to keep track of the suggestions and to reflect them in my proposal. 

@howtonotwin Thanks, that's a good remark, modified the proposal to reflect this. 

@simonmar @goldfirere Thanks, I have added this rule to the proposal, it might be a bit trickier to get the exact implementation right, so I might get back to you once I'm at that stage to consult for some finer details.

**Comment by alanasp** [comment]
@nomeata Do you or anyone else have any other suggestions regarding the proposal?

**Comment by goldfirere** [comment]
I'm still not quite happy here, with two potential problems:

* The proposal now addresses what happens if one export list deprecates the same symbol with multiple messages, but it does not address if a module imports the same symbol with multiple messages (and then uses it). For example:

```
module A ( {-# DEPRECATED "x" #-} head ) where {}
module B ( {-# DEPRECATED "y" #-} head ) where {}
module C where
  import A
  import B
  import Prelude hiding ( head )  -- to force head to be deprecated

  f = head
```

What gets printed? I don't much care what the answer is, but I do want this in the specification.

* Given the syntax for exporting constructors, it seems useful to have multiple deprecation messages attached to one identifier. For example:

```
module A
  ( {-# DEPRECATED "Don't use C, use X instead." #-} T(C)
  , {-# DEPRECATED "Don't use D, use Y instead." #-} T(D)
  , {-# DEPRECATED "Don't use T, use Z instead." #-} T
  ) where ...
```

According to the current proposal, this would be in error. An existing workaround is to use `pattern C` and `pattern D` to export those constructors (the `pattern` namespace specifier works for ordinary constructors, too), but that seems unfortunate, somehow. Is there a better design available?

**Comment by alanasp** [comment]
@goldfirere 
1. Thanks for the spot. Yes, this is still not reflected in the proposal mostly because I haven't yet got to the point where I have to code up this ambiguity. There are a few options here. If a symbol is imported under multiple names all of which are deprecated either a single warning of first/last/arbitrary import would appear or, alternatively, all the warnings could be shown. I think this could go either way and maybe you or someone else could suggest which option they prefer. I would lean towards the option of displaying only one warning and making no guarantees on which message will be picked.

2. It seems that there is some difference in suggestions by you and @simonmar both of which raise valid points on the issue of separate constructor exports. From what you propose, I feel it might pose some implementation challenges to get it done right. For example, whether the duplicate export warning should be suppressed in this case. However, I will make sure to take a look at this and in case it's doable, I will aim to support different warning messages. 

I hope we can resolve these questions soon

**Comment by goldfirere** [comment]
It seems to me that, in case (1), we should print all the messages. After all, if many libraries are re-exporting and all of them plan on not re-exporting, the importing module should be informed about each one. But I'm not at all sold on that idea and would be happy to have a different (specified) behavior.

I don't know anything about the implementation issues here...

**Comment by nomeata** [comment]
1. I find the corner case (1) (multiple warnings) cornerish enough that I don’t need it in the spec, and am happy to let the implementors pick what makes most sense, and revise that based on practice. We generally do not specify the precise form and content of warnings in proposals, and it should suffice if the specification indicates which code causes some warning and which code causes no warning.

2. > According to the current proposal, this would be in error. An existing workaround is to use pattern C and pattern D to export those constructors (the pattern namespace specifier works for ordinary constructors, too), but that seems unfortunate, somehow.

    I don’t find it unfortunate, as I expect explicit name space quantifiers to start showing up in more and more places in GHC Haskell anyways.

**Comment by yav** [comment]
One thing to consider is that the export qualifier `pattern` only works with `PatternSynonyms`, and not with `ExplicitNamespaces`, even if what's being exported is a constructor, not a defined pattern.   Perhaps this is something we should address separately though.

**Comment by nomeata** [comment]
> the export qualifier `pattern` only works with `PatternSynonyms`, and not with `ExplicitNamespaces`

oh, I would consider that a bug that we can fix (maybe even without the proposal process)

**Comment by alanasp** [comment]
Thanks for the suggestions. 
As an aside, is it a bug or a feature that a deprecation warning is not shown whenever a deprecated entity appears in an import list explicitly? I am using the main deprecation mechanism for the export deprecation feature and, in my opinion, the functionality should match up. So, I can either fix the mechanism to have deprecations (whether export or not) arise from explicit imports or remove this behaviour from the proposal.

**Comment by nomeata** [comment]
> As an aside, is it a bug or a feature that a deprecation warning is not shown whenever a deprecated entity appears in an import list explicitly?

Well spotted! I agree that it could be argued that explicitly importing a symbol marked as `DEPRECATED` should cause a warning, as would any other use of that symbol in the file – after all, the code will break once the `DEPRECATED` thing disappears.

**Comment by alanasp** [comment]
In that case, since I am using the main deprecation mechanism, I will add this functionality

**Comment by nomeata** [comment]
Accepted, with the understanding that some corner cases (e.g. the second point of https://github.com/ghc-proposals/ghc-proposals/pull/134#issuecomment-399726779) will be resolved during implementation.

**Comment by alanasp** [comment]
@goldfirere @nomeata @simonmar  I am at the point where I would like to resolve the second point of @goldfirere [comment](https://github.com/ghc-proposals/ghc-proposals/pull/134#issuecomment-399726779). Generally, the features mentioned in the proposal are already working. However, regarding this point I have come to think that neither the error, nor the separate message support would be the best option. The error seems rather excessive, given the fact that, in your example, I would already get "multiple export" warnings for symbol T. Perhaps, a different type of warning that the messages differ would be appropriate.
As it currently stands, my implementation emits the last message whenever any constructor of a deprecated type is used in an importing module. This is similar to the way that if the symbol is imported from multiple modules, no warning/error is given: it is automatically resolved to be imported from the last import statement (I have actually changed this behaviour in my implementation to bring it in line with the proposal). Furthermore, the export deprecation is supposed to attach to the top level export, so allowing different messages would introduce ambiguities such as which deprecation message (if any) applies to the type constructor (T in your example). Given this, patterns seem like the most sensible workaround but it would be great to hear what you think of this.

**Pull request merged**
