### PR TITLE
Update levity polymorphism

### PR DESCRIPTION
**Pull request by goldfirere**
This proposal presents a simplification of the system described in Simon and my draft paper on the subject. This simplification is slightly less expressive but much simpler.

[Rendered](https://github.com/goldfirere/ghc-proposals/blob/patch-2/proposals/0000-levity-polymorphism.rst)

### CODE REVIEW

**Comment by cartazio** [comment]
Question: how is this less expressive than the formulation in the paper? http://cs.brynmawr.edu/~rae/papers/2017/levity/levity.pdf ?

**Comment by goldfirere** [comment]
See the [Alternatives](https://github.com/goldfirere/ghc-proposals/blob/patch-2/proposals/0000-levity-polymorphism.rst#alternatives) section of the proposal for an example. I doubt this will bite.

**Comment by simonpj** [comment]
I'm very keen on this proposal

**Comment by cartazio** [comment]
So I think you're saying that the alternative rep gives the proper
equivalence class for a given calling convention?  And the version in this
proposal distinguishes syntactically different expressions that have the
same runtime rep?

What is an example of the difference in error message quality /
implementation complexity / end user expressivity?

Would I be able to recover those equalences with a carefully constructed
closed type family and careful use of unsafe coerce?

**Comment by goldfirere** [comment]
Yes, that's about right. This proposal makes more distinctions than is necessary.

Error message quality: I imagine that the existing proposal will lead to better error messages, because it's less expressive. I have not tested this though.

Implementation complexity: The proposed version is significantly simpler to implement. The alternative version requires implementing and wiring in a type-level `Concat`, as well as various other machinations.

End-user expressivity: This example appears in the proposal.

Yes, I believe you would be able to mimic the equivalences with a just-right `unsafeCoerce`.

**Comment by RyanGlScott** [comment]
I get `TupleRep`, but how do you interpret the parameters of `SumRep`? Do those represent the representations of the unboxed sum after it's translated to an unboxed tuple behind the scenes? If so, would a user be able to reliably use code that is parametric over `SumRep` (since GHC could, in theory, change the details of how unboxed sums are desugared down to unboxed tuples from version to version)?

Also, what becomes of `VoidRep`? Is it replaced by `TupleRep '[]`/`SumRep '[]`/something else now?

**Comment by Icelandjack** [comment]
The names are an improvement

**Comment by RyanGlScott** [comment]
Also, does this proposal supersede [GHC Trac #12809](https://ghc.haskell.org/trac/ghc/ticket/12809), which proposes a levity polymorphism scheme analogous to what you've laid out in the [Alternatives](https://github.com/goldfirere/ghc-proposals/blob/patch-2/proposals/0000-levity-polymorphism.rst#alternatives) section?

**Comment by goldfirere** [comment]
`SumRep` is simpler than you think: the list contains the reps for the disjuncts. So `(# Int# | (# Float#, Int#, Int #) | Int# #)` has kind `TYPE (SumRep [IntRep, TupleRep [FloatRep, IntRep, LiftedRep], IntRep])` even though this type gets packed into a different representation.

**Comment by cartazio** [comment]
I dont quite see how the concat is necessarily a complexity point... if only because ... I think that by the time you get to core you can't have any quantifying over levity in any code (generally? except it certain negative position spots?)

@goldfirere it sounds like levity polymorphism skirts into expressing exactly the static argument / compile time literal interfaces idea we spoke about 2 years ago at hac boston, where I want to be able to guarantee that any well typed core would  not have any  `( /\x:StaticValue -> bod )` terms, and it seems like theres a similar idea here https://ghc.haskell.org/trac/ghc/ticket/8107 (which i never quite fleshed out clearly )

**Comment by RyanGlScott** [comment]
@goldfirere, thanks for the explanation about `SumRep`. That makes a lot more sense than what I originally envisioned.

Any thoughts about `VoidRep` or [GHC Trac #12809](https://ghc.haskell.org/trac/ghc/ticket/12809)?

**Comment by RyanGlScott** [comment]
I just found https://git.haskell.org/ghc.git/commitdiff/089b085d9660d029663126148665b468809278d7... It looks like the plan is to [keep `VoidRep`](https://git.haskell.org/ghc.git/commitdiff/089b085d9660d029663126148665b468809278d7#patch28) as a distinct representation.

**Comment by osa1** [comment]
Why do we want a `VoidRep`? In `RepType` (mostly used in unarise and stg-to-cmm passes) we use `MultiRep []` for void types:

```haskell
data RepType
  = MultiRep [SlotTy]     -- Represented by multiple values (e.g. unboxed tuple or sum)
  | UnaryRep NvUnaryType  -- Represented by a single value; but never Void#, or any
                          -- other zero-width type (isVoidTy)
```

Having `VoidRep` means we will have more than one voids: `VoidRep` and `TupleRep []` and we need to check for both when we check for void-ness.

**Comment by goldfirere** [comment]
Yes, `VoidRep` is now `TupleRep []`. `SumRep []` and `SumRep [oneElement]` are valid kinds, but no type has these kinds, because all sums have at least two disjuncts.

Yes, this proposal supersedes #12809.

**Comment by goldfirere** [comment]
I believe this proposal is ready for review.

Summary of discussion:
 - @cartazio raises a concern about quality of error messages. I believe that the current proposal, as it is less expressive than what is in the [levity polymorphism](http://cs.brynmawr.edu/~rae/papers/2017/levity/levity.pdf) draft paper, will have better error messages.
 - @cartazio suggests that this proposal is similar to [#8107](https://ghc.haskell.org/trac/ghc/ticket/8107). While I agree that there seems to be a similar smell to them, I don't believe that this proposal is affected by that ticket.
 - I have clarified that this proposal supersedes the plan in [#12809](https://ghc.haskell.org/trac/ghc/ticket/12809).

The rest of discussion is question and answer. Simon PJ has expressed his support, as have 4 others. 2 contributors have specifically agreed that getting rid of `VoidRep` is an improvement. No posts argue against this proposal.

**Comment by RyanGlScott** [comment]
I'm confused the current state of this (and more generally, what it takes to conclude a proposal), since @goldfirere has already pushed [the commit to GHC](https://github.com/ghc/ghc/commit/e7985ed23ddc68b6a2e4af753578dc1d9e8ab4c9) which implements the ideas in this proposal. What happens now?

**Comment by nomeata** [comment]
@RyanGlScott Good point. I tried to amend policy for that case; please discuss that policy in #39.

**Comment by bgamari** [comment]
I am happy to report that the steering committee has accepted this proposal. Thanks for your effort, @goldfirere!

**Comment by Icelandjack** [comment]
> Yes, `VoidRep` is now `TupleRep []`. `SumRep []` and `SumRep [oneElement]` are valid kinds, but no type has these kinds, because all sums have at least two disjuncts.

Why isn't this codified in the type?

```haskell
  | SumRep RuntimeRep RuntimeRep [RuntimeRep]
```

**Comment by goldfirere** [comment]
Your new `SumRep` is perhaps more accurate than what's implemented, but what will be in 8.2 is simpler and the extra expressiveness causes no harm. The kinds `TYPE (SumRep '[])` and `TYPE (SumRep '[_])` are simply uninhabited.

**Pull request merged**
