### PR TITLE
Allow signatures on pattern synonym constructors

### PR DESCRIPTION
**Pull request by treeowl**
* Allow type signatures on the construction functions of
bidirectional pattern synonyms.

* Change the way construction functions are typechecked when
they lack signatures.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/559df2865db8e4427b1f24d3100e59d61cb60e54/proposals/0000-bidir-constr-sigs.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
Better :-)

**Comment by goldfirere** [comment]
Sadly, this plan would violate the three-release policy. All current explicitly bidirectional pattern synonyms would induce no-type-signature warnings, and there is no backward-compatible way to eliminate the warning. To avoid this problem, I think there should be a new warning flag to control whether or not to warn on missing signatures in explicitly bidirectional pattern synonyms, having that warning be off by default (but enabled by `-Wcompat`) and then we can merge it with `-Wmissing-signatures` in a few years. I'll admit not liking this policy much, but it seems that the community wants this behavior.

Otherwise, 👍 from me.

**Comment by treeowl** [comment]
@goldfirere I'm not too worried about specific warning behavior. But I would love to hear what you think about the variants I described. Specifically:

1. If the signature is omitted, should it default to plain old type inference like anywhere else, or to the pattern signature with a hole for the constraint? I think we should decide this now.

2. Do you think it would be reasonable to use `...` (or some other syntax) to copy the non-constraint part of the pattern signature (textually) into the constructor signature? I think this could be a great convenience, but it's another syntactic construct to think about. It would be nice if we decided this now, but it could also wait indefinitely.

**Comment by treeowl** [comment]
@goldfirere, I guess I should probably have added one more alternative: to default to the *provided* constraints, ignoring the *required* ones. I think that's somewhat more likely to be correct, although it still strikes me as too arbitrary.

**Comment by nomeata** [comment]
> I guess I should probably have added one more alternative: to default to the provided constraints, ignoring the required ones.

Without thinking it through: Is that alternative correct when the RHS of the constructor consists only of “real” constructors (possibly nestedly) applied to the parameters of the pattern synonym? If so, this is not so arbitrary any more.

**Comment by treeowl** [comment]
@nomeata, I think that's probably correct, and that's the idea I had in mind. Constraints in the types of the data constructors should (I believe) translate directly to the "provides" constraints of the pattern and also to constraints on the construction function. Maybe that's the right way to go.

**Comment by treeowl** [comment]
@nomeata, actually, I think a slight refinement of that is even better: default to the "provides" constraints plus a constraint hole. That will probably catch the vast majority of likely use cases.

**Comment by goldfirere** [comment]
I'm disinclined to add holes to the mix. Having a hole drastically changes the internal process GHC follows when type checking, and I'm worried about unexpected interactions. Dumb and predictable is better than smart and capricious.

**Comment by treeowl** [comment]
@goldfirere, personally, I'd be reasonably satisfied with *any* of the three choices I outlined. I mostly want to get the signatures, so I'd be happy to defer to your judgement with regard to the defaults.

**Comment by mpickering** [comment]
I think that the points in #8581 should be more clearly addressed. It also seems that this proposal diverges from the latest discussion on that ticket.

Firstly, it is not clear what you mean by Gergo's suggestion. The ticket was originally about bidirectional pattern synonyms but then later on the discussion moved onto this issue which is why the topic title and suggestion were changed. It is distracting to attribute a proposal to anyone.

> Unfortunately, it seems somewhat less attention was paid to the typing need of this element.

The two examples you provide are indeed two limitations of the current design.
The current behaviour is not "wrong", it is a design decision which could have been different. The implementation is less expressive than you desire but there is motivation as noted on #8581.

If you don't require that the builder has the union of the required and provided constraints then there is no guarantee that you can match on a value which is created by the builder. How liberal you want this requirement to be boils down to what equations you want to hold and what programs you want to be able to typecheck. In your proposal it seems that you do not expect

```
case P c of
    P c -> ...
```

to always typecheck. From my perspective this is not desirable as pattern synonyms should behave a lot like data constructors. A data constructor constructs a value which can then be deconstructed by the same punned name, pattern synonyms should behave in a similar manner. 

If there is now no requirement for the two halves of a pattern synonym to be related at all, why are they still defined in one syntactic construct? If there is meant to be no semantic connection between the two then it would be a clearer proposal to allow normal identifiers to be defined with upper case letters (such as is possible in Agda and Idris). This seems to be the direction that #8581 was heading in.

The argument that, "only experts use pattern synonyms" is not sufficient to make a confusing but powerful feature. Users should be able to use pattern synonyms like data constructors, clever library authors creating "one-way" patterns has the potential to be quite confusing for a user who thinks they are using a data constructor. 


Last time I looked at the implementation it was quite difficult to separate the type of the builder from the type of the matcher.

Matchers can be used in the definition of builders so we must ensure that the matchers are type checked first before the builders. See `Note [Pattern synonym builders don't yield dependencies]`. Usually this dependency is ensured by doing a free-variable analysis of bindings and generating SCCs, this is not as easy for pattern synonyms as there is no syntactic distinction made between `P` used in an expression or pattern context. 
The implementation would have to create different data types to mark the different dependencies, independently typecheck the matcher/builder and then finally recombine them all together to form the pattern synonym. 
Whilst not insurmountable, this refactoring suggests that this kind of behaviour is not how the rest of the language works! You can see some of this complexity in `tcValBinds` and `mkPatSynBuilderId`. Gergo also describes some of this complexity on #8518.

I don't think this is straightforward and I don't think #8581 suggest this is straightforward so some more discussion about these issues would be useful in the proposal.

**Comment by nomeata** [comment]
This proposal has not attracted discussion for a while. Please consider submitting it to the Committee for discussion, if you think it is ready, or close it, if you have abandoned this proposal.

**Comment by treeowl** [comment]
@nomeata, I'm still hoping for one or two (specific) people to comment on this; they haven't had a chance to get around to that yet.

**Comment by simonpj** [comment]
1.  Unlike Matthew, I think that in principle this proposal is fine.  It addresses a clear compromise in the original design. It'll be a bit of work to implement but not huge.

2.  For the case where no signature for the builder is provided, I like "default to the "provides" constraints".  That seems like a good default to me.

3.  Let's NOT involve holes of any kind.  They are surprisingly complicated.

4.  A question not addressed by the proposal is this: what does a client (who does not care about the implementation) need to know about the pattern synonym in order to use it?  Previously: its name and its type.  With this proposal: its name, it matcher-type and its builder-type.   That's a significant change, and perhaps the biggest cost of the proposal.

This shows up when you want to implement `:info` in GHCI... what should you show?  Also I suppose what happens with Backpack; how would you describe the API of the pattern synonym?

**Comment by treeowl** [comment]
@simonpj, the story behind your question 4 is much nicer for my earlier version of this proposal, #41 (Add constructor synonyms), which I have just reopened. In that proposal, pattern synonyms and what I'm calling "constructor synonyms" get independent, top-level declarations. So `:i Foo` would tell you

```haskell
pattern Foo :: ...
constructor Foo :: ...
```

**Comment by goldfirere** [comment]
Currently, a user of a pattern synonym needs more than its name and its type. That client also needs the synonym's directionality, in violation of the "typing principle" of the Pattern Synonyms paper. `:info` does not print out directionality currently, which could legitimately be called a bug.

**Comment by bitemyapp** [comment]
This proposal can be accepted and merged with the following modifications to the proposal:

- The modifications should not change the behavior of existing pattern synonyms that have not specified a type signature.

- The proposal doesn't address the relationship between signatures of the constructor and the signature of the pattern. The options discussed in order of most conservative to least were:
  * May not differ in anything but the constraints.
  * Must have the same return type.
  * Must have the same outer type constructor in their return type.
  * No relation.

The committee chose the first, most restricted, variant to follow the principle of least surprise. If there's a strong belief that the looser relationships may be useful, those can be described in a new proposal.

If you have no objections and you can make the modifications to the proposal document, we'll get this merged. Please let me know if you have any questions! Thank you for this proposal and for your patience.

**Comment by treeowl** [comment]
While I do have a strong belief that looser conditions would be preferable,
I will make the requested modifications. A somewhat concrete example of
looser restrictions:

pattern Foo :: F T -> Thing where
    Foo :: (forall s. F s) -> Thing

I'll open a new proposal for that.

**Comment by nomeata** [comment]
@treeowl, ping me when you updated the proposal and I will do the merge (which includes assigning a number and other boring stuff)

**Comment by treeowl** [comment]
@nomeata, please go ahead and merge.

**Comment by nomeata** [comment]
Merged as 07efbecb2181b1759fe3fa18f3d40c9a2d00ad9c.

**Comment by nomeata** [comment]
For the record, there is some follow-up discussion at https://mail.haskell.org/pipermail/ghc-steering-committee/2017-May/000142.html

**Comment by goldfirere** [comment]
What happens once a proposal is merged. I understand that a Trac ticket should be opened, but who is responsible for this? Is there a Trac ticket for this proposal?

**Comment by nomeata** [comment]
That part of the process is underspecified (which is not necessarily a problem). I think it would be reasonable for either the proposer or whoever plans to implement the proposal to create a ticket.

In fact, without anyone planning to do the work, opening a ticket will not be very useful.

**Comment by goldfirere** [comment]
I disagree on that last point: without a ticket, this proposal gets lost. Right now, someone looking at the merged proposals (that is, `master`) can't tell which proposals have been implemented and which haven't. Furthermore, once a proposal is accepted, I see that proposal's content as an extension of GHC's specification. If GHC's behavior doesn't meet that specification, it's a bug that should be reported in Trac.

As for the process, I think we should suggest that the proposer make the Trac ticket, but of course someone else can get there first. I will do it this afternoon for this ticket, but I'm timing out at the moment.

**Comment by treeowl** [comment]
I'll do it today.

**Comment by simonpj** [comment]
Questions about the specification: what does `:info` say in GHCi? Now it (sometimes) has to report two types, one for the pattern and one for the constructor.  Please specify!

Similarly, in a hs-boot file what do you say?  And in a Backpack hsig file?

**Comment by treeowl** [comment]
@simonpj I've submitted PR #101 to address your questions. I don't think we've reached the question of Backpack yet, as it doesn't seem to support pattern synonyms at all. The interaction with `hs-boot` files is currently undocumented. That said, I suspect my answer to the `:info` question will probably suffice for those as well, whenever the time is right.

**Comment by treeowl** [comment]
@simonpj, @ezyang pointed me to Trac 14478, so I think I've got that sorted.

**Pull request closed without merging**
