### PR TITLE
Add call stack suppression

### PR DESCRIPTION
**Pull request by treeowl**
Suppress adding a `CallStack` frame.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/call-stack-suppression/proposals/0000-call-stack-suppression.rst)

### CODE REVIEW

**Comment by treeowl** [comment]
It's almost done. I don't really foresee a lot of interactions or complications.

**Comment by treeowl** [comment]
I just thought of something that might be a tolerable alternative. We could add another constructor to `CallStack`:

```haskell
  | Skip CallStack
```

with `pushCallStack (Skip cs) = cs`. I think we'd probably be able to eliminate the extra frame that way.

**Comment by treeowl** [comment]
No, I don't think the workaround really works. It would force `pushCallStack` to look a couple frames up, which seems like it would be dreadful for performance. It would also be confusing as all get-out.

**Comment by treeowl** [comment]
@bgamari, I finished up the proposal text.

**Comment by treeowl** [comment]
Oh, that was weird.... my last change didn't make it into the branch properly. GitHub has been acting up a bit. @bgamari, it should *actually* be done now. @nomeata, how long do you think I should wait for comments before submitting? This one seems pretty minimal.

**Comment by nomeata** [comment]
Give it a week or so. Also, if you know of anyone who likely has a valuable contribution to make, maybe ping them and ask them to comment here?

**Comment by simonpj** [comment]
The proposal as stated is really hard to understand.  

First, it's a delta from an un-specified baseline.  That's not your fault, but I think it'd be a real help to write down the (fairly simple) specification of the current feature.  It is here: https://ghc.haskell.org/trac/ghc/wiki/ExplicitCallStack/ImplicitLocations; but the text is old, and it's not really a spec, more of a discussion.  I'm not sure it's 100% up to date.

Interestingly, it proposes precisely the same primitive as you do: see `setCallStack`.

Second, you don't explain how the primitive you suggest solves the problem.

**Comment by gridaphobe** [comment]
I like the idea in the linked trac ticket to add user-provided notes to callstacks!

The issue with the additional stack frame for `val` is irritating, and it might be nice to have your magic `callWithStack` function regardless, but I'm actually not convinced it's necessary for your usecase.

IIRC, the only sanctioned way for users to interact with `CallStack`s is to use `getCallStack` to extract a list of frames (ie `[(String, SrcLoc)]`). If that's still true, then your alternative `Skip` idea should be quite simple, we just have to make `getCallStack` a bit more clever. I think something like the following would work.

```
getCallStack :: CallStack -> [([Char], SrcLoc)]
getCallStack stk = case stk of
  EmptyCallStack            -> []
  PushCallStack _ _ stk'@(MessageCallStack _ _) -> getCallStack stk'
  MessageCallStack msg stk' -> {- add msg with whatever logic you had planned -}
  PushCallStack fn loc stk' -> (fn,loc) : getCallStack stk'
  FreezeCallStack stk'      -> getCallStack stk'
```

The point is that your `messageCS` function should be the only source of `MessageCallStack` frames, and we know that each of those frame will be **immediately** followed by a spurious `PushCallStack`, so `getCallStack` will just discard them.

**Comment by winterland1989** [comment]
I'm against this proposal, because there's simply no way to control library author to not abuse it.

The solo purpose of `CallStack` is to help debugging when exceptions are thrown, and *every* call in the stack should not be considered noise, even a helper like your proposed, otherwise library authors may abuse this function to \*clean up\* their code's call stack, which is dangerous because the hidden stack may contain real bugs, and lead to hard debugging times.

Most of the runtime generate callstacks automatically these days, user are not allowed to modify at all, and i strongly suggest we should follow this convention, even sometime we will bring some noise into the callstacks, we should stay on the safer side.

**Comment by nomeata** [comment]
@treeowl you got some feedback here. Do you want to pick this up?

**Comment by llelf** [comment]
I'm strongly against this proposal and agree with everything @winterland1989 said.

Callstacks are debugging aid and *deliberately hiding things* from appearing there… this sounds like a bad joke.
As for “adding notes”, they have much more sense in tracing, not call stacks.

**Comment by nomeata** [comment]
Inactive for many months, marking as dormant.

**Comment by nomeata** [comment]
Closing this due to inactivity, but it can be reopened when necessary.

**Pull request closed without merging**
