### PR TITLE
Improve IEEE float decimal processing

### PR DESCRIPTION
**Pull request by winterland1989**
[Rendered proposal](https://github.com/winterland1989/ghc-proposals/blob/master/proposals/0000-improve-ieee-float-decimal-processing.rst)

### CODE REVIEW

**Comment by cartazio** [comment]
I like the goal of this ... 

1) what does round do? Looks like it'd be a noop, because should have some additional info about number of bits of precision in significand and mantissa.  And that's ignoring that there's like 4+ ieee rounding modes. 

On the rendering side, have you seen the algorithmic that ranjit et al presented at popl 2016?

**Comment by winterland1989** [comment]
> what does round do? Looks like it'd be a noop, because should have some additional info about number of bits of precision in significand and mantissa. And that's ignoring that there's like 4+ ieee rounding modes.

Good question, I should use `round half to even` to be more explict about rouding mode. This is also the current rounding mode `round` use. I expected `roundFloat 1.2 == 1.0` so it's not an noop of course.

> On the rendering side, have you seen the algorithmic that ranjit et al presented at popl 2016?

Yes, but it turned out they did a [false benchmark](https://github.com/marcandrysco/Errol). We should use Grisu3.

**Comment by siddhanathan** [comment]
[This article by BOS](http://www.serpentine.com/blog/2011/06/29/here-be-dragons-advances-in-problems-you-didnt-even-know-you-had/) does a good job at explaining the motivation behind this PR.

**Comment by cartazio** [comment]
i'm still confused about what round is supposed to do...

**Comment by winterland1989** [comment]
@cartazio I have updated the comment of `roundFloat` function in the proposal, is it clear now to you?

**Comment by cartazio** [comment]
Oh. Rounding to nearest integer.  


Zooming out: what's the problem  we are trying to solve in base libraries here?

**Comment by winterland1989** [comment]
Currently in `base` we have `round :: (Integral b, RealFrac a) => a -> b` which force us return result as an `Integral`, but this makes all IEEE Float algorithms using round became inefficient because we have to convert these `Integral` back and forth.

We can't really change `round`,  since `Double/Float` are not the only instances in `RealFrac`, but we can add a special rounding method for `RealFloat` since it's intended for deal with IEEE float, we can even expose round mode to user if there's a need.

**Comment by cartazio** [comment]
One possible near term thing:: maybe this would make sense to add to the ieee754 package.  It looks like @patperry (i think that's his handle or @patrickperry? ) has resumed maintaining that and it has a nice type class just for ieee floats and friends

**Comment by alexanderkjeldaas** [comment]
`decodeFloatDecimal` returns `[Word8]`, but isn't there a bounded length to this list?  As long as this bound is reasonable and the list representation has something like a 30x(?)-ish overhead, the representation seems suboptimal.  The output would never be lazy, would it?  How about using a `ByteString`, `Array` or `Data.Vector`?

**Comment by winterland1989** [comment]
@alexanderkjeldaas Sadly there is no proper compact representation in base now.

**Comment by winterland1989** [comment]
I also would like to hear @patperry 's thought on this proposal, it's better to have complete IEEE float processing tools in `base` IMHO.

I don't know if this proposal is too urgent for 8.2 release, if that's the case i will modify the plan.

**Comment by cartazio** [comment]
The 8.2 merge window already closed.  So in some respects showcasing this
proposal as a type class with all the suitable definitions already written
might help

**Comment by patperry** [comment]
I don't have s strong opinion either way regarding whether this should be part of base.

In the near-term, I'm happy to add this to ieee754 if you send me a pull request.

**Comment by patperry** [comment]
(I'm also happy if you want to fork/take over the ieee754 package yourself--I don't really have time to actively maintain it. You may want to make some major changes to the typeclass, which I wouldn't object to as long as you retain the functionality. Just make sure you give the package authors and contributors appropriate credit.)

**Comment by winterland1989** [comment]
@patperry I'm happy to take over the ieee754 package ; ), please add me to the maintainers.

I have updated the proposal implementation plan, let me start improving IEEE float situation by improving ieee754 first.

**Comment by patperry** [comment]
@winterland1989 sounds like a great plan. Please go ahead and fork https://github.com/patperry/hs-ieee754 , then add the functionality. I'll look over your changes, and give you feedback (likely pretty minimal). If you can address the feedback, then I'll add you as a maintainer.

I'm really glad that you're taking the initiative to improve the float situation, and I look forward to seeing your changes.

**Comment by gridaphobe** [comment]
> > On the rendering side, have you seen the algorithmic that ranjit et al presented at popl 2016?

> Yes, but it turned out they did a false benchmark. We should use Grisu3.

I just asked my labmate about this (he's the author), and he says that since the initial publication he's been able to improve performance to within 10% of Grisu3. Furthermore, someone sent him a patch that supposedly **beats** Grisu3 by 5%. He's working on incorporating the patch, so it might be worth investigating further. Especially given that his approach doesn't rely on a backup rendering algorithm, sounds like a nice code simplification.

**Comment by minad** [comment]
@winterland1989 @patperry Most of the relevant floating point operations are already here it seems https://github.com/ekmett/numeric-extras/blob/master/Numeric/Extras.hs

**Comment by winterland1989** [comment]
Yep, one of this proposal's goals is to bring operations which standard c lib already provided. But I'm not sure if we can directly import them from `math.h` since ghc is supposed to support many architectures , maybe someone worked for ghc cross architectures can show some light here?

**Comment by alexanderkjeldaas** [comment]
Maybe this is off-topic, but if everybody is in agreement that APIs using `String` is bad, but it has to be used because nothing else is in `base`, then shouldn't there be some future-proof way out of this situation?

For example a typeclass representing alternative future String implementations, or naming the function with some suffix like `getFoobarAsString`.

I guess this isn't as much a comment on this particular proposal as a question of how `base` should prepare for a better `String` at some point in the future.

**Comment by cartazio** [comment]
off topic and shouldn't be discussed on this proposal

**Comment by nomeata** [comment]
I get the impression that this is not really a GHC proposal, but rather a base library proposal, in which case it should be submitted to the Core Library Committee as described in https://wiki.haskell.org/Library_submissions.

The proposal says that this code will be developed in a separate library first. This is a good approach! Adoption of such a library will be a strong argument in favor of accepting this proposal.

**Comment by nomeata** [comment]
Since nobody disagrees with my previous post, I am closing this as Out-Of-Scope. But please do pursue the problem, probably by implementing the library, getting users, and turning it into a library submission.

**Comment by winterland1989** [comment]
Yes please, I'll come back to this when i get time ; )

**Pull request closed without merging**
