### PR TITLE
An API for deciding whether plugins should cause recompilation

### PR DESCRIPTION
**Pull request by mpickering**
I submit to the committee a proposal for how the plugins API should be extended in order for
plugins to not cause spurious recompilation. 

[Rendered](https://github.com/mpickering/ghc-proposals/blob/bb7585ef0c565f2b4aec8e4e8677674bacc22788/proposals/0000-plugin-recompilation.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
A core plugin has presumably access to definitions in the environment that can change without usually triggering a module recompilation (e.g. some imported module adds a new function that is not used by the current module).

If the plugin for some reason looks at such information, would it have to declare itself as impure?

If so, does that imply that the plugin author has to anticipate all of the GHC’s recompilation avoidance machinery, to know what part of its input *definitely* would cause a module recompilation on its own?

Or, I guess, you just have to throw everything that you touch in any way into the fingerprint… guess that works.

**Comment by Ericson2314** [comment]
http://blog.ezyang.com/2015/12/the-convergence-of-compilers-build-systems-and-package-managers/ I rather build a system for nix-style caching of pure functions than though down the explicit-invalidation wormhole, but hey! this is fine as a stop-gap.

**Comment by mpickering** [comment]
OK, but I don't really see what that has to do with this proposal?

**Comment by bgamari** [comment]
Thank you for doing this, @mpickering!

In general I wonder whether this shouldn't rather be done on a per-plugin-type basis. For instance, perhaps each plugin hook should return a `Fingerprint` in addition to its result. This would break the plugin interface, but in exchange we would potentially reduce duplicated work (since the plugin could potentially compute its hash as it evaluates its result) and allow ourselves to potentially provide finer-grained recompilation avoidance in the future.

> a plugin P is pure iff for a modules M and N with fingerprints F(M) and F(N), F(M) = F(N) => P(F(M)) = P(F(N)).

I think it would be good to make this explicit in the proposal.

@Ericson2314, while having a more general mechanism for tracking recompilation throughout the compilation pipeline is a nice goal, I think we probably don't want to open that can of worms at this juncture. Moreover, it's not clear to me that we would want to pay the cost of doing ubiquitous input hashing. I think the current proposal puts forth a simple yet sufficiently general interface that we could likely fit it into a more general model if one arose in the future.

**Comment by simonpj** [comment]
In general this looks like a good idea to me.

The specifics are unclear to me, though.  Is the idea as follows?

* If GHC would otherwise not recompile a module, then (we assume) the input passed by GHC to the plugin would be the same if it did recompile it.  So the only reason to recompile would be if the plugin is impure (`pluginHash` returns `Nothing`) or its input flags have changed (`pluginHash` returns a differnet fingerprint to last time).   So GHC checks that each plugin (applied to its flags) returns the same fingerprint as on the previous compilation. If the fingerprint differs, or returns Nothing, recompilation is triggered.

What if the plugin reads or writes a file, with a filename that might be dependent on the program being compiled?   `pluginHash` would like to fingerprint the file contents, but it can't because it can't see the program being compiled.

To handle this, each plugin would really like a token,, produced by it, serialised into the interface file, and given back to `pluginHash`.  But perhaps that's over-elaborate.

**Comment by bgamari** [comment]
Previously I said:

> For instance, perhaps each plugin hook should return a `Fingerprint` in addition to its result. This would break the plugin interface, but in exchange we would potentially reduce duplicated work (since the plugin could potentially compute its hash as it evaluates its result) and allow ourselves to potentially provide finer-grained recompilation avoidance in the future.

However, I'm afraid this won't work to avoid unnecessarily running the plugin: this would require that we run the plugin to determine whether we need to run the plugin. I suppose we could use lazy evaluation to first compute the fingerprint, then only evaluate the plugin result if it has changed, but this seems rather fragile. Consequently, returning a `Fingerprint` with the plugin result will only help in potentially avoiding re-running of the downstream passes. We will still need to have a separate "do you need to run?" interface, as described in the proposal.

I still do wonder whether we should have one such hook for each plugin hook, however.

**Comment by Ericson2314** [comment]
@bgamari Yeah agreed mine is far too ambitious to replace this. Just wanted to point out that this sort of unsafe-caching is a sketchy business and I wouldn't want to get too deeply attached it if we can avoid it altogether long term.

**Comment by nomeata** [comment]
> @nomeata Thanks, great question. The author would certainly have to mark that plugin as impure I think. I would define purity in this context to be that a plugin P is pure iff for a modules M and N with fingerprints F(M) and F(N), F(M) = F(N) => P(M) = P(N). Do you think this condition is too strong? You observe that if you fingerprint the impurity you depend upon you still achieve sensible recompilation behaviour.

That’s reasonable, but it means that authors will have to understand the precise semantics of `F` to make a correct judgment call…

> I still do wonder whether we should have one such hook for each plugin hook, however.

Probably.

**Comment by osa1** [comment]
I think it may be a good idea to ping plugin authors in this thread to get their opinion (authors of Herbie, CLaSH, ConCat, sequent-core, type-nat-solver, ...).

I think most plugins are deterministic, and inputs are simple (command line arguments, module contents). For those this solves the problem.

If the plugin authors also share this opinion then I agree with @bgamari, this is simple enough to implement in a few hours and solves the problem, so :+1: from me.

**Comment by mpickering** [comment]
@christiaanb @conal could you comment whether this proposal is sufficient for you?

**Comment by mpickering** [comment]
Also @yav @mikeizbicki and @adamgundry

**Comment by christiaanb** [comment]
The proposal seems to mostly talk about Core plugins, while all my plugins are type-checker plugins, i.e. I never got to see a `ModGuts` or anything at all related to Core. Also the proposal mentions:

> Users can use the same functions that GHC uses internally to computer fingerprints.

Given that my type checker plugins are pure I'm fine with that as long there is some documentation which fingerprinting function I should be using.

So I'm good with the general idea of this proposal, but would like to see:

1. How is it supposed to work for type-checker plugins
2. The exact API changes to the [Plugin](https://hackage.haskell.org/package/ghc-8.2.1/docs/Plugins.html#t:Plugin) data type
3. Documentation on which fingerprinting function I should be using if my type-checker plugins are pure

**Comment by mpickering** [comment]
I just significantly updated the proposal to answer the questions by @christiaanb 

I also changed the specification so that there is one hashing function for each field in the plugin.

**Comment by conal** [comment]
This proposal looks good to me. My plugin just adds a `BuiltinRule` that then gets applied by the simplifier. I think the [simple `pluginFlagRecompile` definition](https://github.com/mpickering/ghc-proposals/blob/bb7585ef0c565f2b4aec8e4e8677674bacc22788/proposals/0000-plugin-recompilation.rst) would suit my needs for the plugin flags I use for diagnostics.

**Comment by adamgundry** [comment]
@mpickering thanks for tackling this, I'm in favour of the general approach. It would be worth providing clear documentation / predefined smart constructors for `PluginPass` to cover the common cases of `purePlugin` and "plugin depends on the hash of all its arguments".

@bgamari @nomeata 
> > I still do wonder whether we should have one such hook for each plugin hook, however.
>
> Probably.

Forgive me for being slow, but what's the advantage of having one hook per plugin hook? Is it just for a hypothetical future recompilation checker that might want to skip certain passes? I suspect it's currently  rare for a single plugin to include both core-to-core and type checker hooks, so I wonder if the extra complexity is justified. (Though perhaps the source plugins proposal might change this?)

**Comment by mpickering** [comment]
@adamgundry I agree about providing smart constructors for `PluginPass` which will suite most use cases. 

I couldn't decide very easily whether having one hashing hook or one per plugin is more satisfactory. In the former case, if a user did have multiple plugins they would be responsible for combining together the finger prints themselves (or just computing one). As a few people suggested the latter, I just modified the proposal to state that instead so not to get trapped in a quagmire arguing about which was better.

**Comment by mpickering** [comment]
So it seems that everyone is in broad agreement about this proposal. What is the next step to ensure a prompt closure of this issue?

**Comment by nomeata** [comment]
I somewhat dislike the complications introduced here:
```
data Plugin =
  { installCoreToDos :: CorePlugin
  , tcPlugin :: TcPlugin
  }

type CorePlugin = PluginPass ([CommandLineOption] -> [CoreToDo] -> CoreM [CoreToDo])
type TcPlugin = PluginPass ([CommandLineOption] -> Maybe TcRnTypes.TcPlugin)
```
Why not the somewhat simpler
```
data Plugin =
  { installCoreToDos :: [CommandLineOption] -> [CoreToDo] -> CoreM [CoreToDo]
  , tcPlugin :: [CommandLineOption] -> Maybe TcRnTypes.TcPlugin
  , corePluginRecompile ::  [CommandLineOption] -> IfG PluginRecompile
  , tcPluginRecompile ::  [CommandLineOption] -> IfG PluginRecompile
  }
```
which means no breaking change to existing code (at the expense of a bit of repetition)?

**Comment by mpickering** [comment]
I think stuffing each recompilation check into a new field in `Plugin` is a poor design. The choice about whether to recompile is related to each specific plugin rather than all the plugins as a whole. If there was a single recompilation check then of course it would make sense to add an additional field to `Plugin` but as the proposal is now one for each type of plugin, I don't think it is very clean.

The question remains how I can now move this proposal forward? I don't think it is desirable for anyone for this to drag out over several months.

**Comment by nomeata** [comment]
> The choice about whether to recompile is related to each specific plugin rather than all the plugins as a whole.

True. But: Almost all plugins will instantiate exactly one of the plugin fiends and (maybe) one of the recompilation fields). No need to bother them with the extra indirection.

Note that the docs kinda promise to only add fields, and backwards compatibility if plugin writers just use `defaultPlugin`: https://downloads.haskell.org/~ghc/master/users-guide/extending_ghc.html#writing-compiler-plugins This would be broken by your refactoring.

Actually I am not sure anymore we need multiple fingerprints. There is one set of plugin options, and the compiler will either compile a module (and run _all_ plugins, typechecker and core) or not run it. You write

> As we have a separate pluginRecompile function for each different type of plugin we can accurately report why recompilation was required.

but it’s probably not worth it.

So maybe go back to a single additional field to `GhcPlugins.Plugin`?

> The question remains how I can now move this proposal forward? I don't think it is desirable for anyone for this to drag out over several months.

It’s a week old proposal, and there is active discussion. This is the way forward…

**Comment by mpickering** [comment]
Now that discussion has dried up, can this proposal move forward?

**Comment by osa1** [comment]
Is this still in scope after ea57828a1368657eb8bf8626fe80a398ac75d20c ?

**Comment by nomeata** [comment]
Well, it was brought before the committee, so we might as well try to assess the proposal.

**Comment by bgamari** [comment]
The committee has discussed and agreed to this proposal. However, in light of the uncertainty surrounding what sub-module-granularity recompilation will look like in GHC, we concluded that a more  conservative interface change would be preferable.

Specifically, the committee prefers the original proposal of adding a separate plugin hash to avoid needlessly breaking compatibility with existing plugins. @mpickering, would you like to amend the proposal to reflect this or should I?

**Comment by mpickering** [comment]
I am struggling to find time to do this but will get to it eventually.

**Comment by nomeata** [comment]
I am marking this as “Needs revision”, so that it no longer shows up as pending review decisions; I can move it to accepted directly once the proposal has been amended.

**Comment by mpickering** [comment]
Updated it now.

**Comment by bgamari** [comment]
Joachim Breitner <notifications@github.com> writes:

> Merged #108.
>
Thanks @mpickering!

**Comment by mpickering** [comment]
Patch is here for review.

https://phabricator.haskell.org/D4366

**Pull request merged**
