### PR TITLE
Migrate Trac links to GitLab

### PR DESCRIPTION
**Pull request by RyanGlScott**
Now that GHC's issue tracker is hosted on GitLab instead of Trac, there are a number of things in the accepted GHC proposals that deserve to be updated. In particular:

* Explicit references to Trac have been updated, as Trac is no longer the primary source for GHC issues.
* Links to Trac issues and wiki pages have been converted to their GitLab counterparts.
* The `trac-ticket` label on each proposal is now an anachronism, so I've changed this to `ticket-url`.

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks a lot, very helpful!

I wonder if plain full urls in the header field for tickets would be simpler, and easier to follow for uninitiated visitors.

**Comment by RyanGlScott** [comment]
That would work for me. Granted, the name `ticket` doesn't really give a clear indication that it's expecting a URL. Perhaps the label should be named `ticket-url`?

**Comment by nomeata** [comment]
Yeah, that might avoid confusion.

**Comment by RyanGlScott** [comment]
OK, we now use `ticket-url` everywhere.

**Comment by nomeata** [comment]
Thanks a lot!

**Pull request merged**
