### PR TITLE
Add constructor synonyms

### PR DESCRIPTION
**Pull request by treeowl**
Add constructor synonyms to complement pattern synonyms.

[Rendered view](https://github.com/treeowl/ghc-proposals/blob/680d909a07b10b6a37a64adf174ee845783dc2a4/proposals/0000-constructor-synonyms.rst)

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks for bringing this up, this is obviously a shortcoming in pattern synonyms.

> One alternative is to support only bidirectional pattern syntax with an additional signature, or yet another context. Personally, I believe this is unwieldy. Furthermore, it prevents users from writing constructor synonyms without corresponding pattern synonyms, when there is no apparent reason to prohibit such. And, worst, it continues to tie together language features that have almost nothing to do with each other.

What is a constructor without a pattern? Just a normal value! So that is not a compelling argument.

I would say that using this syntax is the right way forward, as it preserves the rough idea of “capitalised things can be matched against”. And is more conservative about adding keywords.

**Comment by treeowl** [comment]
Capitalized things cannot necessarily be matched with! We can't match on type synonyms or type families. And I'll still be able to make something that can't be matched with, but only in an ugly way: `pattern Foo :: Any => ... where ...`. Now I'd much, much rather have the combined syntax with the extra type signature than continue to deal with the current situation, but it feels oddly asymmetrical to me.

**Comment by nomeata** [comment]
> Capitalized things cannot necessarily be matched with! We can't match on type synonyms or type families.

These are on the type level (granted, once we go fully dependent, this will be a valid counter example).

Let me ask differently then: What is the distinguishing factor of a Constructor vs. a normal value binding? What does your `constructor` proposal gain over simply allowing bindings with capitalized names, e.g.:

    Foo :: String
    Foo = "Hello"

**Comment by treeowl** [comment]
The latter clashes badly with pattern bindings. If I write

```haskell
Foo a = y
```

There is no way to tell, locally, whether I mean

```
constructor Foo a = y
```

or

```haskell
a = case y of Foo q -> q
```

**Comment by nomeata** [comment]
Right, I overlooked that. But besides the syntactic ambiguity: Does `constructor … = …` amount to anything else than basically getting rid of the significance of the case of the first character in bindings?

**Comment by treeowl** [comment]
No, there's nothing more to it but syntax. Isn't that beautiful simplicity?

**Comment by nomeata** [comment]
Well, the effect is that there is *no* significance to a term `Foo` any more. It could be anything. Originally we knew it was a real constructor (i.e. matchable, injective etc.). With pattern synonyms, we at least know that it is matchable (up to hacks). With your proposal, the capitalization carries no information any more.

This might be a valid design choice for a new language, but I don’t see at the moment how Haskell gets better from this.

Why would you not use lower-case names in all the instances where you currently propose `constructor` without `pattern`.

**Comment by treeowl** [comment]
I personally tend to think languages features are easiest to understand
when they're maximally orthogonal. That said, if others agree with you I'll
gladly amend the proposal to the more conservative alternative of allowing
a type signature for the constructor in a bidirectional pattern synonym.
That's the really critical element to me.

**Comment by goldfirere** [comment]
One nice design principle around pattern synonyms was this: we should allow a library-writer who has exported a datatype concretely (that is, with constructors), to change the representation without changing the interface. That guiding light showed us the way at a good many junctions.

If we shine it here, we see that tying constructors to pattern synonyms agrees. You can't export an expression-only constructor. So I think I prefer capitalized identifiers always to be matched with pattern synonyms.

Part of what feels wrong here is that, once Haskellers start using this feature, the keyword `constructor` will feel awfully quaint, as there won't be anything constructor-ish about capitalized identifiers, as @nomeata points out. So should the keyword be `capital`? And then it just feels silly.

For the record, I do buy the orthogonality argument here. But not enough to sway my opinion.

**Comment by treeowl** [comment]
Closing in favor of #42

**Comment by treeowl** [comment]
@kosmikus thinks this should be reopened.

**Comment by treeowl** [comment]
@nomeata, I think there's been enough discussion on this and #42 to bring them both to the committee as alternatives. This proposal is more flexible than that one, and gives a better story for `:i`, so I prefer it, but I won't be a grump if the committee favors #42.

**Comment by nomeata** [comment]
I assume that they can both be evaluated together (i.e. same shepherd), right?

**Comment by treeowl** [comment]
Yes, certainly.

**Comment by bitemyapp** [comment]
This proposal is rejected as it abandons the syntactic distinction between constructors and the benefits described don't justify the loss. Your time and cooperation is much appreciated, thank you!

**Pull request closed without merging**
