### PR TITLE
Proposal: use %rsp for the stack pointer on x86_64

### PR DESCRIPTION
**Pull request by simonmar**
This came up a couple of times recently, and I did a bit of digging to see whether it might be a good idea.  Summary: I suspect it's not going to buy us very much and might even be a loss performance-wise due to the increase in code size, but at least this proposal will serve as a place to collect the information.

[Rendered](https://github.com/simonmar/ghc-proposals/blob/patch-1/proposals/0000-template.rst)

### CODE REVIEW

**Comment by cartazio** [comment]
I did some looking a while ago, and it looks like certain optimizations may or may not fire based upon `call` and `ret` being "well parenthesized/matched" (this at least is documented in the intel optimization manual) . 

That said, i've also seen it alleged that the memory region immediately surrounding the address held by rsp gets special treatment / is faster to read/write

one point of confusion for at least myself is: is it possible to do tail calls with the RSP stack specific instructions?

**Comment by bgamari** [comment]
Thanks for doing this Simon!

**Comment by rwbarton** [comment]
I don't have numbers but my gut feeling is the `call`/`ret` pairing as mentioned by Carter is probably important. What about doing a `call` followed by a `jmp` over the info table?

**Comment by simonmar** [comment]
> What about doing a call followed by a jmp over the info table?

You could do that, but I'd be surprised if it was a net win, due to the increase in code size and the penalty for the extra `jmp` on every return.

It might be better to have a separate data structure to map return addresses to info tables, like the stack-unwind tables that C++ uses.  Given that we only look at info tables during GC it might be a better tradeoff to make accessing the info table a little slower in order to get `call`/`ret`

**Comment by takenobu-hs** [comment]
If GHC can use ``ret`` instruction, it's very pretty!

Because ``ret`` instruction drives branch-prediction with return stack.
Return stack's prediction rate is very high.

Return stack predicts using by a next address of the ``call`` instruction. 
I'm a lack of understanding detail yet, how to use ``call`` instruction?
(how to set return address by the ``call``?)

**Comment by cartazio** [comment]
quoting the intel optimization manual 

section 3.4.1 branch prediction optimization
`• Inline functions and pair up calls and returns.`

a little further one theres some more good stuff

> 
> 3.4.1.4 Inlining, Calls and Returns
> The return address stack mechanism augments the static and dynamic predictors to optimize specifically for calls and returns. It holds 16 entries, which is large enough to cover the call depth of most programs. If there is a chain of more than 16 nested calls and more than 16 returns in rapid succession, performance may degrade.
> The trace cache in Intel NetBurst microarchitecture maintains branch prediction information for calls and returns. As long as the trace with the call or return remains in the trace cache and the call and return targets remain unchanged, the depth limit of the return address stack described above will not impede performance.
> To enable the use of the return stack mechanism, calls and returns must be matched in pairs. If this is done, the likelihood of exceeding the stack depth in a manner that will impact performance is very low.
> The following rules apply to inlining, calls, and returns.
> **Assembly/Compiler Coding Rule 4**. (MH impact, MH generality) Near calls must be matched with near returns, and far calls must be matched with far returns. Pushing the return address on the stack and jumping to the routine to be called is not recommended since it creates a mismatch in calls and returns.
> Calls and returns are expensive; use inlining for the following reasons:
> • Parameter passing overhead can be eliminated.
> • In a compiler, inlining a function exposes more opportunity for optimization.
> • If the inlined routine contains branches, the additional context of the caller may improve branch prediction within the routine.
> • A mispredicted branch can lead to performance penalties inside a small function that are larger than those that would occur if that function is inlined.
> **Assembly/Compiler Coding Rule 5. (MH impact, MH generality)** Selectively inline a function if doing so decreases code size or if the function is small and the call site is frequently executed.
> **Assembly/Compiler Coding Rule 6. (H impact, H generality**) Do not inline a function if doing so increases the working set size beyond what will fit in the trace cache.
> **Assembly/Compiler Coding Rule 7. (ML impact, ML generality)** If there are more than 16 nested calls and returns in rapid succession; consider transforming the program with inline to reduce the call depth.
> **Assembly/Compiler Coding Rule 8. (ML impact, ML generality)** Favor inlining small functions that contain branches with poor prediction rates. If a branch misprediction results in a RETURN being prematurely predicted as taken, a performance penalty may be incurred.)
> **Assembly/Compiler Coding Rule 9. (L impact, L generality)** If the last statement in a function is a call to another function, consider converting the call to a jump. This will save the call/return overhead as well as an entry in the return stack buffer.
> **Assembly/Compiler Coding Rule 10. (M impact, L generality)** Do not put more than four branches in a 16-byte chunk.
> **Assembly/Compiler Coding Rule 11. (M impact, L generality)** Do not put more than two end loop branches in a 16-byte chunk.
> 

at some point this sort of thing turns into "we need to design some experiments on different calling convention / abis", but the intel optimization manual does provide some good guide posts for articulating in a qualitative way what might be high impact or high generality, and are good starting points for thinking about the design space (though again, experimentation trumps all)

i guess one question is what are the pieces of the RTS we'd need to tweak to make it "cheap" to do ABI / calling convention experiments?

would using RSP allow us to have the  LLVM backend understand more stack structure so it could do mem2reg and friends?

**Comment by cartazio** [comment]
theres actually a LOT of other good ideas in the intel optimization guide we could probably benefit from too

**Comment by takenobu-hs** [comment]
``ret`` instruction has advantege with two things in CPU.

* using branch-prediction with hardware Return Stack Buffer

  Return prediction is indirect address prediction.
  But it has high prediction success rate.

* executing with out-of-order

  ``ret`` instruction depend on only rsp register.
  The rsp will be determined in advance instead of rbp.
  It can be executed at an earlier cpu cycle.

**Comment by takenobu-hs** [comment]
@cartazio 
> theres actually a LOT of other good ideas in the intel optimization guide we could probably benefit from too


Yes, we could also use technique of branch elimination.
Branch prediction miss is very expensive in deep pipelined CPUs.

> 3.4.1.1 Eliminating Branches
>  Eliminating branches improves performance because:
>  • It reduces the possibility of mispredictions.
>  • It reduces the number of required branch target buffer (BTB) entries. Conditional branches, which
>  are never taken, do not consume BTB resources.
>  There are four principal ways of eliminating branches:
>  • Arrange code to make basic blocks contiguous.
>  • Unroll loops, as discussed in Section 3.4.1.7, “Loop Unrolling.”
>  • Use the CMOV instruction.
>  • Use the SETCC instruction

**Comment by angerman** [comment]
@cartazio 
> would using RSP allow us to have the LLVM backend understand more stack structure so it could do mem2reg and friends?

I don't think this would impact the LLVM backend at all. The llvm backend essentially lays out the code as unregistered (e.g. passing all as arguments). Using the `ghccc` call and `mem2reg`.

Essentially the current llvm backend does this:

1. Cmm -> llvm ir (`.ll`) with `ghccc`
2. llvm `opt`: (`.ll` -> `.bc`) using `-mem2reg -globalopt`; there seems to be an implicit assumption that `-O1` and `-O2` include `-mem2reg`.
3. llvm `llc`: (`.bc` -> `.s`)
4. llvm mangle (`.s` -> `.s`)
5. llvm `clang` (`.s` -> `.o`)

See https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/Backends/LLVM/Design#RegisterPinning and  http://www.nondot.org/sabre/LLVMNotes/GlobalRegisterVariables.txt

**Comment by rwbarton** [comment]
@simonmar, in a sequence like this one (testing and entering the argument of `a n = n + 1 :: Int`)
```
  21:   48 c7 45 f8 00 00 00    movq   $0x0,-0x8(%rbp)
  28:   00 
                        25: R_X86_64_32S        .text+0x50
  29:   4c 89 f3                mov    %r14,%rbx
  2c:   48 83 c5 f8             add    $0xfffffffffffffff8,%rbp
  30:   48 f7 c3 07 00 00 00    test   $0x7,%rbx
  37:   75 17                   jne    50 <cOn_info>
  39:   ff 23                   jmpq   *(%rbx)
```
wouldn't it be a lot smaller to replace the instructions at offset `39` and `21` by a `call` followed by a 2-byte `jmp` past the info table? As a bonus, here we would save the stack pointer manipulation at `2c` as well.

Even a `call` followed by a 5-byte `jmp` would be shorter.

**Comment by takenobu-hs** [comment]
Sorry, I was misunderstood one point.
This proposal is intended to use ``ret`` without ``call``.

This proposal is good for shorter size and out-of-order execution.
However, we need a little attention about branch prediction.

In general, ``ret`` branch prediction requires a corresponding ``call`` instruction.
If there is no ``call``, branch prediction at ``ret``  will almost mistake.

A small summary of the branch prediction of general CPUs:
  (a) jump instructions (jmp\*, call\*, ...) - using a **branch address table**
  (b) return instructions (ret) - using a **return stack buffer**

This proposal will change behavior (a) to (b) at target instructions.
Of course, the overall performance is up to this implementation and CPU's micro architectures.

**Comment by simonmar** [comment]
@rwbarton you're right, I'd forgotten about explicitly pushing the return address.

So perhaps it's a worthwhile experiment for someone to do.

**Comment by takenobu-hs** [comment]
@rwbarton, @simonmar Please ignore if I'm missing context.

```
  21:   48 c7 45 f8 00 00 00    movq   $0x0,-0x8(%rbp)
  28:   00 
                        25: R_X86_64_32S        .text+0x50
  29:   4c 89 f3                mov    %r14,%rbx
  2c:   48 83 c5 f8             add    $0xfffffffffffffff8,%rbp
  30:   48 f7 c3 07 00 00 00    test   $0x7,%rbx
  37:   75 17                   jne    50 <cOn_info>
  39:   ff 23                   jmpq   *(%rbx)
```

It's good that the instruction at offset ``39`` is replaced by ``call`` instruction.
And putting ``ret`` instruction at end (return point) of the entered closure.
If so, branch prediction at the ``ret`` instruction will almost be successful.
(Despite the dynamic address.)

**Comment by takenobu-hs** [comment]
If GHC will use ``ret`` prediction, it's need to modify calling convention as mentioned by @cartazio.

But there is little tricky approach as following (@rwbarton mentioned this?):
* put ``call`` instruction at end of info table (just above the entry code)
* jump to the ``call`` instruction for entering to a closure
* return by ``ret`` from the entered (callee) closure (return to top of the entry code, thus next of the ``call`` instruction)

Example:
```
    movq   $0x0,-0x8(%rbp)
    mov    %r14,%rbx
    add    $0xfffffffffffffff8,%rbp
    test   $0x7,%rbx
    jne    50 <cOn_info>
(A) JUMP TO (B)
info_table
    ..
    ..
(B) CALL CLOSURE
entry_code
(C) RETURN HERE, FROM THE CLOSURE
```

The ``ret`` instruction will almost be success prediction.

**Comment by takenobu-hs** [comment]
I describe a comment about qualitative numbers.

We have opportunity to improve performance at each case expression.
Currently, maybe, GHC lost **5-30** instruction execution at each case expression.
Because branch misprediction will be occurred at each return point of closures.

Qualitatively, we lose performance by CPU's pipeline flush from branch misprediction.
Its penalty is following:

>  "averaged instruction per cycle (1-3)" x "number of frontend pipeline stage (5-30)" -> 5-30 instruction execution

Its size is almost typical entry code size.
So we have opportunity to improve performance by a factor of two.

Thank you.

**Comment by simonmar** [comment]
> So we have opportunity to improve performance by a factor of two.

I very much doubt that :)  We've measured branch misprediction in the past and for GHC-compiled code it's not too bad.  Pointer-tagging had a huge impact on misprediction and only gave us a 10-15% win.

At this point I think someone could experiment with various alternatives for this proposal.  I'd be happy to provide guidance if someone wants to tackle it.

**Comment by takenobu-hs** [comment]
@simonmar
> We've measured branch misprediction in the past and for GHC-compiled code it's not too bad. Pointer-tagging had a huge impact on misprediction and only gave us a 10-15% win.

Oh, it was quantitative evaluation! It is fantastic. Thank you for information.
I feel that pointer-tagging is great implementation.

In addition to it, I imagine possibility of speeding up of the return from the closure in first evaluation.
(Because recent CPUs have more deep and multiple pipeline.)

I'll try it after I learn native code generator :)
(But I need long time...)


> So we have opportunity to improve performance by a factor of two.

Sorry, "a factor of two" means locally at target closure.

**Comment by nomeata** [comment]
I’m surprised to see this as a proposal here, as it is purely an implementation detail of GHC, and does not affect the syntax, the language or the libraries. According to [the proposal proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0000-proposal-process.rst) this is out of scope here (and I would have expect such technical discussions on trac).

**Comment by rwbarton** [comment]
`sigaltstack` should handle the signal issue on POSIX systems, but there seems to be no Windows equivalent...

**Comment by rwbarton** [comment]
From https://msdn.microsoft.com/en-us/library/x4ea06t0.aspx

> All memory beyond the current address of RSP is considered volatile: The OS, or a debugger, may overwrite this memory during a user debug session, or an interrupt handler.

**Comment by simonmar** [comment]
@nomeata you're right it's out of scope.  But this is a really useful mechanism for holding a discussion around an evolving document, so I think we can use it for more than just user-facing changes to the compiler.  I don't mind if people would rather we moved this to the wiki/mailing list though.

**Comment by cartazio** [comment]
There is a ticket on trac for this very rsp experiment btw.

**Comment by bgamari** [comment]
> There is a ticket on trac for this very rsp experiment btw.

This being [#8272](https://ghc.haskell.org/trac/ghc/ticket/8272).

**Comment by takenobu-hs** [comment]
@nomeata, @simonmar
I think that "[the user-visible behaviour of the compiler](https://github.com/ghc-proposals/ghc-proposals/blame/master/proposals/0000-proposal-process.rst#L21)" does not mean only static surface of specifications.
It will also include the following:
* a major change of the performance
* a major change of the code size
* a major change of the timing behaviour on the run time
* a major change of the memory behaviour on the run time

Of course, "*major*" is very important :)
As your worry, if minor changes are proposed, the process will "[become more onerous than necessary](https://github.com/ghc-proposals/ghc-proposals/pull/1#issuecomment-233119267)".


In case of "a major change", when a proponent would hope, it's better to construct the collective wisdom by the ghc-proposal process.

If a major change like this is shared on github, potential contributors will get opportunity to join discussion and development more easily.

**Comment by rwbarton** [comment]
Instead of using `sigaltstack`, we could block all signals and have a thread dedicated to processing them with `sigwaitinfo` or `sigtimedwait`. I don't think this helps with the problem of FFI calls setting signal handlers though.

**Comment by rwbarton** [comment]
A more serious issue is that `ret` doesn't have the exact semantics we currently want. For example for the declaration `data Y = Z` ghc currently generates this cmm and asm:
```
       cGo:
           R1 = R1 + 1;
           call (P64[Sp])(R1) args: 8, res: 0, upd: 8;
```
```
X.Z_static_info:
_cGo:
	incq %rbx
	jmp *(%rbp)
```
We'd surely like to use `ret` here, but `ret` also adjusts the stack pointer, popping the return address off the stack, which the current code does not do. We can't write code with `ret` that behaves like the old code, since before the `ret` the stack pointer must point to the return address and after `ret` we have no control locally.

So we'd be forced into using a slightly different "calling convention" where after return from entry code the return address has already been popped off the stack. I'm not sure what all the ramifications of this are, but it seems impractical to adjust for this in cmm generation, considering the amount of hand-written cmm code. Can we adjust for it in code generation? I'm not sure.

**Comment by simonmar** [comment]
> Instead of using sigaltstack, we could block all signals and have a thread dedicated to processing them with sigwaitinfo or sigtimedwait. I don't think this helps with the problem of FFI calls setting signal handlers though.

I actually explored this (a long while ago) as part of a redesign of the signal API that I never finished.  The real problem is, as you say, that you can never guarantee that third-party code isn't making its own calls to the kernel signal API and messing things up.  The designers of POSIX never imagined that language runtimes might want to virtualise signals.

> A more serious issue is that ret doesn't have the exact semantics we currently want. 

Yes - I don't think the changes to the code generator would be too hard, but you're right that there's some hand-written cmm that would need to be changed. It would be difficult to retain both calling conventions in the codebase, which probably means that the `ret` calling convention would need to be adopted for all platforms, including unregisterised via-C.  How this affects LLVM I'm not sure.

**Comment by nomeata** [comment]
This proposal was not updated in two months. If you think this proposal is its final phase, please tag it as “Pending committee review”.

**Comment by gracjan** [comment]
I'm not sure how relevant this is, but Java got to use rsp for stack pointers so that tools like DTrace and perf can work properly:

http://techblog.netflix.com/2015/07/java-in-flames.html

**Comment by simonmar** [comment]
I'm going to close this.  We don't have a sensible way to make a "decision" about it, and it doesn't have any user-facing consequences (or at least it shouldn't!).  In this case I semi-hijacked the proposal process as a general discussion-around-an-evolving-document process, perhaps the community needs a way to do that?

**Comment by mitchellwrosen** [comment]
The community does need such a thing! GitHub works okay, with watching repositories (how I found this thread), @-mentions, thumbs up/down, and all that. I quite enjoyed reading through this discussion even though it wasn't a real proposal. Perhaps a "gh-discussions" repo could be created, underneath the "gh-proposals" user?

**Comment by bgamari** [comment]
We actually have an "Out-of-scope" label for this exact reason.

That being said, I think @simonmar is right here; the discussion has more or less reached its conclusion: We generally think this would be a nice idea to explore but someone needs to step up to actually push the change through.

**Pull request closed without merging**
