### PR TITLE
Unboxed coercions

### PR DESCRIPTION
**Pull request by treeowl**
Offer access to unboxed coercions.

[Rendered](https://github.com/treeowl/ghc-proposals/blob/unboxed-coercions/proposals/0000-unboxed-coercions.rst)

### CODE REVIEW

**Comment by Ericson2314** [comment]
Forget coersions, I want unboxed constraints in general! In the discussion of https://github.com/ghc-proposals/ghc-proposals/pull/32 the very natural `TYPE :: RuntimeRep -> Coherence -> Type` approach came up. Yes, @goldfirere points out more research is required, well, I'd love to see a looming GHC release expedite that. 😂

**Comment by RyanGlScott** [comment]
Some comments:

1. The scope of this proposal feels a tad limited. Why not also include unboxed equalities as well? They do use the same machinery as your proposed unboxed coercion, after all (just with a different role).
2. You allude to potential issues with tuple constraints that I didn't follow. Can you go into more detail on this aspect?
3. Another potentially troublesome aspect of "banged constraints"/exposing `~R#` directly is coming up with a kind signature for them. At one point, I was curious and tried exposing `~R#` myself (through Template Haskell hackery) and discovered that internally, GHC thinks the kind of `~R#` is:

   ```haskell
   (~R#) :: forall k. k -> k -> TYPE (TupleRep '[])
   ```

   This is sufficiently weird enough that GHC didn't know how to handle it if I tried using `~R#` as an actual constraint, as it wouldn't kind-check (it expected something of kind `Constraint`, but was given something of kind `TYPE (TupleRep '[])` instead.

   To make these options truly usable, we might need to invent another kind to describe it. (`CONSTRAINT :: RuntimeRep -> Type`, where `type Constraint = CONSTRAINT LiftedRep` and `(~R#) :: forall k. k -> k -> CONSTRAINT (TupleRep '[])`?)

**Comment by simonpj** [comment]
I'm usually in favour of exposing in the source language the stuff you can do in Core.  But as Ryan points out, this proposal bumps into the uneasy Constraint-vs-* debate, which is far from settled.  (All we havew now is an unsatisfactory compromise.)

One thought.  For a long time I've wanted to experiment with making GHC be strict in all constraint arguments.  They are always non-bottom.    If we did that, then `One` would evaluate and unbox its `Coercible` constraint, and that would make it much more efficient.  No language change would be needed at all.  And it might make lots of programs run a bit faster. 

I'd love someone to explore this.  `-XStrictDicts` is the flag, but it's atrophied.

**Comment by treeowl** [comment]
@RyanGlScott, now that [GHC Trac 14978](https://ghc.haskell.org/trac/ghc/ticket/14978) is fixed (thanks, @simonpj), we can unpack equalities into datatypes just fine, although I suppose we still can't pass them directly to functions. That works because GADTs already offer a certain amount of access to unboxed equalities. We have nothing similar for representational coercions.

As for tuple constraints, what I mean is that it seems a bit odd to have a "tuple" that contains unboxed things. If we have unboxed equalities, we might write `(Num a, Coercible# a b)`, which makes me a bit nervous.

**Comment by RyanGlScott** [comment]
I'll respond to each of your points separately.

After reading your first point, it seems that your primary use case here is to unpack GADTs with equality/`Coercible` constraints, yes? In other words, you want to be able to do something like the example program from Trac #14978:

```haskell
data a :~: b where
  Refl :: a ~ b => a :~: b

type family Foo a b

data Goof a b where
  Goof :: !(Foo a b :~: Int) -> Goof a b
```

And I presume you also want to do something like this?

```haskell
data Coercion a b where
  Coercion :: Coercible a b => Coercion a b


data Bidoof a b where
  Bidoof :: !(Coercion (Foo a b) Int) -> Bidoof a b
```

Does this work? If not, is your motivation for introducing unboxed coercions to support code like this? Or do you want unboxed coercions for the sake of having them be a first-class programming construct? (Or something in between?)

As for your second point, yes, I agree that `(Num a, Coercible# a b)` is rather intriguing. On one hand, we could just say that that's an OK thing to do, since we could treat `(Num a, Coercible# a b) => r` as `Num a => Coercible# a b => r`, which isn't problematic (AFAICT). But if we do thing, would we need to generalize the kind signature of constraint tuples from `Constraint -> Constraint -> ... -> Constraint` to something more inclusive? I'm not sure.

As @simonpj notes, it would be nice if unboxed constraints Just Worked™ without needing to change the surface syntax to support them. I'm not qualified enough to say how much of GHC would need to be altered to make this happen, but perhaps others can chime in here.

**Comment by treeowl** [comment]
@RyanGlScott, a key point is that `:~:` is defined

```haskell
data a :~: b where
  Refl :: a :~: a
```

which is actually represented differently! There's nothing like the latter (in surface Haskell) to express coercibility.

**Comment by RyanGlScott** [comment]
Oh, so you're saying that `(:~:)` unpacks differently if you have `Refl :: a :~: a` as opposed to `Refl :: a ~ b => a :~: b`? How does this manifest?

**Comment by treeowl** [comment]
Refl ends up unary instead of nullary. This is because explicit constraints
are always boxed.

**Comment by RyanGlScott** [comment]
That's stunning. I would expect them to unbox the same, since they desugar to the same thing in Core! Maybe this should be another Trac ticket in itself.

**Comment by treeowl** [comment]
I don't think they desugar to the same thing. Unless I'm reading it write
wrong.

**Comment by RyanGlScott** [comment]
They most certainly do! The surface syntax is the slightly different, but GHC generates a wrapper function for the `Refl :: a :~: a` version which converts it into the form that Core expects (i.e., with explicit equality constraints). You can verify this for yourself by compiling this:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeOperators #-}
module Foo where

data a :~: b where
  Refl :: a :~: a
```

With:

```
$ ghc Foo.hs -ddump-simpl -dsuppress-module-prefixes -dsuppress-uniques -dsuppress-idinfo 
[1 of 1] Compiling Foo              ( Foo.hs, Foo.o )

==================== Tidy Core ====================
Result size of Tidy Core
  = {terms: 58, types: 29, coercions: 1, joins: 0/0}

-- RHS size: {terms: 2, types: 4, coercions: 1, joins: 0/0}
$WRefl :: forall a. a :~: a
$WRefl = \ (@ a) -> Refl @ a @ a @~ (<a>_N :: (a :: *) ~# (a :: *))
```

**Comment by RyanGlScott** [comment]
For the sake of transparency, I'll mention that I have another ulterior motive for wanting unboxed equalities in addition to unboxed coercions. There's a slew of Trac tickets ([#12677](https://ghc.haskell.org/trac/ghc/ticket/12677) being one of them) which demonstrate surprising behavior of equality constraints. A simple program which demonstrates this is:

```haskell
foo :: forall k (a :: k). k ~ Type => a -> a
foo x = x
```

It turns out that the type signature of `foo` does not kind-check:

```
    • Expected a type, but ‘a’ has kind ‘k’
    • In the type signature:
        foo :: forall k (a :: k). k ~ Type => a -> a
```

This is despite the fact that we've constrained `k` to be `Type`! Well, almost. Because `(~)` is _lifted_ equality, it can (in principle) be inhabited by `⊥`, so we can't use `k ~ Type` in type-level casts (lest the evidence it uses happens to be `⊥`).

In theory, unboxed equalities fix this problem. With unboxed equality, one could write this:

```haskell
foo' :: forall k (a :: k). k ~# Type => a -> a
foo' x = x
```

And have it kind-check, since there is no way for `k ~# Type` to be inhabited by `⊥`.

I want to put emphasis on the "in theory" part, since I've severely downplaying the amount of work needed to actually expose unboxed equalities. @goldfirere has some notes [here](https://ghc.haskell.org/trac/ghc/wiki/DependentHaskell/Internal#Liftedvs.Unliftedequality) about how one might implement this, and while I don't understand all of the details, one thing is very clear: it's not going to be a walk in the park.

What this means is that implementing unboxed coercions will likely be equally challenging. I'm not writing this down to discourage you from pursuing this, since I do think it would be extremely worthwhile to add to GHC, but it is worth keeping in mind that it's a sticky wicket.

An alternative approach would be avoiding the use of unboxed equalities/coercions entirely and allow data constructors with lifted equality or `Coercible` constraints to be unpacked, such as:

```haskell
data Equal' a b where
  Equal' :: (a ~ b) => Equal' a b

data Coercion a b where
  Coercion :: Coercible a b => Coercion a b
```

**Comment by simonpj** [comment]
> An alternative approach would be avoiding the use of unboxed equalities/coercions entirely and allow data constructors with lifted equality or Coercible constraints to be unpacked, such as:

Yes, that was exactly my point in https://github.com/ghc-proposals/ghc-proposals/pull/116#issuecomment-377895291.  I think this avenue is really worth pursuing.

**Comment by RyanGlScott** [comment]
What part was confusing? The problem is quite simple: this unboxes:

```haskell
data Equal a b where
  Equal :: Equal a a
```

But this doesn't:

```haskell
data Equal' a b where
  Equal' :: (a ~ b) => Equal' a b
```

(And similarly when `(~)` is replaced with `Coercible`.)

The questions that this brings up are:

1. Is this intended? (I would think not, for the reasons I articulate in https://github.com/ghc-proposals/ghc-proposals/pull/116#issuecomment-380500018.)
2. Can this restriction be relaxed? I would hope so, but the method by which we accomplish this is unclear. @treeowl proposes several options, with varying degrees of complexity.

I don't feel like we can properly turn this into a Trac ticket until we get a better sense of @treeowl's overarching goals. If simply unpacking data types with equalty/`Coercible` constraints is the heart of the matter, then I think this is just a matter of improving the existing implementation of [`isUnpackableType`](http://git.haskell.org/ghc.git/blob/5d76846405240c051b00cddcda9d8d02c880968e:/compiler/basicTypes/MkId.hs#l875). If having access to unboxed coercions themselves is the end goal, then we'd need to flesh out the proposal more.

**Comment by simonpj** [comment]
Thanks, that is helpful.  But what precisely does "this unboxes" mean?

**Comment by RyanGlScott** [comment]
"Unboxes" in the sense that putting an `{-# UNPACK #-}` pragma in front of it as a data type field does the expected thing. You can observe this for yourself in this program:

```haskell
{-# LANGUAGE GADTs #-}
module Foo where

data Equal a b where
  Equal :: Equal a a

data Equal' a b where
  Equal' :: (a ~ b) => Equal' a b

data Goof a where
  Goof :: {-# UNPACK #-} !(Equal a Int) -> Goof a

data Bidoof a where
  Bidoof :: {-# UNPACK #-} !(Equal' a Int) -> Bidoof a

foo :: Goof Int
foo = Goof Equal

bar :: Bidoof Int
bar = Bidoof Equal'
```
```
$ ~/Software/ghc/inplace/bin/ghc-stage2 -O2 Foo.hs -ddump-simpl -fforce-recomp -dsuppress-module-prefixes -dsuppress-uniques -dsuppress-idinfo
[1 of 1] Compiling Foo              ( Foo.hs, Foo.o )

==================== Tidy Core ====================
Result size of Tidy Core
  = {terms: 221, types: 139, coercions: 10, joins: 0/0}

...

-- RHS size: {terms: 1, types: 1, coercions: 1, joins: 0/0}
foo :: Goof Int
foo = Goof @ Int @~ (<Int>_N :: (Int :: *) ~# (Int :: *))

...

-- RHS size: {terms: 1, types: 6, coercions: 1, joins: 0/0}
bar1 :: (Int :: *) ~~ (Int :: *)
bar1
  = Eq# @ * @ * @ Int @ Int @~ (<Int>_N :: (Int :: *) ~# (Int :: *))

-- RHS size: {terms: 2, types: 1, coercions: 6, joins: 0/0}
bar :: Bidoof Int
bar
  = Bidoof
      @ Int
      (bar1
       `cast` (Sym (N:~[0] <*>_N) <Int>_N <Int>_N
               :: ((Int :: *) ~~ (Int :: *) :: Constraint)
                  ~R# ((Int :: *) ~ (Int :: *) :: Constraint)))
```

Here, `foo` uses unboxed equality, but `bar` uses boxed equality.

**Comment by simonpj** [comment]
Ah, now I see, thanks.

The problem is not in the unpacking into Goof or Bidoof.  It's that
```
Equal :: (a ~# b) => Equal a b
Equal' :: (a ~ b) => Equal' a b
```
So an `Equal` constructor has a zero-width equality field, while `Equal'` has a full word pointer to evidence for `a~b`.  

Possible solutions:

* Make all evidence strict, as I suggest above, and by-default unbox equalities because they are zero width when unpacked.

* Allow bangs on constraints to make them strict.

I really think the former is worth a try.  It'd make lots of pograms faster.

**Comment by treeowl** [comment]
Would making evidence strict cause trouble for `UndecidableInstances` or `UndecidableSuperClasses`? If not, it sounds like a good idea.

**Comment by nomeata** [comment]
This has been quiet for a while. Whither this proposal?

**Comment by RyanGlScott** [comment]
What is the status of this proposal (especially in light of https://mail.haskell.org/pipermail/ghc-devs/2018-September/016191.html)?

**Comment by nomeata** [comment]
Closing this due to inactivity, but it can be reopened when necessary.

**Comment by Ericson2314** [comment]
N.B. as "A Role for Dependent Types in Haskell" resolves the constraint-type separation problem, I think we know how to have unboxed constraints properly now.

**Pull request closed without merging**
