### PR TITLE
Proposing a new implemention for Data.List.sort, with better performance characteristics and more laziness-friendly

### PR DESCRIPTION
**Pull request by greg7mdp**
see https://github.com/greg7mdp/ghc-proposals/blob/ghc-sort/proposals/0000-ghc-sort.rst

### CODE REVIEW

**Comment by siddhanathan** [comment]
What file is this supposed to be?

`ghc-sort: shaks12.txt: openFile: does not exist (No such file or directory)`

**Comment by siddhanathan** [comment]
Also, this is suboptimal. Already sorted lists shouldn't be split into pairs and merged back, they should be split into sublists that are sorted.

Something along these lines:

```haskell
mySort :: forall a. Ord a => [a] -> [a]
mySort xs = mergeSort xs
  where
    -- pair splits a list into sorted sublists
    pair :: Ord a => [a] -> [[a]]
    pair [] = [[]]
    pair xs = takeInOrder xs : pair (dropInOrder xs)
    
    -- helper function for pair
    takeInOrder :: Ord a => [a] -> [a]
    takeInOrder (a:b:cs)
      | a < b = a : takeInOrder (b:cs)
      | otherwise = a : []
    takeInOrder cs = cs
    
    -- helper function for pair
    dropInOrder :: Ord a => [a] -> [a]
    dropInOrder (a:b:cs)
      | a < b = dropInOrder (b:cs)
      | otherwise = b : cs
    dropInOrder [a] = []
    dropInOrder cs = cs

    -- Merge two sorted lists
    merge :: Ord a => [a] -> [a] -> [a]
    merge as [] = as
    merge [] bs = bs
    merge as@(a:as') bs@(b:bs')
      | a < b = a : merge as' bs
      | otherwise = b : merge as bs'

    -- Merge two sublists at a time in the list of sorted sublists
    mergePairs :: Ord a => [[a]] -> [[a]]
    mergePairs (as:bs:css) = merge as bs : mergePairs css
    mergePairs css = css

    -- Fixed point. Keep merging till the list becomes a singleton.
    mergeFix :: Ord a => ([[a]] -> [[a]]) -> [[a]] -> [a]
    mergeFix p = head . until (null . tail) p

    -- The merge sort algorithm
    mergeSort :: Ord a => [a] -> [a]
    mergeSort [] = []
    mergeSort xs = mergeFix mergePairs (pair xs)
```

Except, `pair` shouldn't be doing redundant traversals if possible.


This way, you don't incur the performance penalty of dealing with already sorted lists.

**Comment by siddhanathan** [comment]
Oh, wait. This is not a GHC proposal. @greg7mdp can you close this PR and post this on the Haskell libraries mailing list?

**Comment by bgamari** [comment]
This looks like a libraries proposal, which are handled by the [Core Libraries Committee](https://wiki.haskell.org/Core_Libraries_Committee). I'm afraid you'll have to bring this to the CLC at <mailto:libraries@haskell.org>. Sorry for the confusion, @greg7mdp!

**Comment by greg7mdp** [comment]
Thanks @siddhanathan and @bgamari , submitted it to the  Core Libraries Committee.

**Pull request closed without merging**
