### PR TITLE
Make `forall` a keyword in types

### PR DESCRIPTION
**Pull request by goldfirere**
[Rendered](https://github.com/goldfirere/ghc-proposals/blob/forall-keyword/proposals/0000-forall-keyword.rst)

### CODE REVIEW

**Comment by Ericson2314** [comment]
Yes, and this seems like a good candidate for the next Haskell standard too.

**Comment by harpocrates** [comment]
I'm strongly in support of this.

Perhaps somewhat tangential: would it be useful to have some warning flag for all suspiciously named identifiers (everywhere, not just in types), maybe even turned on by default for `-Wcompat`? That might provide a good path towards eventually (after a bunch of release cycles) turning pseudo-keywords into full-fledged ones: `forall`, `family`, `role`, `via`, `export`, `static`, `pattern` etc.

The lexer's output should ideally not depend on which language extensions are enabled. Even better: turning these "contextual" keywords into real keywords would enable much better parse errors and language extension suggestions.

**Comment by RyanGlScott** [comment]
What happens to the `ExplicitForAll` extension under this proposal? For instance, will `NoExplicitForAll` mean something?

**Comment by goldfirere** [comment]
`ExplicitForAll` is unaffected, actually. This proposal merely makes `forall` a keyword in types always; it does not assign a semantics under `-XNoExplicitForAll`. That is, it's always an error without `-XExplicitForAll`.

**Comment by RyanGlScott** [comment]
> `ExplicitForAll` is unaffected, actually. This proposal merely makes `forall` a keyword in types always; it does not assign a semantics under `-XNoExplicitForAll`. That is, it's always an error without `-XExplicitForAll`.

Ah, OK! It might be helpful to explicitly point this out in the proposal, since the current phrasing might mislead one into thinking that this proposal would always enable `-XExplicitForAll` (since that's currently the language extension that turns `forall` into a keyword).

**Comment by goldfirere** [comment]
Discussion has wound down, with no noted dissent. I submit to the committee, @nomeata.

**Comment by int-index** [comment]
This is a great change, and it also makes [the dot type operator](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0039-dot-type-operator.rst) easier to implement, see [!363](https://gitlab.haskell.org/ghc/ghc/merge_requests/363).

**Pull request merged**
