### PR TITLE
Propose an auto-commit feature for Phab

### PR DESCRIPTION
**Pull request by goldfirere**
As discussed at Haskell Implementors' Workshop. [Rendered](https://github.com/goldfirere/ghc-proposals/blob/phab-auto-commit/proposals/0000-phab-auto-commit.rst)

### CODE REVIEW

**Comment by Ericson2314** [comment]
Does phabricator work with git branches? Merging commits is better than patches for the sake of metadata, signatures, and stable hashes.

**Comment by goldfirere** [comment]
Good point. I would want this to work with git branches. Perhaps the mechanism will include a well to tell Phab where a git branch is (e.g. a github repo/branch) and then will boil down to some invocations of git.

In agreement with you, I would probably avoid using this feature if it just merged patches, not branches.

**Comment by goldfirere** [comment]
I've updated the proposal to make @Ericson2314 's point clear.

**Comment by angerman** [comment]
@Ericson2314, @goldfirere I believe with the staging-area[1] we do have some form of branching.  While this seems primarily intended to get CI right, this might be an option here? Maybe @thoughtpolice can share some insight.

--
[1]: https://secure.phabricator.com/book/phabricator/article/harbormaster/

**Comment by simonmar** [comment]
FWIW, I'd be perfectly happy for this to not merge branches and instead behave like `arc land`, which rebases the diff onto master and then pushes it.  I'm pretty sure that would be easier to implement.

Normally you're working on a feature branch in your local repo, so you don't have to worry about the hash of the committed patch being different from the one in your local repo.  Even if the diff you committed is part of a stack, when you rebase your local feature branch git will be clever enough to omit the patch that has already been committed.

**Comment by goldfirere** [comment]
That's true, Simon, but `arc land` also squashes commits, a feature I've never quite glommed onto. However, I'd be OK if `arc land` is all we can get, though expressing a preference for preservation of git commit structure.

**Comment by thoughtpolice** [comment]
This can be done to... various degrees, with varying amounts of complexity, I think. I think Harbormaster could roughly handle this case, but it would need to be carefully implemented. Note that Harbormaster can absolutely trigger builds just on branches, not repositories, if that's what you want.

Your workflow is essentially an implicit sidestep of the code review mechanism (something I'm generally not a fan of, TBH), but it is very convenient for regular contributors, and for large changes to rapidly moving things. But what this means is that `arc` and all that stuff don't really need to be involved at all, if you don't want it to be.

Something like:

- Add a new build bot tier in Drydock, "Merger". Only committers who have enrolled in this will ever trigger builds on this tier. This tier has buildbots which contain SSH keys that may push to GHC and are highly restricted otherwise.
- Add a Herald rule that triggers when committers pushes a branch under some name like `automerge/`.
- This Herald rule overrides the regular build rule, and triggers a build on the Merger tier.
- This Herald rule invokes a special build rule on the Merger tier that doesn't *just* build GHC, but also will push to `master` if it succeeds with its key.
- This push to `master` will, in turn, trigger an ordinary Herald rule on the "ordinary" build tier, that will cycle again. Which is absolutely what we want; just because something may rebase cleanly does not mean all the tests will past. Thus, running the build again on `master` *after* the automerger has done its thing is the proper thing to do.

This would probably work OK, and is fairly achievable with *only* the things Phabricator provides today, so we wouldn't have to maintain a bunch of stuff ourselves.

---

For what it's worth, on a similar note, Phabricator has a feature already, called "Land from Differential", which opens up a button that looks like this in Differential:

image

(You can see this upstream on https://secure.phabricator.com if you look at some of their diffs). This allows you to instant-merge a patch from the UI the moment someone has given a positive review on it. This function works *for anyone who opened the diff*, because it uses a separate SSH key controlled specifically by a separate automation system -- meaning ordinary contributors can make sure their patch lands immediately once it's reviewed by someone without having to wait on us, or install their SSH key anywhere!

Land from Differential is still relatively new though. What would be great is instead if it could be driven by an API or something so we could trigger "Begin attempts at landing this" from some other system. Also, LfD isn't entirely secure yet. But I figured I'd mention it here to keep ideas afloat.

**Comment by goldfirere** [comment]
Austin says:

> Your workflow is essentially an implicit sidestep of the code review mechanism (something I'm generally not a fan of, TBH),

It is not meant to be. Although this workflow might be used for small patches that (in a contributor's opinion) do not need a review, it can also be used for large patches that have received a positive review. It's still good to do one last validate before pushing, and I (for one) frequently switch away from GHC while that validate happens.

Otherwise, your sketch of an implementation looks plausible. (I really have no idea about this stuff, though.) It also sounds relatively easy to set up, which is a definite plus.

**Comment by simonmar** [comment]
> That's true, Simon, but arc land also squashes commits, a feature I've never quite glommed onto. 

I'm often slightly bemused when people complain about arc squashing commits, because you don't have to use it like that, indeed I always keep commits and diffs in 1:1 correspondence.  Perhaps there are some gaps in our documentation.

To use `arc` without squashing commits: use `arc diff HEAD^` to make a diff, to revise it use `git commit --amend` and then `arc diff HEAD^` again.  When you have multiple dependent commits, `arc diff HEAD^` each one separately, and use `git rebase -i` to modify diffs in the stack.

If you have logically separate changes, they should be separate diffs.  That's the golden rule.  

The alternative workflow is to revise a diff by making more commits locally, and then `arc diff` will squash them into a single diff.  This way you have a record in your repository of the revision history during the review process - it's not necessary to do this because Phab always has the revision history, but if you want the history in git then you can do it this way.  The idea here is that the extra commits are revisions to the original diff as a result of review, and we don't want them cluttering the repository history after landing, so they get squashed away.  The end result is the same as if you had used `git commit --amend` to revise the original diff instead of just `git commit`.  It's harder to do stacked diffs this way though, which is why I use the simpler method in which you have one commit per diff.

**Comment by thoughtpolice** [comment]
> It is not meant to be. Although this workflow might be used for small patches that (in a contributor's opinion) do not need a review, it can also be used for large patches that have received a positive review. It's still good to do one last validate before pushing, and I (for one) frequently switch away from GHC while that validate happens.

Well, I probably didn't explain myself correctly. I guess what I'm asking is, if you want this sort of auto-magic push thing going on, why even *really* involve Differential at all? At least for regular committers who want this, what does Differential add to the above scenario I proposed?

There's some various hemming and hawing about `arc` and stuff in here, but if you just want to "fire a commit and let a bot merge it" for active committers, why involve `arc` or Differential at all? You aren't even really doing code review at that stage -- you might have done more of it earlier and this is just the "final touches" -- so you're really just sort of shoehorning Differential into doing something that seems pointless, y'know? And it obviously implicitly assumes you're some kind of regular developer, since you can  push.

For regular committers, if they want an automerge for things that are already reviewed (or, by their own assessment, is safe to directly push to `master`), I don't see why arc actually has to be involved at all, I guess is my point, if all this magical bot will do is validate the review and then like, immediately close the review instantly after merge?

Now, for ordinary users who want their changes merged more quickly, I think Land from Differential is a much more viable alternative. It also works for committers who want to merge quickly but *do* need to do a little review. It's also directly maintained by Phabricator themselves, so we don't have to write any extra code.

Anyway, I suppose that was my point: it's not really so much an indictment of you not doing review or anything like that (you clearly *do* get it done :) -- it's more like, not writing a tool to shoehorn something that might be necessary for the specific use case of "I want to skip differential and just make a bot merge this for me soon". While I adore Phabricator's extensibility, it should be treated with great care, because it increases the complexity of the things we maintain and their interactions. (I'd much rather reserve such energy for proposed changes like having an automirror Phabricator bot like Facebook has for HHVM, for example, as proposed in another RFC here). Just my thoughts.

**Comment by Ericson2314** [comment]
I'm a little bit confused here, as I understand it, the very-simple-but-usually-not-achieved goal of CI is that every commit that `master` has ever pointed to has been successfully built by the bot prior to being pointed-to by master. [What travis does on github---building PRs once and not rebuilding once master has changed while still given the green light---is absolutely criminal.]

If history is squashed, then this becomes "every commit has been built by the bot...". if a merge commit is always used (with `--no-ff`), then this becomes "every commit has been built by the bot...". In any event, it's nice if any commit needed to prepare the PR (merge/rebase/etc) is performed by the build-bot so the bot is effectively signing off on the commit hash. not just the tree hash.

Finally, while it's nice for every PR to be reviewed by someone else, this is a big burden and not critical. However I think it is reasonable to enforce that the bot does indeed build every PR as described above. With any project, there's much risk that the primary developers have a little extra undocumented setup/configuration that allows their local build to succeed. Conversely, there's nothing more infuriating for new users than to follow the development instructions only for their first build of master to fail.

Reading the proposal, I assumed that "validation" includes GHC, and the "auto-commit" is avoid the pointless step of a human manually pushing/merging a PR that has been reviewed once validation completes, but now I am less confused with, IIUC, this talk of skipping code review, which seems orthogonal.

**Comment by Ericson2314** [comment]
@thoughtpolice OK, reading again what you wrote it makes more sense :). I think all changes should (go through the review tool | have an issue or equivalent | etc), even if they aren't reviewed so that after the fact they can be easily discussed. So I agree your "Land from Differential" idea is the most promising. I guess this should be split up into make-revision-that-is-automatically-reviewed-as-ok-and-sends-less-emails and land-from-Differential?

**Comment by goldfirere** [comment]
@thoughtpolice I see your point about avoiding `arc` and such. By all means suggest another way of implementing auto-commit without creating / updating a Diff. I phrased it the way I did because I want Harbormaster (and not Travis, which skips perf checks) to do the validation. But if there's Another Way to get auto-commits, that's great too. Thanks for thinking about this.

I will say that an email "Your validate succeeded; your patch is committed" is not wasteful or redundant at all!

And I'm utterly confused about what Land-from-Differential is. You've described it as a way to land a patch as soon as it gets a positive review, from anyone. But can't someone then supply their own positive review? I would imagine we would want some check that the positive review is delivered by a committer. And is there any validation as part of this? Or is it expected that the positive review wouldn't come in until validation succeeds. In any case, it seems that you have not proposed Land-from-Differential, but I think (as you seem to) that it solves quite a different problem than I am addressing here.

**Comment by angerman** [comment]
I'm with @thoughtpolice  here. Let me just jot down the three options I see how we can make this work without involving arc.

If the whole point of auto-commit is about running CI, why not transfer commit bits from `master` to a shadow master (for the lack of better naming), and have harbormaster point `HEAD` of `master` to the latest building and validating version of the shadow master? (e.g. the CI would be the only one with commit bits to `master`). 

Now I understand that having a new branch to push to can be tedious, I do think this setup could also work with a second say blessed repository. Such that the current repository becomes the shadow one, and each commit to master there is built and validated (should we keep the artefacts somewhere?) and upon success pushed to the blessed repository? That way everyone could keep on what they are used to do, however if someone want's to get the latest building head, they could always use the blessed repository?

Option three I can think of right now, strip commit bits from master and allow only harbormaster and have branches in `automerge/myfeature` with harbormaster picking up on pushed `automerge` branches to try to integrate them into master, build and validate before merging them? (after all we are interested in master building, not only the branch, right?)

**Comment by simonmar** [comment]
Land-from-Differential is a button that you could press on a diff in Phabricator that would land it for you.  I'd love it if we had that feature on the GHC Phabricator - we have it at work and it's a game-changer.

Whether it should validate first or not is debatable.  It's not possible to atomically validate-and-push given that validate takes 1hr+ and the chances are that someone else has pushed something during that 1hr, so you're always going to have to accept the possibility of a bad merge/rebase breaking something.  So I'd be ok with the land button just doing rebase + push.

The workflow would be
* arc diff
* wait for Harbourmaster to validate it
* if you're not waiting for reviews, hit the land button.

Your local repo is not involved after the initial arc diff.

**Comment by Ericson2314** [comment]
> It's not possible to atomically validate-and-push given that validate takes 1hr+ and the chances are that someone else has pushed something during that 1hr.

Actually not. The Rust tool for this simply forgoes parallelism so no validation becomes invalidated by other changes. Additionally, they do "rollups", verfying the composition of changes as a hack to speed things up when there is more traffic.

With incrental rebuilds, evaluation of a 1 phase bootstrap could be parallel as the thundering herd of revalidstions on master changing would be mitigated by very little recompilation needed in the common case.

**Comment by bgamari** [comment]
> If the whole point of auto-commit is about running CI, why not transfer commit bits from master to a shadow master (for the lack of better naming), and have harbormaster point HEAD of master to the latest building and validating version of the shadow master? (e.g. the CI would be the only one with commit bits to master). 

I have been hesitating to bring this up until now since it's perhaps a bit far afield, but @angerman's comment makes me think that it might be quite germane:

The Rust project has a very interesting means of handling merges: they have no notion of manual merges; instead the only way to merge to `master` is to request a bot to do it on your behalf. The bot checks out the current state of `master`, pulls in one or more patches for which merge has been requested, runs a test build, and, if things went well, merges the resulting branch into `master`. I believe all of this is serial, so there is no threat of someone swooping in before you while the test runs.

Frankly I think this sounds like quite a nice system: it removes most of the potential for human error and the temptation of "let me just merge this one little thing", while eliminating the need for people to merge and manually test patches (which eats a significant fraction of my time), and is nearly foolproof in keeping the tree green.

The only trouble is I don't know how this would integrate into our Harbormaster infrastructure.

**Comment by goldfirere** [comment]
Simon M says

> Land-from-Differential is a button that you could press on a diff in Phabricator that would land it for you. I'd love it if we had that feature on the GHC Phabricator - we have it at work and it's a game-changer.

Ah -- that's much simpler than I understood it to be. (I thought it was a feature the diff poster would use to request landing in the future, pending on some other action, like a positive review.) I imagine this can be given permissions, etc., so that not anyone can push the button. Independent from anything else going on in this thread, I would support adding this button. 

And I very much like @bgamari 's recent description of Rust's procedure, where `master` is protected from non-bot merges. I have no opinion on the amount of work / difficulty of integration of such an approach, but I like the flavor of it. Perhaps there should be an escape hatch (e.g., the impossible has happened and `master` has gone sour, and Austin and Ben are unavailable because it's nighttime in America) allowing a direct commit in dire circumstances. Does Rust have such an escape hatch?

**Comment by thoughtpolice** [comment]
> And I very much like @bgamari 's recent description of Rust's procedure, where master is protected from non-bot merges. I have no opinion on the amount of work / difficulty of integration of such an approach, but I like the flavor of it. Perhaps there should be an escape hatch (e.g., the impossible has happened and master has gone sour, and Austin and Ben are unavailable because it's nighttime in America) allowing a direct commit in dire circumstances. Does Rust have such an escape hatch?

We could easily have Gitolite enforce this, so that it would only ever allow non-bot merges if something like "THE WORLD IS ENDING" is in the commit summary. Then, you have to go pretty far out of your way to deliberately go beyond this.

**Comment by nomeata** [comment]
Since I brought this up at HIW, I want to express my desire for this feature here.

The ideal interface for me would be 
```sh
$ git push origin mybranch:automerge/nomeata-fixes-a-typo
```
with nothing else to do. No use of `arc` if it can be helped. The branch would be built and then either merged into `master` or, in case of failure, maybe be renamed to `failed-automerge/nomeata-fixes-a-typo`, and I get a way to look at the log, possibly on Harbormaster. (While I was at MSR I had a simple shell script that validated all branches names `validate/foo` and either moved them to `validated/foo` or `failed/foo`. It was very handy.) This is pretty much what Austin describes in <https://github.com/ghc-proposals/ghc-proposals/pull/12#issuecomment-250938157>, so yeah, go for it! :-)

**Comment by bgamari** [comment]
This is something that I have the beginning of a prototype for, but my time has been a bit too fragmented recently to finish it up.

**Comment by goldfirere** [comment]
Was just doing some internal cleaning -- didn't realize this would close. But that's probably for the best, anyway.

**Pull request closed without merging**
