### PR TITLE
Type-level type applications

### PR DESCRIPTION
**Pull request by treeowl**
Allow `TypeApplications` syntax to be used in types as well as
terms.

[Rendered](https://github.com/treeowl/ghc-proposals/blob/type-level-type-app/proposals/0000-type-level-type-applications.rst)

### CODE REVIEW

**Comment by AntC2** [comment]
How does this combine with type family applications? Is this valid:

    'Just @(F Int Char)

And if we allow [partially applied type families](https://github.com/ghc-proposals/ghc-proposals/pull/52)?

    'Just @(F Int)

What type is that?

**Comment by treeowl** [comment]
'Just

`'Just @(F Int Char)` looks perfectly sensible to me. Do you envision some sort of difficulty there?

I can't say if this would be able to handle a partially applied family, if we end up having those. Sounds a bit messy. I'd be okay with a requirement that the type argument not be a partially applied type family.

**Comment by goldfirere** [comment]
If we can support partially applied type families anywhere, we can support them here. A kind argument to a type is merely an argument that needn't be specified by the user; there's nothing else special about one. This syntax gives a way to provide an argument visibly (explicitly).

I'm strongly +1.

**Comment by RyanGlScott** [comment]
I'm also supportive of this proposal, but the current write-up is a bit terse on the specifics. In particular, "Allow visible type application in types as well as terms" doesn't really give me the impression that we've thought through all of the implementation details, even though I'm sure some of you folks probably have—let's write those details down! In particular, some things I'd like to see mentioned are:

1. Parser changes. Currently, trying to use `(@)` anywhere at the type level, prefix or infix, appears to result in a parse error. This actually works to our advantage here, since this means visible kind application won't steal the ability to write a type family/type synonym named `(@)`, since GHC never granted that ability in the first place.
2. An overview of how visibilities work for type-level things. For instance, in this term:

   ```haskell
   {-# LANGUAGE PolyKinds #-}
   f :: forall (a :: k) b. Proxy a -> Proxy b
   ```

   There are three sorts of visibilities at play:

   1. `a` and `b` are explicitly quantified, so they're _visible_, and thus available for visible type application.
   2. `k` is implicitly quantified but still user-written, so it's _specified_, and also available for visible type application.
   3. The kind of `b` is _inferred_, and thus not available for visible type application.

   Will these three visibilities (and the rules for when they kick in) also apply at the type level? I suspect so, so it'd be nice to explain this with an example of something that lives at the type level, such as:

   ```haskell
   {-# LANGUAGE PolyKinds #-}
   class C (a :: k) b
   ```
3. Speaking of which, does a promoted data constructor inherit the visibilities of the original, term-level data constructor? That seems like a sensible choice to me, so let's explicitly state that.
4. @AntC2 brings up an interesting point about type families. Currently, we don't allow partial application of type families, so something like this:

   ```haskell
   type family Foo (a :: k)

   type Bar = Foo
   ```

   Is rejected. I assume that `Foo @Type` would also be rejected for similar reasons?
5. One interesting development that's sprung out of the work on visible type applications is the need for [two different variants](http://git.haskell.org/ghc.git/blob/2be55b85b4c7479639b01c3b8f47c1e49ddbcb0a:/docs/users_guide/glasgow_exts.rst#l10085) of GHCi's `:type` command. There's `:type`, which reports the _inferred_ type of an expression (possible after instantiating some type variables), and `:type +v`, which attempts to leave type variables alone as much as possible. This distinction matters for visible type application, as shown in the example GHCi session below:

   ```
   λ> :set -fprint-explicit-foralls 
   λ> :type Just
   Just :: forall {a}. a -> Maybe a
   λ> :type +v Just
   Just :: forall a. a -> Maybe a
   ```

   Here, only `:type +v` accurately reports the fact that `a` is available for visible type application.

   Given that this proposal wants to move `TypeApplications` to the kind level, what should become of the `:kind` GHCi command? Currently, `:kind` appears to behave analogously to `:type +v`:

   ```
   λ> :set -fprint-explicit-foralls -XDataKinds 
   λ> :kind 'Just
   'Just :: forall a. a -> Maybe a
   ```

   Should it remain this way? Or should we have both `:kind` and `:kind +v` to mirror `:type` and `:type +v`?

**Comment by RyanGlScott** [comment]
6. How should visible kind application interact with implicit quantification in type signatures? For example, in the type signature below:

   ```haskell
   f :: Proxy (Just :: a -> Maybe a)
   ```

   The type variable `a` gets implicitly quantified. Should the same happen in this equivalent type signature using visible kind application?

   ```haskell
   f :: Proxy (Just @a)
   ```

   Or should users be forced to explicitly quantify any type variable used in visible kind application?

   ```haskell
   f :: forall a. Proxy (Just @a)
   ```

**Comment by goldfirere** [comment]
I agree with Ryan that more details are good. Though I can't speak for @treeowl, I will try to answer your questions:

1. It seems you've concluded parsing will be easy. I agree. I *do* think we should allow for future-compatibility with type-level as-patterns, and so type-level `@` will retain the space-sensitivity of the term-level `@` (where a type application's `@` *must* be preceded by whitespace or a comment).

2. Your example there is slightly wrong (evidencing the need for more explanation of this). Here is the example: `f :: forall (a :: k) b. Proxy a -> Proxy b`. Here, `a`, `b`, and `k` are all *specified*. The fact that the quantification for `a` and `b` is explicit changes only the order that GHC uses, not whether or not the variables are available for visible type application. There are no `visible` tyvars there. (Contrast with `data T k (a :: k)`, where `k` is visible -- that means it must be supplied at applications.)

    The rules at the kind level should be the same: variables mentioned by the user are specified; other variables are inferred.

3. Yes, a promoted data constructor should have the same visibilities as the original.

4. I still don't see how this feature interacts meaningfully with type families. They are orthogonal to me. Partially applied type families are, for now, utterly illegal. Nothing in this proposal changes that.

5. I think that we got the design for `:type` wrong. (The default behavior should be what's currently done for `:type +v`, in my opinion.) I've made my case for this and lost. However, I think that `:kind`'s behavior should mirror `:type`'s, including the introduction of `:kind +v`.

6. Mentioning a fresh type variable in a visible kind application should lead to quantification, just like any mention of a type variable does now. I personally wouldn't expect this to be detailed in the proposal.

**Comment by RyanGlScott** [comment]
2. D'oh, sorry. I meant to write _required_ in place of _visible_. My bad.
4. So to be clear, `Foo @Type` counts as a partial type family application?

**Comment by goldfirere** [comment]
Yes, if we have `type family Foo (a :: k)`, then `Foo @Type` is a partial type family application and is against the rules -- just like if we had `type family Foo2 k (a :: k)` and were examining `Foo Type`.

**Comment by nomeata** [comment]
@treeowl, what is the status? Are you going to integrate the comments from @RyanGlScott and @goldfirere into the proposal – or maybe one of you two wants to integrate them? Proposals are not “owned” by anyone in a strong sense, and everyone should feel entitled to improve them. You can create pull requests against branch `type-level-type-app` on `treeowl/ghc-proposals`, for example.

**Comment by nomeata** [comment]
Also, the proposal should discuss whether this can happen under `TypeApplications` or whether it needs its own extension. (I’d hope for the former.)

**Comment by treeowl** [comment]
I'd be happy to see more-knowledgeable people help fill in the blanks! I
don't think I'm nearly as qualified to work out the details as they are.
One later thought I had is that we need to make sure this interacts nicely
with ScopedTypeVariables. For example,

\(x :: p @q)

should bind q appropriately.

**Comment by treeowl** [comment]
@goldfirere, thanks for fleshing things out. Can you comment on the potential interaction with `ScopedTypeVariables` I mentioned in my last comment?

**Comment by goldfirere** [comment]
Done -- I've just committed directly.

**Comment by treeowl** [comment]
@goldfirere, with `ScopedTypeVariables`, what happens if the kind variable is already in scope?

```haskell
foo :: forall k ....
foo (x :: Foo @k) = ....
```

Do we verify that they match, or do we introduce a fresh `k`?

**Comment by goldfirere** [comment]
That will verify that they match -- just like occurrences of in-scope type variables in pattern signatures today. There's not really an interaction between the features here.

**Comment by nomeata** [comment]
@treeowl, @goldfirere, what’s the status of this?

**Comment by goldfirere** [comment]
@treeowl ? I'm ready for review here, but you're the proposer.

**Comment by treeowl** [comment]
@nomeata, please submit.

**Comment by goldfirere** [comment]
Forgive me for being dense, but what's the process for getting this implemented? Specifically, is there a ticket to be created? Whose job is that? And in a similar vein, it might be nice to have a list of all accepted-but-unimplemented proposals. Generally, I find that adding a new feature is easier for a newcomer than fixing someone else's mistake, and a list of accepted-but-unimplemented proposals might make a tempting garden to play in.

**Comment by RyanGlScott** [comment]
I second the call for a list of unimplemented proposals.

Also, https://ghc.haskell.org/trac/ghc/ticket/12045 is the closest ticket that pertains to this particular proposal.

**Comment by int-index** [comment]
Given that the feature should be available even without `-XPartialTypeSignatures` (and should not imply partial type signatures in a context other than inside a `@`), I think the `-Wpartial-type-signatures` flag should not control its behavior.

I see 2 reasonable options:

1. disable these warnings when typechecking a `@`-argument
2. add another flag, `-Wpartial-type-applications`, that would report these wildcards both in terms and in types

and since (1) seems easier to implement, I would postpone (2) until someone explicitly requests this feature.

**Comment by simonpj** [comment]
I'm with int_index here: surely it should behave the same as term-level visible type application, whatever that is.

**Comment by mynguyenbmc** [comment]
Thank everyone for your inputs! I have decided to go with option 1 @int-index suggested above.

**Comment by Icelandjack** [comment]
A great test of the extension would be to write every kind application explicitly in https://github.com/ekmett/eq/blob/master/src/Data/Eq/Type/Hetero.hs

**Pull request merged**
