### PR TITLE
[WIP] Additional pragmas for optimisation and other uses

### PR DESCRIPTION
**Pull request by spacekitteh**
This is a (WIP) proposal to add additional pragmas for optimisation passes and the code generator.

[Rendered](https://github.com/spacekitteh/ghc-proposals/blob/optimising-pragmas/proposals/0000-optimising-pragmas.rst)

### CODE REVIEW

**Comment by bgamari** [comment]
I think it would probably be better if we instead considered proposals for individual pragmas covering specific use-cases; the current state of this is a bit abstract and it's not clear that all of the mentioned use-cases are going to be easily covered by one pragma.

**Comment by bgamari** [comment]
I think it would probably be better if we instead considered proposals for individual pragmas covering specific use-cases; the current state of this is a bit abstract and it's not clear that all of the mentioned use-cases are going to be easily covered by one pragma.

**Comment by spacekitteh** [comment]
All of the use-cases I've mentioned correspond exactly to specific annotations in LLVM! :smile_cat: 

But point taken - I figured it would be best to consider them all together, as I'm not sure how scalable the current pragma system is.

Perhaps it would be better to consider just the four extensible ones? The others can all be implemented in terms of them, anyway.

**Comment by cartazio** [comment]
I agree with Ben. Let's start with one focused proposal. Perhaps the branch weight one?

Also LLvm specific pragmas aren't super appealing.

**Comment by spacekitteh** [comment]
I agree they aren't super appealing, but I think the benefits outweigh the distastefulness, especially as they are merely pragmas, not proper surface syntax.

Do you think I should create a new PR for each pragma? Or just create a new document in this PR for each pragma?

**Comment by bgamari** [comment]
Sophie Taylor <notifications@github.com> writes:

> I agree they aren't super appealing, but I think the benefits outweigh
> the distastefulness, especially as they are merely pragmas, not proper
> surface syntax.
>
I'm not sure I like the general LLVM attribute pragma either. There are
several questions regarding their implementation that will be quite
difficult to answer,

 * What do the "parameter attributes" even apply to? The arguments
   passed to a procedure under the GHC calling convention are STG
   registers and in general don't map sensibly to the formal arguments
   of the function?

 * How does this interact with core-to-core transforms?

 * How do we avoid having Haskell code which depends upon a particular
   LLVM version?

 * What do we do if both the user and the compiler want to set a
   particular metadata value?

In general I suspect that exposing raw LLVM metadata to the user is the
wrong approach here. What use-cases do you intend for this to address?

> Do you think I should create a new PR for each pragma? Or just create a new document in this PR for each pragma?
>
A PR for each pragma is probably best.

**Comment by nomeata** [comment]
Not much has happened here since a while, and it still has `WIP` in the title. I am marking this as dormant, to get it off the list of “actively” discussed proposals. This status can of course change easily once there is progress.

**Comment by nomeata** [comment]
This has been dormant for a long time. @spacekitteh, is this abandonned? In that case, please consider closing it.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Comment by nomeata** [comment]
Closing due to inactivity, but it can of course be reactivated any time.

**Pull request closed without merging**
