### PR TITLE
Winapi pseudo calling conv

### PR DESCRIPTION
**Pull request by Mistuke**

### CODE REVIEW

**Comment by Mistuke** [comment]
[Rendered](https://github.com/Mistuke/ghc-proposals/blob/587836d859f50a2f496a9ff3907f9d6de1a50ea0/0000-winapi-callconv.rst)

**Comment by RyanGlScott** [comment]
I like the general idea of this proposal. I request two changes:

1. It took me a while before I actually noticed what you propose _calling_ this new calling convention: `winapi`. Can you highlight this in an example with code formatting? Something like:

   ```haskell
   foreign import winapi "foo" c_foo :: IO ()
    ```

    Would have popped out more.
2. You briefly allude to the fact that foreign exports with a `winapi` calling convention would be "confusing"... but you don't mention what actually _happens_! Please propose what GHC should do in such a scenario. Emit a warning? Error? Something else?

**Comment by Mistuke** [comment]
Done, thanks for the feedback!

**Comment by vagarenko** [comment]
@Mistuke 
The 'Rendered' link in the second comment still points to the older version.

**Comment by Mistuke** [comment]
Thanks, corrected it.

**Comment by vagarenko** [comment]
What happened to this proposal? Was it accepted?

**Comment by nomeata** [comment]
It was never submitted for consideration, and @Mistuke closed it just now, which I take it that they do not want to retract it.

**Comment by Ericson2314** [comment]
This is a good proposal. Can someone else champion this?

**Comment by ndmitchell** [comment]
This is an awesome idea. They aren't wrong that this code crops up all the time, e.g. https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/Internal/FileInfo.hs#L126-L133. I think they undersell that the majority of people doing this get it wrong, so it probably brings conciseness and correctness benefits.

However, I wonder if the time for this proposal has come and gone? GHC no longer seems to ship a 32bit Windows binary. As a consequence, no one is going to maintain their code for 32 bit, and thus the problem has gone away. Maybe it's still worth it to increase the documentation and avoid a potential trap, but the CPP could probably be eliminated in the future regardless.

**Comment by Ericson2314** [comment]
@ndmitchell interesting point, but remember GHC is a cross compiler too. Furthermore I am on the verge of making it multi-target so anyone can produce 32-bit Windows binaries only "rebuilding" rts, base, and other libraries.

**Comment by ndmitchell** [comment]
@Ericson2314 yep, if someone sticks their hand up and says they ever want a 32bit binary, it makes a lot of sense (it may make sense even if no one does). But given I'm one of the "Windows guys" and even I don't use it, I imagine it's not many. However, I suspect there is one company I know that relies on the 32bit version, so it will have some users.

**Comment by Mistuke** [comment]
> GHC no longer seems to ship a 32bit Windows binary

This is not a policy rather than an incident I hope never happens again. A bug prevented the toolchain from building and it was noticed far too late in the release process, one that is fixed in master and being back ported. 8.8.2 should have a 32-bit release.

**Comment by Mistuke** [comment]
And to answer why I closed it, because I found the process too closed. I submitted it, it sat around without any attention at all, while other proposals were attended to that were submitted after this one.

I concluded that it wasn't interested to anyone and just implemented what I needed in a local branch and moved on.

**Comment by ndmitchell** [comment]
Given that Win32 was a mistake that will be rectified, I am strongly in favour, but totally not on the committee. Want to reopen the proposal, and see if the committee wakes up? It would be directly useful to me.

**Comment by Mistuke** [comment]
Sure I'll give it a once over and re-open it once I'm back  Tuesday.

**Comment by Ericson2314** [comment]
Thanks!

**Comment by gbaz** [comment]
I think the confusion, judging from nomeata's comment above, is that it needs to be requested as ready for "official consideration" before the committee acts on it. Many good proposals may not get a lot of attention. What matters is that the committee is requested to consider, then decides :-)

**Comment by Mistuke** [comment]
@gbaz I'm not sure what that actually means. How do you request the committee to look at it? I thought that as a proposal writer I put up the proposal respond to feedback and when there isn't anything more someone would bring it up for the committee.

The Readme doesn't say how this all works https://github.com/ghc-proposals/ghc-proposals/blob/master/README.rst and I couldn't find other documentation on this...

**Comment by gridaphobe** [comment]
@Mistuke the process for requesting a committee review is described at https://github.com/ghc-proposals/ghc-proposals/blob/master/README.rst#how-to-bring-a-proposal-before-the-committee, which really just boils down to pinging the secretary (@nomeata) and saying the proposal is ready for a formal review by the committee.

Individual committee members often review and comment on proposals before the formal review, but this step serves to inform the rest of the committee that the proposal is at a stage where the author (and hopefully the community!) feels that it's ready to be finalized.

**Comment by gridaphobe** [comment]
As to the proposal itself, it does sound like something we should address. One thing that's a bit unclear to me though, not knowing much about calling conventions or windows, is why we need a separate calling convention for windows in the first place. `ccall` is supposed to be the convention of the standard C compiler on the system, which based on the proposal I would expect to be stdcall on x86 windows and __fastcall on x86_64 windows. Put another way, why does `ccall` break x86 windows?

**Comment by Ericson2314** [comment]
@gridaphobe Windows API does not do the default. The default is still cdecl on 32-bit, rather than stdcall which is what the windows ABI does. See https://docs.microsoft.com/en-us/cpp/cpp/cdecl?view=vs-2019

**Comment by gridaphobe** [comment]
Thanks for the link!

So if I understand correctly, `ccall` is correct for regular C code on windows, just not for the specific combination of the Win32 API on x86? For that combo you have to use `stdcall`. Even on x86_64 the Win32 API should use `ccall`?

That’s quite a mess, and I agree that adding a layer of indirection would make things clearer.

**Comment by Ericson2314** [comment]
I think that's all correct.

**Comment by Mistuke** [comment]
Well, it makes sense if you look at it from the historical point of view. `stdcall` was chosen at a time when disk space was prohibitedly expensive. `ccall` has a much larger overhead in terms of disk space. And so when you think about what an API is supposed to be, having to have the cleanup code for each function call will bloat the program size.

By the time x86_64 came around disk space wasn't an issue anymore and so stdcall and everything else was retired.

Also `ccall` doesn't exist on any platform on x86_64. It's just that Compilers needed to name it something to they picked `ccall` so existing code continued to work. However Linux, BSD, Mac OS etc use the System V AMD64 ABI or on Windows https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019 are not cdecl. The calling convention just doesn't have a name.

**Comment by Mistuke** [comment]
Re-opened as #277 as github won't allow me to re-open the PR.

**Pull request closed without merging**
